### ISSUE TITLE
Implement Material for Pager

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-themes#100]

**Comment by MilenaCh** [comment]
Design will be updated. 
@lkarakoleva please add information what should be changed in the current implementation.

**Comment by lkarakoleva** [comment]
We should change dropdown font size to 14px. 

In the design below I illustrate the metrics in a specific configuration and order of the pager elements
<img width="915" alt="screen shot 2018-04-02 at 5 55 19 pm" src="https://user-images.githubusercontent.com/16577622/38200971-1ab72ad0-369f-11e8-8ee4-1cdd8109426b.png">

Updated Design: https://github.com/telerik/kendo-ux/blob/master/themes/material/grid.psd
