### ISSUE TITLE
[Dialog] Page is scrollable while Dialog is opened

### ISSUE THREAD

**Issue by TranHPDung** [telerik/kendo-themes#1000]
## I'm submitting an Enhancement

* Suggestion for improvement
Lock the vertical scrolling of the long content when you open the Dialog

## Current behavior
Preview the issue in [Themebuilder Kendo Angular UI](http://themebuilder.telerik.com/kendo-angular-ui)
When you open the Dialog button, you can scroll the main page as well. 

If the Dialog's height > viewport's height, the browser page will show up 2 scrollings: scroll of the main page (body element) and scroll of the dialog.

## Expected behavior

Hide the vertical scrolling of the main page while the Dialog is opened.

## Minimal reproduction of the problem with instructions
Add/Remove the below CSS lines when the dialog is opened/closed:
```
body {
 overflow: hidden;
}
```
Reference [Bootstrap Modal](http://getbootstrap.com/javascript/#modals)

**Comment by joneff** [comment]
I am not sure why the issue was transferred in the themes. Perhaps it was because we were missing utility classes for overflow...

However, we do have them now (currently available in dev channel) so adding `k-overflow-hidden` to the body element will do the trick.

Moving back to kendo-angular.

**Comment by joneff** [comment]
Closing as `invalid`. Please follow telerik/kendo-angular#3157
