### ISSUE TITLE
[Default theme]: Week number clips the last month column

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-themes#101]
It seems like the week number will push the whole month, thus clipping the last column a bit.

![screen shot 2018-04-02 at 12 21 38 pm](https://user-images.githubusercontent.com/495188/38191320-ee1797d6-3670-11e8-8cee-d18a6a2d267d.png)

The issue can be observed on our online demos:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/week-num-column/

**Comment by TeyaVes** [comment]
no longer reproducible as of Kendo UI v. 2019.2.514
