### ISSUE TITLE
Indeterminate checkbox label has no background

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#1014]
**Describe the bug**
The styles applied to the Label::after pseudo element are missing a background and thus a checkbox in an indeterminate state is appearing empty/unchecked.

**To reproduce**
https://stackblitz.com/edit/kendo-styles-indeterminate-not-working?file=app/app.component.ts

**Expected behavior**
The styling correctly indicates that the Checkbox is in an indeterminate state (a colored inner square) like in previous versions of the theme:

https://stackblitz.com/edit/kendo-styles-indeterminate-not-working-epdbn9?file=app/app.component.ts

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material
* kendo-angular-grid
* kendo-angular-treeview

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please provide)**
- Firefox: [for example, 67, lts]
- Chrome: [for example, 77]
- Edge version: [for example, 15]
- Safari: [for example, 12]
- IE version: [for example, 11]

**Build system information (please provide)**
- OS: [for example, Windows, Linux, Mac]
- Node version: [for example, 10.15.3]
- NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by JoomFX** [comment]
This will be fixed in https://github.com/telerik/kendo-themes/pull/992
