### ISSUE TITLE
Extract all variables for the Grid component

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1027]
**Is your feature request related to a problem? Please describe.**
Extract all variables for the Grid component, that are including appearances and depending on other styles.

**Describe the solution you would like to see implemented**
Extract those variables from the theme files and remove the appearance mixins. This refactoring must **not** regress the current design and behavior.

**Additional context**
We can achieve decoupled styles and more flexibility when customizing the styles for a given component. This enhancement will be needed for creating a consistent and flexible styleguide for creating forms with Kendo components.

Related to: https://github.com/telerik/k2/issues/150

**Comment by silviyaboteva** [comment]
After a discussion with @elena-gancheva, we need to freeze this refactoring for now (also related to Scheduler and Editor components). So, I'll remove it from the project's To Do for now.

**Comment by PreslavKozovski** [comment]
duplicate of https://github.com/telerik/kendo-themes/issues/211
