### ISSUE TITLE
Input floating label color is incorrect in invalid state

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1037]
**Describe the bug**
The floating labels when the input is invalid have to be red based on the original design of Material theme. Currently, it is grey.

**To reproduce**
1. Navigate to https://stackblitz.com/edit/react-1soxse?file=index.html

Scenario 1: Both inputs are empty. Input1's label is grey.
Scenario 2: Focus Input1, the label becomes purple (as in focused state), but the border is red.

**Expected behavior**
Scenario 1: label to be red too.
Scenario 2: Not sure here. Either both to be red, as there is no value yet or to be purple as it is in focus state. 
What do you think? @ivelina-penkova @joneff @elena-gancheva 

**Screenshots**
Scenario 1: https://www.screencast.com/t/h6MiIoi5Y
Scenario 2: https://www.screencast.com/t/TUeW32hHce

**Affected package (please provide)**
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please provide)**
all

**Build system information (please provide)**
all

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
related to: https://github.com/telerik/kendo-react/issues/272

**Comment by joneff** [comment]
Yup. As per material spec, it should be red and completely opaque (no transparency)

![image](https://user-images.githubusercontent.com/8048/68744185-ac5e9a80-05fc-11ea-8918-fc64fb93c893.png)
