### ISSUE TITLE
Reversing the direction of MultiSelect's Popup changes Dialog's overlay color in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#104]
When there is a MultiSelect within a Dialog and there is no enough space so that the Popup's opening direction needs to be reversed, the background color of the overlay is switched to white (still is black according to the elements inspector):

[https://plnkr.co/edit/seLqgFMrpVyp3gskXRjp?p=preview](https://plnkr.co/edit/seLqgFMrpVyp3gskXRjp?p=preview)

![image](https://user-images.githubusercontent.com/7533599/38200311-7fc4d7f4-369c-11e8-9298-42c4a1d20b27.png)

Observable in IE only.

**Comment by inikolova** [comment]
I tested this scenario with the latest versions of the theme, multiselect and dialog and everything is working as expected. Therefore I am closing this issue

https://stackblitz.com/edit/angular-2hifkh?file=app/app.component.ts
