### ISSUE TITLE
MultiSelect's taglist layout is broken when a form-control class is applied

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#105]
The display of the selected tags is distorted when a Bootstrap **form-control** class is applied:

`<kendo-multiselect style="width: 250px;" class="form-control" name="msEmployee" [data]="data" textField="name" valueField="id"
                          [(ngModel)]="selectedEmployees">
                      </kendo-multiselect>`

![image](https://user-images.githubusercontent.com/7533599/38200603-b4d7b14a-369d-11e8-9b8b-2a17e7bae57e.png)

Without **form-control** class:

![image](https://user-images.githubusercontent.com/7533599/38200661-e42abc26-369d-11e8-8637-5dce0f63d949.png)

**Comment by inikolova** [comment]
It appears everything is rendered as expected now
