### ISSUE TITLE
The layout breaks when using a Grid and a Splitter within a .k-form element

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1055]
**Describe the bug**
The layout breaks when adding a Grid and a Splitter within a .k-form wrapping element.

**To reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-skfppx-j9k7h6?file=app/app.component.ts

**Workaround**
add the following css:
     
> .k-form .k-widget.k-splitter {
            display: flex;
        }

https://stackblitz.com/edit/angular-skfppx-8miyuk?file=app/app.component.ts

**Affected package
* theme-default
* theme-bootstrap
* theme-material

**Affected suites
* Kendo UI for Angular

**Affected browsers
- Chrome: 78

**Comment by danielkaradachki** [comment]
Seem to be the same as https://github.com/telerik/kendo-themes/issues/835
