### ISSUE TITLE
Progress Sass ThemeBuilder generates css file riddled with !important

### ISSUE THREAD

**Issue by metoule** [telerik/kendo-themes#1063]
**Describe the bug**
When using the Progress ThemeBuilder for Kendo UI, the generated style contains many rules flagged as `!important`. This breaks a lot of our own customization, and also seems to break [your own code style guidelines](../wiki/Code-Style-Guidelines#avoid-using-!important)

**To reproduce**
1. Go to https://themebuilder.telerik.com/kendo-ui
2. Click 'Start Theming', select the default theme, then click on the 'Create' button
3. Download the generated style
4. Open the generated file `all.css`

**Expected behavior**
I'd expect the generated style not to contain any `!important` rule, so that I can easily override any rule.

**Affected package (please provide)**
* Progress SASS ThemeBuilder

**Affected suites (please provide)**
* Kendo UI for jQuery

I've attached a sample of the generated style.

[test.zip](https://github.com/telerik/kendo-themes/files/3858808/test.zip)

**Comment by PreslavKozovski** [comment]
@metoule 
You are correct, indeed, our guidelines suggest avoiding using the `!important` rule. However, there are cases in which the usage of the rule is needed. For example: 

### Utility classes:
https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/common/utils/_display.scss

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/common/utils/_text.scss

### Achieving a "must" functionality:
Add styles to specific HTML elements during the PDF creation - https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/scheduler/_layout.scss#L725

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/radio/_layout.scss#L39

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/upload/_layout.scss#L340

### Workarounding JS styles:

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/popup/_layout.scss#L194

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/menu/_layout.scss#L168
