### ISSUE TITLE
Spreadsheet's wrap text tool hides a part of the cell's content if the text is too long when using the SASS themes.

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-themes#1067]
### Bug report

The wrap text tool hides some of the cell's text if it is too long when using the SASS themes.  

### Reproduction of the problem

1. Go to this [Dojo.](https://dojo.telerik.com/iZUMEJAn/6) 
2. Select cell B2 and toggle the wrap text tool. The beginning of the text is cut.
![WrapTextIssue](https://user-images.githubusercontent.com/20702110/69219124-d4a94480-0b7a-11ea-89cd-d251631a9345.PNG)

### Current behavior
Part of the cell's content is hidden.

### Expected/desired behavior
All the text should be visible.

### Environment

* **Kendo UI version:** 2019.3.1023
* **Browser:** [all]

**Comment by TeyaVes** [comment]
related to: https://github.com/telerik/kendo-themes/issues/251 

If the line-height is fixed, this issue will be fixed as well.
