### ISSUE TITLE
ListItems in Kendo jQuery should have white-space: nowrap, instead of normal, when autoWidth is true

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#1084]
**Describe the bug**
When `autoWidth` property of AutoComplete, ComboBox, DropDownList or MultiSelect is set to `true`, list items should have white-space: nowrap

**To reproduce**
1. Go to [SASS Dojo](https://dojo.telerik.com/@Dimitar-Goshev/IwUnOben), open the browser console and run the example.
1. Click on the AutoComplete and type i in it
1. Delete the i

**Current behavior**
`k-list-container` receives `white-space: nowrap`, because of `autoWidth: true`, but the child items in `k-list` have `white-space: normal` .
normal is logged in the console.

**Expected behavior**
```
    <style>
        .k-list .k-item {
            white-space: nowrap;
        }
    </style>
```
nowrap is logged in the console, as on [LESS theme Dojo](https://dojo.telerik.com/@Dimitar-Goshev/URileRoV)

**Affected suites**
* Kendo UI for jQuery: 2019.3.1023

**Affected browsers (please provide)**
- Firefox: 70
- Chrome: 78
- Edge version: 44
- IE version: 11

**Build system information (please provide)**
- OS: [for example, Windows, Linux, Mac]
- Node version: [for example, 10.15.3]
- NPM version: [for example, 6.4.1]

**Additional context**
Related to https://github.com/telerik/kendo-ui-core/issues/3498

**Comment by joneff** [comment]
fixed by 15095429fba919f86a59e2f862b7b5415122f2b4
