### ISSUE TITLE
PopupSettings height is not working

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-themes#1102]
**Describe the bug**
popupSettings for DropDownList is not working.

**To reproduce**
[StackBlitz](https://stackblitz.com/edit/angular-edn2wo?file=app/app.component.ts)

**Expected behavior**
Height is properly rendered.

**Screenshots**
![chrome_2019-12-03_14-57-07](https://user-images.githubusercontent.com/1589573/70057466-769a4980-15dd-11ea-9901-281ef6a29c00.png)

**Affected browsers (please provide)**
- Chrome: [for example, 77]
- Maybe others too

**Comment by elena-gancheva** [comment]
Hi @MaklaCof, this issue is not related to the kendo-themes project. Please, follow the existing issue in the kendo-angular bug tracker repository [here](https://github.com/telerik/kendo-angular/issues/1607).
