### ISSUE TITLE
[ButtonGroup] White border on inner buttons

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-themes#1114]
**Describe the bug**
Inner buttons inside a buttongroup have a white border-bottom.

**Expected behavior**
No buttons inside a buttongroup should have white border bottom.

**Screenshots**
![ButtonGroup](https://user-images.githubusercontent.com/6378306/70436550-3c73f080-1a92-11ea-9a0f-bbe9663cea9a.png)

**Affected package (please provide)**
* theme-default

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please provide)**
- Chrome

**Build system information (please provide)**
- OS: Windows

**Comment by elena-gancheva** [comment]
Closing this issue, since it is related to the browsers difference in the sub-pixel precision.
