### ISSUE TITLE
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-themes#1122]
### Bug report
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color

### Reproduction of the problem
1. Run the following [Dojo snippet](https://dojo.telerik.com/oSugolAX)
2. Click button to submit the form

### Current behavior
ColorPicker, MultiSelect, Radio, Checkbox have no invalid border color 

### Expected/desired behavior
All widgets have invalid border color similar to DropDownList

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by IKKI2000** [comment]
MultiSelect wrap ‘k-valid’ class is missing~ The same as ColorPicker~
Checkbox invalid border color must be error color not the accent color~

**Comment by joneff** [comment]
@IKKI2000, as of 2020 R2 (2020.2.513) the checkbox and multiselect do receive the classnames and styles.

Radio, and Colorpicker will require some extra work.

**Comment by silviyaboteva** [comment]
In the KendoReact suite, the `k-invalid` class was added to the RadioButton component in `v3.15.0`.

**Comment by IKKI2000** [comment]
@joneff the styles doesn't set to RadioButton. The classnames "k-invalid" are there, but styles is not set.
CheckBox has style like this, RadioButton can be set in the same way.
```css
.k-checkbox.k-invalid,
.k-checkbox.k-state-invalid {
    border-color: rgba(243,23,0,.5);
}
```
