### ISSUE TITLE
Add animation to .k-textarea and/or introduce new class for the floating label

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#1125]
**Is your feature request related to a problem? Please describe.**
The Floating Label functionality requires an inner element with some CSS animation as it relies on the **animationstart** event to work properly with the browser autofill feature.

**Describe the solution you would like to see implemented**
The .k-textbox class has a CSS animation which allows for inputs with this class to work as expected when placed within a floating label container. However the **k-textarea** class does not have such an animation which prevents textarea elements with the kendoTextArea directive to work as expected in such scenarios.

**Describe the alternatives you have considered**
A separate floating-label-related class that applies an animation to its host element can be introduced and added by the kendoTextBox and kendoTextArea directives alongside the current k-textbox and k-textarea classes.

**Additional context**
WRT https://github.com/telerik/k2/issues/172

**Comment by elena-gancheva** [comment]
Additionally, support floating label animation styling for the new floating label component:
```css
.k-textbox-container>.k-label, .k-textbox-container.k-state-focused>.k-label
````
Extend with `k-floating-label` cc:// @joneff @Raisolution
