### ISSUE TITLE
font styles are not applied via SCSS variables for the Menu component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1140]
**Describe the bug**
Setting the **$font-family**, **$font-size**, and **$line-height** SCSS variables doesn't apply the styles to the Menu component. The provided styles, via the SCSS variables, will take effect if the **font** property of the **.reset** class of the Menu is disabled.

**To reproduce**
Please check the attached project. Run **npm install** and **ng serve** and inspect the applied styles to the Menu component.
[test-proj.zip](https://github.com/telerik/kendo-themes/files/4026107/test-proj.zip)

**Expected behavior**
The styles set via the SCSS variables should be applied to the Menu component.

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
- Chrome: 79

**Comment by inikolova** [comment]
I tested the provided project with the latest version of the default theme and all font styles are applied as expected to the Menu component. Therefore I am closing this issue.
<img width="1048" alt="Screenshot 2020-06-08 at 13 02 34" src="https://user-images.githubusercontent.com/1826086/84018443-bbd27600-a988-11ea-94af-dc5b01c5f942.png">
