### ISSUE TITLE
Add outline style for readonly Editor

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-themes#1157]
When the Editor is readonly, it is not visible when it is focused. It will be good show an outline that indicates it is currently focused.

**Describe the solution you would like to see implemented**
Similar to the textarea in this [example](https://stackblitz.com/edit/angular-4spvzg-ubeewu?file=app/app.component.ts) (which gets an outline when focused) we can add an outline inside the editor indicating that it is focused.

**Additional context**
![ReadonlyOutline](https://user-images.githubusercontent.com/2890242/72157886-9df4eb00-33c1-11ea-8323-a3a0e657a980.png)

**Comment by JoomFX** [comment]
This behavior does not come from the themes, it comes from the component itself.
There is a **styles.ts** file (`src/common`) where you can see the following code which is responsible for the current behavior:

```
div.ProseMirror:focus {
  outline: none;
} 
```
