### ISSUE TITLE
Gantt PDF Exports always generates a file with the maximum width (200 in)

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#1158]
**Describe the bug**
Gantt PDF Exports always generates a file with the maximum width (200 in)

The exported PDF also cuts the last rows of the Gantt

**To reproduce**
Select one of the SASS themes and export the PDF from the following demo: https://demos.telerik.com/kendo-ui/gantt/pdf-export

**Expected behavior**
The exported PDF should have width equal to the exported Gantt width

**Screenshots**
![GanttPdf](https://user-images.githubusercontent.com/3431388/72160457-0e523b00-33c7-11ea-979d-9391e540ddde.png)

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please provide)**
All

**Comment by veselints** [comment]
Also reported in:
https://supportheroes.telerik.com/ticket/1451215

**Comment by veselints** [comment]
Also reported in:
https://supportheroes.telerik.com/ticket/1451209

**Comment by Dimitar-Goshev** [comment]
@Juveniel The issue is fixed in Chrome and Firefox. It is still reproducible in IE11
