### ISSUE TITLE
Gantt Task Dependencies are not properly assigned in RTL

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#1159]
**Describe the bug**
Gantt Task Dependencies are not properly assigned in RTL
If the LESS RTL styling is added, the issue is no longer present:
https://dojo.telerik.com/IduzIdOF

**To reproduce**
1. Go to https://demos.telerik.com/kendo-ui/gantt/right-to-left-support
2. Select one of the SASS themes
3. Hover over the end on one of the tasks so the dependency dot appear
4. Click-hold-drag it to a dot of another task and release it to create a dependency
5. The created dependency will not respect the action. It will swap the places of the start and end of both events

**Expected behavior**
Gantt Task Dependencies should be properly assigned in RTL

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please provide)**
all

**Comment by Dimitar-Goshev** [comment]
@Juveniel @joneff After the changes there are no dependency lines in Gantt at all in SASS themes
