### ISSUE TITLE
CSS are not generated with SCSS files  + bugs in SCSS

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-themes#1169]
**Describe the bug**
/dist/*.css are NOT generated from /scss/* files

 "@progress/kendo-angular-common": "^1.2.1",
 "@progress/kendo-angular-dropdowns": "^4.2.4",
 "@progress/kendo-angular-l10n": "^2.0.1",
 "@progress/kendo-angular-popup": "^3.0.4",
 "@progress/kendo-theme-default": "^4.11.1",

**Example one for all**

SCSS
![image](https://user-images.githubusercontent.com/10418323/72680412-cd8aae00-3ab9-11ea-8b7f-ef1388207379.png)

CSS
![image](https://user-images.githubusercontent.com/10418323/72680415-d7acac80-3ab9-11ea-89a2-cf62ea4494e6.png)

Kendo SCSS imported like it is described in tutorial>
https://www.telerik.com/kendo-angular-ui/components/styling/custom-themes/
![image](https://user-images.githubusercontent.com/10418323/72680427-f448e480-3ab9-11ea-9e6b-7548f4fc634f.png)

**Comment by joneff** [comment]
We've provided documentation for:

* [Compiling themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes)
* [Customizing themes](https://github.com/telerik/kendo-themes/wiki/Customizing-themes)
* [Including themes in React projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-React-projects)
* [Including themes in Angular projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-Angular-projects)

Within the compiling article, you will find solutions for both gulp and webpack. The part that you need is using `postcss-calc` to reduce calc expressions

**Comment by montella1507** [comment]
your solution is for Angular, your guide has missing links for angular and it is not possible to edit webpack config... so it is not solved i think.

**Comment by joneff** [comment]
I guess we can improve with cross-linking to specific parts of the documents: https://github.com/telerik/kendo-themes/wiki/Compiling-themes#using-webpack targets webpack compilation and has an excerpt from webpack.config.js.

**Comment by joneff** [comment]
I've added a [Known Issues](https://github.com/telerik/kendo-themes/wiki/Known-issues) page in the wiki, which currently covers slow compilation and invalid calc expressions.

Do you think the calc section can be improved?

**Comment by montella1507** [comment]
to be honest.. i think WIKI on github is not the place it should be written...  I use your perfect kits in several firms where they have bought it... noone use github - they do not even know...  i think this should be part of documentation. No idea why wiki exists, if you have best looking and so extensive docu on your site.

**Comment by joneff** [comment]
Agreed -- it must be part of the documentation! And it will be part of the documentation. For the time being, it's part of the wiki, but we are going to move it.
