### ISSUE TITLE
The k-chat class has a max-width rule which prevents setting a bigger width to the component.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#1182]
**Describe the bug**
The k-chat class has a max-width rule which prevents setting a bigger width to the component.

**To reproduce**

**Expected behavior**
The Chat component should be able to be wider than 500 px. Someone may want to set it to fullscreen.

**Screenshots**

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please provide)**
- Firefox: [for example, 67, lts]
- Chrome: [for example, 77]
- Edge version: [for example, 15]
- Safari: [for example, 12]
- IE version: [for example, 11]

**Build system information (please provide)**
- OS: [for example, Windows, Linux, Mac]
- Node version: [for example, 10.15.3]
- NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
Developers can now set `$chat-width: null` to remove the max width. In future iterations, we'll remove those absolute values and use relative -- `min(100%, 100vw)`
