### ISSUE TITLE
Add viewport max height to the ContextMenu popup 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#1183]
The context-menu item list is not scrollable (and therefore not usable) when it contains a lot of items.

**To reproduce**
https://stackblitz.com/edit/angular-xf44hh-fx1kkd?file=app/app.component.ts

**Expected behavior**
The popup should be scrollable and have a `max-height`.
https://stackblitz.com/edit/angular-xf44hh-o6tuni?file=app/app.component.ts

**Comment by joneff** [comment]
Fixed with change in rendering.
