### ISSUE TITLE
Calendar Component issue resizing width

### ISSUE THREAD

**Issue by kotva006** [telerik/kendo-themes#1194]
Describe the bug
Changing the width of the calendar component to anything larger than 342px causes the day of week headers of the calendar component to no longer line up with their columns.
To Reproduce
https://stackblitz.com/edit/angular-jersjz

It renders 2 different calendars: one with the default width, and one larger with a larger width.  The larger widths day of the week headers is not be aligned.

Expected behavior
I would expect the whole date table to expand with the rest of the calendar not just the day of week headers.

Browser

OS: Windows
Browser [Firefox, Edge, Chrome]
Version [72.0.2, 79.0.309, 79.0.3945]

**Comment by joneff** [comment]
Related to #1602

**Comment by joneff** [comment]
We've targeted the issue, though not in the way you describe: instead of stretching the calendar days, we are centering the content. Main reason for that is that we can't actually "grow" the cells automatically, yet.
