### ISSUE TITLE
Pager cuts page number larger then 99 in Bootstrap and Material.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#1234]
Pager cuts page number larger than 99 in Bootstrap and Material.
In the default theme, it cuts the page larger than 99.

![image](https://user-images.githubusercontent.com/11087921/74004590-d36c0480-497e-11ea-9251-f26761ea3610.png)

As this is coming from the rendering, we should see if we need a new rendering for this.

A current workaround is to use CSS to make the input larger:

```
.k-pager-wrap .k-pager-input .k-textbox {
    width: 5em;
}
```

**Comment by joneff** [comment]
I am currently refactoring the pager. I will set this to a variable which can be customized.
