### ISSUE TITLE
Automate generation of _variables.scss markdown docs

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-themes#1243]
**Is your feature request related to a problem? Please describe.**
Customizations.md file is manually created, which leads to list of variables that is not complete, and possible divergence from the _variables.scss file in the long run.

We have identified that modifying themes is one obstacle, that may prevent users from adopting them in their project. To resolve this, we need descent documentation on all variables that are available for modification.

**Describe the solution you would like to see implemented**
The _variables.scss for each theme should contain appropriate documentation for each variable within the file. We may use sassdoc to describe them, and then use the extra tools to generate markdown -> http://sassdoc.com/extra-tools/ 
In addition, the file should contain meta annotations that make it easy to parse, and then slice the content to different files containing information for different entities (components wise) 

**Describe the alternatives you have considered**
Manually creating the document, which in short-turn will solve the problem, however, may bring divergences in the long run.

**Additional context**
n/a

**Comment by joneff** [comment]
778eb727b643bb99da869335e88dc62b721b14c9 targets splitting the single file into separate smaller files.

I'll keep this item open because we still haven't completed everything
