### ISSUE TITLE
The Bootstrap checkbox differs from the kendo bootstrap checkbox

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1255]
**Describe the bug**
Currently, the kendo bootstrap theme overrides the default bootstrap custom checkbox component styles. The kendo checkbox has a default #FFF background but the bootstrap custom checkbox has a grey-ish background.

**To reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-xr1kqj?file=app%2Fapp.component.ts

**Affected suites (please provide)**
* Kendo UI for Angular

**Comment by joneff** [comment]
Starting with 4.2.0 bootstrap the checkboxes are no longer with grayish background color.

* 4.1.3: https://getbootstrap.com/docs/4.1/components/forms/#custom-forms
* 4.2.x: https://getbootstrap.com/docs/4.2/components/forms/#custom-forms

@JoomFX  redirect `$checkbox` and `$radio` variables to `$form-check-input` and `$form-check-radio` variables.

**Comment by joneff** [comment]
Related to #441
