### ISSUE TITLE
No space between rows of Editor toolbar buttons

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#1256]
**Describe the bug**
No space between rows of Editor toolbar buttons. Related to the following change: https://github.com/telerik/kendo-themes/pull/1214

The issue is affected by the lack of gap support in Chromium - https://bugs.chromium.org/p/chromium/issues/detail?id=762679&sort=-stars&q=component%3ABlink%3ELayout&can=2

**To reproduce**
1. Use https://demos.telerik.com/kendo-ui/editor/all-tools demo in Default theme
1. Reduce browser window size to have two rows of buttons

**Current behavior**
The two rows of buttons have no space betwee:
![All tools demo in Kendo UI HTML5-based Editor widget](https://user-images.githubusercontent.com/6614183/74586598-c9d34400-4ff1-11ea-8cd5-a8b3a26c77c3.png)

**Expected behavior**
There is space between the two rows as in LESS based Default
![All tools demo in Kendo UI HTML5-based Editor widget - Google Chrome 2020-02-15 12 52 06](https://user-images.githubusercontent.com/6614183/74586628-043ce100-4ff2-11ea-9957-b7502793f554.png)

**Affected package (please provide)**
* theme-default
* theme-bootstrap

**Affected suites (please provide)**
* Kendo UI for jQuery

**Affected browsers (please provide)**
- Firefox: 70
- Chrome: 80

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo/pull/10781 and https://github.com/telerik/kendo-themes/pull/1265
