### ISSUE TITLE
Remove background-color from Autocomplete

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#1274]
**Describe the bug**

The Autocomplete has bg-color in the material.

**To reproduce**
1. Go to https://demos.telerik.com/kendo-ui/grid/filter-row
2. Hover the Filter row.

**Expected behavior**

The Autocomplete has no bg-color.

**Screenshots**

![image](https://user-images.githubusercontent.com/17339722/74724065-58d79a80-5244-11ea-9eab-fbdd2240e937.png)

**Affected package (please provide)**
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please provide)**
- All

**Comment by silviyaboteva** [comment]
Also, on the filter clear icon. If you switch to the Material theme and hover over the filter row, you will see it: https://www.telerik.com/kendo-react-ui/components/grid/filtering/.
