### ISSUE TITLE
Add classes to all HTML elements in the Calendar

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#1278]
Update the following Calendars:

- [x] jQuery (telerik/kendo#12953)
- [x] Angular
- [x] React
- [x] Blazor (telerik/blazor#2764)

You can add issues in the relevant repositories.

**Comment by JoomFX** [comment]
We agreed on using the HTML element name in the class name.
Here are the classes that will need to be added:

```
k-calendar-table
k-calendar-thead
k-calendar-tbody
k-calendar-tr
k-calendar-th
k-calendar-td
```

**Comment by joneff** [comment]
Nice. And some day we'll be able to do https://dojo.telerik.com/@joneff/IDikiKAj, as long as we have `aspect-ratio` implemented
