### ISSUE TITLE
Unexpected end of JSON input while parsing near '...js.org/@progress/kend'

### ISSUE THREAD

**Issue by ketanISM** [telerik/kendo-themes#1318]
Error while npm install

> silly fetchPackageMetaData error for @progress/kendo-theme-default@latest Unexpected end of JSON input while parsing near '...js.org/@progress/kend'

package json added

> "@progress/kendo-theme-default": "latest",

**Comment by joneff** [comment]
Can you provide more information to how this is happening?

**Comment by ketanISM** [comment]
Couldn't regenerate. So closing this issue.
