### ISSUE TITLE
The input of kendo.prompt doesn't resize when the width of the dialog is changed in SASS themes

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#1331]
**Describe the bug**
When customizing the **kendo.prompt** dialog and defining a new width for it, the input field inside it doesn't resize according to the dialog's width when a SASS theme is applied. 

The issue is not reproducing when a LESS theme is applied. 

**To reproduce**
1. Open [this Dojo](https://dojo.telerik.com/aWAdELoK) and click on the "myprompt" button
2. See the length of the input field inside the dialog

**Expected behavior**
The input field inside the Dialog should expand to the borders of the dialog as it can be seen in [this Dojo](https://dojo.telerik.com/afowOLEn) that loads a LESS theme. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/75870705-0c7b8580-5e14-11ea-99ea-44560c7bc1a1.png)

**Affected package (please remove the unneeded items)**
* Default v2(SASS)
* Bootstrap v4(SASS)
* Material(SASS)

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment]
Note: after we refactor dialogs to use forms, this will change!
