### ISSUE TITLE
[Menu] the dropdown options list closes unexpectedly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1332]
**Describe the bug**
When using the bootstrap theme and opening the menu dropdown list, there is some space between the menu button and the dropdown list. If the cursor is over that location then the dropdown list closes. 

**To reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-wfa8p4?file=app/app.component.ts
**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by inikolova** [comment]
It appears a fix for this problem has been already pushed: 

https://github.com/telerik/kendo-themes/commit/f7abe08f9c44282bf0af80bf2d8448ee5816bf01#diff-fa07b9148db3147bc0e101b8230bffefL6

The problem should disappear with the next release of the Bootstrap theme
