### ISSUE TITLE
Pager duplicates page number 1

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-themes#1349]
When I use https://kendo.cdn.telerik.com/2020.1.219/styles/kendo.bootstrap-v4.min.css, the pager looks appropriate.  When I use https://cdn.jsdelivr.net/npm/@progress/kendo-theme-bootstrap@4.11.0, the pager duplicates page 1.

EDIT: This appears to be a regression issue.  I THINK https://cdn.jsdelivr.net/npm/@progress/kendo-theme-bootstrap@4.10.2 works.

Dojo of it working: https://dojo.telerik.com/oCUdATiJ
Dojo of it not working: https://dojo.telerik.com/oXuPUBUD
Dojo of it working in the previous version: https://dojo.telerik.com/imoXALeW

Please help, because I use the npm package to generate my CSS from SASS, and can't use the CDN version.

**Comment by joneff** [comment]
Kyle,

that's an inherent flaw in the distribution of kendo-themes. The themes serve kendo-jquery (and the derivatives), kendo-angular, kendo-react, kendo-vue and telerik-blazor. Excluding kendo-jquery, the rest if the suites, including the themes are distributed not on fixed dates, but as soon as ready. If a bug is found in a given suite, it can be targeted and released in due time. Unlike kendo-jquery that has a fixed product lifecycle -- three releases per year plus three service packs.

In other words, when me make changes in kendo-themes that affect kendo-jquery, while the themes will be available immediately (either on dev or stable channel), kendo-jquery release will take some more time to propagate. It could even be a couple of months, if the change was made right after service pack.

We know about that inherent flaw from day one and the only way to target it is to have semantic lifecycle of kendo-jquery, which for the time being is not an option.

The change in question is from #1322, which improves the current way of "transforming" the linear links to "popup" to actual native select element.

A temporary solution would be to have the following styles until 2020 R2:

```css
.k-current-page { display: none !important; }
```

when the rendering will be updated to match the styles.

On a side note, you do report a truly legitimate bug: if you explicitly set `pageable.responsive: false`, the pager shouldn't render the responsive part. We are going to fix that as well.

**Comment by DaleyKD** [comment]
Thank you so much for the wonderful explanation.

Is there a way to know when the kendo-theme lines up with a kendo-jquery release, and therefore, I'm content keeping my npm package at the same release cycle.

For the meantime, I've rolled back to @progress/kendo-theme-bootstrap: 4.10.2

And honestly, the only reason I set `responsive: false` is because I have a grid on a Bootstrap tab that's not active by default.  When I would activate that tab, the pager was calculated as being `.k-pager-md`, which was causing it to look different than the grid that was on the first, active Bootstrap tab.

**Comment by joneff** [comment]
> Is there a way to know when the kendo-theme lines up with a kendo-jquery release, and therefore, I'm content keeping my npm package at the same release cycle.

That is a great question, one I am afraid we do not address directly, but I think we can with 2020 R2: usually, a week before a release we produce a stable (not dev) version of the themes.  We can, from 2020 R2 onward, have an item in the change log that says: update kendo-themes to that and that version. We can also bump the npm dependency in `package.json` of the project.

Would something like that be of any help?

**Comment by DaleyKD** [comment]
That sounds great.  ANYTHING to assist in a release cadence that doesn't have me running `npm update` and getting borked. :)

The main docs makes no mention of this being an issue: https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes#using-the-build-process-of-the-application

**Comment by DaleyKD** [comment]
@joneff - I just noticed that 2020 R2 was released on April 6, 2020.  Where can I tell what version of the SASS theme (npm package) is for that?

**Comment by joneff** [comment]
Let me break down the version number (XXXX.Y.ZZZ), which unfortunately is not semver:

* XXXX, or in this case 2020 is the year
* Y, or in this case 1 is the major release
* ZZZ, or in this case 406 is the month and day in European format 6th of April.

The release you are referring to is 2020 R1 SP2 or 2020.1.406. and it was released with the same themes as 2020 R1 SP1 (because the fixes were purely in javascript), which are:

* @progress/kendo-theme-default@4.12.2 
* @progress/kendo-theme-bootstrap@4.10.2 
* @progress/kendo-theme-material@3.10.2 

2020 R2 should be out in early / mid May.

**Comment by DaleyKD** [comment]
Please forgive me, I feel like a moron.  I saw "SP2" and my mind read "R2."

Ignore me. :)

**Comment by joneff** [comment]
Quick update, 2020 R2 should be out next week.

With this, I am closing the issue.

**Comment by joneff** [comment]
The release is out and even the documentation: https://docs.telerik.com/kendo-ui/styles-and-layout/sass-version-compatibility. Yes, it's a short article, but we'll extend it both for future and previous versions.

**Comment by DaleyKD** [comment]
@joneff - This. is. GLORIOUS.

Thank you *SO* much.
