### ISSUE TITLE
In IE menu, context menu and grid's column menu overlaps or is shrink

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-themes#1360]
**Describe the bug**
In IE menu, context menu and grid's column menu overlaps or is shrink.

**To reproduce**

1. Go to http://kendobuild-windows.dev.progress.com/kendo-ui/menu/index
2. Check the menu items - they overlap

**Expected behavior**
The menu items, context menu, column menu don't overlap, have a box that is enough width to present them in a readable way.

**Screenshots**
![IE-ContextMenuShrinked](https://user-images.githubusercontent.com/52446546/76633047-ca0d2380-654c-11ea-9276-37b41cbe960e.png)
![IE-ColumnMenuShrinked](https://user-images.githubusercontent.com/52446546/76633055-cd081400-654c-11ea-965f-b86f7a5bb889.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* IE version: [11]

**Comment by inikolova** [comment]
The same problem can be observed with the Angular components too
