### ISSUE TITLE
Revise .k-action-buttons

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#1368]
The `.k-action-buttons` class is used across different components (Grid, Upload, Form, Spreadsheet, etc.) to position action buttons. The class however is very strict in terms of layout and does not allow to customize the position and also affect the inner buttons sizes. 

**Describe the solution you would like to see implemented**:

Revise the `.k-action-buttons` implementation and allow to:

* control the buttons positioning (flex-start, center, flex-end)  through classes.
* have stretched or normal buttons.

In addition to the above, some of the components that implement the `.k-action-buttons` class have additional styling that affects how the container looks. Consider making action buttons consistent across widgets.

**Comment by inikolova** [comment]
As discussed with @joneff, we should use the following classes: 
- k-actions (default) -> for normal buttons;
- k-actions-stretched -> for stretched buttons;

Buttons positioning:
- k-actions-start -> buttons are placed at the start;
- k-actions-center -> -> buttons are placed at the center;
- k-actions-end -> buttons are placed at the end;

@joneff @Juveniel @Raisolution @Xizario @silviyaboteva @hadjieva
