### ISSUE TITLE
The Upload Success Indicator shouldn't fade away

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#1371]
**Describe the bug**
The Upload Success Indicator shouldn't fade away as it currently does (as discussed with @ivelina-penkova )

- [x] jQuery - https://github.com/telerik/kendo/issues/10754

- [x] Angular 

- [x] React

- [x] Blazor

**To reproduce**
Check the Upload demo and upload an item.

**Expected behavior**
The progress indicator shouldn't fade.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Telerik UI for Blazor

**Comment by Raisolution** [comment]
@ivelina-penkova can we update [the design](https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/upload.png) with an example of file focused state in combination with Progress (blue) / Success (green) indicator? Currently the indicator is overlaping the bottom shadow which looks strange. I would like to confirm if this look is by design.

**Comment by kspeyanski** [comment]
Hello, jumping on here out of nowhere, but i have some questions.

For me, the fading of the success indicator is not something we should decide. Even if we are to provide a default behaviour, it still seems to me that it should be done per-theme, by following the specific design guidelines - which can further be customised through SASS or component-template.

I am able to observe a `fade-able` Progress Indicator in the [Material Design Guidelins](https://material.io/components/progress-indicators/#linear-progress-indicators)(the first illustration under the `Types` section), which leads me to believe that even if the indicator should fade away by default, this does not apply for the Material Theme.

Please let me know if i'm missing something.

**Comment by ivelina-penkova** [comment]
@joneff what do you think on the fading of the progress bar?

**Comment by Raisolution** [comment]
@ivelina-penkova Iva, any update on my question?

**Comment by ivelina-penkova** [comment]
@Raisolution Yes, this week the designs will be updated. The reason for the delay was that the fading progress bar and the validation process were also discussed with the front-enders and all changes will be applied together.

As agreed with the front-enders and @joneff on the case of the fading progressbar, we decided to make it an option which is turned off by default, but if a client needs it, he can turn it on.
