### ISSUE TITLE
Pager does not display page number

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-themes#1376]
**Describe the bug**
Using the latest kendo-theme-default the page number is not displayed. 

**To reproduce**
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/ekEfUkOw) 
1. Run this [Stackblitz](https://dm4o1d.run.stackblitz.io) for Vue-wrappers example
1. Notice page number is not displayed. The issue is reproducible with version 4.13.0 as well

**Expected behavior**
Page numbers should be displayed

**Screenshots**
v4.13.0 and latest:
![grid_pager_4 13 0](https://user-images.githubusercontent.com/46348689/76937656-e1a62c80-68fd-11ea-9526-b2127ba70095.jpg)

v4.12.2:
![grid_pager_4 12 2](https://user-images.githubusercontent.com/46348689/76937674-ecf95800-68fd-11ea-8b86-ccfe91e3aa8e.jpg)

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please remove the unneeded items)**
* All

**Comment by PreslavKozovski** [comment]
The same cause as https://github.com/telerik/kendo-themes/issues/1349

**Comment by TeyaVes** [comment]
no longer reproducible as of Kendo v. 2020.2.513
