### ISSUE TITLE
Broken Grouping headers in Bootstrap - AutoComplete, ComboBox, DropDownList, MultiSelect

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#138]
Both LTR and RTL - https://demos.telerik.com/kendo-ui/multiselect/grouping:
![image](https://user-images.githubusercontent.com/6614183/39122251-f8e78490-46fc-11e8-9893-efb5139946b2.png)

**Comment by politigf** [comment]
Can we get an update on when this will get fixed?

**Comment by Dimitar-Goshev** [comment]
@politigf We plan to fix this issue for R1 2019 release. Please note that in case there are issues with higher priority in our R1 2019 backlog, the fix may be postponed. Tracking the issue's progress will update you when it is closed.
