### ISSUE TITLE
Revise upload styles

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#1391]
- [x] "_Drop files here to upload_" hint should be permanently visible
As discussed offline, the _k-dropzone-hint_ element should be initially visible and its visibility should be controlled via the **k-hidden** class:
    - add the **k-hidden** class while uploading;
    - remove the **k-hidden** class when dragging a file to upload.

**Edit:** Due to some specifics in Angular, the Upload component in Kendo UI for Angular suite will not follow this approach. Instead, the _k-dropzone-hint_ element will be rendered **after** the _k-upload-status_ element and their visibility will be controlled via CSS.

- [x] There should be hover effect for the dropzone

- [x] There should be grey background color behind the progress indicator; Progress indicator should be moved to top and respects the ._k-file_ padding
**Edit:** As discussed offline, to achieve this outcome we should use the following HTML: 

```
<div class='k-progressbar'>
    <span class='k-progress'></span>
</div>
```

- [x] The validation messages will be wrapped in .k-file-validation-message container and depending on the success or failure add k-text-success and k-text-error

- [x] Remove the k-i-file-error and k-i-files-error icons in the invalid state, keep the original ones

- [x] Batch Upload - when uploading multiple files, there should be file size shown below each file. The rendering, discussed offline should be: 
```
<span class="k-multiple-files-wrapper">
    <span class="file-name-size-wrapper">
         <span class="file-name"></span>
         <span class="file-size"></span>
    </span>
    <span class="file-name-size-wrapper">
         <span class="file-name"></span>
         <span class="file-size"></span>
    </span>
    ......
</span>
```

CC: @joneff @Raisolution @vladimirivanoviliev @Juveniel @TeyaVes @Stamo-Gochev

**Comment by inikolova** [comment]
All changes have been implemented in the Kendo UI jQuery and Angular suites

**Comment by Stamo-Gochev** [comment]
@matanasov Can we make a test whether the updated styles cause any issues with the current blazor upload rendering? The styles can be built from the [branch](https://github.com/telerik/kendo-themes/tree/upload-redesign-styling#development) and tested locally as they are not merged to `@dev` yet.

**Comment by matanasov** [comment]
Yes there are changes. I tested only Default and I am pasting some images here. 
Once this is at least in Dev, we can make more detailed tests:

![image](https://user-images.githubusercontent.com/5861835/80730202-f3403e00-8b11-11ea-803c-55200bf2da9f.png)

![image](https://user-images.githubusercontent.com/5861835/80729701-4ebdfc00-8b11-11ea-91d7-36e33b192790.png)

![image](https://user-images.githubusercontent.com/5861835/80729814-72814200-8b11-11ea-83d3-29f3bf46ac2f.png)

**Comment by inikolova** [comment]
@matanasov, I pushed a fix which should address the illustrated problems
