### ISSUE TITLE
$enable-rounded variable causes compilation error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1403]
**Describe the bug**
Using the **$enable-rounded** variable and compiling the SCSS with **"node-sass": "^4.13.1"** the following error is thrown:

```
SassError: ".k-card-header" failed to @extend "%top-rounded-child".
       The selector "%top-rounded-child" was not found.
       Use "@extend %top-rounded-child !optional" if the extend should be able to fail.
```

**To reproduce**
Please check the attached Angular 9 project. Use the $enable-rounded variable in the root styles.scss file:

```
$enable-rounded: false;

@import "~@progress/kendo-theme-default/dist/all.scss";
```
and try to run it:
 
[scss-build.zip](https://github.com/telerik/kendo-themes/files/4381612/scss-build.zip)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by JohannesHoppe** [comment]
This is a blocker here! 😞

**Comment by JohannesHoppe** [comment]
It looks like `npm uninstall node-sass` solves the problem.
Then the Angular CLI uses dart-sass instead of node-sass.

**Comment by JohannesHoppe** [comment]
see also https://github.com/telerik/kendo-themes/issues/834#issuecomment-608309954

**Comment by kdubious** [comment]
Also failed with gulp-sass installed, and `npm uninstall gulp-sass` fixed it.
