### ISSUE TITLE
input\_theme.scss contains an invalid comma

### ISSUE THREAD

**Issue by darrellzook** [telerik/kendo-themes#1404]
This section contains an invalid comma after "$input-focused-border":

        &:focus,
        &.k-state-focused {
            @include fill (
                $border: $input-focused-border,
            );
            @include box-shadow( $input-focused-shadow );
        }

**Comment by darrellzook** [comment]
this is a duplicate of https://github.com/telerik/kendo-themes/issues/1385

**Comment by joneff** [comment]
@darrellzook just for context, can you tell in which theme this was happening? I skimmed trough the themes and I found one instance where we have this sort of code and it's been fixed for a while.

**Comment by darrellzook** [comment]
It was in the bootstrap theme. The one place I remember seeing this (bootstrap/scss/input/_theme.scss) was fixed April 8 with this commit: https://github.com/telerik/kendo-themes/commit/6e7e507c748c32a1d45842690aefe5d4a7677a5e#diff-071a945b924402903caa772f49694a45. The error was on line 23, but that line was removed in this commit.

**Comment by joneff** [comment]
Thanks! Like you said, we fixed that, but I wanted to make sure if we missed a place.
