### ISSUE TITLE
Kendo Forms styles

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#1407]
Implement styling of the forms and form-bound components corresponding to the new design and the dev implementation of the components related to this Enhancement. Cover all the differences in the rendering per suite.

related to: https://github.com/telerik/k2/issues/150
related to: https://github.com/telerik/k2/issues/194

- [x] All form related styles should be in `forms/_layout.scss` file
- [x] Add support for form layout - horizontal/vertical
- [x] Add support for form group (fieldset and legend)
- [x] Add support for aligning (left/right/stretched?) and wrapping the form buttons in a separate container element
- [x] Consider `width: 100%` of the widgets where needed
- [x] Add styles for Labels, Optional text, floating labels
- [x] Add styles for Hint and Error messages
- [x] Add styles for a validation summary message
- [x] Add visual tests with all the configuration scenarios and all form-bound widgets
- [x] Add styles for Checkbox&Radio button groups (@inikolova )
- [x] Consider allowing empty labels for alignments (@joneff )
- [ ] Tooltip validation revisit styles & apply fixes if needed
- [x] Fix all inconsistent state styles of the widgets (error, disabled, readonly states) (@inikolova )
- [x] RTL syles for all above
- [ ] Variables & documentation

- [ ] **Important** Add visual tests with at least 2 complex forms (from the Scheduler, for example)

cc:// @joneff @inikolova @Raisolution 	@tapopov @vladimirivanoviliev 
@telerik/kendo-front-end

**Comment by JoomFX** [comment]
implemented with https://github.com/telerik/kendo-themes/pull/1399
