### ISSUE TITLE
Component density

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1408]
Related to #1090.

Unlike size, which may alter font-size, line-height, padding and border, density only alters padding. In other words, it gives a visually denser component, without necessarily being smaller proportionally.

As per discussion and [material specification on density](https://material.io/design/layout/applying-density.html), denser components will happen at steps with each step taking a fixed amount of padding away from the component.

**Describe the solution you would like to see implemented**

Provide class names for setting density.

**Describe the alternatives you have considered**

There is no viable alternative than providing built in classes. Customizing the components outside of the scope of the framework would yield inconsistent results at best.

**Comment by hadjieva** [comment]
Duplicated with this one: #1090
