### ISSUE TITLE
Revisit all components error state styles

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#1425]
**Describe the bug**
Currently there are some bugs across the styles of the components which can be form-bound and have error states. Some components have red borders, that disappears on hover, some of the dateinputs or dorpdowns have icons, which are not styled with the error color when in error state.

**To reproduce**
Please, revisit and fix all design inconsistent components 

**Screenshots**
![image](https://user-images.githubusercontent.com/8842674/78035377-b4339700-7371-11ea-9133-4e9ba7a69d11.png)

![image](https://user-images.githubusercontent.com/8842674/78035568-f52bab80-7371-11ea-8649-393b19678fb0.png)

![image](https://user-images.githubusercontent.com/8842674/78035595-fbba2300-7371-11ea-8825-460f669c840c.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Comment by inikolova** [comment]
As discussed with https://github.com/tyanko, both - text and icon, in components (such as DropDownList, Combobox, DatePicker, TimePicker, DateTimePicker) should keep their theme color in error state (not getting the error color)
