### ISSUE TITLE
Too big padding for input in RTL mode

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-themes#143]
It can be seen on our official demos.
Please refer to this [online demo](https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/rtl/)
As you can see autocomplete has too big padding.
kendo-theme-default version 2.50.0
![screenshot](https://user-images.githubusercontent.com/4143177/39195694-05d831d0-47e9-11e8-9590-909e7671930e.png)

**Comment by ipeshev** [comment]
![screenshot](https://user-images.githubusercontent.com/4143177/41912384-3f6bc1c8-7958-11e8-8020-16bdc1b3949f.png)
Still the padding is not looking right.

**Comment by joneff** [comment]
Appears to be fixed now
