### ISSUE TITLE
Grid Pager is misaligned when using SASS to build the Bootstrap theme together with the original Bootstrap

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-themes#1437]
**Describe the regression**

The grid pager is now misaligned.

**To reproduce**

1. Run the following Blazor app: https://github.com/telerik/blazor-dashboard - it follows the build process advised by @joneff 
1. Go to the Issues page
1. Look at the pager

**Expected behavior**

aligned pager like it is right now

**Screenshots**

Before: 
![aligned-pager](https://user-images.githubusercontent.com/5746515/78354912-6ad38980-75b5-11ea-8a18-33ae4fd23920.png)

After: 
![broken-pager](https://user-images.githubusercontent.com/5746515/78354954-83dc3a80-75b5-11ea-9693-45c0a302efbf.png)

**Affected package (please remove the unneeded items)**

* theme-bootstrap

**Affected suites (please remove the unneeded items)**

* Telerik UI for Blazor

Note: I don't know if this will affect other suites, Blazor shares rendering with React and Angular, afaik

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: [Windows]
* Node version: [v12.16.1 on my PC, not sure what we have on the build PC]
* NPM version: [v6.13.4  on my PC, not sure what we have on the build PC]

**Additional context**

There seems to be a new wrapper on the pager rendering that is probably the cause. I am not sure how the themes are supposed to handle this since already have the following in the package.json

```
  "devDependencies": {
    "@progress/kendo-theme-bootstrap": "latest",
```

![new-pager-rendering](https://user-images.githubusercontent.com/5746515/78355392-475d0e80-75b6-11ea-827e-f545330da2a6.png)
![old-pager-rendering](https://user-images.githubusercontent.com/5746515/78355394-47f5a500-75b6-11ea-96e1-e33f2895696a.png)

**Comment by TeyaVes** [comment]
The issue was caused by the fact that the app didn't use the latest styles.

**Comment by marin-bratanov** [comment]
Then please fix the app to use them, because it uses the approach advised by the FE team, and it does not seem to work. It is being advertised as the correct approach.

**Comment by TeyaVes** [comment]
@joneff , can you please give more information on the issue here

**Comment by marin-bratanov** [comment]
bump?

**Comment by marin-bratanov** [comment]
Hopefully fixed with https://github.com/telerik/blazor-dashboard/pull/5 and adding explicit build steps through `npm`. Basically the same commands but through VS task runner that executes `gulp` directly did not work for me previously.
