### ISSUE TITLE
IE11: Kendo Menu: Menu Items: Piled on top of each other

### ISSUE THREAD

**Issue by frederikdekegel** [telerik/kendo-themes#1442]
**Describe the bug**
In IE11, all menu items are piled on top of each other.

**To reproduce**

1. Open https://www.telerik.com/kendo-angular-ui/components/menus/menu/ in IE11
2. View the example

**Expected behavior**
In IE11, all menu items are aligned next to each other as is the case in Chrome, ...

**Screenshots**
![kendo-menu-ie11](https://user-images.githubusercontent.com/8667499/78378442-3d94d480-75d1-11ea-8fe5-13cb48994bc5.jpg)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* IE version: 11

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
This is broken since at least theme-bootstrap 4.12 and theme-default 4.14

**Comment by inikolova** [comment]
Hi, @frederikdekegel. This issue has been already addressed in the Kendo UI themes - 
https://github.com/telerik/kendo-themes/issues/1360
