### ISSUE TITLE
Wrong position of File/Image Browser search in Kendo UI for jQuery Editor

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#1447]
**Describe the bug**
Wrong position of File/Image Browser search in jQuery Editor

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/editor/imagebrowser
1. Click on Image Editor tool

**Expected behavior**
Search is to the right border:
![File and image browser in Kendo UI Editor _ Kendo UI demo - Google Chrome 2020-04-06 09 09 41](https://user-images.githubusercontent.com/6614183/78527738-69d56e80-77e6-11ea-8c32-feba4b586700.png)

**Screenshots**
Search is after the breadcrumb
![File and image browser in Kendo UI Editor _ Kendo UI demo - Google Chrome 2020-04-06 09 10 51](https://user-images.githubusercontent.com/6614183/78527792-8a052d80-77e6-11ea-9016-9c26e83a499c.png)

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by Dimitar-Goshev** [comment]
This issue is no longer reproducible, as the Search is inside the toolbar since R2 2020:
![File and image browser in Kendo UI Editor _ Kendo UI demo - Mozilla Firefox 2020-05-19 11 27 00](https://user-images.githubusercontent.com/6614183/82303551-c1f5b800-99c3-11ea-9b26-a5306f55ff43.png)

**Comment by joneff** [comment]
Yeah, I fixed that when refactoring the imagebrowser.
