### ISSUE TITLE
Can not set text-align on GridColumn via className

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1449]
Related to: https://github.com/telerik/kendo-react/issues/545.

## I'm submitting a...
* Bug report 

## Current behavior

Cannot set per-column text-align via classes on the react grid due to text-align: inherit being set on td on line 10767 of all.scss

## Expected behavior

I expect there not to be unnecessary css that interferes with customization.

## Minimal reproduction of the problem with instructions

Just add a className to GridColumn that has text-align and color. You will see color applied, but not text-align.
https://stackblitz.com/edit/react-dkef5a?file=app%2Fmain.jsx

## What is the motivation or use case for changing the behavior?
To set the text-align dynamically, per column.

## Environment

Browser:

- Chrome (desktop) version 79.0.3945.88 (Official Build) (64-bit)

**Comment by joneff** [comment]
We already have classes that can customize text align:
* `k-text-left`
* `k-text-right`
* ...

The selectors have `0 1 1` specificity, which is quite small. we could, eventually, bring it down to `0 0 2` or `0 0 1` if we expose global page styles.

Closing as `wontfix`
