### ISSUE TITLE
Notification component doesn't wrap the message text inside it (LESS themes only)

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#1459]
**Describe the bug**
The Notification component doesn't wrap long message texts in all LESS themes. 

* This is a regression introduced in the 2019.2.619 release.

**To reproduce**

1. Go to [this Dojo](https://dojo.telerik.com/IHakuYAZ) and runt it
1. See how the message inside the Notification appears

**Expected behavior**
The Notification text should be wrapped as can be seen in [this Dojo project](https://dojo.telerik.com/EjalabUV).

**Screenshots**
Expected behavior:
![image](https://user-images.githubusercontent.com/41293735/78865746-dcdd2000-7a46-11ea-865f-7829ee8afe08.png)

Current behavior:
![image](https://user-images.githubusercontent.com/41293735/78865762-e5cdf180-7a46-11ea-988d-7e5a2366642b.png)

**Affected package (please remove the unneeded items)**
* All LESS themes

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by TeyaVes** [comment]
This is happening when a custom template is used. If the template follows the correct rendering of the notification and the content is wrapped in k-content-notification class, the overflow issue will be fixed: https://dojo.telerik.com/IHakuYAZ/3
