### ISSUE TITLE
Grid row height changes on focusing and then blurring cells 

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#1463]
**Describe the bug**
Unexpected change of row height on focusing/blurring cells.

**To reproduce**

1. Go to [https://dojo.telerik.com/uPOjecEC/3](https://dojo.telerik.com/uPOjecEC/3)
1. Focus random cells.
1. If the behavior is not visible right away, narrow down the dojo's output pane.

See the attached video for a demonstration of the issue. 
[Recording #18.zip](https://github.com/telerik/kendo-themes/files/4458598/Recording.18.zip)

The recently added padding calculation is related to the issue:
```
.k-grid .k-command-cell, .k-grid .k-edit-cell, .k-grid .k-grid-edit-row td {
    padding: calc(.75rem - (1.5em + .75rem + 2px - 1.5em)/ 2) .75rem
}
```
The following can be used as a temporary **workaround**:
```
.k-grid .k-command-cell, .k-grid .k-edit-cell, .k-grid .k-grid-edit-row td {
  padding: .75rem .75rem;
}
```

**Expected behavior**
The rows should keep their initial height. 

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
*Windows

**Comment by joneff** [comment]
Fixed by #2594
