### ISSUE TITLE
Radio button cannot be toggled if clicked between the input and the label

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1465]
**Describe the bug**
Currently, the label has an 8px margin-lef that applies the needed spacing between elements. 

**To reproduce**
If you place your cursor between the label and the radio button over the mentioned margin, your click is not registered.

**Expected behavior**
That area to be clickable. 
The solution would be to use padding-left instead of margin-left.

**Screenshots**
-

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
-

**Comment by joneff** [comment]
If the radiobutton / checkbox is outside of `label` element, that's expected -- you are clicking in the "dead" space between the two.

If the said input is inside the `label`, then it's a bug. Which one is it?

**Comment by silviyaboteva** [comment]
The first one. The input and the label are siblings.

**Comment by joneff** [comment]
That's expected behaviour -- the same will happen if you have native elements. Closing this one as invalid.
