### ISSUE TITLE
[Scheduler] Rows are misaligned 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#1466]
**Describe the bug**
Scheduler rows are misaligned in IE and Chrome (when the browser is zoomed). 

Default theme (v**4.17.0**)
IE (zoom 100%)
![IE-100%_zoom](https://user-images.githubusercontent.com/33104481/78984808-d8d8fd00-7b2f-11ea-8d36-1f13e56e8106.png)

Chrome
zoom 150%
![2020-04-10_133](https://user-images.githubusercontent.com/33104481/78984925-29e8f100-7b30-11ea-87ba-ab665f1da34b.png)

Bootstrap theme (v**4.15.0**)
IE  - when [kendoSchedulerMajorTimeHeaderTemplate ](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/MajorTimeHeaderTemplateDirective/) is used:
![Bootstrap-IE](https://user-images.githubusercontent.com/33104481/80365460-4e62fe00-8890-11ea-8b57-2ec594740bc9.png)

In Chrome the more you scroll down the more misaligned it gets with zoom:
https://screencast-o-matic.com/watch/cYf66Eagnw

Material theme (v**3.14.0**)
Rows are aligned correctly in both browsers.

FF works as expected in all cases.

**To reproduce**
1. Go to [https://www.telerik.com/kendo-angular-ui/components/scheduler/#toc-basic-usage](url) StackBltz example
1. Change the browser zoom with different themes
1. Scroll the Scheduler

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Chrome version: [80.0]
* IE version: [11.1304]

Similiar issue #554

**Comment by joneff** [comment]
I should not that we do not commit to supporting zoomed browsers. Still, the issue appears to have been fixed in Chrome at least.
