### ISSUE TITLE
MultiSelect is misaligned when using floating label

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1468]
**Describe the bug**
When the MultiSelect is used with a floating label it isn't aligned properly to other input elements

**To reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-4tq9po-mlipsu?file=app%2Fapp.component.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/20015190/79111006-585f0a00-7d84-11ea-9e28-88ae698e86a8.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by inikolova** [comment]
It appears the problem has been addressed in the latest version of the theme, so I am closing the issue
