### ISSUE TITLE
File to import not found or unreadable: chat

### ISSUE THREAD

**Issue by datadisc** [telerik/kendo-themes#147]
File to import not found or unreadable: chat.
      in P:\najem_na_karte\vhost\htdocs\back\node_modules\@progress\kendo-theme-bootstrap\scss\all.scss (line 87, column 1)

when compiling assets with webpack

**Comment by gyoshev** [comment]
Thank you for reporting this, the chat.scss file was added at a different location. The next development build, which will be available in a few minutes, will resolve the problem. Strangely, the theme builds were successful even though the file was missing.
