### ISSUE TITLE
The default hover color of the text in Bootstrap 4 Flat swatch results in hidden text issues in some components

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#1480]
**Describe the bug**
The default colors of the Bootstrap 4 "Flat" swatch result in unexpected behavior in some components. There are areas in components like the PivotGrid and Gantt which text "disappears" when they are being hovered. 

The default hover color of the text in the theme is the same as the header background value which results in the mentioned text "disappearing" when we hover some parts of the components.  

**To reproduce**

1. Go to https://themebuilder.telerik.com/kendo-ui
1. Select "Bootstrap" and then click "Create"
1. Select "Flat" color combination from the color swatches on the left
1. Scroll to PivotGrid and hove the area with text "All Categories" or "Beverages	Condiments	Produce	Meat/Poultry	Seafood"
1. Scroll to the Gantt component and hover the header elements in the component's timeline. 

When the mentioned above parts o the components are being hovered, the text is colored with the same color as the background making it to "disappear". 

**Expected behavior**
When hovered, the text in the described areas should stay visible 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/79345609-006a0400-7f3a-11ea-849b-d4bc3449ef43.png)

![image](https://user-images.githubusercontent.com/41293735/79345444-cb5db180-7f39-11ea-8d7b-338e479e43dc.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
We split the flat swatch into two separate swatches: `turquoise` and `turquoise dark`. As such this issue is no longer relevant.
