### ISSUE TITLE
In the Material theme, on the Dark color swatches, the input element with k-textbox class has black background with black text 

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-themes#1488]
**Describe the bug**
In the Material theme, on the Dark color swatches, the input element with k-textbox class has a black background with black text.

**To reproduce**

1. Open [ThemeBuilder](https://themebuilder.telerik.com/kendo-ui)
1. Select Material theme, DateRangePicker widget, and a Dark color swatch

**Expected behavior**
Background and text colors should be different so the text is readable, similar to DropDownList widget

**Screenshots**
![image](https://user-images.githubusercontent.com/46348689/79474300-e4846200-800e-11ea-836f-caf588202be8.png)

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Comment by TeyaVes** [comment]
related to: https://github.com/telerik/kendo-themes/issues/856

**Comment by TeyaVes** [comment]
No longer reproducible as of v. 2020.2.513
