### ISSUE TITLE
Calendar broken layout in mat-tab

### ISSUE THREAD

**Issue by tburi** [telerik/kendo-themes#1495]
**Describe the bug**
The calendar layout is broken when inside a `mat-tab`, scrolling the calendar makes the date jump between 1900 and 2099

**To reproduce**
https://stackblitz.com/edit/angular-m14nyp-7dyyxc

**Screenshots**
![s1](https://i.imgur.com/SHQludu.png)
**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by inikolova** [comment]
According to the Angular material docs, _If the tab contains several complex child components or the tab's contents rely on DOM calculations during initialization, it is advised to lazy load the tab's content._
https://material.angular.io/components/tabs/overview#lazy-loading

Declaring the calendar in a ng-template with the matTabContent attribute fixes the issue. For your convenience below is the updated example: 

https://stackblitz.com/edit/angular-m14nyp-1jxhiu?file=app/app.component.html
