### ISSUE TITLE
The Editor is broken when using the latest version of the Default theme

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1505]
**Describe the bug**
When using the Kendo UI for jQuery Editor inside an Angular 8 or 9 application (as demonstrated in [this article](https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/)) and using the latest theme version the layout of the Editor breaks:

![image](https://user-images.githubusercontent.com/20015190/80116986-499c0280-858f-11ea-8373-7551c525157d.png)

Using version 3.7.0 of the Default theme resolves the issue.

**To reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-xkkqmx?file=src/index.html

I am also attaching a project demonstrating the described setup using Angular 8 and Angular 9. Please use the latest version of the Default theme to reproduce issue and use version 3.7.0 to see that it functions as expected:
[editor-jquery-ng9.zip](https://github.com/telerik/kendo-themes/files/4523500/editor-jquery-ng9.zip)
[editor-jquery-ng8.zip](https://github.com/telerik/kendo-themes/files/4523501/editor-jquery-ng8.zip)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
@svetq, as a general rule, kendo-jquery can not be run against arbitrary version of the themes. When 2020 R2 is out, can you double check again?

**Comment by kakone** [comment]
I confirm this very annoying bug with the latest version (and we use the good corresponding version of the theme). We will check with the 2020 R2 version too.

**Comment by inikolova** [comment]
Hi guys, I tested this example using the latest version Kendo UI for jQuery (2020.2.513) and the latest version of the default theme and everything is working as expected on my side (https://stackblitz.com/edit/angular-hkohxd?file=src/app/app.component.ts). Therefore I am closing this issue.
