### ISSUE TITLE
[NumericTextBox] Spinners overflow in Edge when width is below 200px

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#1506]
**Describe the bug**
The NumericTextBox spinners are no longer within the component when the width goes below 200px in Edge:

**To reproduce**

1. Go to https://stackblitz.com/edit/angular-vfubww?file=app/app.component.ts
1. Resize the demo until the example viewport is below 200px

**Expected behavior**
The behavior should be the same across all supported browsers.

**Screenshots**
Reported in the following issue:

https://github.com/telerik/kendo-angular/issues/2853

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Edge

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by inikolova** [comment]
Тhe issue cannot be observed in the latest version of Edge -> 81.0.416.64
