### ISSUE TITLE
In jQuery 3* Editor Create Table does not display properly the cells in its pop-up

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#1509]
**Describe the regression**
In jQuery 3* Editor Insert Table does not display properly the cells in its pop-up

**To reproduce**
Run the following Dojo and click the Create table tool:
http://kendobuild.telerik.com/dojo-staging/EQOhoCAD/2

Its cells will be rendered like so:
![CreateTableTool](https://user-images.githubusercontent.com/3431388/80217073-c1c5ff00-8647-11ea-8a59-a38d8898581b.png)

The issue is because of the `display: flex` applied to the pop-up element upon calling the `jQuery.show()` method.

**Expected behavior**
Cells should be properly positioned.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by Juveniel** [comment]
The insert table tool layout is broken in the jQuery Editor, as the cells need to be wrapped in a block element, similar to the rendering in React and Angular.

Handled in Kendo jQuery with https://github.com/telerik/kendo/commit/719dc9a85cd21dce3d878da9d96c32a6312d82e2

**Comment by kjeyakanthan** [comment]
Is there a workaround till the fix is released? or will there be a hotfix made available? Thanks for you work

**Comment by Juveniel** [comment]
@kjeyakanthan The fix will be included with the upcoming Kendo jQuery Service Pack that is scheduled for mid to late June. The fix is also available in the Latest Internal Build that you can download from [your Telerik Profile](https://www.telerik.com/account/product-download?product=KENDOUICOMPLETE).

**Comment by kjeyakanthan** [comment]
Thanks @Juveniel. Unfortunately the latest Latest Internal Build on my Telerik Profile for Kendo UI for JQuery is 2020.1.402 released 2nd April. I will follow up with a support ticket to see what is going on.

**Comment by Dimitar-Goshev** [comment]
@kjeyakanthan The fix is now available in the Latest Internal Build for Kendo UI for jQuery 2020.2.528.
