### ISSUE TITLE
The Drawer in Blazor has some styles that don't follow the design

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-themes#1550]
**Describe the bug**
Some of the styles for Bootstrap and Material themes are not following the design

**To reproduce**

1. Go to 'https://winslaveblazor.dev.progress.com/blazor-ui-production/drawer/overview'
2. Inspect the styles

**Expected behavior**
Styles follow the design (see screenshots bellow)

**Screenshots**
 - [x] Bootstrap icon sizes/padding
![image](https://user-images.githubusercontent.com/5861835/81684969-31b5f100-9460-11ea-98ab-6a97855198c2.png)

Teya: In Bootstrap, the padding and icon size depend on the font-size of the root element (it's in rem units). In the blazor demo website, the font-size of the <html> element is 14px, which is why the padding is smaller than the one on the design. 

 - [x] Bootstrap active/focused item border

![image](https://user-images.githubusercontent.com/5861835/81685322-a721c180-9460-11ea-8401-504710b18392.png)

 - [x] Material Focused style over selected item:

![image](https://user-images.githubusercontent.com/5861835/81685129-7e013100-9460-11ea-9b33-56e0f10ee9d8.png)
 

**Affected package (please remove the unneeded items)**

* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**

**Comment by joneff** [comment]
@matanasov regarding the blue colors in Bootstrap theme -- we follow bootstrap guidelines so it's possible that we differ from the design.

**Comment by matanasov** [comment]
It is not the colors but "_Bootstrap active/focused item **border**_"

**Comment by TeyaVes** [comment]
@joneff , The box-shadow of the focused items in Bootstrap in the design is 2px, while what we currently have in the drawer is 3px. This is because we are using the list-item focused styles.
