### ISSUE TITLE
Combobox list items incorrect layout

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#1569]
**Describe the bug**
Importing the ComboBox SCSS style file breaks the list items layout when enabling the [virtual scrolling](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/virtualization/) functionality.

![2020-05-22_1555](https://user-images.githubusercontent.com/33104481/82669758-ab11c880-9c44-11ea-8e0a-efe953dcc7c3.png)

**To reproduce**
1. Download and extract the file.
1. Execute **npm install** command in the root folder
1. Execute **ng serve** command
[combobox.zip](https://github.com/telerik/kendo-themes/files/4668213/combobox.zip)

**Comment by ipeshev** [comment]
The client wasn't loading all.scss but only combobox style, thus missing popup styles needed,
