### ISSUE TITLE
Bootstrap SCSS compile error with $enable-rounded: false;

### ISSUE THREAD

**Issue by Metricity** [telerik/kendo-themes#157]
Hi,

I've encountered the following error when setting $enable-rounded to false, the error mentions including optional which may suffice.
(2.12.1)
```
".k-card-header" failed to @extend "%top-rounded-child".
The selector "%top-rounded-child" was not found.
Use "@extend %top-rounded-child !optional" if the extend should be able to fail.
node_modules\@progress\kendo-theme-bootstrap\modules\@progress\kendo-theme-default\scss\card\_layout.scss (line 33, column 17)
```

Example SCSS
```
$enable-rounded: false;
@import "node_modules/bootstrap/scss/bootstrap";
@import "~@progress/kendo-theme-bootstrap/scss/all.scss";
```

Previous versions of the sass compiler allowed empty selectors to compile see https://github.com/sass/node-sass/issues/1469 for some background on the changes.

**Comment by andreavitali** [comment]
I got the same error using bootstrap 4.1.1 and kendo-theme-bootstrap 2.13.2

**Comment by gyoshev** [comment]
The issue has been fixed in `@progress/kendo-theme-bootstrap@2.13.3`.

**Comment by x2764tech** [comment]
This seems to have crept back into 4.10.1 - 

```
The selector "%top-rounded-child" was not found.
Use "@extend %top-rounded-child !optional" if the extend should be able to fail.
on line 95 of node_modules/@progress/kendo-theme-bootstrap/modules/@progress/kendo-theme-default/scss/card/_layout.scss
>>         @extend %top-rounded-child;
```

**Comment by joneff** [comment]
@x2764tech I think it's related to recent reports we had about placeholder selectors not being extensible when the theme is imported inside a class. See #1235
