### ISSUE TITLE
Remove the browser text selection when multiple items are selected

### ISSUE THREAD

**Issue by KristianMariyanov** [telerik/kendo-themes#1578]
**Describe the bug**
When you select the items with range selection (shift + click) in the Grid and TreeView, the part of the text between the selected items is selected too.

**To reproduce**
Go to the online demo of the grid with multiple selection enabled.

- Click on an item.
- Hold shift and click on another item (click on the text of the item)

**Expected behavior**
The text is not selected when you make a range selection, but you still can select the text in other cases.

**Screenshots**

![treeview-demo](https://user-images.githubusercontent.com/6886919/83010901-a7ee5200-a021-11ea-83fb-87a1a9773622.gif)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
We should leave some of the selection of the text, especially in the grid. Maybe we could just remove the selection when the item is selected.

**Comment by Stamo-Gochev** [comment]
Might not be possible with CSS-only in all cases though: https://github.com/telerik/blazor/issues/318#issuecomment-525738088

**Comment by TeyaVes** [comment]
this should be handled in the source, not in the themes.
