### ISSUE TITLE
Bulk edit grid validation tooltip not displayed correctly in IE11 

### ISSUE THREAD

**Issue by Jekata** [telerik/kendo-themes#1592]
**Describe the bug**
The validation tooltip is displayed incorrectly in IE11 when the column is resized too wide.

**To reproduce**

1. Please run this dojo
[http://dojo.telerik.com/oBoNataJ](http://dojo.telerik.com/oBoNataJ)
2. Expand Product Name column - horizontal scrollbar appears
3. Scroll to the far right
4. Add new record
5. Clear the Units in Stock entry on the new record and move off

6. The error message is unreadable

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5063488/83635105-4fccc800-a5ac-11ea-9e25-22929e7848a1.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* Internet Explorer 11

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
[ticket](https://supportheroes.telerik.com/ticket/1469778)

**Comment by joneff** [comment]
Appears to be fixed.
