### ISSUE TITLE
Calendar Design enhancements

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#1602]
Update calendar styles as per latest design:

https://github.com/telerik/kendo-ux-private/blob/master/Calend%D0%B0r/design:guides/New%20Calendar%20guideline.png

The major difference is in the selected state of the months:

### Current
![calendarcurrent](https://user-images.githubusercontent.com/45764088/84119376-ef6ed800-aa3c-11ea-856e-b92f410af43e.png)

### Expected
![calendartobe](https://user-images.githubusercontent.com/45764088/84119410-fc8bc700-aa3c-11ea-968b-88dc35632439.png)

Also, the TODAY link should not have an outline when focused.

**Comment by JoomFX** [comment]
As per the [latest design](https://xd.adobe.com/view/a177c722-7f4d-4e25-89b7-39cda8b0a4e6-f424/), the selected state is as it should be, meaning filling the cell with a solid background-color.
The red dot (shown in the screenshot above) should be used as an indicator that on this date/month there is an event scheduled, which is out of the calendar scope as of now.

The TODAY link also does not have an outline when focused, therefore I'm closing this issue.
