### ISSUE TITLE
Create a json file for theme variables

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1610]
We need a json file containing all the meta information about variables in the theme:

* friendly name
* description
* group
* deprecated version
* deprecated description
* variable type (unit, color, ... )
* variable sub type ( text color, border-color ... )
* value, as is
* value, computed
* parent variable(s), if it uses
* derived (children) variables, if any

The above implies that we have annotations for friendly name and sub type and any additional meta we need that cannot be generated.

At the end the json should look like:
```js
{
    "version": "VERSION", // the semantic version of the theme
    "name": "theme-name", // the name of the theme
    "variables": {
        "$blue": {
            "name": "", // friendly name, from annotation
            "description": "", // description, from annotation
            "deprecated": "VERSION", // the semantic version, from annotation
            "deprecatedDescription": "", // reasoning behind deprecation, from annotation
            "group": "", // group name, from annotation
            "type": "color", // sass variable type, from annotation 
            "subtype": "text-color", // custom subtype, from annotation
            "value": "as is | EXPRESSION -> native css, function, var-ref", // generated
            "computed-value": "computed", // generated
            "parent": "$VARIBALE_NAME || EMTPTY_STRING", // generated
            "children": ["$VAR_NAME", "$VAR_NAME", "EMPTY_ARRAY"] // generated
        }
    },
    ...
}
```

We also need a json schema to validate against.

The resulting file can be used to generated to augment the documentation, create variables hierarchy or if needed to be consumed from other applications like Sass Themebuilder.

**Comment by joneff** [comment]
Those might be worth looking at:
* https://www.npmjs.com/package/sass-extract
* https://github.com/mrmlnc/scss-symbols-parser

**Comment by eeasss** [comment]
@joneff what would be the composition? Is there one file per component + references to global files, or other structure would be in place?  One of the things that I dislike about JSON is that it doesn't allow comments, so those comments should either be part of the JSON structure or we should use JS files instead.

**Comment by joneff** [comment]
That's a good question. To me, it should be a single file that contains everything. If we need a per-component file, we could extract it from the all in one json.

On comments inside json: I haven't thought about that particular limitation of json format. What kind of comments do you expect in this file?
