### ISSUE TITLE
Research sizes, colors, shapes ...

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1617]
In order to address multiple component sizing, colors, shapes, where applicable, we need to find the best way possible: are we going to have variables for everything? are we going to rely on maps? are we going to be somewhere in between?

This research should help us have a unified approach when it comes to dealing with such features.

**Comment by eeasss** [comment]
Vanka, what would be the output of the research RFC? What are the criteria that can guide you in making this decision?
