### ISSUE TITLE
:focus-within styles

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1619]
Research to see if `:focus-within` styles are a viable alternative to `.k-state-focus`. Note: `k-state-focus` will remain as a class for the purposes of testing.

That being said, if `:focus-within` are indeed a viable alternative, it will allow us to move the styling classes to the top of the components, where they should be.

**Comment by Stamo-Gochev** [comment]
Nice, this will be very useful in blazer components as it will eliminate the need to cross between the .NET and JS parts of the code just to toggle a class.

**Comment by joneff** [comment]
shipped with 6f45cf0e1c4aeeca31cf8607e7f5b16f51dec598
