### ISSUE TITLE
Editor 'view HTML' dialog styling is broken

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#1620]
**Describe the bug**
When _'view HTML'_ tool is used in Safari, the text container has small height. When viewed in Chrome and FireFox the text container is too large and the buttons are not visible

Angular Safari:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/33104481/84475617-8b931c00-ac95-11ea-90d9-3fb14b229c8d.png)

jQuery Safari:
<img width="927" alt="Screenshot 2020-06-12 at 10 11 00" src="https://user-images.githubusercontent.com/33104481/84475652-9948a180-ac95-11ea-97a3-baf2c411f463.png">

jQuery Chrome:
![image](https://user-images.githubusercontent.com/46348689/88677658-3cdefb80-d0f6-11ea-8015-93d921b9012a.png)

jQuery FireFox:
![image](https://user-images.githubusercontent.com/46348689/88677777-5ed87e00-d0f6-11ea-9d63-6d3d10148d8b.png)

**To reproduce**
Only in Safari browser.
https://stackblitz.com/edit/angular-muc1sj?file=app/app.component.ts

In Chrome and FireFox:
[Editor All Tools Demo](https://demos.telerik.com/kendo-ui/editor/all-tools)

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers**
* Safari, Chrome, Firefox

**Comment by aleksandarevangelatov** [comment]
Styling issues for the 'view HTML' dialog are also reported in ticket #1477978

**Comment by IvanDanchev** [comment]
Another report for the textarea in the "View Html" popup in Safari: Ticket ID: 1481690
