### ISSUE TITLE
Toolbar appearance in PDFViewer is not correct on smaller screen sizes

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#1626]
### Bug report
Toolbar appearance in PDFViewer is not correct on smaller screen sizes. That applies to all LESS and SASS thems.

Related to:
https://github.com/telerik/kendo/issues/11103

### Reproduction of the problem
Reduce the window width and run the following demo:
https://demos.telerik.com/kendo-ui/pdfviewer/index

The result would be:
![PDFViewerToolbarSass](https://user-images.githubusercontent.com/3431388/84630499-b038ff00-aef4-11ea-95e8-9a5567461c44.png)

### Expected/desired behavior
Toolbar tools should not overlap the overflow button.

### Environment
* **Kendo UI version:** 2020.2.513
* **Browser:** [all]

**Comment by joneff** [comment]
As noted in the related PR, the issue cannot be fixed with the themes, but rather in the js code.
