### ISSUE TITLE
Wrong styles when used as an editor in the Grid

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#1630]
**Describe the bug**

NumericTextBox has wrong styles when used as an editor in the Grid.

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/grid/editing-inline
1. Select the Material theme
1. Edit a row 

**Expected behavior**

https://github.com/telerik/kendo-ux/blob/master/themes/material/PNG/grid.png

![image](https://user-images.githubusercontent.com/17339722/84903401-baa2f680-b0b6-11ea-81d2-d4da53aac25e.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/17339722/84903455-cd1d3000-b0b6-11ea-8cd1-da9eed42ecc8.png)

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
Fixed by #1975
