### ISSUE TITLE
Styles for Loader component

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1670]
Design files:
* [Design for Default Theme](https://xd.adobe.com/view/989e7bcb-afce-4c5e-a367-288be28fc4bc-cdcd/)
* [Design for Bootstrap Theme](https://xd.adobe.com/view/8265fc3c-aa87-4966-81fa-25d0783e2204-d736/)
* [Design for Material Theme](https://xd.adobe.com/view/d494448c-124e-4f45-aabe-38de7c32dcae-81c7/)

**Comment by JoomFX** [comment]
Here's the design - https://github.com/telerik/kendo-ux-private/issues/101#issuecomment-663066805
