### ISSUE TITLE
Restyle sticky and locked columns

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1673]
TBA

**Comment by inikolova** [comment]
According to the latest design, there shouldn't be darkening overlay and should have darker borders:

https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/grid.png
https://github.com/telerik/kendo-ux/blob/master/themes/bootstrap/PNG/grid.png
https://github.com/telerik/kendo-ux/blob/master/themes/material/PNG/grid.png
