### ISSUE TITLE
Clear value button is displayed over the input value, in both IE and Chrome - [Kendo UI for Angular] - [Combobox]

### ISSUE THREAD

**Issue by zhaparoff** [telerik/kendo-themes#1676]
**Describe the bug**
Faced an issue when customizing a Telerik UI for Angular default theme with custom colors.
For combobox, clear value icon is displayed over the input value text, in both, IE and Chrome.

**To reproduce**
1. Apply custom theme colors as described in the docs:
```
// Telerik custom theme
$primary: #005f8b;
$text-color: #75757c;
$bg-color: #ffffff;
$base-text: #75757c;
$base-bg: #ffffff;
$hovered-text: #75757c;
$hovered-bg: #f2f3f0;
$selected-text: #ffffff;
$selected-bg: #005f8b;

@import "~@progress/kendo-theme-default/dist/all.scss";
```
2. Add kendo-combobox component to a page
3. Run the app, select some value in the combobox

**Expected behavior**
Clear value button is displayed in the right side

**Actual behavior**
Clear value button is displayed in the left side of input, overlapping the input value text

**Screenshots**
![image](https://user-images.githubusercontent.com/7301860/86235066-880df900-bba0-11ea-9e1d-81e6641bfc0b.png)

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Chrome version:  83.0.4103.116
* IE version: 11

**Additional context**
As per my investigation, the issue is in these two lines in __variables.scss_:
```
$picker-select-border-width: 0 !default;
$picker-icon-offset: calc(#{$picker-select-calc-size} + #{$picker-select-border-width} + #{$input-icon-offset}) !default;
```

The final result will be something like: `$picker-icon-offset: calc(calc((20 / 14) * 1em + 4px * 2) + 0 + 6px);`
Internal calc is calculated fine.
Nested calc is working fine in Chrome, but not in IE, since IE has some issues with it.
But the zero value, without units, `0`, breaks calculation in all browsers.

Thus,
`$picker-icon-offset: calc(0 + 6px);` is broken;
`$picker-icon-offset: calc(0px + 6px);` works fine.

There is an existing issue, which seems to have very similar root cause: https://github.com/telerik/kendo-themes/issues/546

**Comment by zhaparoff** [comment]
Just in case someone will need a temporary workaround untill this will be resolved.

I've ended up with adding the following line `$picker-select-border-width: 0px;` 
```
...
$selected-text: #ffffff;
$selected-bg: #005f8b;

$picker-select-border-width: 0px;

@import "~@progress/kendo-theme-default/dist/all.scss";
```

It overrides the default value without units and makes calc() working fine.

**Comment by joneff** [comment]
@zhaparoff the issue is related to the toolchain you need to build the themes -- https://github.com/telerik/kendo-themes/wiki/Known-issues. In a nutshell, you need postcss-calc to deal with those values.

The same applies to #546.

**Comment by zhaparoff** [comment]
Thanks @joneff.
For some reason, documentation on official site missing that usefull info.
Unfortunatelly, fibers dependency, that is needed for such kind of theme build, requires python to be installed on the build server...

**Comment by joneff** [comment]
Fibers is only needed if you are using dart-sass compilation. If you are using node-sass, you don't really need it.

Previously, the dart sass documentation stated that you need fibers to speed up build, but now it's rephrased to state that's it's needed only for asynchronous build (which is the case when compiling with gulp).

I think we can improve on the documentation by extending it with non-gulp examples. We should also see where should we add that documentation in the framework sites.

I am leaving the issue open, until we resolve those documentation issues.
