### ISSUE TITLE
Event's title color is not changed when different background colors are used

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-themes#168]
It can be replicated in this demo - https://demos.telerik.com/kendo-ui/scheduler/index
Scroll a bit to HR Lecture event -
 the color of the title in it is **black** in bootstrap 3
the color of the title in it is **white** in bootstrap 4

expected: 
the color of the title in it is **black** in bootstrap 4

**Comment by joneff** [comment]
The issue is related to how a contrasting color is determined. It's partially in the themes and partially in `kendo.scheduler.views.js` and more particularly in `_shouldInverseResourceColor`.

**Comment by joneff** [comment]
The main issue here, apart from not having the correct color is the logic in `_shouldInverseResourceColor`: it compares the color of the scheduler, against the background of the event and determines whether or not there is contrast between them.

What should be done instead is to create the event as element and then measure the contrast between the its own text and background and then decide if inverse text is needed.
