### ISSUE TITLE
Icons not rendered in SASS themes

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#1687]
**Describe the bug**
There are icons not rendered in SASS themes.
The icons exist - https://docs.telerik.com/kendo-ui/styles-and-layout/icons-web#list-of-font-icons
And they are visible if the respective code is applied to the before element or if LESS themes are used.

**To reproduce**

1. Run the following [Dojo snippet](https://dojo.telerik.com/asihijeZ)

**Expected behavior**
![Untitled _ Kendo UI Dojo - Google Chrome 2020-07-07 14 17 19](https://user-images.githubusercontent.com/6614183/86772385-95bdf580-c05c-11ea-8335-ed26dc267bd8.png)
Achieved with LESS themes - https://dojo.telerik.com/@Dimitar-Goshev/ipOsoFAl

**Current behavior**
![Untitled _ Kendo UI Dojo - Mozilla Firefox 2020-07-07 14 18 24](https://user-images.githubusercontent.com/6614183/86772451-bdad5900-c05c-11ea-9c13-80214d80aaf2.png)

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery - 2020.2.617

**Affected browsers (please remove the unneeded items)**
* All

**Comment by marin-bratanov** [comment]
There are a few more, see here: https://dojo.telerik.com/iNePUxam

**Comment by joneff** [comment]
Looking at the code, it appears the icons *are there*, but the entries are not added. I can't say why exactly.

With the new process of kendo-font-icons, that will not be an issue. I will provide a one time ad-hoc fix and then we'll work on integrating kendo-font-icons package in the pipeline.

**Comment by joneff** [comment]
I've prepared a sample dojo, using the latest kendo-font-icons -- https://dojo.telerik.com/@joneff/APuSowiB.

Note: i will be using only the icon list from that file, not the content of the font, because it still has some issues.

**Comment by joneff** [comment]
Note: `chart-line` and `shape-line` both used the `line` name. That led to some conflict. As a result, I prefixed all chart icons with that prefix.

**The icons are not removed, just renamed!** Even so, I doubt it will be a good idea to have this in kendo-jquery. We could wait for 2020 R3 SP1 and then introduce the changes there.
