### ISSUE TITLE
(Material theme) Issues with the layout of the FileManager's Toolbar

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#1688]
**Describe the bug**
There are missing spaces between:
- the "View Details" text and the Switch inside the FileManager's toolbar
- the Switch in the Toolbar and the Search input
- The search input and the border of the FileManager component

![image](https://user-images.githubusercontent.com/41293735/86902215-52c05880-c116-11ea-8dee-428a56ff568a.png)

**To reproduce**

1. Open [this Dojo](https://dojo.telerik.com/OsapAwAZ)
1. See the reproduction of the behavior demonstrated in the above screenshot

**Expected behavior**
There should be spacings between the listed above elements as demonstrated in [this Dojo](https://dojo.telerik.com/eBEYixAV)
![image](https://user-images.githubusercontent.com/41293735/86902925-4dafd900-c117-11ea-9a72-98d9dc023063.png)

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Fixes suggested by client:
![image](https://user-images.githubusercontent.com/41293735/86903542-23125000-c118-11ea-8835-bf0fc461cf65.png)

**Comment by JoomFX** [comment]
This issue doesn't seem to be reproducible any more ([demo](https://demos.telerik.com/kendo-ui/filemanager/index?autoRun=true&theme=material-v2)).
@PekoPPT Could you please confirm if the issue can be closed?

NOTE: The Toolbar styles in the Material theme were revised and reworked few months ago.
Now the styling is a bit different which might have solved the issues mentioned above.
