### ISSUE TITLE
Scheduler Timeline View is broken on IE

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1703]
**Describe the bug**
There are several bugs in IE.
1) wrong first column width
2) wrong "all day" row height 
3) in timeline view the first column width is wrong and all labels are in top left corner

**To reproduce**

1. Create a Scheduler with a Timeline view.

**Expected behavior**
The Scheduler to render correctly. Like in the Chrome browser.

**Screenshots**
![bugs](https://user-images.githubusercontent.com/17604855/87910419-a87bf580-ca72-11ea-9892-8070aea8bd0d.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Affected browsers (please remove the unneeded items)**
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
We dropped support for IE.
