### ISSUE TITLE
Datepicker in a resizable grid column gets clipped in Edge 

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-themes#172]
Reported in ticket with ID 1165869 

Screencast : [link](https://www.screencast.com/t/QIg6ChpZ2w)

Steps:

- Open [Dojo](http://dojo.telerik.com/iwoKUNOM/2) in Edge
- Click any cell which is part of the OrderDate column
- resize the column and see how the picker gets clipped when the width is below 200px

###### Workaround

```
   .k-edit-cell .k-input[data-role='datepicker'] {
     width: 0 !important;
     flex-grow: 1 !important;
   }
```

**Comment by TeyaVes** [comment]
fixed in develop branch by: https://github.com/telerik/kendo-themes/pull/555
