### ISSUE TITLE
А disabled flat button in toolbar does not have a visible focus state

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-themes#1742]
**Describe the bug**
А disabled flat button in toolbar does not have a visible focus state

**To reproduce**
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/eboWUMOd)
1. Press Alt + W to focus the toolbar

**Expected behavior**
A focus indicator should be available when a disabled flat button in the toolbar is focused.

**Screenshots**
![image](https://user-images.githubusercontent.com/46348689/88920710-f87a6980-d275-11ea-8832-e789c6c51ab0.png)

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Comment by joneff** [comment]
This will probably be fixed when we revise our buttons
