### ISSUE TITLE
iframe content in the tooltip does not resize to 100% of the Tooltip's height

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#1744]
**Describe the bug**
Before [this commit](https://github.com/telerik/kendo/commit/3c67ebfc534d7566de7b40f651abcc73195e1897#diff-f0d3423b43ebc92037ee07a7bd2e0886), the LESS themes contained the following rule 
```
.k-tooltip-content {
  height: 100%;
}
```
After R2 2020 the content no longer resizes to 100% of the Tooltip's height. 

The SASS themes don't have this rule now and didn't have it before, but it would be nice if we can have consistency with the LESS  themes. 

**To reproduce**

1. Go to [dojo example](https://dojo.telerik.com/OJaCafog/14)
1. Hover the Tooltip target

**Expected behavior**
The iframe occupies 100% of the Tooltip's height.

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [Windows]

**Additional context**
N/A

**Comment by pboisso** [comment]
I've been experiencing this issue.  While I understand this is a visual bug and that there is now a workaround, I think it should be classified higher than 'low' because this is a breaking change for anyone upgrading from R1 2020.  Just my 2 cents.
