### ISSUE TITLE
Inconsistent layout in Scheduler recurrence editor 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#1772]
**Describe the bug**
- [ ] Material - A horizontal scrollbar is produced in Events dialog https://take.ms/Cuilo
- [ ] Bootstrap - 'Repeat on' dropdown fall down into two rows https://take.ms/kShsD 

Use recurrence-editor branch from Kendo repo and open the event dialog

**Expected behavior**
No horizontal scrollbar is produced
'Repeat on' dropdown is on one row as with Default and Material themes

**Affected package (please remove the unneeded items)**

* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

Related to https://github.com/telerik/kendo/issues/11112

**Comment by joneff** [comment]
That's by design: https://github.com/telerik/kendo-ux/blob/master/themes/material/PNG/dialogs-scheduler.png.

We could ask the designers to revise the dialogs, but that will take some time.
