### ISSUE TITLE
Add a responsive grid system to themes

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-themes#1783]
**Is your feature request related to a problem? Please describe.**
A while ago, using bootstrap styles made a lot of sense but Kendo UI has improved a lot and with time the use of bootstrap components has become less compelling, especially since the addition of cards, avatars and badges. The only bootstrap features which I still rely on are the 12 column responsive grid and the navbar (which the Kendo UI toolbar cannot replace). 

**Describe the solution you would like to see implemented**
Add a 12 column responsive grid system.

**Describe the alternatives you have considered**
Using bootstrap.

**Additional context**
https://getbootstrap.com/docs/4.5/layout/grid/

**Comment by jlchereau** [comment]
This would offer more options for form layout.
TileLayout also need to rely on a grid system to be responsive (it resizes but it is not responsive).

**Comment by joneff** [comment]
@jlchereau, more than often I find that it's a cultural thing, when I am not responding. Rest assure, I am reading every question asked in the repo,  every issue reported and every suggestion. Most of those, I read multiple times. However, I tend to respond only when I have something meaningful to say: be it adding to the discussion, updating on status or asking for clarification.

If I were to respond now, and please bear in mind this is not a definitive response, it would be something like the following:

Inevitably quoting that there are 2 hard things in computer science "naming things, cache invalidation and offset by 1 errors", let's talk naming, API and how it all works together for kendo-jquery, kendo-angular, kendo-react, kendo-vue and telerik-blazor:

An obvious choice for "just getting a responsive grid into kendo" would be to copy and modify bootstrap with a `k-` prefix. Unfortunately, I've done that for [another product](https://demos.telerik.com/aspnet-ajax/page-layout/overview/defaultcs.aspx) and it didn't turn out so well... Still, lesson learned.

Then we have what we've been fiddling with the last couple of months: sizes. Think different component sizes. Again, a lot like bootstrap, with a `k-` prefix.

And immediately we have a problem: no longer is the suffix `-sm` denoting either component size or viewport size. It is, instead, denoting both and to me, that's an issue. It also doesn't fit API wise.

If we look at another approach, say tailwind, and we move the responsive to the beginning of the class name and then have the suffix, that would make more sense, and here is what I mean:

```css
.k-hidden { display: none !important }
@media (mx-width: 360px) { .xs\:k-hidden { display: none !important }
/* more styles */
```

```html
<span class="k-hidden">Always hidden</span>
<span class="xs:k-hidden">Hidden on very small viewports</span>
<span class="k-btn k-btn-lg sm:k-btn-xs">Button with adaptive size</span>
<span class="k-bg-success md:k-bg-red">Adaptive background</span>
<span class="k-d-flex-row lg:k-d-flex-col">Adaptive flex direction</span>
<span class="xl:k-bordered">Adaptive border</span>
```

Of course, we are yet to define what is very small, small, medium etc viewports and factor in device pixel scaling and canonical size (and other boring aspects).

If we say we've resolved them, and we move forward with using this approach, it would actually translate nice into API as well. Say ... a react button `<Button size="md" sm:size="lg" ... >Button</Button>` of course, assuming that xml-like attributes are allowed in react.

Going full circle, this is why I haven't responded yet -- there are still many things to consider in terms of naming, API and integration. I am not a fan of adding stuff in for the sake of it being there.

That being said, the responsive / adaptive part will make it into kendo ui and I thank you for the feedback and involvement.

Oh.. and the part about navbar... remember how I said naming is hard... We are calling it appbar and it is a simple container for any items that can be positioned, made sticky or fixed. If memory serves me correctly, it's available for jquery, vue, angular and react. Blazor is coming, but I can't comment when.

(here is the Bootstrap theme with all the color variations)

![image](https://user-images.githubusercontent.com/8048/99364450-a5790080-28be-11eb-989e-4983a834aa06.png)

**Comment by jlchereau** [comment]
@joneff I did not expect a response but thanks for this significant (and very instructive - cf. xml-like attributes for styling) effort. BTW my comment about the navbar was dated Aug 17 and the appbar was only released on Sep 16, but this only confirms that keeping bootstrap in the tool belt makes less sense as Kendo UI progresses into an extremely comprehensive framework. I love the new SASS themes and the added flexibility of proper size management. Your work is appreciated.

**Comment by epetrow** [comment]
A responsive layout system has been introduced with https://github.com/telerik/kendo-themes/pull/5089, hence I am closing this thread.
