### ISSUE TITLE
The modal overlay is displayed over the Window when it is dragged

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#1784]
**Describe the bug**
When you have a draggable modal Window, on dragging it an overlay is displayed over the Window.

**To reproduce**

1. Go to [https://dojo.telerik.com/IdIyaBUR](https://dojo.telerik.com/IdIyaBUR)
1. Drag the Window

a .k-overlay element appears in the Window

**Expected behavior**
The overlay remains below the Window, as it is in the LESS themes.

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
N/A

**Comment by Dimitar-Goshev** [comment]
The issue is reproducible with Kendo UI for jQuery Window and the fix will be available in R2 2021 SP1.
