### ISSUE TITLE
SASS themable charts inherit the font

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-themes#1789]
**Describe the regression**
Some dataviz widgets like charts could read variables from the themes by setting property "theme": "sass". In previous versions seems that the chart uses a theme predefined font, but in the latest "development" branch the font is inherited from the document or parent element.

**To reproduce**
https://dojo.telerik.com/IpUFUYub

**Expected behavior**
The theme specific font is used for charts' tittle, legend, labels etc. 
In case this change is done on purpose, please comment and close the issue.

**Screenshots**
Current state:
![image](https://user-images.githubusercontent.com/52446546/90731731-bc658200-e2d2-11ea-9c13-131fe5807222.png)

Old state:
![image](https://user-images.githubusercontent.com/52446546/90731812-dacb7d80-e2d2-11ea-948b-9088a22489ea.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment]
I've created a fix in kendo-jquery repo.
