### ISSUE TITLE
Toolbar toggle button has inconsistent styling with Default theme

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#1790]
**Describe the bug**
When a button inside toolbar is configured as toggle button, the styling applied with Default theme is inconsistent so the toggle mode is not distinguishable.

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/toolbar/index / (Latest dev channel) http://kendobuild-windows.dev.progress.com/kendo-ui-dev/toolbar/index?autoRun=true&theme=default-v2 
1. Switch to default sass theme 
1. Click on the toggle button so its state becomes active

**Expected behavior**
The button state becomes active and the style applied makes it clearly distinguishable from the inactive button similar to the text align buttons
**Screenshots**
![image](https://user-images.githubusercontent.com/7202037/90767254-8e456980-e2f5-11ea-927f-96bc53936d92.png)

**Affected package (please remove the unneeded items)**
* theme-default 4.21.0

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please remove the unneeded items)**
* All

**Comment by Raisolution** [comment]
Linking some related issues regarding the same problem.

Initially brought up in [kendo-angular-buttons#333](https://github.com/telerik/kendo-angular-buttons/issues/333) and later logged for design revision of the same in [kendo-ux-private#120](https://github.com/telerik/kendo-ux-private/issues/120).

**Comment by joneff** [comment]
Resolved by #2058 (@inikolova)
