### ISSUE TITLE
Focus styles are applied to elements in Chrome

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#1796]
**Describe the bug**
As of recently, Chromium-based browsers add additional focus styles (a border) around focused elements, e.g.:
![image](https://user-images.githubusercontent.com/1857705/91562059-3afe9700-e945-11ea-9638-4c4549de9143.png)

**To reproduce**

1. Go to https://winslaveblazor.dev.progress.com/blazor-ui/grid/column-menu
2. Click on the column menu icon inside a grid header cell to open it

**Expected behavior**
No additional styles are added to the first focused element (except our own like from `k-state-focused`)

**Screenshots**
![image](https://user-images.githubusercontent.com/1857705/91562059-3afe9700-e945-11ea-9638-4c4549de9143.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Chrome version: 84

**Comment by matanasov** [comment]
@joneff 
I now see similar behavior in the Scheduler component:
https://winslaveblazor.dev.progress.com/blazor-ui-production/scheduler/overview

![image](https://user-images.githubusercontent.com/5861835/93207712-0ae82e00-f764-11ea-9455-849b1cb6f70c.png)

**Comment by joneff** [comment]
I suppose there will be many cases where something is focusable and we haven't removed the focus from it.

We'll target this.

**Comment by joneff** [comment]
@matanasov I opened a new issues, because this one is done.
