### ISSUE TITLE
Styles for ImageEditor component

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#1801]
Designs:

* [Design for Default Theme](https://xd.adobe.com/view/e080168d-4caf-41c9-8bbe-1c76fb368471-b5d3/)
* [Design for Bootstrap Theme](https://xd.adobe.com/view/02720380-f3a5-4287-8500-fd9faf13ef40-5721/)
* [Design for Material Theme](https://xd.adobe.com/view/76540064-b69a-48c4-9f71-378fb68b8f9f-2307/)

**Comment by Dimitar-Goshev** [comment]
- [ ] - IE - Tools in Tools pane fall on new lines, compared to design:
![Example of Kendo UI Image Editor widget keyboard navigation feature  - Internet Explorer 2020-09-02 19 27 59](https://user-images.githubusercontent.com/6614183/92010579-a20bb980-ed52-11ea-8c88-c431960d3391.png)

![Example of Kendo UI Image Editor widget keyboard navigation feature  - Internet Explorer 2020-09-02 19 28 10](https://user-images.githubusercontent.com/6614183/92010626-afc13f00-ed52-11ea-9014-3d3dfaa089bf.png)

- [ ] Crop Image and Resize issues:
  - Space above main title should be 32px
  - There should be more space between main title and line
  - Wrong space between Width and Height tools - should be 8px as on Resize Image
  - Checkbox should be on the same line with the label - this probably comes this way from Form and won't be fixed?

![Kendo UI Image Editor Demo - Google Chrome 2020-09-02 19 21 01](https://user-images.githubusercontent.com/6614183/92010945-12b2d600-ed53-11ea-8882-07c57d57939a.png)

![Kendo UI Image Editor Demo - Google Chrome 2020-09-02 19 23 40](https://user-images.githubusercontent.com/6614183/92010968-18102080-ed53-11ea-9a4a-bdd371e3a202.png)
