### ISSUE TITLE
DropDownList is shrunk when with floating label

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-themes#1808]
DropDownList is shrunk when with floating label

**To reproduce**

1. Go to https://www.telerik.com/kendo-react-ui/components/dropdowns/floating-labels/

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9494406/91935959-8d4e0800-ecf7-11ea-9a19-e6d019882e9a.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
probably related to #1786 and how browsers treat inputs and spans in flexbox container differently.
