### ISSUE TITLE
Material: missing days k-state-focused styling in calendar

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-themes#182]
The `k-state-focused` class does not apply any styling on the calendar days. The issue can be observed by using the keyboard navigation to focus a day, in the [react](https://www.telerik.com/kendo-react-ui/components/styling/theme-material/) and [angular](https://www.telerik.com/kendo-angular-ui/components/styling/theme-material/) theme-preview apps.

Current:

![image](https://user-images.githubusercontent.com/30626787/40045255-75ec85e4-5832-11e8-93f0-885e6f6b1f43.png)

Expected something like this:

![image](https://user-images.githubusercontent.com/30626787/40045298-95108e84-5832-11e8-9e52-49f58fb4e107.png)

**Comment by PreslavKozovski** [comment]
fixed in #286
