### ISSUE TITLE
Field buttons in PivotGrid sort indicator missing padding and delete setting misaligned

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-themes#1839]
**Describe the bug**

- Default - missing sort indicator padding
- Material - delete setting button misaligned 

**Expected** same as the arrow in the Configurator
![image](https://user-images.githubusercontent.com/10980842/92577049-e6d3ab00-f292-11ea-9b62-fb33ab7dc169.png)

**Actual** in PivotGrid ToolBar:
![image](https://user-images.githubusercontent.com/10980842/92576405-28b02180-f292-11ea-9643-c2d841863656.png)

- Material theme misaligned delete settings icon

![image](https://user-images.githubusercontent.com/10980842/92576560-56956600-f292-11ea-8a14-727de40aab8b.png)

**To reproduce**

[Demo Default](https://demos.telerik.com/aspnet-mvc/pivotgrid?autoRun=true&theme=default-v2)

1. Click the PivotGrid toolbar field buttons

[Demo Material](https://demos.telerik.com/aspnet-mvc/pivotgrid?autoRun=true&theme=material-v2)

**Expected behavior**

- There should be padding between the sort arrow and the field name.
- The delete icon should be centered

**Affected package (please remove the unneeded items)**
* theme-default
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Comment by dmanova** [comment]
Bootstrap, also missing sort indicator padding:
![image](https://user-images.githubusercontent.com/52446546/95430121-f7d81080-0953-11eb-938f-585a55985298.png)
