### ISSUE TITLE
Border overlapping on dropdownbutton and splitbutton

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-themes#184]
Focused item border is overlapping with popup border.
![overlap](https://user-images.githubusercontent.com/4143177/40048009-c85f4152-5839-11e8-8018-16f55666cedc.png)

**Comment by ipeshev** [comment]
Indeed, there seem to be multiple borders that appear next to each other in this case:
1. The button border
2. The popup border
3. The focus state border
We could make 1&2 overlap, although this would depend on the popup orientation. @lkarakoleva and @joneff, what do you think?

**Comment by ipeshev** [comment]
@lkarakoleva we suspected that this is correct implementation, but it just does not look ok. Of course we can not argue about taste as the dog says ;). What about vote , thumb up - ok , thumb down - not ok. @joneff , @gyoshev , @elena-gancheva - please vote.

**Comment by joneff** [comment]
Regardless how we feel about it, this is the design for the theme. Developers are free to customize it anyway they see fit, including, but not limited to, changing how the focused items look and how the popup looks.

I should say that borders are not overlapping, but rather are stacking, hence the appearance issue. If they were overlapping, you wouldn't notice it.

Finally, it is possible to reduce the total stacked size, by just 1 pixel, however it will require implementation in kendo-angular-buttons to provide the needed class, the same way kendo-jquery does. Then and only then we can begin discussing the styles (and the design should be updated).

/cc @gyoshev
