### ISSUE TITLE
Filter button misses box-shadow in IE

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1855]
**Describe the bug**
Using the Grid filter menu in IE 11 there isn't applied a box-shadow to the filter button when it is focused. 

**To reproduce**
Please run the attached project:
[grid-filter.zip](https://github.com/telerik/kendo-themes/files/5208498/grid-filter.zip)

The current behavior when the filter button is clicked is the following:
![Capture](https://user-images.githubusercontent.com/20015190/92917143-de1bda00-f436-11ea-92b7-e218ff5a4e3b.PNG)

**Expected behavior**
![Capture2](https://user-images.githubusercontent.com/20015190/92917346-14595980-f437-11ea-98f0-70bdab8715a8.PNG)

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* IE version: 11

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
@svetq, @inikolova made significant improvements to the header of the grid. After her improvements are released, can you test again to see if the behaviour persists?

**Comment by joneff** [comment]
The following styles must be added to the menu button on open: `k-state-focus`.
