### ISSUE TITLE
Row headers container has fixed width in IE

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#1880]
**Describe the bug**
In IE, the Pivotgrid row headers container is not expanding its width when needed.

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/pivotgrid/templates?autoRun=true&theme=default-v2 in IE
1. Swap "[Date].[Calendar]" and "[Product].[Product Line]"
1. Start expanding the rows

**Expected behavior**

Row headers container has a dynamic width.

**Screenshots**

![image](https://user-images.githubusercontent.com/17339722/93352193-4148aa80-f843-11ea-9d74-88a6fd48335c.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* IE version: 11

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
related to: https://github.com/telerik/kendo-theme-default/issues/647

**Comment by joneff** [comment]
Fixed by #1881
