### ISSUE TITLE
Material: Inline edit row / cell - use the correct metrics padding and form elements

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#192]
In the current implementation the row height in inline edit mode is incorrect - it should be equal to other gird rows - 48px. The top and bottom padding should be decreased, the inputs should be increased to the correct height: 36px.
**Design:** https://github.com/telerik/kendo-ux/blob/master/themes/material/grid.psd

**Inline row editing**

- Implementation
![1](https://user-images.githubusercontent.com/16577622/40239091-b1b3aed0-5abd-11e8-9114-b5bfc7e25294.png)

- Design
![2](https://user-images.githubusercontent.com/16577622/40239092-b1d2106e-5abd-11e8-8616-d73c5a9459ed.png)

**Cell editing**
- Implementation - input height should be 36px; top padding should be 6px:
![3](https://user-images.githubusercontent.com/16577622/40241572-0856bcb8-5ac4-11e8-94e1-cccefe091454.png)

**Comment by joneff** [comment]
Fixed by #1226
