### ISSUE TITLE
Material: Incorrect styling of drag clue

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#193]
**Implementation:**
![1](https://user-images.githubusercontent.com/16577622/40307329-aaef32f0-5d0a-11e8-972e-727f6f53537b.png)

**Design:**
![2](https://user-images.githubusercontent.com/16577622/40307927-074f11d0-5d0d-11e8-8e25-21ee1fa95546.png)
 Drag clue background is: 0.07 opacity of black background over white color = #ededed, 0.9 opacity of the background

**Comment by PreslavKozovski** [comment]
fixed in https://github.com/telerik/kendo-themes/issues/252
