### ISSUE TITLE
Wrong border width and border radius of textbox in Grid edit row in Material theme

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#1932]
**Describe the bug**
Can be observed in this example - [https://stackblitz.com/edit/angular-bsk8as-qjdwyq?file=app/app.component.ts](https://stackblitz.com/edit/angular-bsk8as-qjdwyq?file=app/app.component.ts)

**To reproduce**
Click some of the Grid rows to edit

**Expected behavior**
Border-radius should be 0; Textbox bottom border should be 1px;

**Comment by joneff** [comment]
Appears to be fixed now.
