### ISSUE TITLE
The text of the progressbar label is cut

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#1945]
**Describe the bug**
The text of the progressbar label is partially cut with Bootstrap theme in Firefox.

**To reproduce**

1. Go to https://winslaveblazor.dev.progress.com/blazor-ui/progressbar/label

**Expected behavior**
The text is not cut at the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/1857705/95049553-a4b35300-06f2-11eb-9dfc-10f502fa0b59.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Firefox version: 79

**Comment by dtopuzov** [comment]
A similar thing happens in the default theme too, but it is only 1px difference.

Here is how it looked before (when the progress bar was initially implemented at Blazor):
https://github.com/telerik/blazor-tests/blob/38b6c5c55368ce578c90ccc5a8fd673118e7c692/BlazorTests/Blazor.Playground.VisualTests/Images/Chrome/progressbar-vertical-progressbar.png
Here is how it looks now with the latest commits:
https://github.com/telerik/blazor-tests/blob/master/BlazorTests/Blazor.Playground.VisualTests/Images/Chrome/progressbar-vertical-progressbar.png

I see the difference only in the vertical progress bar, horizontal looks the same as before.

Tested on latest stable Chrome on Windows.

**Comment by Stamo-Gochev** [comment]
I have posted some other issues regarding the ProgressBar in the [Kendo Front-end Teams Channel](https://teams.microsoft.com/l/message/19:1f8c4e9c40004fbf8fe23af65fe52970@thread.tacv2/1601885848557?tenantId=db266a67-cbe0-4d26-ae1a-d0581fe03535&groupId=d825ddf5-c7c7-4f9b-8422-1d8f39041b8d&parentMessageId=1601885848557&teamName=Kendo%20Front%20End%20Team&channelName=General&createdTime=1601885848557), feel free to log them separately (if they are issues) or update this issue accordingly.
