### ISSUE TITLE
Add styles for floating action button

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1948]
Designs:
[Default](https://xd.adobe.com/view/71c896dd-b1e4-435e-9bd2-89f55a2d68b0-249b/)
[Material](https://xd.adobe.com/view/481aea43-7f90-4774-be3f-c761f38fac48-1d49/)
[Bootstrap](https://xd.adobe.com/view/8fc898ac-6581-4b27-81c6-f1840999ecd9-da9b/)

@silviyaboteva will implement sass themes
@Juveniel will port to less

**Comment by silviyaboteva** [comment]
I prepared a demo with the rendering of the component: https://dojo.telerik.com/OPevoLoY/7

- In the demo, I listed all the classes that can be applied.
- I used the rendering of the Icon and Badge components as it is noted in the designs

@telerik/kendo-front-end please share your thoughts/suggestions for improvement on this.

**Comment by PreslavKozovski** [comment]
The rendering looks good. I would suggest renaming `k-fab-button` to `k-speed-dial-button`

**Comment by inikolova** [comment]
I agree with Presli -> rename the class to **k-speed-dial-button**. Rendering looks good to me, too :)

**Comment by silviyaboteva** [comment]
After offline discussion with @elena-gancheva and @Juveniel, and based on the feedback of Presli and Iliyanka, I updated the rendering. Here you can find the latest version: https://dojo.telerik.com/eREjORiV

After the quick brainstorming session, there are a few questions that need to be discussed:
-  We need to add `role` and `aria` attributes to the component
- We need a root wrapping element that will hold both - the button and the speed dia. **Q:** What will be the class name? k-fab` or`k-floatingactionbutton` or `k-floating-action-button` or `k-floating-action-btn` or `k-speed-dial`?
- We need to decide what will be the main class name of the button itself. Is the `k-floatingbutton` or `k-floating-button` or `k-floating-btn` or something else?
- Based on https://github.com/telerik/kendo-themes/issues/1983#issuecomment-709926692, we are thinking of adding a wrapper element over the icons. But what will be the class name? `k-btn-icon` and respectively `k-btn-text`?
- Based on the designs, there are different positions of the labels of the speed dial items, how can we handle this? From the themes and introducing new classes for the positioning or via the component to swap the elements (icon and label)?
- How to handle animations - via CSS or JS animations? What if the users want custom animation duration?

@joneff can you please check the list of questions and let's discuss the possible rendering changes beforehand? As we do not want to change the rendering once we implement the new buttons API .

**Comment by joneff** [comment]
Forget for a second that we are doing a floating action button (fab for short). How would you call it? Either a button, when it has primary action or menu button (dropdown button) if it has a popup.

With that in mind, some of thoughts, on naming:
```html
<span class="fab ..."></span> <!-- omitted for simplicity -->
<div class="k-popup ..."> <!-- omitted for simplicity -->
    <ul class="k-fab-item-list|k-fab-items">
        <li class="k-fab-item">
            TEMPLATE
        </li>
    </ul>
</div>
```

```html
<!-- inside k-fab-item -->
<span class="k-badge" /> <!-- appropriate badge -->
<span class="k-button" /> <!-- primary circle button with icon -->
```

* to me, `k-speed-dial` is a good name, as long as we can reuse it elsewhere
  * if we cannot reuse it, I would prefer `k-fab-items` or `k-fab-item-list`
* same applies for `k-speed-dial-item` <=> `k-fab-item`
* in the template, we don't need any kind of special button. we could use plain ol button customized to fit

**Comment by silviyaboteva** [comment]
@joneff @elena-gancheva @Juveniel and I had another discussion of the final rendering and this is it:
https://dojo.telerik.com/eREjORiV/4

Let me know if I missed something

**Comment by silviyaboteva** [comment]
After extensive discussions and brainstorming about the best approach for all the suites, we agree to remove the badge and avatar related classes and dd fab-specific ones, also to have difference in the rendering of the component in Angular (as they need to have a wrapping host element that will hold the positioning classes). The rendering could be seen in the visual tests from this PR: https://github.com/telerik/kendo-themes/pull/2007
