### ISSUE TITLE
Add styles for bottom navigation component

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1949]
## Meta

<details>

* Aha item -- [KUI-466](https://progresssoftware.aha.io/features/KUI-466)
* Cross-team issue -- telerik/k2#263
* Design issue -- telerik/kendo-ux-private#197

</details>

**Design**
* [Default theme](https://xd.adobe.com/view/8e1c8b07-28f9-43a6-a96d-21fc158cbc2d-db4f/)
* [Bootstrap theme](https://xd.adobe.com/view/f3778c49-6b14-447c-85cb-d9fa3bb7b603-a624/)
* [Material theme](https://xd.adobe.com/view/70ef723a-5ffb-41e2-89c6-00a8c1507bdf-25bc/)

**Assignee(s)**
* @Juveniel is the main developer

---

## Markup

```html

<nav class="k-bottom-nav k-bottom-nav-primary k-bottom-nav-flat k-bottom-nav-border k-bottom-nav-item-flow-vertical k-pos-fixed">
    <!-- Item element can be one of the following - BUTTON, A, SPAN -->
    <span class="k-bottom-nav-item k-state-selected">
        <span class="k-bottom-nav-item-icon k-icon k-i-email"></span>
        <span class="k-bottom-nav-item-text">Prices</span>
    </span>
    <span class="k-bottom-nav-item k-state-disabled">
        <span class="k-bottom-nav-item-icon k-icon k-i-email"></span>
        <span class="k-bottom-nav-item-text">Heat Map</span>
    </span>
    <span class="k-bottom-nav-item" href="#">
        <span class="k-bottom-nav-item-icon k-icon k-i-email"></span>
        <span class="k-bottom-nav-item-text">Portfolio</span>
    </span>
    <span class="k-bottom-nav-item">
        <span class="k-bottom-nav-item-icon k-icon k-i-email"></span>
        <span class="k-bottom-nav-item-text">Search</span>
    </span>
</nav>
```

<details>
<summary>Framework specific markup</summary>

Markup is unified across frameworks.

</details>

## API

* `BottomNav.fill= 'solid` -> `<nav class="k-bottom-nav-solid" />` | `('solid' or 'flat')` | `Default: 'flat'`
* `BottomNav.themeColor = 'secondary'` -> `<nav class="k-bottom-nav-secondary" />` | `Default: 'primary'`  |
* `BottomNav.itemFlow= 'horizontal` -> `<nav class="k-bottom-nav-item-flow-horizontal" />` | `Default: 'vertical'`  |
* `BottomNav.border = 'true` -> `<nav class="k-bottom-nav-border" />`
* `BottomNav.shadow = 'true` -> `<nav class="k-bottom-nav-shadow" />`

## Remarks
* Item element can be one of the following - BUTTON, A, SPAN (`<element class="k-bottom-nav-item"></element>`)
* Although the design features light and dark color variants, the styles of the Bottom Navigation include all the solid theme colors. These can be observed in[ the tests](https://github.com/telerik/kendo-themes/pull/2089/commits/6f88f7a493b85c60f6320abc348097ce52940b06?short_path=3dbfc39#diff-3dbfc3958b7f4c8ec58bc037e48fc72a07d9ef7483185d7e1c2d67557ea172e2).

**Comment by Juveniel** [comment]
As the main purpose of the component is to provide navigation, I suggest utilizing the following rendering:

[https://dojo.telerik.com/ICuveJEl/2](https://dojo.telerik.com/ICuveJEl/2)

As different product flavors handle navigation in a different manner (e.g there is built-in routing in Angular, React and Blazor vs none in jQuery), we could utilize similar markup to the Breadcrumb and Menu components that suits both use cases. The main difference is that jQuery will utilize an anchor that wraps the item text and icon, while other products will utilize the built-in routing mechanisms.

@telerik/kendo-front-end thoughts and suggestions?
