### ISSUE TITLE
failed to @extend ".k-bare"

### ISSUE THREAD

**Issue by Ristaaf** [telerik/kendo-themes#195]
In kendo-theme-default@2.53.2/calendar/_layout.scss you try to extend .k-bare this fails since:

The selector .k-bare was not found.

This problem has been there since 2.51.0

The impact for us in this is that we cannot build our project since we include the calendar.scss file in it.

**Comment by gyoshev** [comment]
Released in `@progress/kendo-theme-material@1.1.3`, `@progress/kendo-theme-default@2.54.0`, and `@progress/kendo-theme-bootstrap@2.13.6`.
