### ISSUE TITLE
Add styles for expansion panel component

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1950]
Designs:
[Default theme](https://xd.adobe.com/view/829efe58-3e5b-408f-9dc6-039f9392eda7-d7cd/)
[Bootstrap theme](https://xd.adobe.com/view/4ba238a8-525c-4f54-a15e-d07b2a7fc8b1-1ef1/)
[Material theme](https://xd.adobe.com/view/e66685ff-b597-4337-955a-ca533b24cf9c-b335/)

@inikolova will implement Sass themes
@PreslavKozovski will port to less

**Comment by inikolova** [comment]
In the following dojo can be found my proposal for rendering of the component: 

https://dojo.telerik.com/@inikolova/ASAjaZIW

Because of the component name is long enough, I suggest using **k-expander** and **k-expander-....** classes instead.

@joneff @PreslavKozovski @silviyaboteva please share your thoughts.

**Comment by PreslavKozovski** [comment]
As I am not a fan of adding a lot of HTML where it is not needed. I would simplify the "header" rendering to:

```
      <div class="k-expander-header">
        <div class="k-expander-title">brazil</div>
        <span class="k-expander-spacer"></span>
        <div class="k-expander-sub-title">South America</div>
        <span class="k-expander-indicator k-icon k-i-arrow-chevron-down"></span>
      </div>

      .k-expander-spacer {
        flex: 1 1 auto;  
      }

```

In the above code, I removed the "k-expander-inner" and "k-expander-indicator" wrappers.

However, the rendering, at its current state, LGTM, so the above suggestion is just for consideration.

**Comment by silviyaboteva** [comment]
I'm dropping my suggestions as well:
 - I agree with Presli's proposal for removing the inner element and use the spacer instead. We use this approach in the AppBar and Scheduler toolbar as well.
 - I was expecting to see a root element with a class by it's name, e.g. `<div class="k-expander">...</div>`. And inside, we can list the expander collection of items. 

Here is a demo with the proposed changes: https://dojo.telerik.com/oZOKUhEG/2.

**Comment by joneff** [comment]
Just have in mind that flex does not yield the results you always expect:

```
// imagine the following consecutive expanders

gosho          sub v
pesho    longersub v

// in material guidelines it should be
gosho    sub       v
pesho    longersub v
```
All being said, I am in favour of flex.
I would probably

**Comment by inikolova** [comment]
Thank you for the feedback. Please find my comment: 

- After offline discussion, it appears that the expand / collapse icons should have purely decorative purpose, so we could remove the additional span with class **k-expander-indicator**;

- I like the idea for using spacer :)

- IMO a root component for multiple expansion panels is not needed - this scenario is covered by the PanelBar;

Based on the suggestions above, here is the updated dojo: https://dojo.telerik.com/@inikolova/ASAjaZIW

Are you ok to proceed with this rendering?

**Comment by PreslavKozovski** [comment]
FYI, we will add the `k-widget` class to the root element in jQuery.

**Comment by PreslavKozovski** [comment]
The `Less` Styles are in the following branch - https://github.com/telerik/kendo/commits/expansion-panel
