### ISSUE TITLE
Add styles for pager overlay with a light and a dark mode

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#1959]
[Default theme](https://xd.adobe.com/view/fc7a4cbf-5864-4490-8d8c-7860e4947b48-a929/)
[Bootstrap theme](https://xd.adobe.com/view/81f3df33-48d4-4981-9a1c-b30dcf8e89b6-d4a0/)
[Material theme](https://xd.adobe.com/view/c2547d22-0d0a-4efa-a6fc-ae3510fc4297-9707/)

**Comment by joneff** [comment]
Done with #2108
