### ISSUE TITLE
TextArea floating label overlaps the textarea content 

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#1961]
**Describe the bug**
The extArea floating label overlaps the textarea content after scrolling.

**To reproduce**

1. Go to https://winslaveblazor.dev.progress.com/blazor-ui/textarea/label
2. Select "Material" theme from the theme chooser on the right.
3. Type text inside the textarea, so that it becomes scrollabel
4. Scroll the textarea

**Expected behavior**
The floating label and the textarea's text do not overlap.

**Screenshots**
![textarea](https://user-images.githubusercontent.com/1857705/95706772-6e308780-0c60-11eb-9dd4-9d266e1ce5df.gif)

Refrerence: https://github.com/telerik/blazor/issues/1512#issuecomment-706144123

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Chrome version: [for example, 85]

**Note: ** The problem is not observed in Firefox

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by svdimitr** [comment]
Made public in https://supportheroes.telerik.com/ticket/1512311

**Comment by PreslavKozovski** [comment]
This behavior is caused by a bug in Chromium that is not going to be fixed - https://bugs.chromium.org/p/chromium/issues/detail?id=81560

A possible workaround for Chromium-based browser could be adding an element with a solid background to the top of the textarea between the label and the textarea text. The CSS could look like:

```
        .k-floating-label-container .k-textarea::before {
          content: "";
          width: calc(100% - 17px);
          height: calc(6px + 1.125em);
          background-color: #f5f5f5;
          border-radius: 2px;
          display: block;
          position: absolute;
        }

        .k-floating-label-container .k-textarea:hover::before {
          background-color: #ebebeb;
        }
```

For a runnable example, check this Dojo: https://dojo.telerik.com/eGUmeQAq
