### ISSUE TITLE
Sass compilebreak: Undefined variable $input-bg in kendo-theme-default (checkbox) after updating from v4.23.0 to v4.24.0

### ISSUE THREAD

**Issue by sceee** [telerik/kendo-themes#1973]
**Describe the bug**
After updating `kendo-theme-default` from ^4.23.0 -> ^4.24.0, the following Sass compilebreak occurred:
```
ERROR in ./src/common/kendo.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/common/kendo.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
12 │ $checkbox-bg: $input-bg !default;
   │               ^^^^^^^^^
   ╵
  node_modules\@progress\kendo-theme-default\scss\checkbox\_variables.scss 12:15  @import
  node_modules\@progress\kendo-theme-default\scss\checkbox\_index.scss 9:9        @import
  node_modules\@progress\kendo-theme-default\scss\adaptive\_index.scss 7:9        @import
  node_modules\@progress\kendo-theme-default\scss\grid\_index.scss 7:9            @import
  src\common\kendo.scss 5:9                                                       root stylesheet
```

**To reproduce**

1. Use the following code to embed kendo themes in a `kendo.scss` file:
```
@import "@progress/kendo-theme-default/scss/grid/_index.scss";
@import "@progress/kendo-theme-default/scss/spreadsheet/_index.scss";
@import "@progress/kendo-theme-default/scss/dataviz/_index.scss";
@import "@progress/kendo-theme-default/scss/editor/_index.scss";
```
2. Compile it using webpack with sass-loader
3. Compilebreak mentioned above occurs - I feel it is resulting from 1b9bf25f854d9d864e2adba24ec07022cf2328b1

Note that the code compiles successfully in `v4.23.0`.

**Expected behavior**
Variable is defined, compile still works

**Screenshots**
N/A

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* OS: Windows
* Node version: v12.19.0
* NPM version: 6.14.8

**Additional context**
As mentioned, it feels it was introduced by 1b9bf25f854d9d864e2adba24ec07022cf2328b1.

**Comment by joneff** [comment]
Targeted in related pull request. Depending on when the PR gets reviewed, we can have it in `dev` channel as soon as tomorrow and in `stable` channel some time after.

**Comment by joneff** [comment]
The themes are out
```
 - @progress/kendo-theme-bootstrap@4.23.2
 - @progress/kendo-theme-classic@0.3.2
 - @progress/kendo-theme-default@4.25.2
 - @progress/kendo-theme-material@3.21.2
 - @progress/kendo-theme-nouvelle@0.2.4
```
