### ISSUE TITLE
React build fails because of compile error "cannot divide by zero"

### ISSUE THREAD

**Issue by stefanelsat** [telerik/kendo-themes#1987]
**Describe the bug**
React build is failing to compile.

**To reproduce**
Create a new build using `react-scripts build`.
Build fails because of following error: 
`Cannot divide by zero`
`CompileError: Begins at CSS selector undefined`.

**Expected behavior**
The build succeeds without throwing an error.

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* OS: Windows
* Node version: v12.18.4
* NPM version: 6.14.6

**Additional context**
I was able to fix this issue by downgrading theme-bootstrap to [4.16.2](https://github.com/telerik/kendo-themes/releases/tag/%40progress%2Fkendo-theme-bootstrap%404.16.2).
This issue is probably related to [that one in facebook/create-react-app](https://github.com/facebook/create-react-app/issues/9801).

**Comment by joneff** [comment]
I believe the issue was fixed by #1976 which was included in @progress/kendo-theme-bootstrap@4.23.0 released a couple of days later.

**Comment by stefanelsat** [comment]
Yes @joneff , bug does not occure any more. Thank you!
