### ISSUE TITLE
Custom swatch doesn't compile: Undefined variable: "$input-bg"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1996]
**Describe the bug**
Using the following swatch:

```
// Variables.
$primary: blue; 
$secondary: pink; 

// Import the theme file for the components you use. 
@import "../grid/_index.scss";
```

and running the **npm run sass:swatches** command throws an error: _Error: Undefined variable: "$input-bg"_.

The error can be further reproduced by following the steps at the following article:
https://www.telerik.com/kendo-react-ui/components/styling/customizing/#customizing-themes-with-swatches

**Comment by joneff** [comment]
Duplicate of #1973. Please refer to it and the related PR.
