### ISSUE TITLE
"Filter" button blinks in IE when bootstrap theme is used

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#200]
Check the following sample plunker in IE version 11:

[StackBlitz example](https://stackblitz.com/edit/angular-ztnbmy-eubj8h?file=app%2Fapp.component.ts)

1. Click the filter icon on any row.
2. The "Filter" button blinks on opening of the filter popup.

**Comment by TeyaVes** [comment]
no longer reproducible as of Kendo UI v. 2019.2.514
