### ISSUE TITLE
The expand/collapse arrow moves horizontally in editable Grid with Detail rows

### ISSUE THREAD

**Issue by aleksandarevangelatov** [telerik/kendo-themes#2011]
**Describe the bug**
When a SASS theme is used for an editable Grid with detail rows, triggering the edit mode causes the expand/collapse arrow to move horizontally

**To reproduce**
1. Run this [dojo](https://dojo.telerik.com/@AleksandarEvangelatov/igAGOpuw)
1. Click on a field to edit a Grid master row

**Expected behavior**
The expand/collapse arrow should not move horizontally

**Screenshots**
[Screencast](https://www.screencast.com/t/Jaw0hPy6hUsw)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Comment by dmanova** [comment]
Notes from internal testing:
The cell top and bottom padding especially in the Material theme seem to has changed significantly as a side effect of the fix (at least I don't find other recent changes that could affect it). Here is a screenshot of the difference (now at left, with version 2020.3.1021 at right):
![Material-BiggerPaddingInEdit](https://user-images.githubusercontent.com/52446546/98385082-4235d580-2057-11eb-86f4-58f3e83d24b8.PNG)
