### ISSUE TITLE
The DropDownList items don't have ellipsis

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#2030]
**Describe the bug**
When having a too long text for any of the DropDownList items it should display ellipsis.

**To reproduce**
Please check the following example:

https://stackblitz.com/edit/angular-pd7jww-vmv8tm?file=app%2Fapp.component.ts

**Expected behavior**
There should be ellipsis for the first option in the popup.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by aleksandarevangelatov** [comment]
Also reported for Telerik UI for ASP.NET Core DropDownList in support thread: 1533702

**Comment by joneff** [comment]
fixed by 15095429fba919f86a59e2f862b7b5415122f2b4
