### ISSUE TITLE
SCSS Gantt styles kendo-theme-default build incorrectly by sass library

### ISSUE THREAD

**Issue by anton-marchenko** [telerik/kendo-themes#2031]
**Describe the bug**

Version: @progress/kendo-theme-default@4.25.1

When we build kendo-theme-default with sass library, we get an incorrect Gantt behavior.
In file node_modules\@progress\kendo-theme-default\scss\gantt\_layout.scss
you have in line 37:

```
        .k-grid-content tr {
            height: calc( #{$line-height-em} + #{$grid-cell-padding-y * 2} + #{$grid-cell-horizontal-border-width} );
        }
```

With node-sass that you use it compiled to:

```
.k-grid-content tr {
  height: calc( 1.4285714286em + 16px);
}
```
We have Angular project with JQuery Gantt inside. Angular uses sass library by default for compiling scss
So with sass library scss compiled to:

```
.k-grid-content tr {
  height: calc( 1.4285714286em + 16px + 0 );
}
```

And it is NOT correct height property. Because of this Chrome skips this property and Gantt works incorrectly.

![image](https://user-images.githubusercontent.com/45929621/97956004-a424df80-1db8-11eb-9eae-34ec44959334.png)

**Expected behavior**
Mentioned scss has to compile to:

```
.k-grid-content tr {
  height: calc( 1.4285714286em + 16px);
}
```

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Chrome version: [for example, 80]

**Additional context**
I have made [an issue](https://github.com/sass/sass/issues/2934) about it in sass repository. But they said that Sass's behavior here is correct.
Please see [the issue](https://github.com/sass/sass/issues/2934) for more details

**Comment by joneff** [comment]
@anton-marchenko we are aware of that particular behaviour of dart-sass, so we explicitly set our variables to `0px` in most locations. That particular variable is set: https://github.com/telerik/kendo-themes/blob/6bf8081b600ab309e960e7403568f10b10ce296e/packages/default/scss/grid/_variables.scss#L24

Can you verify you are not overriding that variable somewhere?

I do understand if you need to have set the variable to `0` (without unit), so you could actually get away with that by using post css plugins. Because this is a common scenario, we have an article in our wiki about [compiling the themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes#using-webpack). But if you were unable to find it, perhaps we should move it to a more prominent place...

**Comment by anton-marchenko** [comment]
@joneff 

But there are no dependencies from grid scss inside [gantt scss](https://github.com/telerik/kendo-themes/blob/6bf8081b600ab309e960e7403568f10b10ce296e/packages/default/scss/gantt/_index.scss)
I suppose that it is reason for loosing $grid-cell-horizontal-border-width variable value in gantt layout: https://github.com/telerik/kendo-themes/blob/6bf8081b600ab309e960e7403568f10b10ce296e/packages/default/scss/gantt/_layout.scss#L37

**Comment by joneff** [comment]
The way importing works is as follows:

* gantt/index imports treelist/index
* treelist/index imports grid/index
* grid/index imports grid/variables

In all instances we have of grid variables, we specifically use `px` unit. I just checked and doublecked:
* classic theme: https://github.com/telerik/kendo-themes/blob/bf0c1137b776118eda6967930a5f83b6342df427/packages/classic/scss/grid/_variables.scss#L24
* default theme: https://github.com/telerik/kendo-themes/blob/bf0c1137b776118eda6967930a5f83b6342df427/packages/default/scss/grid/_variables.scss#L24
* bootstrap theme:https://github.com/telerik/kendo-themes/blob/bf0c1137b776118eda6967930a5f83b6342df427/packages/bootstrap/scss/grid/_variables.scss#L24
* material theme: https://github.com/telerik/kendo-themes/blob/bf0c1137b776118eda6967930a5f83b6342df427/packages/material/scss/grid/_variables.scss#L24

There are a total of 8 mentions of `$grid-cell-horizontal-border-width`(https://github.com/telerik/kendo-themes/search?q=%24grid-cell-horizontal-border-width) :
* two in default/gantt/layout
* one in dropdowngrid/layout
* one in grid/layout
* one in grid/variables, per theme (a total of 4)

Even with [postcss-calc](https://www.npmjs.com/package/postcss-calc) disabled for compilation, I get the following output:
```css
.k-gantt .k-grid-content tr {
    height: calc( 1.4285714286em + 16px + 0px);
}
```

There should be something else that is causing the issue. My guess is, and that's a wild guess, that in your toolkit there is an optimizing bit that sees `0px` and optimizes it to `0` and that causes the error.

One way to verify this is to look for other selectors that have `0px`. For instance, historically we've put `border-width: 0px` on many selectors: `.k-switch-container`, `.k-progressbar`, `k-tooltip` ... and many more. Can you lookup those in the output of your application and verify that the `border-width` property reads `0` or `0px`?

**Comment by anton-marchenko** [comment]
@joneff 

As I understand, It would be enough to check our compiled (ng build) style.css, right?

I just checked it and discovered border-width: 0;

There are parts from our compiled style.css from dist folder:

```
.k-switch-container{border-radius:6em;padding:0;width:6em;border-width:0;border-style:solid;flex:1 0 auto;position:relative;outline:0;transition:background-color .2s ease-out 0s}

.k-progressbar,.k-progressbar>.k-state-selected{border-width:0;border-style:solid;overflow:hidden}
```

**Comment by joneff** [comment]
The compiled file indeed shows something plugs in after the compilation:

* all irrelevant space is stripped
* final in rules `;` is stripped
* units for zero values are stripped

I am assuming css nano on postcss, or something similar.

But that's good news -- it means there is the option to plug into that process. The article I referenced earlier, about [compiling the themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes), shows not only webpack setup, but gulp setup as well. So depending on your actual workflow, you can use the article to tweak your build process and get the desired output.
