### ISSUE TITLE
Rework grid toolbar styling to use flexbox

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#2037]
Currently, the Grid toolbar does not look ok on smaller screen sizes - there is no space around the input / buttons.
![Screenshot 2020-11-04 at 13 51 49](https://user-images.githubusercontent.com/1826086/98108598-e3c8f580-1ea4-11eb-8837-abd60779729a.png)

Rework toolbar styling to use flexbox and add margin to the toolbar children (similar to the standalone toolbar component). 

Expected outcome:
![Screenshot 2020-11-04 at 15 23 53](https://user-images.githubusercontent.com/1826086/98116973-c0f10e00-1eb1-11eb-89dc-9bd788291b7a.png)

**Comment by joneff** [comment]
Note on kendo-jquery: a certain small fix needs to be applied in kendo-jquery!

**Comment by Dimitar-Goshev** [comment]
Kendo UI for jQuery Grid's toolbar has no space around its buttons anymore:
![image](https://user-images.githubusercontent.com/6614183/101803859-a695fa00-3b19-11eb-99ab-a0c9ff4a8285.png)

Reproducible on SASS staging - Grid Batch Editing

**Comment by joneff** [comment]
Yes, some styles have to be transffered

**Comment by Dimitar-Goshev** [comment]
@joneff I looked at it, but as there was no linked PR at that time, the comment was a little unclear to me.
