### ISSUE TITLE
Syncronize swatches between themes and theme builder

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#2043]
Currently there is disparity between the swatches included in the themes and the swatches available in the [themebuilder](https://themebuilder.telerik.com/): say in the default theme we have 0 swatches, but in the themebuilder, we have [more than 20](https://themebuilder.telerik.com/kendo-ui?component=Button&theme=Default).

That's not the biggest issue here, really: the real issue is that if we update something in the themes, say we rename a variable, the themebuilder has no way of "knowing" that has happened and will still customize the old variable. In terms that will have no effect on the generated theme.

Another interesting bit is that if we include all available swatches in dist files, that' going to be a huge lump to download.

To tackle those here is what I propose:

* describe the swatches in a similar json format to the one in themebuilder
* based on that json file, generate swatch scss files
* specify which swatch files should be bundled for distribution

Finally, integrate those changes in the themebuilder, which by itself is a separate task.

**Comment by eeasss** [comment]
Do we need CI to validate whether the TB can compile against the themes?

**Comment by eeasss** [comment]
`
That's not the biggest issue here, really: the real issue is that if we update something in the themes, say we rename a variable, the themebuilder has no way of "knowing" that has happened and will still customize the old variable. In terms that will have no effect on the generated theme.
`
Vanka, do you think we need CI of some kind to address this?

**Comment by joneff** [comment]
If we have said integration, there will be no need for CI: the act of republishing the themebuilder will update it to the latest version of the themes, swatches and additional meta information.

**Comment by joneff** [comment]
That task kinda exploded and got much bigger, with portability of swatches being just part of the problems it will solve. So let's recap:

**Problems to solve**
* reliable compilation of themes
* exact output (as little as possible)
* portability of swatches

Let's start with **reliable compilation**. We already kinda have that, in the form of kendo-theme-tasks. However, the package is not the source of the build tasks, rather a target (copied during prepublish). To improve this, we'll extract the tasks in a separate repo and make this one dependent on it (#2226). That will also allow for fixed version releases and not the independent ones we currently have.

For all intents and purposes, kendo-theme-tasks will be the sole mediator between developers who want to compile the themes and the themes.

The next two, **exact output** and **portability of swatches** are actually interconnected i.e. solved together.

What does **exact output** mean? Say we want to build the grid. The grid only. It's not editable, just pageable. We'll, we are out of luck... The grid will also "bring in" all the inputs, pickers, buttons, toolbar, window ... because they might be needed. An **exact output** would be, just the grid and the pager. 

The reason for the described behaviour is quite simple and quite intended: we hard coded dependencies inside the sass files. We could ... massage the compilation input via our importer, but it's less than ideal. So what could we do instead?

For start, we could have separate file that lists the dependencies between components and use those relations to load only the files we need, prior compilation. In terms, that will make component files standalone, sort to speak; that will reduce compilation time, which is always nice.

Add in the portability, and things click into place quite nicely: we need a structured manifest for the themes that can be used both from themebuilder and theme tasks (and anyone else that wants to).

### Enter `kendoTheme.config.js`

So what is theme config? We'll it's a file that describes all the aspects of a theme.

```js
module.exports = {

    // Portability -- allow importing of other configs

    // from package
    'extends': '@namespace/pkg/theme.config.js',
    // from local path
    'extends': './path/to/theme.config.js',


    // Global variables -- we'll pass those to the compiler, or expose them to themebuilder
    'variables': [
        {
            'name': 'Primary',
            'var': '$primary',
            'value': '...'
        }
        // more variables
    ],


    // Components -- what to compile
    'components': [

        // include the component in its entirety
        'button',

        // customize it
        {
            name: 'combobox',
            options: [
                // ...
            ]
        },

        'grid'
    ],


    // Utils -- utility class names are a different type
    'utils': [
        'spacing',
        {
            name: 'float'
        }
    ],


    // Exclude / ignore -- explicitly remove items from compilation
    exclude: [
        'pager'
    ]
};
```

Note: the described format is far from final!

After some resolution of the file (and the linked files, if any) there will be a final that lists the files to be compiled and will compile those only!

### Usage

Since all this will be happening trough theme-tasks, the usage might be as follows:

* `tasks.build(file)`
* `$ kendotheme build --file ...`

Depending on the passed file (js or scss) one of two things will happen:
* js: validate input. if successful, proceed with resolution and build
* scss: build directly

Note: I will add diagram examples later

cc @tsvetomir

**Comment by tsvetomir** [comment]
Having such metadata is a great idea and would help a lot.

Is `options` intended to list high-level features, similar to the [custom download builder](https://www.telerik.com/download/custom-download)? That would be convenient. It's probably better if it's an object so we could pair it with a JSON schema for auto-completion and validation.

**Comment by joneff** [comment]
> Is `options` intended to list high-level features

It's intended for all types of features. Swatches, for instance, will customize just a couple of props. In that respect, themebuilder will customize, again, a couple of props (swatches) and which components styles to include. Complete themes, on the other hand, will delve into customizing ... well more :D

> It's probably better if it's an object so we could pair it with a JSON schema for auto-completion and validation.

Validation is on my mind, just as suggested by @eeasss. However, I would like to have the option to use `require` functions and reference values like webpack config does, or tailwind for that matter. But I guess it's still doable

**Comment by eeasss** [comment]
adding: @telerik/web-components-and-tools

**Comment by Xizario** [comment]
cc @vladimirivanoviliev

**Comment by joneff** [comment]
Looking back at this item, only the `extend` option is not implemented, but the initial core functionality is there.

I think for v1 we've done enough!
