### ISSUE TITLE
Flex tooltip content element

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#2060]
See https://dojo.telerik.com/@Dimitar-Goshev/OHAwUxIj:

```js
$("#target").kendoTooltip({
      autoHide: false,
      content: '<div style="width:100px;"><span>content</span></div>',
      width: 300
});
```

While the behaviour described inside is quite and edge case, it does make sense that we stretch `.k-kendo-tooltip-content`.

**Comment by Juveniel** [comment]
Please, make sure that the fix is also applied in the Less-based themes: telerik/kendo-ui-core/issues/6132
