### ISSUE TITLE
Add a class that sets touch-action and user-select to 'none' when dragging

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#2065]
**Is your feature request related to a problem? Please describe.**
When KendoDraggable is used for dragging-based functionalities like reordering, resizing, drag selection, etc., the pointer-cancel event is thrown on mobile devices, effectively stopping the drag action, and triggering the **handleRelease** event.

To prevent this, we need to dynamically add the **touch-action: none** style to a suitable element while dragging.

There are similar concerns, related to the **user-select: none** style that prevents text selection while dragging.

**Describe the solution you would like to see implemented**
A dedicated new class(es) applying the described styles will allow us to add/remove the said class(es) instead of applying and removing specific styles directly in the DOM.

**Describe the alternatives you have considered**
The currently available alternative is to add/remove the custom styling manually for the related elements, but having a dedicated class that can be reused across all suites seems a cleaner and more scalable solution.

**Additional context**
Currently there is a class, scoped to the Grid header that is handling the scenario for draggable columns:
https://github.com/telerik/kendo-themes/blob/4f71b79b60646e7898f5f04aa9c643ecfa3f0a95/packages/default/scss/grid/_layout.scss#L627

**Comment by joneff** [comment]
This will make a fine addition to our utils framework

**Comment by joneff** [comment]
@dtopalov, looking at the less themes, the same class is called `k-prevent-selection`. It's not a bad name, but since we are naming our utility classes after the property they target, we are calling this one `k-user-select-none`.
