### ISSUE TITLE
Readonly input widgets has different appearance on hover with Sass and Less themes

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#2073]
**Describe the bug**
When an input widget such as ComboBox, DropDownList, DatePicker is readonly and it is hovered if Sass themes are used, the styles of the widget are changed as it is interactive. With Less themes the styles are not changed. 

**To reproduce**

1. Open the [ComboBox API Demo](https://demos.telerik.com/kendo-ui/combobox/api)
1. Click on the 'Readonly' button to make the widget readonly and hover over it.

**Expected behavior**
The behavior should be consistent with the LESS themes. 

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
The less themes are outdated in many respects, including usability and accessibility:
* even if a component is readonly, it should be hoverable and keyboard and mouse focusable
* even if a component is disabled, it should be keyboard focusable, but not hoverable

@ivelina-penkova thoughts?

**Comment by joneff** [comment]
This will not be worked on: readonly components should be hoverable and focusable.
