### ISSUE TITLE
Floating label remains in input, using IE 11

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#2079]
**Describe the bug**
Using IE 11 and the latest theme version, the Kendo Angular [Floating Label](https://www.telerik.com/kendo-angular-ui/components/labels/floatinglabel/) does not float and remains in the input. See screencast:

https://screenrec.com/share/H9wNjpP43U

**Note**
The last version (Default theme) where the floating label works as expected is **4.20.0**.

**To reproduce**
[fl-label-IE.zip](https://github.com/telerik/kendo-themes/files/5553624/fl-label-IE.zip)

1. Download and unzip the folder
1. Run `npm install` in the root folder
1. Compile the app execute `ng serve`
1. Open http://localhost:4200/ and see the issue

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* IE 11

**Comment by devenchawlayyc** [comment]
Please fix this. This also seems to be an issue with kendo-react. Here's what I'm using:

    "@progress/kendo-data-query": "^1.5.4",
    "@progress/kendo-drawing": "^1.9.3",
    "@progress/kendo-react-animation": "^3.18.0",
    "@progress/kendo-react-buttons": "^3.18.0",
    "@progress/kendo-react-data-tools": "^3.18.0",
    "@progress/kendo-react-dateinputs": "^3.18.0",
    "@progress/kendo-react-dialogs": "^3.18.0",
    "@progress/kendo-react-dropdowns": "^3.18.0",
    "@progress/kendo-react-form": "^3.18.0",
    "@progress/kendo-react-grid": "^3.18.0",
    "@progress/kendo-react-inputs": "^3.18.0",
    "@progress/kendo-react-intl": "^3.18.0",
    "@progress/kendo-react-popup": "^3.18.0",
    "@progress/kendo-theme-material": "^3.22.0",

**Comment by devenchawlayyc** [comment]
@TelerikAdminTeam Do you have an update on this issue?
