### ISSUE TITLE
Group header height is too small when no groups are selected

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#210]
## I'm submitting a...
* Bug report 
## Current behavior

Only in IE 11, the Group header is too small when no groups are selected.

## Expected behavior

The Group header's size should be the same as in Chrome.
## Minimal reproduction of the problem with instructions
Open the example demonstrated in the following page in IE 11:

[https://www.telerik.com/kendo-angular-ui/components/grid/grouping/](https://www.telerik.com/kendo-angular-ui/components/grid/grouping/)

1. Remove the groups from the group header.
2. The group header height becomes too small.
## Environment

Browser:

- IE version 11

**Comment by gyoshev** [comment]
A CSS workaround until this is fixed in the themes:

```css
.k-grouping-header-flex > .k-indicator-container:last-child {
    line-height: 30px;
}
```

Here is the above rule integrated in a [StackBlitz example](https://stackblitz.com/edit/angular-ztnbmy?file=styles.css).
