### ISSUE TITLE
Floating Action Button style adjustments with Bootstrap

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#2100]
**Is your feature request related to a problem? Please describe.**
When Bootstrap is loaded in the page, the Floating Action Button styles are overriden, which leads to rebooting bootstrap styles with custom styles.

- `.k-fab-item-icon` should have `box-sizing: content-box;`
- `.k-fab:focus` should have `outline: none;`

Additionally, after a discussion with @joneff, we decided to add `.k-p-0` class, which will be responsible for resetting paddings -> `padding: 0 !important;`

**Comment by silviyaboteva** [comment]
@elena-gancheva .k-p-0 class name already exists. Check here: https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_spacing.scss#L15
