### ISSUE TITLE
When the widths of the Splitter panes exceed the width of the component, panes visibly overflow

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#2105]
**Is your feature request related to a problem? Please describe.**
When the Splitter component has an explicitly set width, and the sum of the widths of the panes exceeds the preset Splitter width, the panes overflow. This could happen both when one or more panes have "size" set such that the panes width exceeds the Splitter width, and when one or more panes have "max" set such that when resizing the pane it goes beyond the boundaries of the container:

1) Middle pane overflows:
https://stackblitz.com/edit/angular-14fhxv-xmmnyc?file=app/app.component.ts

2) Resize the Middle pane to the right
https://stackblitz.com/edit/angular-14fhxv-gticyo?file=app/app.component.ts

**Describe the solution you would like to see implemented**
Addressing the overflow with a scrollbar seems to be a more intuitive behavior:

https://stackblitz.com/edit/angular-14fhxv-vpftxf?file=app/app.component.ts

**Describe the alternatives you have considered**
All other suggestions to make the Splitter behavior in such scenarios more user-friendly are welcome.

**Comment by joneff** [comment]
We could provide utility classes -- `.k-overflow-*` that developers themselves attach **when needed**. Would that work?
