### ISSUE TITLE
Floating label stays inside the input after the value is entered (IE 11).

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#2112]
**Describe the bug**
The floating label stays inside the input after the value is entered (IE 11).

**To reproduce**

1) Open this demo on IE 11 https://www.telerik.com/kendo-react-ui/components/inputs/floating-labels/.

2) Enter value inside the Input.

3) Notice how the label stays inside:

![image](https://user-images.githubusercontent.com/11087921/101158323-37f5ff80-3634-11eb-94a0-aefcaf0c9835.png)

**Expected behavior**

The label floats.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material - Tested on material, but it should affect all.

**Affected suites (please remove the unneeded items)**
* Kendo UI for React - Tested on React, but it could affect others as well.

**Affected browsers (please remove the unneeded items)**

* IE version: [for example, 11]

**Additional context**

The top CSS rule of the label is not correctly calculated in IE 11 due to the not supported focus-within rule:

https://stackoverflow.com/questions/50932080/why-does-ie-and-edge-ignore-a-whole-css-rule

**Comment by silviyaboteva** [comment]
Browsers are ordered to ignore the entire CSS block if they do not understand the selector by the specs. Link: https://stackoverflow.com/questions/50932080/why-does-ie-and-edge-ignore-a-whole-css-rule.
We will have to separate the selectors.

**Comment by devenchawlayyc** [comment]
@silviyaboteva Just thought I'd also let you know that we do have the floating label working when we've used in a form. Is this bug only applicable to the use-case when floating labels are used outside of forms?

This is what we have currently with a working implementation of floating label inside of forms. Here's a code snippet:

`return (
    <FieldWrapper>
      <FloatingLabel
        optional={optional}
        editorValue={value}
        editorId={id}
        editorValid={valid}
        editorDisabled={disabled}
        label={label}
      >
        <Input
          valid={valid}
          type={type}
          id={id}
          value={value}
          disabled={disabled}
          ariaDescribedBy={`${hintId} ${errorId}`}
          {...others}
        />
        {showHint && <Hint id={hintId}>{hint}</Hint>}
        {showValidationMessage && <Error id={errorId}>{validationMessage}</Error>}
      </FloatingLabel>
    </FieldWrapper>
  );`

npm packages being used:
` "@progress/kendo-data-query": "^1.5.4",
    "@progress/kendo-drawing": "^1.9.3",
    "@progress/kendo-react-animation": "^3.18.0",
    "@progress/kendo-react-buttons": "^3.18.0",
    "@progress/kendo-react-data-tools": "^3.18.0",
    "@progress/kendo-react-dateinputs": "^3.18.0",
    "@progress/kendo-react-dialogs": "^3.18.0",
    "@progress/kendo-react-dropdowns": "^3.18.0",
    "@progress/kendo-react-form": "^3.18.0",
    "@progress/kendo-react-grid": "^3.18.0",
    "@progress/kendo-react-inputs": "^3.18.0",
    "@progress/kendo-react-intl": "^3.18.0",
    "@progress/kendo-react-notification": "^3.18.0",
    "@progress/kendo-theme-material": "^3.23.0"`

**Comment by devenchawlayyc** [comment]
Seems like the functionality was broken after specific release. If you rollback the following two npm packages, floating labels seem to work as expected in IE11:

npm install @progress/kendo-theme-material@3.17.0 --save
npm install @progress/kendo-react-inputs@3.15.0 --save

**Comment by silviyaboteva** [comment]
Hello @devenchawlayyc,
Yes, we recently introduced :focus-within CSS pseudo-class. The older versions work as expected.

**Comment by devenchawlayyc** [comment]
@silviyaboteva  What's the latest version I could use that work as expected?

**Comment by joneff** [comment]
@devenchawlayyc we are preparing a fix (#2176). When it's ready it will make it into our nightly and then our stable version.
