### ISSUE TITLE
Active styles are not applied to splitter bar when clicked in Firefox

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#2143]
**Describe the bug**
Active styles are not applied to splitter bar when clicked in Firefox

Firefox has decided that `event.preventDefault` on an element does not apply the `:active` state thus the CSS selector fails:
https://github.com/w3c/csswg-drafts/issues/2262
https://bugzilla.mozilla.org/show_bug.cgi?id=771241
https://bugzilla.mozilla.org/show_bug.cgi?id=1430196

**Note:** The `:active` styles problem might be present in other components as well and thus adding the [k-state-focused](https://github.com/telerik/kendo-themes/blob/2d61686b499ae7e762cdff708688ae0b256697d4/packages/default/scss/splitter/_theme.scss#L26) class to style the element is one of the solutions that work in all browsers.

Handling this from the themes only (as it is intended now) is a better option instead of using `mousedown/mouseup` events as suites prevent the default action on drag/resize. As this might turn out to be impossible to workaround, it is probably better to remove the `:active` styles and rely on a class only as the Firefox behavior is tricky to spot.

**To reproduce**

1. Go to https://www.telerik.com/kendo-angular-ui/components/layout/splitter/panes/#toc-specifying-the-dimensions in Firefox
1. Clock and hold the splitter bar

**Expected behavior**
The color of the element is changed.

**Screenshots**
The `:active` styles are not applied, thus the color of the element is not changed.
![image](https://user-images.githubusercontent.com/1857705/102076368-47cdca80-3e10-11eb-8fb7-a88fcf2173eb.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular
* Kendo UI for React
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Firefox 81.0

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
Changed the selector from `:active` to `:focus`, because this is the correct selector: when the splitbar is clicked it's also focused. Actually, no element can be active without being focused...

Not sure if we can workaround the behaviour, but adding a `k-state-focus` class should do the trick.
