### ISSUE TITLE
Enhance Fab & Fab Dial items box shadow elevation

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#2148]
**Is your feature request related to a problem? Please describe.**
Currently, the default box shadow of the Fab & dial items is very close to the focused one. This can be observed when having more than one Fabs on the same page. The focused Fab is difficult to be recognised.

Additionally, allow box-shadow when navigating through the disabled dial items, for a visual indication.

**Comment by silviyaboteva** [comment]
After an offline discussion, we decided to make 6dp shadow only in Bootstrap and Material themes as they do not require following the material guidelines. 

About the focus box-shadow on the disabled items, it will be lighter than the normal items have.
