### ISSUE TITLE
Bootstrap 5 compatibility

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#2154]
No sooner than Bootstrap v5 RC we should provide compatibility for our kendo-theme-bootstrap. Considering the breaking changes are not that much in terms of something changed, more in terms of something dropped (IE support), we should be able to handle this with a swatch.

The end result will be 3 swatches (v3, v4, v5) with some backporting of v5 features, such as the color maps, which are non existent in v3 and v4. Having v3 swatch would allow us to drop our bootstrap based less theme for Kendo UI for jQuery and derived products.

That of course is all **should**. We are yet to see how it all plays out.

**Comment by kdubious** [comment]
Must have.

**Comment by joneff** [comment]
@kdubious I updated the description with some vague wording on timeline and what needs to be changed. As soon as we have v5 RC we can begin the transition.

The reason we need RC is that they tend to be stable enough, while beta versions might change significantly.

**Comment by cawise** [comment]
@joneff 
Bootstrap 5 has just officially launched. Let the games begin!

https://blog.getbootstrap.com/2021/05/05/bootstrap-5/

**Comment by hexpoint** [comment]
Is there any updated timeline on this now? Starting a new project and the only thing holding us back from using bootstrap 5 is this.

**Comment by mattstewart1189** [comment]
Waiting for an update here to. Even if it's just a rough estimate.

**Comment by kdubious** [comment]
The [Roadmap](https://www.telerik.com/support/whats-new/kendo-ui/roadmap) page shows the following:
```
Bootstrap 5 Support
During the R3 2021 development release cycle Kendo UI for jQuery will receive Bootstrap 5 support, ensuring that any user updating to the latest version of Boostrap can continue to use their Kendo UI components.
```

**Comment by hexpoint** [comment]
I've gone ahead and started using Bootstrap 5 while still targeting the kendo bootstrap 4 css. So far only run into very minor issues that were easily fixed in case anyone else is considering doing the same.

**Comment by joneff** [comment]
@kdubious roadmap spoils the fun for everyone. Indeed we are targeting 2021 R3.

**Important Note**

Considering that we can support only a single version of bootstrap and there are some differences between v4 and v5, our v4 inspired swatch may differ from the current v4 swatch. I can think of at least one such difference: disabled checkboxes and disabled radios: [v5](https://getbootstrap.com/docs/5.0/forms/checks-radios/#disabled-1) vs [v4](https://getbootstrap.com/docs/4.6/components/forms/#disabled).

**Comment by kdubious** [comment]
@hexpoint Care to share your fixes here? I'm having an odd rendering issue with a chart.

@joneff I know... sorry to do that to everyone!

**Comment by hexpoint** [comment]
Sorry, haven't used any charts in this project yet, its been mainly the grid. We had a pretty custom setup for sizing/spacing of filtering fields and buttons. So fixes were just margin and padding types of minor changes. Still haven't run into any major issues with the grid though fortunately.

**Comment by joneff** [comment]
A quick bump, there is a PR in progress targeting bootstrap 5 compatibility. We are looking at july 26th date for the themes, or about three weeks from now.

**Comment by joneff** [comment]
The PR is merged and hence this issue is closed and the first dev version will be available monday, July 19th... HOWEVER

* considering bootstrap 5 is more than just a color swap of bootstrap 4, there will be additional PR's that polish the theme
* we'll create a color swap swatch of bootstrap 4 that will be 5, but with the colors of 4
* there were some incompatible changes between the versions so we did take some liberty with variables...

I will try to go into more details in the coming days

**Comment by kdubious** [comment]
Great work to all involved! Excited to try this out.

**Comment by joneff** [comment]
There were several challenges with the migration:

* variable names
* cascades
* colors
* spacing

**Variable names**

It does happen that several people while creating independent projects come up with the same name for a variable, say `$primary` or `$input-bg`. Since our kendo-theme-bootstrap depends on Bootstrap project, it's not rare to see constructs like `$primary: $primary !default`.

That particular construct -- it's meaningless... It assigns to the `$primary` variable the value of `$primary` variable if it doesn't exist... However, it's there for a reason: to denote that the variable's initial value is indeed coming from Bootstrap.

It gets more interesting with `$input-bg`.  Both in our theme the computed value is white (`#fff`), but we differ in the way we cascade the value. For instance, in Bootstrap it's directly linked to `$white`, where as our theme, we go trough an intermediate variable `$component-bg`, which in turns points to `$body-bg` which in turn points to `$white`.

That may look like an overkill to some, but reason is to have several plug points for customization. Say you customize the body background to be black, so will be the component and input. I will get back to the components in a bit, but let's continue with inputs for now.

Within our theme, we have defined rules for naming: variables ending with `-bg` refer to background color, `-text` refer to text color and `-border` refer to border color. That's not the case with Bootstrap, which use `-color` and `-border-color` respectively, but somehow use `-bg` for background... in most cases that is...

So it may happen, and it does a lot, that there is a concept in our theme that is present in bootstrap (and vice versa) and the only variables in common is `-bg` and sometimes padding variables. Since we need to adhere to Bootstrap guidelines, our `$input-text`variable is mapped to `$input-color`.

Side note: we do have this tool that allows to customize themes with a very few clicks. The question is: do we customize `$input-color` or `$input-bg`? We used to customize both... You may have noticed `_bootstrap-overrides.scss` file. With this update, we significantly reduced the overrides and left just a few.

Probably the best solution would be to have all our variables prefixed, say `$kendo-input-bg` to leave no room for doubt if the variable is native or not.

**Cascade**

I already mention this, but in kendo themes, variables cascade a lot -- we tend to have intermediate variables that allow multiple components to be customized via a single variable and also have specific variables for that component. Also, most variables follow the same cascading logic.

That's not always the case for Bootstrap and it makes things quite unpredictable. Let's take a look at checkbox: the background variable is linked to input background variable, but the border color variable is a fixed color... So if I go trough all the trouble to make my inputs dark, then my checkboxes will need additional tweaks.

Which leads to

**Colors**

Colors are not uniform in Bootstrap: some are tied to specific variables, like `$gray-300`, but some are tied to percentages of black. There are several near identical values: `rgba($black, .125)`, `rgba($black, .15)`, `rgba($black, .2)` and `rgba($black, .25)`. It's OK that they exist and do blend nicely, but they are loose and are hard to fit inside a design system.

**Spacing**

Spacing is another not uniform aspect of Bootstrap. There is sort of sizing system, which is great, but it's not used nearly enough. It's sort of weird going trough `.25rem` at first and then skipping a few. But then we have variables like button padding, which is `.375rem`. With normal font settings, `.375rem` is `6px` which mind bogling-ly hard number to work with and no matter how I add or subtract `.25` I can never get to `.375`.

---

It may seem like it, but that was not a rant against Bootstrap. The Bootstrap team and contributors did a splendid job with v5 and it is indeed a much more mature version, so I am not downplaying anyone's efforts.

It's just become much more apparent to us that in order to have a stable kendo bootstrap theme, we need to rethink how we integrate with it and how we use the variables. If a variable is stable enough, we are going to use it; if we are unsure that a variable is stable enough, we are going to use its value.

For instance, `body-bg` and `body-color` are quite stable and we don't expect them to change. In terms, we link our variables to them. In the case of checkboxes, however, we've simply assigned the values (except for the border, which is `$gray-300` and not `rgba($black, .25)`.

What I've outlined above is the areas in which we are going to polish and improve our bootstrap theme, so we can ensure a stable version with coherent look and feel for our 2021 R3 product release. I don't expect much changes between v4.40.0 (due out on July 26th) and the next version, either 4.41.0 or 4.40.1 (due out early September).

I can already tell you that the first fix for the theme is going to be focus shadow of inputs which are currently invalid... Expect that sort of changes.

**Comment by kdubious** [comment]
@joneff How would I get access to this to check it out?

**Comment by joneff** [comment]
@kdubious just install the latest kendo-theme-bootstrap version. we've matched all version of the themes to roll together, so the latest version currently (and all the way to september 6th) will be 4.40.1

**Comment by kdubious** [comment]
@joneff The README in 4.40.1 reads like this: `The Kendo UI Bootstrap Theme is a theme for the Kendo UI components which is based on the Twitter Bootstrap framework, version 4.`

**Comment by joneff** [comment]
Rarely, have I been more embarrassed. Removed bootstrap version information with #2699. We must definitely word more carefully which version we use...

**Comment by kdubious** [comment]
@joneff if this is one of your biggest embarrassments, you are lucky!
