### ISSUE TITLE
The selected DropDownList items aren't fully highlighted

### ISSUE THREAD

**Issue by lachezar-georgiev** [telerik/kendo-themes#2162]
**Describe the bug**
When a selected item in the DropDownList is longer than the input width, it's not getting fully highlighted.

**To reproduce**
Use this demo:
https://demos.telerik.com/blazor-ui/treelist/custom-editor

1. Click Add
2. Click Save so that DDL doesn't have value set and a default value will be used.
3. Edit the newly added item.
4. Open the DropDownList and use its horizontal scroll to verify its selected value

**Expected behavior**
The selected item should be fully highlighted when using the horizontal scroll

**Screenshots**
![image](https://user-images.githubusercontent.com/73476307/102484081-63361100-406e-11eb-9e66-c2f171ca92b7.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Additional context**
There is another [issue ](https://github.com/telerik/kendo-themes/issues/2030), that describes the same bug but proposes a different solution. After a discussion with @nedevp, it was suggested that the selected item should be fully highlighted and the scroll X should remain.

Might apply to other dropdown components like AutoComplete/ComboBox.

**Comment by lachezar-georgiev** [comment]
Link to blazor issue: https://github.com/telerik/blazor/issues/1359

**Comment by joneff** [comment]
This is a well known issue, or rather a limitation in any browser. Here is good explanation: https://stackoverflow.com/a/45497692. 

In order to overcome the issue, we either need specific size on the scrolled element (`.k-list`) or many wrapping elements around it. Those were the ways we fixed the issue in Telerik UI for ASP.NET Ajax... Either way, this is not a themes issue. Closing.
