### ISSUE TITLE
Notification close button is visible when Notification button property is false

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#2174]
**Describe the bug**
The **close** button of Kendo UI for jQuery Notification visibility should be controlled by the [button](https://docs.telerik.com/kendo-ui/api/javascript/ui/notification/configuration/button) property, which is **false** by default.
But with SASS themes the close button is always visible.
NOTE: this is not a regression - it has always been this way with SASS themes.

Hint - set [autoHideAfter](https://docs.telerik.com/kendo-ui/api/javascript/ui/notification/configuration/autohideafter): 0 to disable auto hiding.

**To reproduce**
1. Go to Notification [Basic Usage demo](https://demos.telerik.com/kendo-ui/notification/index?autoRun=true&theme=default-v2)
1. Click the buttons to display notifications - the close button is visible.
1. Switch to LESS Default theme
1. Click the buttons to display notifications - the close button is NOT visible.

**Expected behavior**
The close button is not visible with SASS themes, unless button is set to true

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment]
This should be handled from the code: if the button must not be visible, it must not be present in the rendering

Thoughts @telerik/kendo-jquery-team2-dev ?
