### ISSUE TITLE
Search input not aligned correctly in Filter Multi Checkboxes demo

### ISSUE THREAD

**Issue by NikoPenev21** [telerik/kendo-themes#2187]
**Describe the bug**
Search input not aligned correctly in Filter Multi Checkboxes demo
**To reproduce**
Open below link and on ProductName filter icon
https://demos.telerik.com/aspnet-core/grid/filter-multi-checkboxes

**Expected behavior**
The input shall be aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/46747298/103097151-02c74680-460f-11eb-970f-f0182b527165.png)

**Affected package (please remove the unneeded items)**
All

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by PreslavKozovski** [comment]
WIll be automatically fixed when https://github.com/telerik/kendo-themes/issues/2119 is done.
