### ISSUE TITLE
Slider ticks are not positioned on Safari Mac

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#2197]
**Describe the bug**

Ticks positioning is not working for Slider and RangeSlider under Mac Safari.

**To reproduce**

1. Go to https://winslaveblazor.dev.progress.com/blazor-ui/rangeslider

**Expected behavior**
The ticks to be evenly distributed around the track

**Screenshots**
![image](https://user-images.githubusercontent.com/7159157/103739824-dc39e000-4ffe-11eb-84e3-cdd3001a3869.png)

**Affected package**
* all themes

**Affected suites **
* Telerik UI for Blazor

**Affected browsers **
* Safari version: 14/13

**Build system information (please remove the unneeded items)**
* OS: Mac

**Comment by dtopuzov** [comment]
Looks better now, but we have another issue.

Safari vs Chrome on macOS:
![image](https://user-images.githubusercontent.com/6651651/103888422-6496ae80-50ed-11eb-863b-108b194f5fc1.png)

In Safari there is no margin between ticks and Increase/Decrease buttons and that cause some overlaps when you set min/max value.

**Comment by joneff** [comment]
Currently, Safari is the only modern browser to not support flex gap. It does in Technology Preview which means it will be shipped either in 14.1 or 15. With that in mind, I am closing the issue.

On a related note: the initial issue here was that Safari didn't respect `flex-basis: 100%` without having explicit `flex-grow`. I guess the WebKit / Safari team are still polishing their flexbox implementation.

With that in mind, I am closing the issue.
