### ISSUE TITLE
Form Validation Styles Revision

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#2200]
Related to: https://github.com/telerik/kendo-ux-private/issues/261
Blazor issue: https://github.com/telerik/blazor/issues/1824

- [x] Verify the validation styles of all form components
       - Validation icon support
       - Error validation border styles
- [x] Tooltip validation - depends on the design item

**_Blazor release: 24th of February (Blazor Dev will start working on the Form at the beginning of February)_**

**Comment by Juveniel** [comment]
Summary from the revision:

* Error validation styles(inline) - the styles for errors and hints currently match the design.
* Tooltip validation - based on the design guidelines, the tooltip should utilize the default styling from the themes, thus no further enhancement is needed.
* Validation summary styles(message-box) - _Update TBD_.
* Validation icons support - this item will be reviewed as part of the buttons & inputs standartization cross-team task, as it involves implementing different rendering for some of the components. I have logged a separate issue for the task where further information is available: https://github.com/telerik/kendo-themes/issues/2252
