### ISSUE TITLE
CSP improvement for font loading (avoid data:)

### ISSUE THREAD

**Issue by andrewb273** [telerik/kendo-themes#223]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Fonts are loaded via `data:` which requires an additional CSP exception. Specifically I think this is `WebComponentsIcons`.

## Expected behavior
Alongside this behavior which I understand is required for Angular, it'd be great to provide a build option or even an alternate output option (e.g. `all-csp.css` & adding the font manually) so that the `data:` font CSP rule doesn't need to be added.

## Minimal reproduction of the problem with instructions
1. Include `all.css` and perhaps a grid
2. Load page with CSP only allowing fonts from `self`
3. See the CSP exception in the dev console and the lack of fonts loading

## What is the motivation or use case for changing the behavior?
Tighter security via CSP

## Environment
Product:
* Kendo Ui for React (but it's likely for all)

Package versions:
```
"@progress/kendo-theme-default": "^2.54.0"
```

Browser:
- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)
- Firefox version 60.0.2 (64-bit)

System:
- TypeScript version: 2.9.1
- Node version: v8.9.0
- Platform: Windows 7

**Comment by gyoshev** [comment]
Thanks for providing a workaround for the problem!

I think we can easily add a variable that, if set, will allow loading the font from a path:

```scss
$icon-font-path: "~@progress/kendo-theme-default/scss/common/font/WebComponentsIcons.ttf";
```

If not set, the default font will be embedded.

**Comment by andrewb273** [comment]
@gyoshev so this would be an actual CSS variable? Are you thinking that it'd take precedence over the base64 font spec, but if null it'd fallback to the base64? The key thing is to not have the base64 in the content loaded to the browser, and the CSS variable solution sounds as though it might still include that base64 in the output. Though I could be misinterpreting? Key thing is that base64 isn't in the content that the browser loads.

**Comment by gyoshev** [comment]
@andrewb273 I meant a SCSS variable, which allows  controls the CSS output. This will allow you to compile the theme without a data URL &mdash; if the variable is set to a path, the SASS processor will not embed the base64 string, but use the path instead.

See the [linked commit](https://github.com/telerik/kendo-themes/commit/28aab4a586bee59ef5191347d2677aedc93fdb2e) for the suggested solution. You can [install the theme from the git repo](https://stackoverflow.com/a/21918559/25427) to try it out in your scenario. You can use `$icon-font-url: "~@progress/kendo-theme-default/scss/common/font/WebComponentsIcons.ttf";` to compile the SCSS in the same way that the above Webpack plugin does.

**Comment by gyoshev** [comment]
The variable is introduced in `@progress/kendo-theme-material@1.2.0`, `@progress/kendo-theme-default@2.55.0`, and `@progress/kendo-theme-bootstrap@2.13.8`

**Comment by andrewb273** [comment]
Thanks so much, sorry I didn't get to test it out! Task was pushed to the backlog 😞

**Comment by gyoshev** [comment]
@andrewb273 No worries 😄 We had other reports of this limitation, so we've decided to release the fix, so that there is a way to resolve this without a webpack plugin.

**Comment by andrewb273** [comment]
Worked perfectly - great improvement on my webpack config! :+1:
