### ISSUE TITLE
Kendo Themes Standalone Documentation 

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-themes#2235]
This is part of the https://github.com/telerik/kendo-okrs/issues/17 OKR. 

The purpose of this item is to create the base for a standalone kendo themes documentation. 

We should create new Katana instance that is using the Default theme for styles. 

Initial goal of this effort could be running documentation that
- Applies applicable colors from the Default theme to the styled components used in Katana
- Displays the existing docs that live under https://github.com/telerik/kendo-themes/tree/develop/packages/default/docs
- Has build setup and deployment to a server

Child items:
- [x]  Structure and styles for standalone theme documentation (#2246)
- [x]  Site and deployment for standalone theme documentation (#2247)

**Comment by kspeyanski** [comment]
We were discussing with @joneff about dropping the usage of `styled-components` completely from the `kendo-themes` website only, and proceed with an UI build entirely with the `kendo-themes`. While the `styled-components` approach is more-suitable for the business needs of `kendo-react/angular/vue-ui`, this might not be the case for the `kendo-themes`

What we aim to achieve with this move is to validate that building such public facing webapps is indeed possible with the KendoThemes and further showcase their capabilities.

While we are yet to agree on this, i wanted to share it nevertheless.

**Comment by joneff** [comment]
The way I see it, we could split the task in two:

* one person (or group of people) can see what we can do to have the site reliant on kendo themes i.e. what we need in the themes to build the skeleton of a site
* the other person (or group of people) should work in direction of the actual deployment

I actually think we could go with styled components for the layout, so we have the maximum performance. It should also help validate if we can go with more specific layout components. Think barebone UI layouts with no, or little, own chrome (https://examples.sencha.com/extjs/7.0.0/examples/kitchensink/#layouts).
