### ISSUE TITLE
Structure and styles for standalone theme documentation

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#2246]
Part of #2235. Part of #2247

* [x] styles and markup

The goal here is use kendo theme styles as much as possible -- the theme should be customizable enough to fit the needs. Think only utility classes and little to no additional styles!

Considering our typography is currently scoped behind `k-typography` class, we'll need to expose it to first level without scoping, but have switch to maintain backwards compatibility.

* [x] information architecture

Establish information architecture to be used for the site. Determine the different sections and parts of the site, as well as future development needs.

We'll most definitely need to change how our md files are structured (our docs files reside in docs flat folder), so think about that as well.

Consider that various kendo products rely on the documentation to source some articles. We have some articles in the wiki that will probably need to be exposed.

Finally, each theme's README file is less than ideal and we could and must improve them..

**Comment by eeasss** [comment]
A couple of checkboxes from https://github.com/telerik/kendo-okrs/issues/17

  - [ ] HTML for each component, presented as a React Component
  - [ ] List of Primitives that apply for each Component and Common ones
  - [ ] List of Keyboard Interactions and ARIA, standardized definitions. 
  - [ ] List of Animations that exist in the components and their usage within components
