### ISSUE TITLE
Site and deployment for standalone theme documentation

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#2247]
Part of #2235. Related to #2246.

* [x] create katana-centric site

Consult with @kspeyanski about scaffolding and bootstraping such site. Decide on the number of templates / plugins that need to be created

* [x] create components

As noted in the related item (#2246), we want to use kendo themes as much as possible. While we can always just use static markup in the templates, perhaps a component approach will be more useful: apart from achieving the goal of critical styles separation, it can also serve as test bed for layout components based on kendo themes.

* [x] infrastructure and deployment

As with any site, we'll need to deploy and keep the code somewhere. Since the site is a mere shell around markdown content, the codebase is not required to live alongisde it. Consult with @ipeshev how and where we should deploy and if we can do it with github actions.

**Comment by joneff** [comment]
@peshev we've reached the part where we need your help:

* we need to deploy the site internally, say under `kendo-theme-docs`
* currently, the site is in `kendo-theme-site` branch in katana and the location of the sources is `/kendo-themes`
* after all testing is done, we'll merge it, but the location will remain the same.

**Comment by eeasss** [comment]
Can you please post link to the deployed site here?

**Comment by Juveniel** [comment]
The site is available on staging from the `kendo-theme-site` branch in katana here:

* https://k2build.dev.progress.com/katana/kendo-theme-site/kendo-themes/getting-started/installation/

There are some minor issues with selection/link navigation on staging that we are still to fix before merging in develop.

**Comment by Juveniel** [comment]
The site deployed from develop is available here:

- https://k2build.dev.progress.com/katana/develop/kendo-themes/getting-started/installation/

**Comment by ipeshev** [comment]
https://k2build.dev.progress.com/kendo-themes-docs/getting-started/installation/  
https://k2build.dev.progress.com/kendo-themes-docs-develop/getting-started/installation/
are available
