### ISSUE TITLE
Themes do not color the loading sign, text and icons of the Upload

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-themes#2260]
**Describe the bug**

The text color and loader color of the upload header remain black.

**To reproduce**

1. Go to the theme builder https://themebuilder.telerik.com/blazor-ui
1. Choose the Bootstrap theme (might manifest with others too)
1. Select all components
1. Choose a dark theme (it is easier to see the issue)
1. Use that theme with an upload, such as the snippet below
1. Click the Upload button on that snippet (it will fail with the upload itself but you can see the loading sign and the text in the header - they are black). The icons are also black and should probably be white

**Expected behavior**

The text color and loader color from the theme are applied to the upload too

**Screenshots**

![8f967160-17f5-4904-ab30-b47e70ae9638_img1](https://user-images.githubusercontent.com/5746515/106158586-92bb5b80-618c-11eb-995d-59eec4d60127.png)
![8f4b4023-8031-4dbe-8d60-3b8c1b06f7c7_img2](https://user-images.githubusercontent.com/5746515/106158588-9353f200-618c-11eb-8d2e-1da0dc58087d.png)

**Affected package (please remove the unneeded items)**

* theme-bootstrap 
* theme-material - the icon becomes gray so that may be OK

**Affected suites (please remove the unneeded items)**

* Telerik UI for Blazor - I have not tested others, likely there too

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional information**

A workaround could be using some additional CSS to change the colors:

```
div.k-upload .k-file-group.k-icon,
div.k-upload .k-dropzone .k-upload-status,
div.k-upload .k-dropzone .k-dropzone-hint {
    color: #fff;
}
```

**Comment by joneff** [comment]
Appears to be fixed. Probably by #2652
