### ISSUE TITLE
Timepicker milliseconds label cut off

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#2274]
**Describe the bug**
The columns in the Timepicker are not wide enough, therefore the milliseconds label gets cut off.
The issue can be seen in all 3 themes but it is most obvious in Material
Kind of related to https://github.com/telerik/kendo-themes/pull/2107

**To reproduce**

1. Go to [Angular Timepicker demo](https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/incremental-steps/)
1. Click on the picker to expand it
1. See the milliseconds label

**Expected behavior**
There should be enough space for all labels so they are not cut off.

**Screenshots**
![timepicker](https://user-images.githubusercontent.com/7753940/106717795-d983d800-6608-11eb-9822-8a4e96f83df9.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
This will not be worked on:

1) there is a variable controlling how wide that "column" is.
2) this should be a resource and as such, it can be changed to something shorter

Note: `milliseconds` can also be changed to something longer, so it's not like we can have one size fits all.
