### ISSUE TITLE
Grid Checkbox Filter menu looks broken

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-themes#2277]
**Describe the bug**
With latest theme the Grid Checkbox Filter Menu looks broken as seen in the following screenshot. The issue is applicable to all themes.

**To reproduce**
1. Go to https://www.telerik.com/kendo-react-ui-develop/components/grid/filtering/#toc-column-menu-filter 
1. Click on ProductName column menu

**Screenshots**
![image](https://user-images.githubusercontent.com/2195951/106868473-7c0a8c80-66d7-11eb-84ae-759bcef5aad1.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: Ubuntu

**Comment by PreslavKozovski** [comment]
Should be fixed with https://github.com/telerik/kendo-themes/issues/2119
