### ISSUE TITLE
Grid: new column index indicator not appearing on reorder

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-themes#2278]
**To reproduce**

1. Go to [https://dojo.telerik.com/@anton.mironov/UYUliHUp](https://dojo.telerik.com/@anton.mironov/UYUliHUp)
2. Reorder random columns

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/64422725/106877001-fbe92480-66e0-11eb-82cb-786a0df6fea9.png)

**Affected browsers**
* All

**Comment by Juveniel** [comment]
related to missing default zIndex in jQuery kendo.reorderable
