### ISSUE TITLE
Importing separate scss files requires specific order

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#2283]
**Describe the bug**
Importing separate scss files requires specific order. When importing separate scss files for switch, notification and grid, and overriding some of the variables, no changes are applied if grid.scss is imported first.

**To reproduce**

1. Import separate scss files for grid, notification and switch in this specific order;
1. Change some sass variables in switch;
1. See no changes are applied.

However, changing files order and move the grid.scss to the bottom, the changes are applied.

**Expected behavior**
Order of files should not matter.

**Additional context**
Reported in private issue: 1505633

**Comment by joneff** [comment]
The described behaviour is actually the correct one: when `_grid.scss` imports grid styles from the themes, that second grid file is going to be importing the switch styles. Note that at this current compilation time the variables for switch are not yet processed, so wont be used. Those styles will be cached so they won't be processed again. When the `_switch.scss` file imports the swtich styles again, nothing will happen.

The solution is to have the variables inside the index file. That way variables will be used the first time the styles are loaded. That's a side effect from having dependencies.
