### ISSUE TITLE
Label and input checkbox are misaligned in form

### ISSUE THREAD

**Issue by lachezar-georgiev** [telerik/kendo-themes#2291]
**Describe the bug**
When in a k-edit-form-container the label and the field are misaligned.

**To reproduce**
1. Run this blazor playground page:
https://winslaveblazor.dev.progress.com/blazor-playground-server/grid/popup-editing
1. Click the Edit button on any row.
1. The label and checkbox elements are misaligned.

**Expected behavior**
The label and field are aligned.

**Screenshots**
default theme:
![image](https://user-images.githubusercontent.com/73476307/107402603-d27b2f00-6b0c-11eb-9920-6cc1b3f937a4.png)

bootstrap theme:
![image](https://user-images.githubusercontent.com/73476307/107402728-f8a0cf00-6b0c-11eb-8d6c-aefa69de6e56.png)

material theme: seems like it's working as intended, not sure really:
![image](https://user-images.githubusercontent.com/73476307/107402932-33a30280-6b0d-11eb-85e3-915e3d4cf8a8.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
The form in question is using the legacy styles for forms. Update to the latest markup and things will be fine.
