### ISSUE TITLE
Grid with sticky column is shown over dragged tile in TileLayout

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-themes#2339]
**Describe the bug**
A Grid with sticky column overlaps neighboring tile when it is resized

**To reproduce**

1. Go to https://dojo.telerik.com/UmIValuP/2
1. Start resizing the left Tile

**Expected behavior**
The Grid should be under the resized Tile

**Screenshots**
![image](https://user-images.githubusercontent.com/11771009/109009014-ab992d00-76b6-11eb-8871-203286a27c19.png)

![GridInTileLayout](https://user-images.githubusercontent.com/11771009/109009140-dd11f880-76b6-11eb-86aa-a33b95247422.gif)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by GeorgeGindev** [comment]
While resizing, the tile  applies inliine z-index: 2, and the sticky column has z-index: 3

One way to overwrite it is with **!important** declaration like in this dojo - https://dojo.telerik.com/UmIValuP/5

**Comment by joneff** [comment]
I've set lower initial z-index so this should do it. However, upon resizing, all other items should receive `k-pointer-events-none` class to prevent any mouse interaction within the rest of the cards.
