### ISSUE TITLE
Material Outline Button should not have shadow in active state

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#237]
`.k-button.k-state-active, .k-button:active` should not have a box-shadow

Preview: https://plnkr.co/edit/boFCDvAXE2PEA09cfwHi?p=preview
Material Implementation: https://material-components-web.appspot.com/button.html
Design: https://github.com/telerik/kendo-ux/blob/master/themes/material/buttons.psd

**Comment by elena-gancheva** [comment]
The issue has been fixed and is available in the development builds of the themе: https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/
