### ISSUE TITLE
Status Text of the Vertical Progressbar is not Centered in Chrome

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#2370]
**Describe the bug**
Status Text of the Vertical Progressbar is not Centered in Chrome.

This bug is caused by Chromium - https://bugs.chromium.org/p/chromium/issues/detail?id=1120156&q=component%3ABlink%3ELayout%3EFlexbox

We will close this issue when they fix it.

### Workaround

```
.k-progressbar-vertical .k-progress-status {
    width: fit-content;
}
```

**Expected behavior**

The status text is centered.

**Screenshots**

![image](https://user-images.githubusercontent.com/17339722/110944682-7131c000-8345-11eb-89df-ca4867f9f24f.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Chrome version: 89

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
Seems to be OK with chrome 92.
