### ISSUE TITLE
Filter Menu has additional border

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#2374]
**Describe the bug**

**.k-button-group** class applied to the action buttons of the filter menu, has _box-shadow_ CSS property which adds an additional border to the filter menu popup:

https://screenrec.com/share/sMVSDL5EZf

![MicrosoftTeams-image](https://user-images.githubusercontent.com/33104481/111166497-d1746c00-85a8-11eb-99d7-0de6cf24fb37.png)

**To reproduce**
Open Filter Menu
https://stackblitz.com/edit/angular-4zguqe

**Affected package (please remove the unneeded items)**
* theme-material (Grid and TreeList)

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Comment by inikolova** [comment]
The following PR addresses the problem:
https://github.com/telerik/kendo-themes/commit/02e2f544fa9337a2710cfa45f62ac17e303ad83e
