### ISSUE TITLE
The Stepper progress bar is larger in IE11

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#2387]
**Describe the bug**

The Stepper progress bar is larger in IE11

**To reproduce**

This can be seen in every demo.

**Expected behavior**

The progress bar should look the same on all supported browsers

**Screenshots**

![image](https://user-images.githubusercontent.com/11087921/111760267-2d8c0880-88a7-11eb-9de6-b0f56d17a433.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**

* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by TeyaVes** [comment]
No longer reproducible as of Kendo v. 2022.1.119
