### ISSUE TITLE
Command buttons overlap if the column does not have enough width.

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#239]
## I'm submitting a...
* Bug report 

reported in 1178646

## Current behavior

Command buttons overlap if the column does not have enough width.

https://www.screencast.com/t/sJLhyNY6v
https://www.screencast.com/t/b6uVQ28B8p

## Expected behavior

https://www.screencast.com/t/RfLoICH5av

## Minimal reproduction of the problem with instructions

https://dojo.telerik.com/ePohucoL
https://dojo.telerik.com/UMAgeWOv

## Environment
Product:

* Kendo Ui for jQuery
Package versions:

```

```

Browser:

- Chrome (desktop) version XX

**Comment by NikoPenev21** [comment]
Reported also in 1448153
