### ISSUE TITLE
The DropDownList is not styled properly when used in a Toolbar 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#242]
## I'm submitting a...

* Bug report 

## Current behavior
The appearance of a DropDownList inside a Toolbar is not as expected for the material theme.

## Minimal reproduction of the problem with instructions

![2018-07-27_1619](https://user-images.githubusercontent.com/20015190/43322935-d63b5118-91b8-11e8-92d5-387d757eb991.png)
[https://stackblitz.com/edit/kendo-toolbar-lookup-1tp8as](https://stackblitz.com/edit/kendo-toolbar-lookup-1tp8as)

## Environment
Product:
* Kendo Ui for Angular

**Comment by joneff** [comment]
Appears to be fixed as of 2018 R3 (v 1.3.0).
