### ISSUE TITLE
ListView k-listview and k-listview-bordered classes have redundant border CSS rule

### ISSUE THREAD

**Issue by CecoMilchev** [telerik/kendo-themes#2446]
**Describe the bug**
Both the k-listview and k-listview-bordered classes have the same border-width rule. The ListView widget has a [**bordered**](https://docs.telerik.com/kendo-ui/api/javascript/ui/listview/configuration/bordered) option that indicates whether the outermost element should have a border or not.

Since this class is added on demand (added by default), the border is shown. However, if the property is set to false, the border will still be visible because of the border-width applied to the k-listview class. Therefore, making the **bordered** property non-functional.

- [Style applied to k-listview](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/listview/_layout.scss#L6)
- [Style applied to k-listview-bordered](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/listview/_layout.scss#L19)

Since the two classes are applied to the exact same div HTML element of the ListView, the border styles inside the .k-listview class should be removed.

- [Logic for setting the k-listview-bordered class in the ListView](https://github.com/telerik/kendo/blob/master/src/kendo.listview.js#L254)

**To reproduce**

1. Create a ListView widget.
2. Set the bordered option to false.
3. Border is shown.

Dojo sample for reproduction:
https://dojo.telerik.com/IhuFociL

**Expected behavior**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
the duplicate styles in question were added as a temporary solution. with 2022 R1 we'll remove them.

**Comment by epetrow** [comment]
Will be fixed with the following PR: https://github.com/telerik/kendo-themes/pull/3142
