### ISSUE TITLE
Revise "Notes on Performance" section and replace Fibers method in the themes

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#2452]
According to the the latest update: 
_Fibers is not compatible with nodejs **v16.0.0** or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial._

https://github.com/laverdet/node-fibers/commit/8f2809869cc92c28c92880c4a38317ae3dbe654d

The following documentation section should be revised:
https://www.telerik.com/kendo-angular-ui/components/styling/custom-themes/#toc-notes-on-performance

as well as the implementation in the themes.

Reported in private ticket 1516771.

**Comment by Juveniel** [comment]
The Fibers package is removed from the themes with https://github.com/telerik/kendo-themes/pull/1713 and is no longer a dependency. 

As for the article in the Angular docs - we can remove the referred section. Also, the swatches section needs an overhaul, thus I suggest to log a new issue in the Angular repo to revise the entire article. 

//cc @PaskalevStoyan
