### ISSUE TITLE
Scheduler selection is not applied to non-work-hours slots

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-themes#247]
* Bug report 

## Current behavior
Non working hour slots are not highlighted when selected.

## Expected behavior
Non working hour slots to be highlighted when selected.

## Minimal reproduction of the problem with instructions
https://demos.telerik.com/kendo-ui/scheduler/events - Try to select any of a grayed out slots.

For example in the following screenshot the selected range is 7:00 to 9:00, but only 8:00-9:00 is highlighted.
 
![image](https://user-images.githubusercontent.com/568765/43578622-fb69bb7a-9657-11e8-95bc-7c17f915fad6.png)

**Comment by gyoshev** [comment]
Closed in development builds with e69ac94
