### ISSUE TITLE
The cursor changes when hovering the ComboBox

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#249]
## I'm submitting a...
* Bug report 

## Current behavior
The cursor changes when hovering over the border of a ComboBox.

## Minimal reproduction of the problem with instructions
[https://plnkr.co/edit/5kj9W96yYGlA1WwlyFSc?p=preview](https://plnkr.co/edit/5kj9W96yYGlA1WwlyFSc?p=preview)
## Environment
Product:
* Kendo Ui for Angular

**Comment by TeyaVes** [comment]
no longer reproducible
