### ISSUE TITLE
Scheduler TimelineView does not render as expected when there are 1-min slots and the numberOfDays is higher than 1

### ISSUE THREAD

**Issue by kkapitanova** [telerik/kendo-themes#2497]
The TimelineView does not render as expected when the numberOfDays props is higher than 1 and there are 1-minute slots, achieved in either of the following ways, for example:
- slotDuration={1} and slotDivisions={1}
- slotDuration={60} and slotDivisions={60}

This can be seen in the following example: https://stackblitz.com/edit/react-fxpxer-y5c9mj?file=index.html 

The timeline is rendered correctly when the following CSS is included (uncomment this in the example above to see it in action):
.k-scheduler-layout-flex .k-scheduler-cell {
      flex: 1 1 auto;
 }

**Comment by silviyaboteva** [comment]
As `.k-scheduler-layout-flex .k-scheduler-cell` has `flex: 1 1 100%` rule already applied, consider changing that to `flex: 1 1 auto` or use `flex-basis: auto`.
