### ISSUE TITLE
Add a utility class for visually hidden but focusable elements

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#2501]
**Is your feature request related to a problem? Please describe.**
In terms of Accessibility, we quite often need an element that's visually hidden but at the same time focusable.
That's why it might be a good idea to implement such utility class which will bring some more consistency in the rendering.

The `.visuallyhidden` class on [this page](https://fuzzbomb.github.io/accessibility-demos/visually-hidden-focus-test.html) is a good example of the concept.

**Comment by joneff** [comment]
`.k-visually-hidden` should be a good enough name. ping me before you start

**Comment by JoomFX** [comment]
There is such class already - [`.k-sr-only`](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_aria.scss)
