### ISSUE TITLE
Utils are not imported in ExpansionPanel Bootstrap individual theme SCSS

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-themes#2502]
**Describe the bug**
We offer two ways to include the SCSS for our components. All the styles from one file (all.scss) or importing separate SCSS for each component in use (to avoid importign unnecessary SCSS). If the ExpansionPanel SCSS is imported individually, [it does not include the `utils` `_display` styles](https://github.com/telerik/kendo-themes/blob/253dc7444ea432727aa85fec6d270e148b1b145b/packages/bootstrap/scss/expansion-panel/_index.scss#L4) and therefore the class `.k-display-none` does not hide the collapsed ExpansionPanel in Angular (not certain about other suites).

**To reproduce**
Please refer to [support ticket `1520323`](https://supportheroes.telerik.com/ticket/1520323)

**Expected behavior**
The following SCSS import to include the styles for `.k-display-none` and to not require manual import of the `utils` styles:
`@import "~@progress/kendo-theme-bootstrap/scss/expansion-panel/index";`

**Screenshots**
https://user-images.githubusercontent.com/45083324/119517216-19212c00-bd80-11eb-8488-c501276179c8.mp4

**Affected package (please remove the unneeded items)**
* Bootstrap definitely. Not sure for the rest.

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular definitely. Not sure about the rest.

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by JoomFX** [comment]
The [Spacer utils](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_spacer.scss) are also missing.
They should be imported as well.

**Comment by joneff** [comment]
@gkarapeev you should use `.k-hidden`, not `k-display-none`
