### ISSUE TITLE
[Grid] Spacer util not imported

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#2503]
**Describe the bug**
The [Spacer util](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_spacer.scss) is not imported in the Grid module, therefore the [GridSpacerComponent](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridSpacerComponent/) does not work when only the Grid SCSS is imported as described [here](https://www.telerik.com/kendo-angular-ui/components/styling/#toc-compiling-the-theme-from-scss-source-files).
For reference - support ticket 1521229.

**Expected behavior**
The Spacer util should be imported as a dependency so the GridSpacerComponent can work properly.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
as a gentle reminder, if something is a bug, assign the bug hunt project
