### ISSUE TITLE
Blue Gray not applied in themebuilder

### ISSUE THREAD

**Issue by dtopuzov** [telerik/kendo-themes#2510]
**Describe the bug**
Blue Gray not applied in theme builder app.

**To reproduce**

1. Start https://themebuilder.telerik.com/
1. Select Blazor -> Material -> Smoke swatch
1. The primary color `Blue Gray` is not applied in the preview

**Expected behavior**
All colors from the `Smoke` swatch to be applied properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6651651/119815367-1f381980-bef4-11eb-8478-0b09f4fd81bb.png)

**Notes**
Notices this in theme builder, but @Dimitar-Goshev told me that it should be a themes issue.

**Comment by joneff** [comment]
Fixed by #2546. The themebuilder is not yet updated.
