### ISSUE TITLE
Review Grid editing styles

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#2526]
**Describe the bug**
When you click on a Grid cell it switches to Editing mode.
And because of the [different padding](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/grid/_layout.scss#L937) that the cell gets in Editing mode, the content of the whole row kind of "jumps".

**To reproduce**
The issue is reproducible in both Kendo Angular and Kendo jQuery

1. Go to the [Angular Demo](https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-directives/#toc-the-in-cell-directive) or the [jQuery Demo](https://demos.telerik.com/kendo-ui/grid/editing)
1. Click on a cell so it switches to Editing mode
1. Notice how the row height gets changed when switching a cell between editing and non-editing mode

**Expected behavior**
Switching a cell between editing and non-editing mode should be smooth and the row content should not "jump".

A possible solution might be to delete the `.k-grid .k-grid-edit-row td:not(.k-hierarchy-cell)` selector [here.](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/grid/_layout.scss#L937)
The Angular Grid component rendering should also be reviewed because it currently adds the `.k-grid-edit-cell` class in Editing mode while it might need to be changed to `.k-edit-cell` (as it is in the jQuery Grid).

**Screenshots**
N/A

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by JoomFX** [comment]
It seems that simply increasing the [`$grid-command-cell-padding-y`](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/grid/_layout.scss#L937) variable with `1px` (tested with the Default theme only) fixes the "jumping" issue.

**Comment by Pryver** [comment]
Workaround how I made it work inside project I'm working on:

- control grid columns width through additional css class (to prevent undesirable behaviour with width for inputs like k-input(dropdownlist))
- add line-height property for .k-grid td,  f.e.  td height: 26px and td line-height: 8px works together with .k-input height: 24px or .k-textbox set to 26px height
- padding doesn't have to be set to 8px 12px, in my case it is set to 0px 12px and works fine with these styles

`.k-grid td {
  height: 26px;
 }

  .k-input{
    height: 24px;
}
  .k-textbox {
  height: 26px;
}

.k-grid th, .k-grid td  {
  white-space: nowrap;
  line-height: 8px;
  padding: 0px 12px;
}
`
Input type inside cells may have different height, it depends on input type.
Increasing/decreasing td line-height together with height for all elements inside grid prevents cells from "jumping".

**Comment by joneff** [comment]
with #2594 we've introduced edit cell padding variables as well, so that should do the trick.

fixed by #2594.
