### ISSUE TITLE
Stepper indicator text overflow when the text is too long

### ISSUE THREAD

**Issue by KristianMariyanov** [telerik/kendo-themes#2553]
**Describe the bug**
If long text is added to the stepper indicator, the text overflows. Is this expected?

**To reproduce**

1. Define stepper with long text indicator (You can use the code below)
```html
<nav dir="rtl" class="k-stepper k-widget" style="display: grid; grid-template-columns: repeat(6, 1fr)">
                <ol class="k-step-list k-step-list-horizontal" style="grid-column-start: 1; grid-column-end: -1;">
                    <li class="k-step k-step-first k-step-done" style="max-width: 33.333%">
                        <a href="#" class="k-step-link">
                            <span class="k-step-indicator">
                                <span class="k-step-indicator-icon k-icon k-i-check"></span>
                            </span>
                        </a>
                    </li>
                    <li class="k-step k-step-current k-step-focus" style="max-width: 33.333%">
                        <a href="#" class="k-step-link">
                            <span class="k-step-indicator">
                                <span class="k-step-indicator-text">Looooooooooooong text</span>
                            </span>
                        </a>
                    </li>
                    <li class="k-step k-step-last k-step-optional" style="max-width: 33.333%">
                        <a href="#" class="k-step-link">
                            <span class="k-step-indicator">
                                <span class="k-step-indicator-text">3</span>
                            </span>
                            <span class="k-step-label">
                                <span class="k-step-label-optional">(Optional)</span>
                            </span>
                        </a>
                    </li>
                </ol>
                <div class="k-widget k-progressbar k-progressbar-horizontal" style="grid-column-start: 2; grid-column-end: 6;">
                    <span class="k-progress-status-wrap k-progress-end"></span>
                    <div class="k-state-selected" style="height: 100%; width: 50%;">
                        <span class="k-progress-status-wrap k-progress-end" style="height: 100%; width: 200%;"></span>
                    </div>
                </div>
            </nav>
```
The resulted output looks like this:

![image](https://user-images.githubusercontent.com/6886919/122362456-cf7fc780-cf60-11eb-84f3-50043ce527d7.png)

**Expected behavior**
Prevent the indicator text from overflowing outside the stepper

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* 
**Build system information (please remove the unneeded items)**
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Comment by silviyaboteva** [comment]
Hi @KristianMariyanov,
What is the use-case of implementing a long text inside the indicator itself? It, as the name tells, is for indication purposes only (number of the step or an icon). I'm not sure that the Stepper should be used if you have 99+ steps.
In this case, labels only mode could be set.

**Comment by KristianMariyanov** [comment]
Hello @silviyaboteva 

In Blazor (I believe in React too) we are providing an option for the users to change the indicator text. Apparently, they could add a longer indicator text which could lead to the described in the issue behaviour.

I'm not sure if this is a valid case, but adding the number with words (One, two, three...) or any other custom word that describe the step could potentially break it.

In case the indicator is designed to put only numbers and icons in it. Feel free to close this issue as invalid. We can work with that.

**Comment by silviyaboteva** [comment]
The indicator is designed to contain just an indication of the step (either a number or an icon). All of the descriptive information goes inside the label.

cc/ @tyanko
