### ISSUE TITLE
When stepper doesn't have set width, it flickers when changing steps

### ISSUE THREAD

**Issue by KristianMariyanov** [telerik/kendo-themes#2558]
**Describe the bug**
The stepper bold the step label when the step is selected. This could lead to flickering in the whole stepper. Is this could be avoided?

**To reproduce**

1. Define a stepper without width
1. The width of the stepper depends on its content
1. Change selected steps and see how the stepper is flickering

**Expected behavior**
Stepper doesn't flicker.

**Screenshots**
https://www.screencast.com/t/woke50WpweDE

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: Windows

**Comment by joneff** [comment]
That is expected, due to text changed font weight from normal to bold. the same will happen with any type of content, unless the font-family is monospace..

This will not be worked on.
