### ISSUE TITLE
Grid headers lagging behind when using cell template with svg icons

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-themes#2570]
**Describe the bug**
The Grid header is lagging behind when scrolling cells with many svg icons
**To reproduce**
1. Go to https://stackblitz.com/edit/angular-jkdnie-qius2o?file=app%2Fapp.component.ts or https://stackblitz.com/edit/angular-jkdnie-od1uwu?file=app%2Fapp.component.ts
2. Click the use SVG Icon or use SVG Font icon radio button and scroll horizontally

In addition, we also isolated the problem removing angular out of the picture and using JS.
With our theme, the problem can be observed:
https://stackblitz.com/edit/typescript-brla3w?file=index.ts
Without our theme seems to work fine:
https://stackblitz.com/edit/typescript-qemfeq?file=index.ts
Example without themes with added background-color(doesn't seem to affect the headers much):
https://stackblitz.com/edit/typescript-tj1f4s?file=style.css

**Expected behavior**
Smooth scrolling without the header lagging behind.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Chrome version: [91 latest]

**Additional context**
As a workaround setting the .k-grid .k-grid-content {background-color: inherit; } , unset or transparent fixes the issue.
Older versions of Chrome or the latest Firefox don't seem to be affected by this issue.

**Comment by inikolova** [comment]
It appears the problem has been already addressed, therefore I am closing this issue

cc @yanmariomenev
