### ISSUE TITLE
Scheduler more events button is not completely visible

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-themes#2572]
**Describe the bug**
Scheduler `more events` button is only partially visible.

**To reproduce**
Use any demo where more than 2 appointments are available for any time slot, for example: 
https://winslaveblazor.dev.progress.com/blazor-ui/scheduler/overview
NOTE: you may need to navigate between dates to find a proper time slot)

**Expected behavior**
The `more events` button is completely visible

**Screenshots**
![image](https://user-images.githubusercontent.com/5861835/122935207-d2bbee80-d378-11eb-97f7-adbee6e68322.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment]
fixed by db31d3f2c5da75d8a02e16f4824835574af45e14
