### ISSUE TITLE
Column menu icon is visible over sticked columns

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-themes#2576]
**Describe the bug**
In a Grid with sticky columns and column menu enabled, the column menu's icon remains visible over sticked columns on horizontal scroll.

**To reproduce**

1. Go to https://www.telerik.com/kendo-angular-ui/components/grid/columns/menu/#toc-stick-item
2. Start scrolling the example horizontally

**Expected behavior**
When a column is hidden, the column menu icon should not be visible as well.

**Screenshots**

https://user-images.githubusercontent.com/18744873/123785594-6180bc00-d8e1-11eb-900d-fc6983da53e1.mov

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* All

**Comment by silviyaboteva** [comment]
Can you please check if this is a rendering problem? As in the KendoReact, the icon displays ok while scrolling: https://stackblitz.com/edit/react-bdkmco?file=app/main.tsx
