### ISSUE TITLE
z-index of .k-card-header and .k-appbar-fixed / .k-appbar-sticky clash

### ISSUE THREAD

**Issue by jrdutton** [telerik/kendo-themes#2589]
Within the SCSS of the kendo-theme-default, the z-index of the Card header and the fixed/sticky App Bar are both set to 1. This means that the Card header text bleeds through.

![image](https://user-images.githubusercontent.com/3248773/124559091-380ce680-de33-11eb-8479-608b6da6521f.png)

When scrolled:

![image](https://user-images.githubusercontent.com/3248773/124559202-5e328680-de33-11eb-8201-8a321a6c9bf8.png)

If the z-index of the sticky app bar is changed to 10.

![image](https://user-images.githubusercontent.com/3248773/124559479-ac478a00-de33-11eb-8a9a-15fd786ca3b8.png)

**Comment by joneff** [comment]
@jrdutton I exposed a variable that allows setting the z-index of appbar component. Still the bigger issue remains that we need to have a stacking hierarchy of components and variables to control those indices. That way by default things should work and if need be, the stacking can be customized to fit the needs of the application.
