### ISSUE TITLE
Double bottom border on the popup of a filter menu

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#262]
## I'm submitting a...
* Bug report 

## Current behavior
When using the material theme, there are two borders on the bottom of the popup of a filter menu.

## Minimal reproduction of the problem with instructions
![2018-08-20_1332](https://user-images.githubusercontent.com/20015190/44335567-8c820a80-a47d-11e8-80e9-e19355035782.png)

[https://stackblitz.com/edit/angular-hwk6qs-rcws1k?file=index.html](https://stackblitz.com/edit/angular-hwk6qs-rcws1k?file=index.htmll)

## Environment
Product:
* Kendo Ui for Angular

**Comment by TeyaVes** [comment]
no longer reproducible
