### ISSUE TITLE
Month view of Scheduler component has no background color for the dates in the current month.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#2625]
In the previous version of SASS themes, all dates in Month view had grey background color.

Current issue:
Only the dates from the previous month have a background set.
![scheduler](https://user-images.githubusercontent.com/3844466/126167750-6698915b-dc64-4f6b-9dc7-e5f929f0c8cf.PNG)

**Comment by joneff** [comment]
This is the correct behaviour. I added a test in #2703 so we can monitor if something changes.
