### ISSUE TITLE
PivitGrid Toolbar has no background color.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#2626]
In the previous versions of SASS themes, PivitGrid Toolbar has a background color.

Previous:
![pivot2](https://user-images.githubusercontent.com/3844466/126172587-d36d077c-8e30-4c71-8b24-fa021dcbcdc1.PNG)

Actual:
![pivot1](https://user-images.githubusercontent.com/3844466/126172603-b3cfb567-5ef8-442e-9123-cc4b932b5993.PNG)

**Comment by joneff** [comment]
Changed buttons to chips shipped with v5
