### ISSUE TITLE
Buttons in PivotGrid Toolbar shouldn't be glued to each other and to the toolbar's borders.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#2627]
Expected:
![pivot2](https://user-images.githubusercontent.com/3844466/126174540-d159df37-0dfb-4a4a-95f2-23eaa6ff3f83.PNG)

Actual:
Currently, there is no any distance between the buttons and also, between the buttons and Toolbar's borders.
![pivot1](https://user-images.githubusercontent.com/3844466/126174519-da24caf5-1fb3-4088-87a4-7d16f7f4c2d4.PNG)

**Comment by joneff** [comment]
changed button with chips. shipped with v5
