### ISSUE TITLE
Updating the primary color does not update the Pager color.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#2632]
**Describe the bug**

Updating the primary color does not update the Pager color.

**To reproduce**

Open the theme builder and change the primary color:

![image](https://user-images.githubusercontent.com/11087921/126290118-31221c46-cc38-4e62-8713-8af2f33f9b13.png)

Changing the link text color is not respected as well.

**Expected behavior**

Changing the primary color of the theme should update the color of the Pager numbers + the background of a selected item as the UI kit for Figma does.

**Affected package (please remove the unneeded items)**

* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**

* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**

Please test again when the support for Bootstrap 5 is released.

**Comment by joneff** [comment]
That was due to the fact pager variables relied on bootstrap variables.

This particular issue is actually fixed by ae064e894ec2ba5733ce6acd7b1e0f96b533f015 but the fix is not yet deployed to themebuilder.
