### ISSUE TITLE
Form Controls Improvements 

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#264]
Some of form controls like date input, date picker and time picker, datetime picker, maskedtextbox, numeric textbox, autocomplete and multiselect do not apply double bottom border on focus:

**Implemented:** 
<img width="444" alt="screen shot 2018-08-22 at 1 34 59 pm" src="https://user-images.githubusercontent.com/16577622/44458900-4dd08980-a610-11e8-8a79-a78b287cbaa6.png">

**By design:** 
![1](https://user-images.githubusercontent.com/16577622/44458917-6771d100-a610-11e8-9935-027c8411b08a.png)

**Comment by joneff** [comment]
That particular bit is related kendo-jquery functionality, as shown in this example: https://dojo.telerik.com/@joneff/IWIGUbeV

The styles are already there, we just need a couple of extra things to make it work: one is the wrapper that adds the extra border, when needed; the other is the handling of the input events.

**Comment by joneff** [comment]
Resolved by #3603 when input ripple was merged with the input component.
