### ISSUE TITLE
The hover style is missing for year, decade and century views of Calendar

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#2671]
1. Navigate to: http://kendobuild-windows.dev.progress.com/kendo-ui/calendar/index
2. Open year, a decade, or century navigation from Calendar's fast navigation button
3. Hover over the items in the navigation menu

Result:
The hover styles are missing

**Comment by joneff** [comment]
The issue is in the rendering. I will provide a fix.
