### ISSUE TITLE
CompileError: Begins at CSS selector undefined

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#2713]
**Describe the bug**
When compiling the theme an error occurs:
```
./node_modules/@progress/kendo-theme-default/dist/all.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@progress/kendo-theme-default/dist/all.css)
ParserError: Syntax Error at line: 1, column 40
```
**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by chriscrowley** [comment]
What do you mean by?
>please remove the unneeded items

Removing @progress/kendo-theme-bootstrap and @progress/kendo-theme-default prevents the styles from working.

**Comment by joneff** [comment]
We start with issue template with some instructions. It does happen that we forget to remove the instructions before posting the issue. See https://github.com/telerik/kendo-themes/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md
