### ISSUE TITLE
[BUG][theme-material]  Tooltips are rendered with extra space

### ISSUE THREAD

**Issue by samuelcolburn** [telerik/kendo-themes#2718]
**Describe the bug**
Tooltips in the Material UI theme have space between the animation container and the tooltip. Because the box-shadow is applied to the animation container, there is a gap between the box shadow and the tooltip.

**To reproduce**

1. Go to https://www.telerik.com/kendo-react-ui/components/tooltip/controlled-mode/
2. Make sure the demo is on "Material Theme"
1. Click either of the "Show Tooltip buttons"
1. See space between tooltip and box-shadow.

**Expected behavior**
There should be no extra space, they should line up.

**Screenshots**
Screenshot:
![image](https://user-images.githubusercontent.com/9741902/129818642-2177f6b6-2739-4296-a6a7-6b58fae80991.png)

**Affected package**
* theme-material

**Affected suites (only tested React)**
* Kendo UI for React

**Affected browsers (that I tested)**
* Firefox: Version: 92.0b4 (64-bit)
* Chrome version: 92.0.4515.159 (Official Build) (64-bit)
* Edge version: 92.0.902.73 (Official build) (64-bit)

**Build system information**
* OS: Windows 10 Pro x64, version Build 19043

**Additional context**
This seems to be fixed by changing `.k-tooltip` from `display: inline-flex` to `display: flex`. However, I only looked at the most simple use case.

**Comment by joneff** [comment]
Good one!

Indeed, for some reason having the tooltip be inline just doesn't size it correctly... We'll fix it promptly.
