### ISSUE TITLE
Customizations do not work for popups in Dropdowns Module/Material Theme

### ISSUE THREAD

**Issue by dashkan** [telerik/kendo-themes#272]
## I'm submitting a...

* Bug report

## Current behavior
The dropdown module popup does not respect color customizations when using the material theme. It always uses the default material accent theme (pink).

## Expected behavior
Use customized colors.
[Styling Overview](https://www.telerik.com/kendo-angular-ui/components/styling/)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gdruch

## What is the motivation or use case for changing the behavior?
N/A

## Environment
Product:
* Kendo Ui for Angular

Package versions:

```
├── @angular-devkit/build-angular@0.7.5
├── @angular/animations@6.1.4
├── @angular/cdk@6.4.6
├── @angular/cli@6.1.5
├── @angular/common@6.1.4
├── @angular/compiler@6.1.4
├── @angular/compiler-cli@6.1.4
├── @angular/core@6.1.4
├── @angular/forms@6.1.4
├── @angular/http@6.1.4
├── @angular/language-service@6.1.4
├── @angular/material@6.4.6
├── @angular/platform-browser@6.1.4
├── @angular/platform-browser-dynamic@6.1.4
├── @angular/router@6.1.4
├── @progress/kendo-angular-buttons@4.1.3
├── @progress/kendo-angular-dropdowns@3.0.3
├── @progress/kendo-angular-inputs@3.2.1
├── @progress/kendo-angular-intl@1.5.0
├── @progress/kendo-angular-l10n@1.2.0
├── @progress/kendo-theme-material@1.2.1
├── @types/jasmine@2.8.8
├── @types/jasminewd2@2.0.3
├── @types/node@8.9.5
├── codelyzer@4.2.1
├── core-js@2.5.7
├── jasmine-core@2.99.1
├── jasmine-spec-reporter@4.2.1
├── karma@1.7.1
├── karma-chrome-launcher@2.2.0
├── karma-coverage-istanbul-reporter@2.0.2
├── karma-jasmine@1.1.2
├── karma-jasmine-html-reporter@0.2.2
├── protractor@5.4.0
├── rxjs@6.2.2
├── rxjs-compat@6.2.2
├── ts-node@5.0.1
├── tslint@5.9.1
├── typescript@2.7.2
└── zone.js@0.8.26
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 2.9.2
- Node version: 10.9
- Platform:  Mac

**Comment by IT-CASADO** [comment]
The same thing appears on bootstrap theme.
DropDowns uses the .k-multiselect-wrap class which is using styles from a button (secondary).

With that the bootstrap and kendo themes are out of sync.

**Comment by inikolova** [comment]
I tested the themes customisation using the latest versions of Kendo UI Material and Bootstrap and everything is working as expected. Therefore I am closing this issue.
