### ISSUE TITLE
Sass compilation fails with version 4.41.0.

### ISSUE THREAD

**Issue by kosimas** [telerik/kendo-themes#2721]
I follwed the instruction on this page https://www.telerik.com/kendo-react-ui/components/styling/customizing/#toc-using-the-build-process-of-the-application
This worked with versions prior to 4.41.0.
I created a file named custom.theme.scss with the following content:
```scss
$primary: #1C3359;

@import "~@progress/kendo-theme-default/dist/all.scss";
```
This file will throw following error:
```
$ npm run build

> client@0.1.0 build
> react-app-rewired build

The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)

Creating an optimized production build...
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($padding-x, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
955 │ $padding-x-sm: $padding-x / 2 !default;
    │                ^^^^^^^^^^^^^^
    ╵
    node_modules\@progress\kendo-theme-default\dist\all.scss 955:16  @import
    src\custom.theme.scss 3:9                                        root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
956 │ $padding-y-sm: $padding-y / 2 !default;
    │                ^^^^^^^^^^^^^^
    ╵
    node_modules\@progress\kendo-theme-default\dist\all.scss 956:16  @import
    src\custom.theme.scss 3:9                                        root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($border-radius, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
962 │ $border-radius-sm: $border-radius / 2 !default;
    │                    ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules\@progress\kendo-theme-default\dist\all.scss 962:20  @import
    src\custom.theme.scss 3:9                                        root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20, 14)

More info and automated migrator: https://sass-lang.com/d/slash-div

     ╷
1187 │ $line-height: ( 20 / 14 ) !default;
     │                 ^^^^^^^
     ╵
    node_modules\@progress\kendo-theme-default\dist\all.scss 1187:17  @import
    src\custom.theme.scss 3:9                                         root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($drop-hint-arrow-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

     ╷
1195 │ $drop-hint-arrow-spacing: ($drop-hint-arrow-size / 2) !default;
     │                            ^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
    node_modules\@progress\kendo-theme-default\dist\all.scss 1195:28  @import
    src\custom.theme.scss 3:9                                         root stylesheet

WARNING: 129 repetitive deprecation warnings omitted.

Failed to compile.

./src/custom.theme.scss
ParserError: Syntax Error at line: 1, column 40
```
With @progress/kendo-theme-default: 4.40.1 everything works as expected.
**Used packages**
"@progress/kendo-theme-default": "^4.41.0"
"sass": "1.36.0"
"react": "^17.0.2"
"react-dom": "^17.0.2"
"react-router-dom": "^5.2.0"
"react-scripts": "^4.0.3"
"typescript": "^4.3.5"

**Comment by gkalpak** [comment]
We also run into issues upgrading from v4.40.1 to v4.41.0 on angular/ngcc-validation#4138 ([example CI failure][1]).
Debugging locally, the error seems to be that PostCSS cannot correctly parse [dist/all.css][2] due to the following invalid CSS:

```css
calc(var(--kendo-scrollbar-width, 17px + 1px) - 1px)
```

There seem to be several occurrences of this. For example, one of them comes from [packages/default/scss/pivotgrid/_layout.scss][3].


[1]: https://circleci.com/gh/angular/ngcc-validation/56039
[2]: https://unpkg.com/browse/@progress/kendo-theme-default@4.41.0/dist/all.css
[3]: https://github.com/telerik/kendo-themes/blob/b2129d45c57d7821ea3a6fab491bbf86799f6170/packages/default/scss/pivotgrid/_layout.scss#L71

**Comment by billdwhite** [comment]
I think I'm getting a related error since updating to 4.41.0:

`⠙ Generating browser application bundles (phase: building)...Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but postcss-preset-env uses 7.0.36. Perhaps this is the source of the error below.
`

and

`ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ParserError: Syntax Error at line: 1, column 40
    at <mypath>/node_modules/@progress/kendo-theme-default/dist/all.css:25758:5
    at Parser.error (<mypath>/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (<mypath>/node_modules/postcss-values-parser/lib/parser.js:183:18)
    at Parser.parseTokens (<mypath>/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (<mypath>/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (<mypath>/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (<mypath>/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at <mypath>/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at <mypath>/node_modules/postcss/lib/container.js:72:18
    at <mypath>/node_modules/postcss/lib/container.js:55:18
    at Rule.each (<mypath>/node_modules/postcss/lib/container.js:41:16)
    at processResult (<mypath>/node_modules/webpack/lib/NormalModule.js:713:19)
    at <mypath>/node_modules/webpack/lib/NormalModule.js:819:5
    at <mypath>/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at <mypath>/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (<mypath>/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (<mypath>/node_modules/postcss-loader/dist/index.js:142:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by silviyaboteva** [comment]
This is a duplicate issue. Link to the initial one: https://github.com/telerik/kendo-themes/issues/2713
