### ISSUE TITLE
Font sizes have increased dramatically

### ISSUE THREAD

**Issue by jrdutton** [telerik/kendo-themes#2760]
Since https://github.com/telerik/kendo-themes/pull/2725 our k-h2 font size has increased from 18 pixels to 34 pixels. Is this working as expected?

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by silviyaboteva** [comment]
For R3 2021 we have developed the typography for our own design system. The design team defined the sizes and used culturally relevant, historically pleasing ratios that are easily scalable and with accessibility in mind.

With that said, these are the styles for the typography of the Default Theme from now on. However, using the [SCSS variables customization approach](https://www.telerik.com/kendo-angular-ui/components/styling/custom-themes/#toc-using-the-build-process-of-the-application), you can easily change the default values with your own.

The variables are listed here: https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/typography/_variables.scss#L45
