### ISSUE TITLE
bug(material): outline button non-visible with `primary` and `selected`

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-themes#2762]
The `material` outline button is not visible (same text-color as background-color) when the following properties are set to true:
- primary &mdash; `k-primary`
- selected &mdash; `k-state-selected`

Can be observed in the following demo:
https://stackblitz.com/edit/react-qmxwh7?file=app/main.tsx

**Affected package**
* theme-material

**Affected suites**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers**
* All

**Comment by elena-gancheva** [comment]
cc @telerik/unite-ux
