### ISSUE TITLE
bug: Outline button not visible with some swatches

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-themes#2763]
The `outline` button is not initially visible due to it's `button-text` color being set to `white` in the following swatches:
- default-urban
- bootstrap-urban

https://stackblitz.com/edit/react-hfw7wr?file=app/main.tsx

**Affected package**
* theme-default
* theme-bootstrap

**Affected suites**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers**
* All

**Comment by silviyaboteva** [comment]
Part of https://github.com/telerik/kendo-themes/issues/1983

**Comment by silviyaboteva** [comment]
No longer reproducible in `v5.0.1`:
https://stackblitz.com/edit/react-oo2he4?file=index.html - Default Urban Swatch
https://stackblitz.com/edit/react-8rh1kv?file=index.html - Bootstrap Urban Swatch
