### ISSUE TITLE
Mismatch between time headers and timeslots in Scheduler Week and Timeline views

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#2764]
**Describe the regression**
Mismatch between time headers and timeslots in Scheduler Timeline view
Regression since v 4.**41**.1 . The scenario is OK with 4.40.1

**To reproduce**

1. Run https://dojo.telerik.com/@Dimitar-Goshev/INUQiZuG

**Expected behavior**
Time headers and time slots size is identical and there is no mismatch on scrolling horizontally
![image](https://user-images.githubusercontent.com/6614183/132372228-08563aa8-a944-4c0a-aeae-a5da48077a5d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6614183/132371765-8e66595b-d4bf-49f8-9c1d-eec439886769.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by Frank-DKD** [comment]
Same deal here on Kendo UI for Vue. Even all the demos on the kendo site have the issue, so plenty of examples there. Reverting to `@progress/kendo-theme-material@4.41.0` worked for me atleast.

**Comment by nelito987** [comment]
Reported in ticket ID: 1549813

**Comment by CecoMilchev** [comment]
Reported in ticket ID: 1550515

**Comment by IvanDanchev** [comment]
In MVC, in addition to the Timeline views, misalignment between the time headers and the timeslots in can be observed in the Week and WorkWeek view (R3 2021 and newer). Reported in thread ID: 1551367

**Comment by Dimitar-Goshev** [comment]
In Week and WorkWeek views the issue was reproducible in Scheduler with no `height` set.
The issue will be fixed in R1 2022 SP1 of Kendo UI for jQuery.

**Comment by yanisslav** [comment]
The issue is still reproducible. In the following demo with the Bootstrap theme, when the Timeline view is selected:
https://demos.telerik.com/blazor-ui/scheduler/overview
![image](https://user-images.githubusercontent.com/93312843/214568962-ce1d3663-d049-4753-b277-4a75e668110e.png)
