### ISSUE TITLE
Customize default theme scss not loaded 

### ISSUE THREAD

**Issue by exiadbq** [telerik/kendo-themes#2772]
**Describe the bug**
using vite to load scss file from  "@progress/kendo-theme-default": "^4.41.1",
```
//App.scss
$primary: #0271e0;

@import '@progress/kendo-theme-default/dist/all.scss';
```
however it throws 

```
9:30:47 AM [vite] Internal server error: expected ")".
      ╷
31860 │             background-image: url(../node_modules/@progress/kendo-theme-default/dist/map-get($data-uris, $spreadsheet-insert-image-dialog-preview-img));
      │                                   ^
      ╵
  node_modules/@progress/kendo-theme-default/dist/all.scss 31860:35  @import
  src/App.scss 3:9                                                   root stylesheet
  Plugin: vite:css
  File: /home/ec2-user/gs/cmp-srmp-web/node_modules/@progress/kendo-theme-default/dist/all.scss
  Error: expected ")".
        ╷
  31860 │             background-image: url(../node_modules/@progress/kendo-theme-default/dist/map-get($data-uris, $spreadsheet-insert-image-dialog-preview-img));
        │                                   ^
        ╵
    node_modules/@progress/kendo-theme-default/dist/all.scss 31860:35  @import
    src/App.scss 3:9                                                   root stylesheet
```
Remove the line `background-image: url(../node_modules/@progress/kendo-theme-default/dist/map-get($data-uris, $spreadsheet-insert-image-dialog-preview-img));`
can make it work 
**To reproduce**

1. Click '...'
1. Scroll down to '...'
1. See error '...'

**Expected behavior**
Load without error

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**

* Kendo UI for React

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**

* OS: Linux
* Node version: v14.16.1
* NPM version: 7.14.0

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
I tested with a new Create React App demo and didn't experience the issue. The output in the `dist/all.scss` is the following valid scss:
```
background-image: url(map-get($data-uris, $spreadsheet-insert-image-dialog-preview-img)); 
```

Are there any plugins that touch the URLs in your setup? For example https://github.com/postcss/postcss-url.

**Comment by exiadbq** [comment]
Thanks for looking into it, I used [create vite app](https://github.com/vitejs/vite/tree/main/packages/create-app) with react and ts. And the built in scss support from it. No postcss used.

The dist/default-blue.scss works fine, but not all, since I want to customize the theme, then it becomes a problem.

**Comment by exiadbq** [comment]
Found a walk around, basically load
```
// App.tsx
import type { ReactElement } from 'react';
import '@progress/kendo-theme-default/dist/all.scss';
```
But also have the following, so the variable customization can be loaded correctly. 
```
//vite.config.ts
export default defineConfig({
...
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@import "./src/variables";',
      },
    },
  },
});
```
https://github.com/vitejs/vite/issues/832#issuecomment-866889636

**Comment by silviyaboteva** [comment]
In our docs, we've documented the process for customizing the themes via [Create React App](https://reactjs.org/docs/create-a-new-react-app.html).

However, scaffolding a new project with Vite, indeed, comes with it's specifics. In this case the loading the variables through the config file. I'm attaching a runnable demo app for those of you who want to check it out: [vite-project.zip](https://github.com/telerik/kendo-themes/files/7155162/vite-project.zip)

I'm closing this issue :)
