### ISSUE TITLE
Inconsistent behavior when shrinking columns with FilterMenu

### ISSUE THREAD

**Issue by radkostanev** [telerik/kendo-themes#2831]
**Describe the bug**
There is an inconsistent behavior when resizing the columns of a grid and filter menu is enabled. If the column is sortable, the filter menu icon goes over and essentially hides the text. If the column is not sortable, the filter menu icon goes under the text.

**To reproduce**

1. Go to https://stackblitz.com/edit/angular-beytp5-mdsmtt?file=app/app.component.ts
1. Resize the second and third column to about 50px, or to the point where the first letter can't fit within the header.
1. The result should look like this(note the text is hidden beneath the second filter icon):
![image](https://user-images.githubusercontent.com/49035696/135433355-0b791a9d-e1f2-445f-82df-e0e56dd68f85.png)

**Expected behavior**
Consistent behavior when shrinking down columns.

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
If the rendering is correct, this should not happen.
