### ISSUE TITLE
Bootstrap 5: Inset box-shadow for Input/Select

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-themes#2899]
**Describe the bug**
It appears that Bootstrap 5 now puts inset box-shadows for controls like `type="text"` or `<select />`. Kendo does not appear to do the same.

**Expected behavior**
I'm trying to get Kendo to be OH SO close to Bootstrap.  This is like the last thing I've found. 

**Y'all have done a GREAT job so far!!**

**Screenshots**
![image](https://user-images.githubusercontent.com/7206282/137814806-6693d152-8ec7-4c7b-8634-de8b910fb532.png)
![image](https://user-images.githubusercontent.com/7206282/137815038-8edd9e82-e96b-4684-8853-fed284475290.png)
![image](https://user-images.githubusercontent.com/7206282/137815097-c907ef6b-4a8b-4182-b521-e2864e50f527.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by silviyaboteva** [comment]
Hi @DaleyKD,
I do not see box-shadow applied neither in the form control nor form select components:
  - https://getbootstrap.com/docs/5.0/forms/form-control/
  - https://getbootstrap.com/docs/5.0/forms/select/

**Comment by DaleyKD** [comment]
Thanks @silviyaboteva .  I confirmed what you said, so now I have to figure out why my SCSS is picking this variable up when it never did before.

**Comment by silviyaboteva** [comment]
So, in this case, I'll close the issue. However, you can re-open if needed. :)
