### ISSUE TITLE
Inconsistent behavior of the labels in Grid PopUp Edit Form in 2.26 and 2.27 of Telerik UI for Blazor

### ISSUE THREAD

**Issue by ntacheva** [telerik/kendo-themes#2901]
**Describe the bug**
In version 2.27 of Telerik UI for Blazor the following problematic behavior is observed with long labels in the Grid PopUp edit form:

- If no space is included, they are cut from the form
- If space is included, they are misaligned, not matching the alignment of the other ones

![image](https://user-images.githubusercontent.com/73842592/137886233-dee86633-bc06-4618-986b-412d9965de3e.png)

**To reproduce**

1. Go to https://telerik.blazorrepl.com/repl/mbFuvNYt55DDwZo248
1. Run the snippet (test with 2.27)
1. Click 'Edit' on some record to open the PopUp
1. See the long labels behavior

**Expected behavior**
Long labels should not be cut and they should be properly aligned

**Screenshots**
More screenshots to demonstrate the different behavior in 2.26 and 2.27:

**2.26:**
<img width="424" alt="2 26-popup" src="https://user-images.githubusercontent.com/73842592/137886399-4d50120b-7185-4b9e-bd52-8bccd6c3c3ce.png">

**2.27:**
<img width="309" alt="2 27-popup" src="https://user-images.githubusercontent.com/73842592/137886489-78ea0f87-8c85-4435-a695-98d047988d16.png">

**Affected package **
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Telerik UI for Blazor

**Affected browsers**
* All

**Build system information**
* Not Applicable

**Comment by jivanova** [comment]
Not reproducible after changing UI of forms
