### ISSUE TITLE
TabStrip: closeButton cannot be clicked when a tab is selected

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-themes#2922]
In the Material theme when а tab is selected, pressing its closeButton is not possible. The reason for that is the ::after element, which is placed over the tab. Thus, the closeButton cannot be clicked.

**To reproduce**

1. Open this demo https://stackblitz.com/edit/angular-3ivqyd?file=app/app.component.ts
2. Make sure the material theme is enabled
3. Select a tab
4. Click the clearButton
5. ClearButton is not clicked

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* All

**Build system information**
* Not Applicable

**Comment by silviyaboteva** [comment]
@preslavapetrova1 can you double-check this issue as, on my end, the selected tab can be closed as expected?

**Comment by silviyaboteva** [comment]
Working with v5 and latest version of the TabStrip
