### ISSUE TITLE
TabStrip does not have any visual indication when it is focused

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#2928]
**Describe the bug**
TabStrip does not have any visual indication when it is focused. Upon focusing the widget there is no indication that it is focused, nor an indication that its currently active tab is focused. That is a violation of the Accessibility standards.

**To reproduce**
- Run the TabStrip index demo:  https://demos.telerik.com/kendo-ui/tabstrip/index 
- Focus the TabStrip using keyboard
- No visual clue will indicate the TabStrip is focused

**Expected behavior**
There should be a visual indication that the focus is currently on the TabStrip/Tab

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Comment by nedevp** [comment]
@veselints Focus states are now added to the TabStrip:

[Default](https://www.figma.com/file/3fta3SPx6nJMPTUcHTKmNI/Telerik-%26-KENDO-UI-Kit-Default-1.8-(UNPUBLISHED)?node-id=5401%3A201390)
[Material](https://www.figma.com/file/Bun5XXsG0UuzCMz5GyDoHK/Telerik-%26-KENDO-UI-Kit-for-Material-1.8-(UNPUBLISHED)?node-id=3205%3A141649)
[Bootstrap](https://www.figma.com/file/YjhpzSsYaZI5VOaamsvIku/Telerik-%26-KENDO-UI-Kit-for-Bootstrap-1.8-(UNPUBLISHED)?node-id=3323%3A140429)

**Comment by epetrow** [comment]
The styles are also available in the themes, through the element with class k-item
