### ISSUE TITLE
Component options for Chip

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#2935]
**Dependencies**

**Component options for Chip**

```ts
enum ChipSize { small, medium, large };
enum ChipRounded { small, medium, large, pill };
enum ChipFillMode { solid, flat, outline };
enum ChipThemeColor { base, info, success, warning, error }

class Chip {
   size: (null | ChipSize) = ChipSize.medium;
   rounded: (null | ChipRounded) = ChipRounded.medium;
   fillMode: (null | ChipFillMode) = ChipFillMode.solid;
   themeColor: (null | ChipThemeColor) = ChipThemeColor.base
}
```

**Rendering**
* [x] Rendering

**Chip**
```html
<!-- default rendering -->
<div class="k-chip k-chip-md k-rounded-md k-chip-solid k-chip-solid-base">
    <span class="k-chip-text">Chip Text</span>
</div>

<!-- canonical rendering -->
<div class="
    k-chip
    k-chip-${size}
    k-rounded-${rounded}
    k-chip-${fillMode}
    k-chip-${fillMode}-${themeColor}

    ${disabled && 'k-disabled'}">
        {icon !== '' && <span class="k-chip-icon k-icon k-i-${icon}"></span>}
        {avatar !== '' && <span class="k-chip-avatar k-avatar"></span>}
        <span className="k-chip-content">
            { children.length
                ? children
                : text &&
                <span className="k-chip-label">{text}</span>}
        </span>
        {removable && <span class="k-chip-icon k-icon k-i-${removeIcon}"></span>}
</div>
```

**Documentation**
* [x] Variables

**Comment by kspeyanski** [comment]
Should the default `rounder` configuration of the `Chip` be `pill`?

**Comment by Juveniel** [comment]
The Chip idea originates from MD, and in [the latest version 3](https://m3.material.io/components/chips/overview), the Chip is rounded. In order to conform to these guidelines, as well as the different use cases in our components (e.g MultiSelect tag list, Grid grouping, etc. ) the Chip has a default of `rounded: medium` in v5 version of the themes.

**Comment by kspeyanski** [comment]
> The Chip idea originates from MD, and in [the latest version 3](https://m3.material.io/components/chips/overview), the Chip is rounded. In order to conform to these guidelines, as well as the different use cases in our components (e.g MultiSelect tag list, Grid grouping, etc. ) the Chip has a default of `rounded: medium` in v5 version of the themes.

Understood, thank you for the broad explanation.
