### ISSUE TITLE
Grid column headers do not resize correctly in IE11 (scrollable: false)

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#2945]
**Describe the bug**
Column headers do not resize properly in IE11 when scrollable is set to **false**. Regression introduced in 2021.3.914.

**To reproduce**

1. Go to [https://demos.telerik.com/kendo-ui/grid/selection-export?autoRun=true&theme=bootstrap-main](https://demos.telerik.com/kendo-ui/grid/selection-export?autoRun=true&theme=bootstrap-main)

The column headers are squished to the left side. 

**Expected behavior**
Columns headers must have the same width as the respective columns. 

Workaround: 
```
.k-ie .k-grid-header {
  display: table-header-group;
}
```

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* IE version: 11

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by icnocop** [comment]
I experienced this issue in a hybrid ASP.NET Core and Blazor application after upgrading Telerik UI for Blazor from 2.26.0 to 2.29.0 and Telerik Kendo UI for ASP.NET Core from 2021.2.511 to 2021.3.1109.

I added these to my `Site.css` to fix the issues I found in IE11:
```
/* Begin Grid
   Grid cell columns when binding to remote data are positioned after the last header cell in IE 11
*/
.k-ie .k-grid-header {
    display: table-header-group !important;
}

.k-ie .k-grid-footer {
    display: table-footer-group !important;
}
/* End Grid */

/* Begin Popup Windows
   Relative positioned popup windows outside of active tab's contents within a tabstrip are unclickable in IE 11
*/

.k-tabstrip-content,
.k-tabstrip > .k-content {
    position: static !important;
}
/* End Popup Windows */

/* Begin Tabstrip
   Tabstrip bottom border is displayed on top of popup windows
*/
.k-tabstrip {
    display: unset !important;
}
/* End Tabstrip */
```

Thank you.

**Comment by joneff** [comment]
@icnocop we'll make sure to include the fix in the next version of the themes
