### ISSUE TITLE
Drawer hierarchical items

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-themes#2946]
FrontEnd item related to:
- AHA item https://progresssoftware.aha.io/features/KUING2-293
- Design https://github.com/telerik/kendo-ux-private/issues/292#issuecomment-813433893
- Planning item https://github.com/telerik/web-components-planning/issues/10

The idea is to display items on subsequent levels as nested. Similar implementation is available in the PanelBar component through the `k-level-x` CSS classes.

Planned Release date R3 2022 Iteration 1

**Comment by Xizario** [comment]
Is this a followup to https://github.com/telerik/kendo-themes/pull/2423 ? 
From my understanding you want to move the styles from this demo https://www.telerik.com/kendo-angular-ui/components/layout/drawer/hierarchical-drawer/#toc-using-flat-data to the theme itself. Is this correct?

**Comment by Raisolution** [comment]
> Is this correct?

The demo has only a single CSS class to _fake_ level 2 items. But pretty much yes - we will need `k-level-x` CSS classes for multiple levels nesting as in the PanelBar.

**Comment by Raisolution** [comment]
> Planned Release date R1 2022 Iteration 3

Updated the product increment to R3 2022 Iteration 1.
