### ISSUE TITLE
Kendo colorpicker is broken in release 4.42.0 of kendo-theme-default

### ISSUE THREAD

**Issue by rros** [telerik/kendo-themes#2950]
**Describe the bug**
The Kendo colorpicker is broken with version 4.42.0 of @progress/kendo-theme-default
![afbeelding](https://user-images.githubusercontent.com/279664/140292521-3c44c0cb-de06-4cef-ac09-98c3548b062c.png)

**To reproduce**
```html
<!DOCTYPE html>
<html>
<head>

<!-- broken -->
<link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-default@4.42.0/dist/all.css" />

<!-- works -->
<!--<link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-default@4.41.2/dist/all.css" />-->

<script src="https://kendo.cdn.telerik.com/2021.3.914/js/jquery.min.js"></script>
<script src="http://kendo.cdn.telerik.com/2021.3.914/js/kendo.all.min.js"></script>
</head>
<body>
<input id="picker" />

<script>
    $("#picker").kendoColorPicker({
        value: "#ffffff"
    });
</script>
</body>
</html>
```

**Expected behavior**
![afbeelding](https://user-images.githubusercontent.com/279664/140292943-62957e33-0974-454e-ac13-7a3880801442.png)

**Affected package**
* theme-default

**Affected suites**
* Kendo UI for jQuery

**Comment by Juveniel** [comment]
Hey @rros,

Kendo UI for jQuery is released on a quarterly basis ( + Service Packs following one month after each release), while the Kendo Themes use semantic release. Taking this into consideration, each Kendo UI for jQuery version is compatible with a specific version of the themes that is listed in [the following documentation article](https://docs.telerik.com/kendo-ui/styles-and-layout/sass-version-compatibility).

The change that you have observed in the 4.42.0 version of the themes is related to new functionality in the ColorPicker component that will be available with the upcoming release of  Kendo jQuery( scheduled for the end of this week). Thus, you can upgrade the themes to 4.42.0 after the jQuery release to be able to benefit from the latest themes and component enhancements.

Closing this issue
