### ISSUE TITLE
Error icon's position is wrong

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#2952]
Error icon has wrong position in NumericTextBox and DateInput 

**Screenshots**
![error-indicator](https://user-images.githubusercontent.com/3844466/140487963-5ba9090a-a814-4ef9-b1db-5856d8e7dc84.PNG)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment]
fixed by 6f45cf0e1c4aeeca31cf8607e7f5b16f51dec598
