### ISSUE TITLE
ColorGradient - SVG Contrast Tool Lines

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-themes#2959]
The following properties should be added to the `.k-color-contrast-svg` selector for the SVG contrast tool lines. 

`position: absolute;
  overflow: visible;
  pointer-events: none;
  left: 0px;
  top: 0px;`

![Screenshot 2021-11-12 at 11 44 09](https://user-images.githubusercontent.com/52581229/141446185-f26927bb-9515-465a-b149-62c865b5596e.png)

Without them, it does not work and looks like this:

![Screenshot 2021-11-12 at 11 44 57](https://user-images.githubusercontent.com/52581229/141446305-ace70afc-a0d1-44f3-b09d-31e4171c768e.png)

**Comment by silviyaboteva** [comment]
I think this is not a bug, but an enhancement as currently, the KendoReact implementation have these styles inline and the color contrast looks ok: https://www.telerik.com/kendo-react-ui/components/inputs/colorgradient/color-contrast/

We can just move the inline styles to the themes via class name.

**Comment by JoomFX** [comment]
@silviyaboteva Yes, this is the exact purpose of this issue - to move the styles in the themes so the components do not have them inline :)

Yep, the "bug" tag is not the best one in this case.
