### ISSUE TITLE
Readonly state of DropDownList & DropDownTree class "k-no-click" missing.

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-themes#2966]
**Describe the bug**
Readonly state of DropDownList & DropDownTree class "k-no-click" missing.

**To reproduce**
See [dojo](https://dojo.telerik.com/OboKOlIj)

1. Click 'Run'
2. Check element span class 'k-widget k-dropdown', 'k-no-click' is missing
3. You can refer to  MultiSelect readonly state

**Expected behavior**
Readonly state of DropDownList & DropDownTree class must be 'k-widget k-dropdown k-no-click'.

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Kendo UI for jQuery

**Affected browsers**
* All

**Additional context**
DropDownTree single selection readonly state "k-no-click" missing too.

**Comment by TeyaVes** [comment]
Since this issue is not related to the Kendo themes, but to the rendering of the components, I've moved it to the Kendo jQuery public repository here: https://github.com/telerik/kendo-ui-core/issues/6711

You can subscribe to it and track it's status over there
