### ISSUE TITLE
Editor Material issues

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#302]
## Current behavior
- [x] Wrong dropdown items height:
![image](https://user-images.githubusercontent.com/6614183/45284839-2ae81580-b4ea-11e8-8e3a-aa92c995ea7d.png)

- [x] Selected state color is not applied to Format dropdown item:
![image](https://user-images.githubusercontent.com/6614183/45284839-2ae81580-b4ea-11e8-8e3a-aa92c995ea7d.png)

- [x] Dialog issues:
![image](https://user-images.githubusercontent.com/6614183/45285056-d2654800-b4ea-11e8-8ca8-bb3428d0c0e6.png)
  - Labels' text should be lighter
  - There should be no line above buttons
  - Primary and normal button positions are switched

- [x] Insert image/file dialog issues:
![image](https://user-images.githubusercontent.com/6614183/45285277-7949e400-b4eb-11e8-8b0d-4f25c08c5726.png)
  - Unexpected border around Upload
  - Unexpected bottom border of sort dropdown
  - Missing border of files list

- [x] Table wizard dialog:
  - Wrong color of selected tab - blue instead of pink
  - Text area is not outlined in Accessibility tab
  - Alignment drodown should be shorter (as the Background)
  - Width/ height units dropdowns should be shorter (Table and Cell tabs)

## Minimal reproduction of the problem with instructions
Tested on Kendo jQuery Gantt demos

## Environment
* Kendo Ui for jQuery
* R3 2018

Browser:
- Chrome (desktop) version 69

**Comment by joneff** [comment]
There is one issue remaining regarding how selected state works in material, but that requires change in the editor, not the themes.

shipped with v5
