### ISSUE TITLE
WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by msmolka** [telerik/kendo-themes#3029]
**Describe the bug**
When compiling sass file I have few deprecation warnings

WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($spacer, 2) or calc($spacer / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

**To reproduce**
Compile scss using Dart-SASS

**Comment by silviyaboteva** [comment]
Duplicate of https://github.com/telerik/kendo-themes/issues/2505
