### ISSUE TITLE
Buttons in Grid toolbar and group indicator are misaligned

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-themes#3030]
**Describe the bug**
When the grid is grouped and the toolbar is shown the left padding in the toolbar and in the group header are different.

**To reproduce**

1. Go to https://demos.telerik.com/kendo-ui/grid/index?autoRun=true&theme=bootstrap-main

**Expected behavior**
The buttons in the toolbar and the group indicator should be aligned

**Screenshots**
jQuery/MVC/Core: 

![image](https://user-images.githubusercontent.com/11771009/144872814-552b241f-2c3f-4c2c-82d7-8cc3b60809b5.png)

Angular:

![image](https://user-images.githubusercontent.com/11771009/144873089-67d653c5-c572-498b-8749-f9fda98d29d1.png)

React: 

![image](https://user-images.githubusercontent.com/11771009/144874030-286664f4-1172-482d-aff7-c35c614abc44.png)

Blazor

![image](https://user-images.githubusercontent.com/11771009/144874443-35099548-7903-45c7-a654-5652bffe3ea9.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
Also applicable to Material theme
<img width="1283" alt="Screenshot 2021-12-13 at 8 26 28" src="https://user-images.githubusercontent.com/17604855/145762977-b87d7624-684d-403e-b9bb-b90baf894143.png">
