### ISSUE TITLE
Input issues related to the new styling options

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3050]
- [x]  Rounded is not applied properly(all inputs) - the proper classes are set to the inputs, but the styling is the same in all rounded modes
- [x] Small size should be 24px.
- [x] Focused style of maskedtextbox and dateinput doesn't correspond to the other inputs(there is no shadow)
- [x] Spin buttons of NumericTextBox don't look good in small size(Material,Default and Classic themes)
- [ ]  The text of floating label is not centered in the small size(all inputs)
- [x] Text selection color is always blue. In the previous version, the color corresponds to the theme's base color(all inputs)
- [ ] Placeholder text disappears when click inside the input and floating label is set(textbox/index) - it's valid for all inputs
- [x] Spin buttons of numerictextbox don't look good in Bootstrap and Classic themes:

<details>
<summary>Image</summary>

![numeric](https://user-images.githubusercontent.com/3844466/146397573-2b13cead-5996-4902-8269-20ab010243fd.PNG)

</details>

- [ ] TextArea small size with rounded full text and selection is cut 

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/7159157/146952052-9f06ed62-b01f-4300-a369-9558e94ab239.png)

</details>

**Integration issues**

- [x] Missing shadow:
Shadow is not applied to textbox on focus - BreadCrumb (editmode), Filter, PivotGrid(Filter inputs), FileManager(SearchBox), Pager, Scheduler(textaria in edit mode), SpreadSheet(Data Validation, Insert comment, insert hyperlink, export), Grid(filter input, Searchbox)

- [x] [FileManager] Vertical border appears before search icon when searchbox is focused. 
- [x] [Grid, Treelist TaskBoard] Proper width should be set to SearchBox - currently it is expanded on 100% width of the main container
- [x] [TaskBoard] Search icon is located too close to input's border
- [x] Spreadsheet - Filter Menu(http://kendobuild-windows.dev.progress.com/kendo-ui-next/spreadsheet/sorting-filtering)
- [x] broken Filter by condition input (http://kendobuild-windows.dev.progress.com/kendo-ui-next/spreadsheet/sorting-filtering)
![image](https://user-images.githubusercontent.com/6614183/145858044-12cd1f83-1406-4f22-aad5-e23f771bfea6.png)

- [x] broken Searchbox(http://kendobuild-windows.dev.progress.com/kendo-ui-next/spreadsheet/sorting-filtering)
![filter4](https://user-images.githubusercontent.com/3844466/145834947-cfc988cf-56f1-4f9f-bb76-25f8f5044d02.PNG)
- [x] A proper width should be added to dropdownlist in Pager component(currently is too wide). In addition - dropdownlist and label should have space between them.
- [x] FORM: Checkbox has invalid class applied on initial load when required attribute is set(http://kendobuild-windows.dev.progress.com/kendo-ui-next/form/index)

Demos:
 - [x] http://kendobuild-windows.dev.progress.com/kendo-ui/listview/editing - set proper widths and roles to the inputs in edit mode 
 - [x] Checkbox has too small size in Grid edit mode demos
- [x] Replace 'k-textbox' class with 'k-input' for password inputs in Form demos.

**Comment by dtopalov** [comment]
The integration between the textboxes and the kendo-label component is broken in a couple of ways:

1. The label text is not vertically aligned to the center of the kendo-textbox component:

![image](https://user-images.githubusercontent.com/7533599/148203751-17a987c1-4e6b-4e96-aedb-28646c276b11.png)

like it used to be:

![image](https://user-images.githubusercontent.com/7533599/148203789-8612d191-5c51-4b7e-aa50-e81f66343d56.png)

This issue is not present with NumericTextBox or MaskedTextBox components.

2. There is no space between the label text and the components (this issue is present for all three textbox components):

![image](https://user-images.githubusercontent.com/7533599/148203995-214dcb84-5875-4ee8-ba42-6d73a8c3b9ae.png)

**Comment by slavenai** [comment]
When a custom icon is applied to a Button with no text, the icon is not centered.

Before:
https://www.telerik.com/kendo-angular-ui/components/buttons/button/icons/

<img width="279" alt="FontAwsome icon" src="https://user-images.githubusercontent.com/67437411/148380229-804e40e0-cf84-43c6-a76e-77a97a0a9060.png">

After:

<img width="230" alt="FontAwsome icon" src="https://user-images.githubusercontent.com/67437411/148380259-e62c1b34-6eac-4e92-88a4-dbedf97f3195.png">

Is this the expected behavior?

**Comment by Raisolution** [comment]
### Previous behaviour
Icons in Prefix and Suffix had sizing/alignment styles
<img width="202" alt="Screenshot 2022-01-07 at 10 38 41" src="https://user-images.githubusercontent.com/730205/148516753-85ce332f-2f1e-4806-98a7-e64559c22ffc.png">
<img width="220" alt="Screenshot 2022-01-07 at 10 38 52" src="https://user-images.githubusercontent.com/730205/148516766-e10d8457-5e73-49b6-b17b-b335ecdd4d5d.png">

### Current behaviour

Those styles are missing, thus icons don't have spacing from the border
<img width="231" alt="Screenshot 2022-01-07 at 10 39 25" src="https://user-images.githubusercontent.com/730205/148516815-bd299ac9-7d8b-476c-b318-dd5cf7a29522.png">

**Comment by Raisolution** [comment]
### Previous behaviour
Buttons in Prefix/Suffix examples were demonstrated using _clear_ button look i.e. with applied background on focus
<img width="376" alt="Screenshot 2022-01-06 at 19 46 13" src="https://user-images.githubusercontent.com/730205/148519342-bf6ba02a-0c06-4c79-9460-9d63df1f637d.png">

### Current behaviour
With the removal of the _clear_ button, we don't have a button in Default theme with such styling. We tried replacing the buttons with flat ones, but they apply border styling in the Default theme when focused (background is applied in Material theme though), so it looks a bit strange - along the focused style of the TextBox.
<img width="395" alt="Screenshot 2022-01-06 at 19 44 36" src="https://user-images.githubusercontent.com/730205/148519723-67a8c86e-29ad-49d2-b564-ad5c0df92cff.png">

Any suggestions how to handle this?
cc @tyanko @ivelina-penkova @joneff @tsvetomir

**Comment by preslavapetrova1** [comment]
If the ColorPicker has an icon to the left side of its button, the ColorPicker is rendered lower on the screen. 

**Previous Behavior**

![Screenshot 2022-01-10 at 16 43 46](https://user-images.githubusercontent.com/52581229/148784753-7a1969a7-ed08-471a-8a0c-9c3a1b09e04b.png)

**Current Behavior**

![Screenshot 2022-01-10 at 16 46 11](https://user-images.githubusercontent.com/52581229/148785105-947523ab-a278-444d-9025-7cb68a8f63fe.png)

**Comment by KristianMariyanov** [comment]
Flat autocomplete with focus looks broken (valid for all inputs)

When we are set Flat fill mode and we focus the input, the focused outline is too close to the text. Is this expected?
Demo: https://demos.telerik.com/blazor-ui-dev/autocomplete/appearance
![image](https://user-images.githubusercontent.com/6886919/148915387-f691a342-4e7a-4e56-b715-4e32d2fc72b8.png)
