### ISSUE TITLE
Switch issues related to the new styling options

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#3053]
**Describe the bug**
Switch in Kendo UI for jQuery is broken in RTL - The circle is outside the Switch and the labels are not positioned correctly for RTL

Related to https://github.com/telerik/kendo-themes/issues/2809

**To reproduce**

1. Go to Kendo UI next staging and unselect the Switch - kendo-ui-next/switch/right-to-left-support

**Expected behavior**
https://demos.telerik.com/kendo-ui/switch/right-to-left-support?autoRun=true&theme=default-main
The circle is not outside the Switch and the labels are positioned correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6614183/145811460-13080832-c5f0-495d-9d60-860c92531bb7.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment]
fixed by #3069
