### ISSUE TITLE
Spreadsheet Material issues

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#307]
## Current behavior
- [ ] Text is vertically not centered in cells:
![image](https://user-images.githubusercontent.com/6614183/45281151-a7c1c200-b4df-11e8-94f6-0f369d6c7a61.png)

- [ ] Font-size input text is cut:
![image](https://user-images.githubusercontent.com/6614183/45281545-cffdf080-b4e0-11e8-87ad-5a2f01a777f0.png)

- [ ] Filtering dialog:
  - Buttons are not per design
  - Missing line above buttons
  - Wrong margins to the left and right
![image](https://user-images.githubusercontent.com/6614183/45281240-ebb4c700-b4df-11e8-8919-7a2bbf5c3bd4.png)

- [ ] Data validation dialog:
  - Labels' text should be lighter
  - Radio buttons overlap their label
  - REMOVE button should be to the left
![image](https://user-images.githubusercontent.com/6614183/45283152-c925ac80-b4e5-11e8-8677-f2ef22d1ea44.png)

## Minimal reproduction of the problem with instructions
Tested on Kendo jQuery Spreadsheet demos

## Environment
* Kendo Ui for jQuery
* R3 2018

Browser:
- Chrome (desktop) version 69

**Comment by hadjieva** [comment]
@Dimitar-Goshev could you please revise this bug and confirm that it still exists.
