### ISSUE TITLE
Rounded component option is overridden by default button group styles

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3076]
**Describe the bug**

Nested Buttons in a buttongroup cannot have rounded setting

**To reproduce**

https://dojo.telerik.com/UkAwErIR

1. Change the `k-rounded-[value]` class

**Current behavior**

Rounded value does not have affect.

![image](https://user-images.githubusercontent.com/7159157/146349461-c8ea6ab2-af61-4081-b2d7-a69bc5728fca.png)

**Expected behavior**

Define the possible values for rounded option. If we want to keep the rounded options, than changes in styles are required.

**Comment by silviyaboteva** [comment]
Hey @jivanova ,
The button group is expected to look this way. The first child should be rounded at the left side and the last child should be rounded at the right side. The rest of the buttons shouldn't be rounded.

I have updated the dojo to see the expected result from all options - https://dojo.telerik.com/UkAwErIR/6 
> Note: `rounded: pill` will become `rounded: full` as we agree offline - https://github.com/telerik/kendo-themes/pull/3078
> Note2: the demo attached initially, the second button shouldn't have`k-group-start` class name
