### ISSUE TITLE
Add reference rendering for filtering of dropdownlist 

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3090]
Related to: https://github.com/telerik/kendo-themes/issues/2802

- [x] Include reference rendering for filtering and styles
       - Should the size be passed from the defined to the list?
- [x] Update documentation & html packages https://github.com/telerik/kendo-themes/tree/v5-dev/packages/html/src/dropdownlist

<details>
<summary>Currently used rendering in Blazor</summary>

``` html
<!-- default rendering -->
<span class="k-list-filter k-textbox k-input k-input-md k-rounded-md k-input-solid">
    <input type="text" class="k-input-inner" value="..." placeholder="..." />
     <span class="k-input-suffix"><span class="k-icon k-i-search"></span></span>
</span>

<!-- canonical rendering -->
<span class="
    k-list-filter 
    k-textbox
    k-input
    <!-- size is cascading from the list -->
    k-input-{size}
    k-rounded-md
    k-input-solid
    {loading && 'k-loading'}
">
    <!-- searchbox always render search icon -->
    {<span class="k-input-suffix"><span class="k-icon k-i-search"></span></span>}
    {showClearValue && text !== '' && <span class="k-clear-value"><span class="k-icon k-i-x"></span></span>}
</span>
```

</details>

**Comment by Juveniel** [comment]
@jivanova  I have updated both [the DDL issue ](https://github.com/telerik/kendo-themes/issues/2802)and [the list html helper readme](https://github.com/telerik/kendo-themes/pull/3115) with the rendering. 

In terms of the size - > the size for the parent component should be passed down to the child components (in this case the searchbox). This information is also available as a note in the DDL main issue.
