### ISSUE TITLE
ToolBar issues related to the new styling options

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#3095]
**Describe the bug**
The buttons in the ToolBar overflow PopUp need styles in order to keep the proper appearance.

**Screenshots**
![Toolbar](https://user-images.githubusercontent.com/3431388/146887846-53219d44-d9a2-4f80-b14b-b72c8c4ac13c.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Describe the bug**
The `k-active` class should bring the same visual appearance for Buttons as the `k-selected` class.

**Screenshots**
![Toolbar2](https://user-images.githubusercontent.com/3431388/146888246-46b6a348-c700-4d97-8478-ec3d9fc8b9d0.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by Juveniel** [comment]
fixed with https://github.com/telerik/kendo-themes/commit/148a0ab0543b81f6fa8d98a37efb100c308e043e
