### ISSUE TITLE
DropDownList issues related to the new styling options

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#3097]
**Describe the bug**
- [x] [**No visual tests**] DropDownList with virtualization and placeholder - the placeholder and first item overlap in dropdown: 
![image](https://user-images.githubusercontent.com/6614183/147076602-657ce305-7c29-4b3b-bfa0-cfe248e51345.png)

- [x] [**No visual tests**] DropDownList with virtualization, grouping and placeholder - the placeholder overlaps the group header in dropdown:
![image](https://user-images.githubusercontent.com/6614183/147076477-d2dfea66-590c-42b1-b496-732071b6859a.png)

- [x] DropDownList's toggle element has unexpected left border on click and hold

- [x] DropDownList is shorter than expected in ImageEditor's ToolBar and the first option falls on two rows - compare ImageEditor demos on next and dev staging for Kendo UI
- [x] DropDownList is shorter than expected in Filter and options fall on multiple rows when a short text option is selected - - compare Filter demos on next and dev staging for Kendo UI when a short option is selected:
![image](https://user-images.githubusercontent.com/6614183/147094435-1af43cc9-a2e4-4498-a70d-40067cb8b017.png)

**To reproduce**
Steps to reproduce the behavior for both points above

1. Go to [ImageEditor](http://kendobuild-windows.dev.progress.com/kendo-ui-next/imageeditor/index)
1. Click on Zoom DropDownList toggle element - left border is visible
1. When the dropdown is expanded, the first option is on two rows

**Expected behavior**
DropDownList in ImageEditor has default width enough to avoid options falling on two rows

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by MilenaCh** [comment]
- [ ] (Filter DropDown in Grid header)Filter icons are not centered(ex.: grid/filter-row):
![filter2](https://user-images.githubusercontent.com/3844466/147102987-702bc8f8-88e9-4cae-a391-60f036a98937.PNG)

**Comment by MilenaCh** [comment]
- DropDown text of PageSize is not completely visible in Pager with Material theme(http://kendobuild-windows.dev.progress.com/kendo-ui-next/treelist/index?autoRun=true&theme=material-main):
![pager2](https://user-images.githubusercontent.com/3844466/149337609-03dad798-3be5-4ecc-bb45-64fa244d8b39.PNG)

**Comment by Juveniel** [comment]
Virtual optionlabel bug is fixed with https://github.com/telerik/kendo-themes/pull/3253
