### ISSUE TITLE
Implement Material for Dialog - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#31]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- [ ] Scrollable content has no top and bottom border:
![image](https://user-images.githubusercontent.com/6614183/38371157-6a3dd250-38f4-11e8-81c4-145d10a1679b.png)

- [ ] Long button text overflows dialog. Should buttons fit on only one row and their excess text be with ... ?
![image](https://user-images.githubusercontent.com/6614183/38371261-a8d3563e-38f4-11e8-829b-50b1180efaac.png)
