### ISSUE TITLE
Menu issues related to the new styling options 

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#3101]
**Describe the bug**
- [x] Sub-Menu item's toggle arrow overlaps item's text, when the text is long: 
![image](https://user-images.githubusercontent.com/6614183/147048740-67e836ac-88e7-4da3-a6a6-ae2b89c66b42.png)

- [x] Root Menu item's toggle arrow overlaps item's text - https://github.com/telerik/kendo-themes/blob/v5-dev/tests/visual/output/default/misc/menu.png - see the Hover item
- [x] Focused Menu item has no focus indicator - https://github.com/telerik/kendo-themes/blob/v5-dev/tests/visual/output/default/misc/menu.png - see the Focus item

**To reproduce**

1. Go to Kendo UI for jQuery next staging - menu demos

**Expected behavior**
Compare the above issues with the develop branch image - https://github.com/telerik/kendo-themes/blob/v5-dev/tests/visual/output/default/misc/menu.png

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Comment by mparvanov** [comment]
https://kendobuild-windows.dev.progress.com/kendo-ui-next/menu/index?autoRun=true&theme=default-main
![image](https://user-images.githubusercontent.com/7202037/149781700-b1ebbda7-130c-4b7d-9377-f3239a0f3acf.png)

**Comment by Juveniel** [comment]
fixed in latest version of the themes
