### ISSUE TITLE
Primary button integrated in Grid has wrong text color.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3103]
Grid could be configured to display the command buttons like primary button, in such scenarios button's text has wrong color.

**Configuration**:
           toolbar: [{ name: "create", className: "k-primary" },
                    { name: "save" },
                    { name: "update" },
                    { name: "cancel" }
                ],
**Result**:
![command](https://user-images.githubusercontent.com/3844466/147089570-68959fca-411b-4139-92b8-dc6d07c0b702.PNG)

**Comment by Juveniel** [comment]
This should be fixed in the jQuery Grid by utilizing an actual `<button>` element for commands. I have linked a PR that fixes this.
