### ISSUE TITLE
Scheduler layout issues

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#315]
- [x] Scheduler events do not span from border to border of a timeslot:
 - Expected - R3 2018 SP1 of Kendo - https://demos.telerik.com/kendo-ui/scheduler/index 
![image](https://user-images.githubusercontent.com/6614183/50141264-bc1c1480-02af-11e9-9cdd-e611345c4ab7.png)
![image](https://user-images.githubusercontent.com/6614183/50141371-fc7b9280-02af-11e9-8842-b763fcafaff5.png)

 - Actual on Kendo staging:
![image](https://user-images.githubusercontent.com/6614183/50141322-deae2d80-02af-11e9-95c3-df61bdfcdc89.png)
![image](https://user-images.githubusercontent.com/6614183/50141411-1ae18e00-02b0-11e9-8062-48dddf90098c.png)

- [x] https://demos.telerik.com/kendo-ui/scheduler/timeline The vertical borders in header are not aligned to the content table in Timeline Week and Timeline Work Week views: 
![image](https://user-images.githubusercontent.com/7202037/45676407-50a09a80-bb3a-11e8-8540-f0c5a4cdda21.png)

- [x] https://demos.telerik.com/kendo-ui/scheduler/timeline There is a missing horizontal border in the scheduler times table at the header: 
![image](https://user-images.githubusercontent.com/7202037/45676305-1df6a200-bb3a-11e8-8546-6250f5b26fab.png)

- [x] https://demos.telerik.com/kendo-ui/scheduler/timeline Attendees are not vertically aligned:
![image](https://user-images.githubusercontent.com/7202037/45682063-e858b580-bb47-11e8-9ef4-b2cf7dde78eb.png)

- [x] https://demos.telerik.com/kendo-ui/scheduler/index Redundant horizontal separator at 7 am
![image](https://user-images.githubusercontent.com/7202037/45682116-13430980-bb48-11e8-862f-eb42df31dc15.png)

- [x] hover state of agenda view: icon overlaps text 
![image](https://user-images.githubusercontent.com/90405/45746005-d25ff900-bc0a-11e8-96d6-c8142e468747.png)

- [x] in agenda view, resource headers have a hover state 
![image](https://user-images.githubusercontent.com/90405/45746307-9ed19e80-bc0b-11e8-85da-e32ef82a5907.png)

- [x] `k-link` elements, like the day headers in week / month view, need to show a `cursor: pointer` 
![image](https://user-images.githubusercontent.com/90405/46131059-6e10eb00-c243-11e8-9a9c-438e12c0cc0f.png)

**Comment by tsvetomir** [comment]
- [ ] The event close icon is misaligned in Forefox:

![image](https://user-images.githubusercontent.com/247917/50514602-e0de6c00-0aa7-11e9-90c8-1b194b7aaf83.png)

**Comment by TeyaVes** [comment]
> * [ ]  The event close icon is misaligned in Firefox:
>   ![image](https://user-images.githubusercontent.com/247917/50514602-e0de6c00-0aa7-11e9-90c8-1b194b7aaf83.png)
>   Dimitar Goshev edit: It is reproducible on my side in all browsers in Material theme and Kendo UI jQuery Scheduler

> * [ ]  hover state of agenda view: icon overlaps text
>   ![image](https://user-images.githubusercontent.com/90405/45746005-d25ff900-bc0a-11e8-96d6-c8142e468747.png)

fixed in: https://github.com/telerik/kendo-themes/pull/559
