### ISSUE TITLE
Wrong tooltip width when Gantt is scrolled horizontally

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#316]
## I'm submitting a...
* Bug report
Gantt tooltip becomes narrow and high, although there is enough space to fit its content. The issue is related to scrolling time slots horizontally.

## Current behavior
![image](https://user-images.githubusercontent.com/6614183/45691296-05e64900-bb61-11e8-8d00-74a85f1cdcdc.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/6614183/45691329-126aa180-bb61-11e8-8ee5-81a53440617b.png)

## Minimal reproduction of the problem with instructions
1. https://demos.telerik.com/kendo-ui/gantt/index
1. Switch to Default v2 theme
1. Scroll Gantt horizontally with one slot so that Mon 6/02 is the first visible time slot
1. Hover task UI Design over the **e** letter in **Design** word - tooltip appears as Expected above
1. Hover task UI Design over the **g** letter in **Design** word - tooltip is narrow, although there is enough space to the right to fit its normal layout.

Note: hovering over the **s** letter in **Design** word starts taking abnormal effect - the title of the tooltip breaks on two rows.

## Environment
Product:
* Kendo Ui for jQuery - 2018.3.911
* Kendo Ui for Vue

Package versions:

```

```

Browser:

- Chrome (desktop) version Version 69.0.3497.92

**Comment by GreySage** [comment]
This bug occurs in multiple styles, including custom styles.
I found a workaround though. If you are using a template for the tooltip you can add in a div wrapping the rest of the code, set the div width style to a value, and the element style will override whatever broken styling kendo is applying and it will stay at the specified width.

**Comment by joneff** [comment]
Fixed by #2712
