### ISSUE TITLE
Referenced file paths have changed to using a tilde sign

### ISSUE THREAD

**Issue by radkostanev** [telerik/kendo-themes#3161]
With v5, file import paths have changed to using a tilde `~` sign to refer to home instead of using `..` for the parent folder. This causes certain web compilers/bundlers to fail to locate files.

**4.43.0:**
`
@import "../../../modules/@progress/kendo-theme-default/scss/core/functions/_index.scss";
`

**5.0.0-beta.3:**
`
@import "~modules/@progress/kendo-theme-default/scss/core/functions/_index.scss";
`

**Comment by Juveniel** [comment]
There is currently no errors when compiling the themes with both node and dart sass from the themes build process/cli/gulp-sass. That being said, I would suggest utilizing [the described gulp setup to compile](https://github.com/telerik/kendo-themes/wiki/Compiling-themes#using-gulp) the themes in sample applications.
