### ISSUE TITLE
No spacing in dropdowntree popup

### ISSUE THREAD

**Issue by dtopuzov** [telerik/kendo-themes#3174]
**Describe the bug**
No spacing in dropdowntree popup.

**To reproduce**

1. Open jQuery demos build with v5 themes
1. Go to `dropdowntree` demos and expand popup
1. No spacing between content and popup

**Expected behavior**
Dropdown tree popup looks as v4.

**Screenshots**

v4:
![image](https://user-images.githubusercontent.com/6651651/148531894-5a66b438-cb70-4c1b-9434-478ad8482bd2.png)

v5:
![image](https://user-images.githubusercontent.com/6651651/148531851-db01eb66-7dda-4fbb-b67c-0d9c86762a12.png)

Note: Ignore the colors, it is while debug breakpoint is hit.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by MilenaCh** [comment]
The same issues exist in scenario without checkboxes also:
![dropdowntree2](https://user-images.githubusercontent.com/3844466/149335564-e9afa44d-40bd-4b72-a2d1-2538f64958e6.PNG)

Result: There is no spacing between the root item and top border.
Ex.: http://kendobuild-windows.dev.progress.com/kendo-ui-next/dropdowntree/index

**Comment by joneff** [comment]
fixed by 7907d94a8af62115cb5fdae0df630b7c0ec24c83
