### ISSUE TITLE
Expand button is not aligned properly in Safari

### ISSUE THREAD

**Issue by dtopuzov** [telerik/kendo-themes#3176]
**Describe the bug**
Expand button is not aligned properly in Safari.

**To reproduce**

1. Open `combobox` demos of jQuery build with themes v5 (it is ok with v4).
1. See the expand button

**Expected behavior**
Expand button aligned properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6651651/148549326-95abb17d-3257-436a-8831-19b853403193.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* Safari

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by ahmadjubair33** [comment]
hey can I solve this isssue?

**Comment by silviyaboteva** [comment]
fixed in `v5-dev`: https://github.com/telerik/kendo-themes/pull/3192
