### ISSUE TITLE
Autocomplete left border is not correct when placed in the filter row of the Grid

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#318]
## I'm submitting a...

* Bug report reported in 1343089  
## Current behavior

Autocomplete left border is not correct when placed in the filter row of the Grid

## Expected behavior

https://dojo.telerik.com/OfAPOdIg/5

## Minimal reproduction of the problem with instructions

1. https://demos.telerik.com/kendo-ui/grid/filter-row
1. Check the borders of the "Ship Name" column.

## Environment
Product:

* Kendo Ui for jQuery

**Comment by joneff** [comment]
That's related to many components having `k-header` class. The correct way is to remove the class from the rendering

**Comment by joneff** [comment]
Fixed by removing the said class from the rendering
