### ISSUE TITLE
Kendo Angular ScrollView theme update

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-themes#32]
There are few open issues related to Angular ScrollView component:
 
 - https://github.com/telerik/kendo-angular/issues/493
 - https://github.com/telerik/kendo-angular/issues/1311

We can address them by removing the following rules:
```
.k-scrollview li {
  user-select: none;
}

.k-scrollview li>* {
  user-select: none;
  pointer-events: none;
}
```

**Comment by gyoshev** [comment]
Fixed with the above commits.
