### ISSUE TITLE
Button group link fill mode doesn't show selection

### ISSUE THREAD

**Issue by KristianMariyanov** [telerik/kendo-themes#3210]
**Describe the bug**
Button group link fill mode doesn't indicate which buttons are selected

**To reproduce**

1. Go to https://demos.telerik.com/blazor-ui-dev/buttongroup/appearance
1. Choose FillMode Link
1. Select Buttons

**Expected behavior**
Selected buttons are bisible

**Screenshots**
Two of the buttons are selected:
![image](https://user-images.githubusercontent.com/6886919/148926665-3b7d3b82-6e55-4479-88a9-d5c36c1e74dc.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
It doesn't has selection. neither does "clear" button.
