### ISSUE TITLE
TabStrip has no scrollbuttons and tabs fall on separate lines

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#3212]
**Describe the bug**
The flex-flow rule forces tabs to fall on separate rows

Note: the issue also affects tabs of Spreadsheet sheets:
![image](https://user-images.githubusercontent.com/6614183/148962991-df355aa3-9ba0-4ac7-a199-4ed50fea84d5.png)

**To reproduce**

1. Go to Kendo UI staging for version next - use [TabStrip scrollable-tabs](https://demos.telerik.com/kendo-ui/tabstrip/scrollable-tabs) demo

**Expected behavior**
Scroll buttons in Kendo UI for jQuery are rendered dynamically - there should be scroll buttons
![image](https://user-images.githubusercontent.com/6614183/148962161-5ed0a1d7-2db4-4f97-a7c9-9669ab85b321.png)

**Screenshots**
Currently there are no scroll buttons
![image](https://user-images.githubusercontent.com/6614183/148962020-6856b73a-6987-4cb4-8191-bcd82d14ef61.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Comment by Juveniel** [comment]
fixed in v5.0.0.beta-6
