### ISSUE TITLE
[Button] Buttons in Split/DDB list of options and Toolbar overflow popups get wrong "active" styling

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#3215]
**Describe the bug**
While pressed, the buttons in the DropDown/SplitButton list of options, as well as in a responsive Toolbar's overflow popup, get the salmon pink color due to a **:active** selector that is applied to them.

**To reproduce**

1. Open http://v5-themes-dev.k2build.dev.progress.com/kendo-angular-ui/buttons/dropdownbutton/
1. Open any Split or DrodDown button and click any of the options

Same goes for the buttons in the Toolbar overflow popup.

**Screenshots**

![image](https://user-images.githubusercontent.com/7533599/149093179-8372838f-c59a-49b5-8874-e329738307b4.png)

![image](https://user-images.githubusercontent.com/7533599/149093348-d20bf6ee-6c0e-496a-8911-fb334c632536.png)

![image](https://user-images.githubusercontent.com/7533599/149093483-f9d36a5a-eba8-4e7a-a759-6fc9478c9a80.png)

**Expected behavior**
The button should keep its current active styling while pressed:

![image](https://user-images.githubusercontent.com/7533599/149093710-059503a9-0fcd-4dda-9ea8-9a8b337b8b76.png)

![image](https://user-images.githubusercontent.com/7533599/149094437-b8a6620f-a647-44be-8cb1-c9d47c17e6a4.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
Hey @dtopalov, you might check my comment in https://github.com/telerik/kendo-themes/issues/3216#issuecomment-1013213132. I think that changing the rendering with the reference one will solve this issue as well.

**Comment by joneff** [comment]
fixed by 7e0b9d19ae57558cd7af98c70312ebd023931496
