### ISSUE TITLE
[Toolbar] Toggle buttons "selected" styling not applied in overflow popup

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#3216]
**Describe the bug**
The toggleable buttons do not behave as such in the responsive Toolbar's overflow popup - k-selected is applied, but does not seem to have any effect.

**To reproduce**

1. Ensure there is a toggleable button in the Toolbar overflow popup
2. Open the overflow popup
3. Click the toggleable button

**Expected behavior**
The toggled state is applied as expected.

**Screenshots**
New behavior after clicking the button:

![image](https://user-images.githubusercontent.com/7533599/149096012-f83ac41d-5b73-47a1-bf1c-168c6f625ce8.png)

Current (correct) behavior:

![image](https://user-images.githubusercontent.com/7533599/149096113-efd1b7ec-1bc9-4105-985b-8598015882b1.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
Hey @dtopalov,

Can you check the reference rendering of the toolbar popup in the following test -> `tests/visual/src/misc/toolbar-popup.html`. 

I could not see issues related to selected styling. Let me know if you have any questions.

**Comment by Juveniel** [comment]
fixed in v5.0.0-beta.6
