### ISSUE TITLE
[Toolbar] Buttons with icons and no text are broken in overflow popup

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#3217]
**Describe the bug**
Buttons with icons but no text are rendered way too big in the Toolbar overflow popup. Buttons with icons AND text look OK.

**To reproduce**

1. Check open the Toolbar overflow popup with icon buttons inside

**Expected behavior**
Buttons that have icons only to look like the ones having only text or both icon and text

**Screenshots**

![image](https://user-images.githubusercontent.com/7533599/149099905-86cec892-a31a-4311-ab03-b7b8bb1b56bb.png)

![image](https://user-images.githubusercontent.com/7533599/149100193-89ff9e30-789d-4641-920e-6e1277df00b7.png)

Current (working) rendering:

![image](https://user-images.githubusercontent.com/7533599/149100512-a948f9c4-0615-44cb-a61f-b21833ab00d2.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.

**Comment by silviyaboteva** [comment]
@dtopalov, may I ask you to provide the rendering of the toolbar popup? 

In general, when there is no text, we should provide &nbsp; character to preserve the height of the menu item. Let me demonstrate it:
**markup**
<img width="473" alt="Screenshot 2022-01-12 at 11 45 23" src="https://user-images.githubusercontent.com/17604855/149115210-aa869e18-d6c0-47de-9442-12312cadabf7.png">

**output**
<img width="225" alt="Screenshot 2022-01-12 at 11 45 35" src="https://user-images.githubusercontent.com/17604855/149115439-c4d8bff3-c880-49fb-862c-10b8f4f9f8b2.png">

However, either if the k-menu-link-text element is removed, the output doesn't look like the provided screenshots:
**markup**
<img width="519" alt="Screenshot 2022-01-12 at 11 50 47" src="https://user-images.githubusercontent.com/17604855/149116947-71878ad8-40b6-4104-9fb2-d9df94fbe611.png">

**output**
<img width="189" alt="Screenshot 2022-01-12 at 11 42 44" src="https://user-images.githubusercontent.com/17604855/149116826-1cd568c1-85db-4ee4-b263-fbb515e77f2d.png">

**Comment by Juveniel** [comment]
fixed in v5.0.0-beta.6
