### ISSUE TITLE
Include :focus styling for menu items of the li element

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3223]
**Describe the bug**

With v5 implementation, the focus state styling seems to be moved to the k-item. In blazor team, adding and removing the css class comes with a cost. Thus, it is important for us to use :focus as much as possible.

**To reproduce**

https://demos.telerik.com/blazor-ui-dev/menu/keyboard-navigation

1. Start interacting with the menu
2. Open a popup
3. Observe that there is no focus state
 
The issue stems from `:focus` applied to `k-item`, but our focusable elements are the li elements. We would like to keep this behavior because of templates that render inside the li directly where the keyboard navigation should work as well.

**Expected behavior**
Focus state appear

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Comment by Dimitar-Goshev** [comment]
Kendo UI for jQuery Menu uses `k-focus` class to highlight the currently focused item. With v5 there are styles for focused root menu items, but there are no styles to highlight sub-menu items on focus.
1. Go to https://demos.telerik.com/kendo-ui/menu/orientation?autoRun=true&theme=default-main
2. Click before the menu and then press Tab to focus the menu - Men's item is highlighted as focused
3. Press Down arrow to expand its sub-items - the first item Footwear is focused, but there are no styles to highlight it.
