### ISSUE TITLE
Improve edit buttons appearance in Material theme

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3229]
Demo:  http://kendobuild-windows.dev.progress.com/kendo-ui-next/treelist/editing?autoRun=true&theme=material-main
![treelist5](https://user-images.githubusercontent.com/3844466/149367776-0116833c-fe17-44c6-a53e-00a941a82474.PNG)

**Comment by silviyaboteva** [comment]
Hi @MilenaCh,
In v5, the buttons in the Grid, Treelist etc. are not having custom styles overwriting their default look. In Material theme, the default look of the button is like shown in the screenshot above.

There was an additional styling to remove the box-shadow of the buttons previously, but as of now, it is removed.
So, this is the expected appearance :)

 As for the alignment, I can suggest setting a bigger column width value to render them on a single line.
