### ISSUE TITLE
Treeview child nodes are not aligned properly

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#3238]
**Describe the bug**
With the latest themes version the treeview items are not aligned properly 

**To reproduce**
1. Go to https://kendobuild-windows.dev.progress.com/kendo-ui-next/treeview/basic-usage

**Expected behavior**
Child nodes are aligned as on live:
https://demos.telerik.com/kendo-ui/treeview/basic-usage

**Screenshots**
https://www.screencast.com/t/S2Zso69N2F18

Themes:  v5.0.0-beta.4

**Comment by Juveniel** [comment]
fixed in v5.0.0-beta-6
