### ISSUE TITLE
Dropdowntree input height is not correct when a placeholder is not set

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#3239]
**Describe the bug**
The issue is happening only when a placeholder is not se to DropDownTree.

**To reproduce**
http://kendobuild-staging.dev.progress.com/dojo-staging/UzecucIH/3 

**Expected behavior**
Input height is set as with placeholder:
http://kendobuild-staging.dev.progress.com/dojo-staging/EyaPoqoM
Working as expected with the latest official:
https://dojo.telerik.com/IpAyAMud

**Screenshots**
https://www.screencast.com/t/rwXyRXTp

Themes:  v5.0.0-beta.4

**Comment by Juveniel** [comment]
fixed in v5.0.0.beta-6
