### ISSUE TITLE
Components that should be documented

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#3265]
As of v5 in `docs/components` folder we started documenting the components (options, use-cases, per theme use-cases, etc.) that are collected from the Katana and transferred to the Kendo Themes website (currently WIP).

Here is the list of missing docs articles with v5 improved components:
- [ ] TextBox
- [ ] MaskedTextBox
- [ ] NumericTextBox
- [ ] TextArea
- [ ] RadioGroup
- [ ] CheckBoxGroup
- [ ] ButtonGroup
- [ ] ColorPicker (with ColorPallete, ColorGradient and FlatColorPicker)
- [ ] AutoComplete
- [ ] ComboBox
- [ ] DropDownList
- [ ] MultiSelect
- [ ] MultiSelectTree
- [ ] DateInput
- [ ] DatePicker
- [ ] DateRangePicker
- [ ] DateTimePicker
- [ ] TimePicker
- [ ] Menu List
- [ ] ListBox
- [ ] TreeView

**Comment by Juveniel** [comment]
Closing this issue, as it is no longer relevant. Docs for these components should be added based on the design perspective as part of the Design System effort.
