### ISSUE TITLE
Textarea resizable option regression

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-themes#3281]
**Describe the bug**
The [resizable option](https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextAreaComponent/#toc-resizable) of the Angular TextArea is not working as expected after v5. It should allow resizing in all directions or `auto` resizing, in which case the TextArea adjusts its height depending on the value.

The problem is already reported by clients in ticket 1550352

**To reproduce**

1. Go to https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/ (Currently this is working, because it is temporary fixed with inline CSS styles added by the component itself)
1. The TextArea should adjust it's height automatically
### 
1. Go to https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/#toc-setting-the-resize-directions
1. Only the horizontal resizing is working. The TextArea should allow vertical resizing too.

**Expected behavior**
The resizable option should behave as prior to v5.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Comment by joneff** [comment]
We do not recommend the textarea to be sized horizontally, as it will lead to unexpected results.

What is changed is that the text are was inline level element and is now a block level element. we'll revert to inline level element, because that's the native behaviour. There are, however, additional issues, that will need to be resolved by adding class names.

**Comment by Raisolution** [comment]
Adding this to R2 2022 PI 1. The regression is related to a functionality available in the Angular Textarea prior to v5, namely resizing in all directions and vertical auto-sizing. The resizable option supports the following values:

https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextAreaComponent/#toc-resizable

Currently we implemented a temporary fix for the customers with inline CSS in the component, but it would be best for the regression to be addressed in the theme.

**Comment by tsvetomir** [comment]
Related: https://github.com/telerik/kendo-themes/pull/3365

**Comment by Raisolution** [comment]
Thanks @tsvetomir 

#3365 is a step in the right direction. A bit of additional styling will be needed for the Angular TextArea in order to correctly position the prefix/suffix content according to the current flex direction. This is currently handled by internally attached inline CSS.

**Comment by Juveniel** [comment]
@Raisolution in terms of the adornments:

* This inline style can be removed from the component, as the `k-input-prefix/suffix` also utilize the same:
![image](https://user-images.githubusercontent.com/16972160/152933252-be479e81-7794-469b-8d2f-cc031805b9c1.png)

* The layout of the adornments can be changed by toggling the same class that is toggled on the textarea host element e.g `!k-flex-col/row`. Thus, no need for inline styles.

**Comment by Raisolution** [comment]
@Juveniel this style is toggled between `center` and `start` depending on the flex direction. Otherwise when `k-flex-row` is applied, the adornments are centered vertically, instead of staying at the `top`.
