### ISSUE TITLE
Kendo button using iconClass with font-awesome not displaying icon due to specificity

### ISSUE THREAD

**Issue by jrdutton** [telerik/kendo-themes#3283]
**Describe the bug**
The order in which classes are applied means that the font awesome icon is not displayed. This is because the k-icon font-family of "WebComponentsIcons" is overriding the font-awesome font-family of  "Font Awesome 5 Pro"

**Expected behaviour**
The font awesome icon should be displayed within the button. It is not.

**Screenshots**
With the HTML...
![image](https://user-images.githubusercontent.com/3248773/150975033-50c6c062-062a-4b30-a5b8-b421e3d5730d.png)

I am seeing...
![image](https://user-images.githubusercontent.com/3248773/150975172-af8754d6-20a5-4062-9bc8-1423884a1029.png)

So the outcome is...
![image](https://user-images.githubusercontent.com/3248773/150975346-396e8120-6b46-4253-ab6c-8d0dad19005f.png)

**Affected package**
* theme-default

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* Chrome version: 97.0.4692.71

**Comment by JoomFX** [comment]
The classes order does not matter. What matters is the order in which the stylesheets are loaded.
Looking at the screenshot, loading `regular.scss` after Kendo Themes will solve the issue.
