### ISSUE TITLE
Fix URI malformed error when using the SASS themes in NextJS projects.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#3285]
**Describe the bug**

URIError: URI malformed error occurs when adding the scss file of the themes. This occurs after updating to version 5.0.0

**To reproduce**

1. Go to our repo for NextJS and update the package to the latest https://github.com/telerik/kendo-react-nextjs
1. Run 'npm run dev' and the error will be shown

**Expected behavior**

The application is built successfully. 

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Affected browsers (please remove the unneeded items)**

* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by Juveniel** [comment]
@simonssspirit, I was able to successfully build the app with node 14 with no errors after upgrading the themes package to `5.0.0`.  Can you think of any specific steps that would enable me to replicate the issue ?

**Comment by jake-tourtech** [comment]
@Juveniel, ensure that you are using the current version of Nextjs (>= v12) and importing the theme's `all.sass` file so that it must go through Nextjs's postcss process.
