### ISSUE TITLE
There is no visual indication on hover

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3287]
1. Navigate to: https://demos.telerik.com/kendo-ui/datepicker/index?autoRun=true&theme=bootstrap-main
2. Hover over picker's input

Result: 'k-hover' class is added to the input, however there is no visual indication that the input is hovered
Valid for all pickers

**Comment by silviyaboteva** [comment]
Hey @MilenaCh, it seems that we follow the Figma design for Bootstrap ([link](https://www.figma.com/file/YjhpzSsYaZI5VOaamsvIku/Telerik-%26-KENDO-UI-Kit-for-Bootstrap-1.9--(UNPUBLISHED)?node-id=0%3A1)). Check that all Inputs, Dropdowns, and DateInputs have the same border color for the Normal and Hover states.

@telerik/kendo-ux @ivelina-penkova, just to be sure, is this the correct behavior?

**Comment by ivelina-penkova** [comment]
@silviyaboteva yes, this is the correct behavior, it's synced with Bootstraps guide on inputs: https://getbootstrap.com/docs/4.1/components/input-group/
