### ISSUE TITLE
Component options update based on the design revision

### ISSUE THREAD

**Issue by hadjieva** [telerik/kendo-themes#3290]
Changes are expected mainly in the Size and FillMode options of buttons and inputs, so once the suggestions for improvement are provided by the design team, they should be applied to the Themes. Here is the respective design issue: [Component options - Design Revision](https://github.com/telerik/web-components-ux/issues/410) on which this item depends.

**Comment by joneff** [comment]
fixed #3382

**Comment by joneff** [comment]
@hadjieva we'll open another issue for fill mode revision, because they are in different iterations.
