### ISSUE TITLE
Component options for Toolbar

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#3294]
**Dependencies**

design: https://github.com/telerik/web-components-ux/issues/431
part of: https://github.com/telerik/kendo-themes-private/issues/6

**Component options for Toolbar**

```ts
enum ToolbarSize { small, medium, large };

class Toolbar {
   size: (null | ToolbarSize) = ToolbarSize.medium;
}
```

**Rendering**
* [x] Rendering

**Toolbar**

<details>
  <summary>Canonical Rendering Toolbar & Overflow Popup/Menu</summary>
  
```html
<!-- canonical rendering toolbar -->
<div class="
    k-toolbar
    k-toolbar-{size}

    {resizable && 'k-toolbar-resizable'}
">
    <button class="k-toolbar-button k-button k-button-{size} k-button-solid k-button-solid-base k-rounded-{rounded}">
        <span class="k-button-text">Button</span>
    </button>
    <div class="k-separator"></div>
    <div class="k-toolbar-button-group k-button-group">
        <button class="k-toolbar-button k-button k-button-{size} k-button-solid k-button-solid-base k-rounded-{rounded}">
            <span class="k-button-icon k-icon k-i-align-left"></span>
            <span class="k-button-text">Left</span>
        </button>
        <button class="k-toolbar-button k-button k-button-{size} k-button-solid k-button-solid-base k-rounded-{rounded}">
            <span class="k-button-icon k-icon k-i-align-center"></span>
            <span class="k-button-text">Center</span>
        </button>
        <button class="k-toolbar-button k-button k-button-{size} k-button-solid k-button-solid-base k-rounded-{rounded}">
            <span class="k-button-icon k-icon k-i-align-right"></span>
            <span class="k-button-text">Right</span>
        </button>
    </div>
    <div class="k-separator"></div>
    <div class="k-toolbar-item">
        <label>Label:</label>
        <input>
    </div>
    <button class="k-toolbar-overflow-button k-button k-button-{size} k-button-flat k-button-flat-base k-icon-button">
        <span class="k-button-icon k-icon k-i-more-vertical"></span>
    </button>
</div>

<!-- canonical rendering overflow popup/menu -->
<div class="k-animation-container">
    <div class="k-toolbar-popup k-popup k-menu-popup">
        <ul class="k-menu-group k-menu-group-{size}">
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-menu-link-text">Button</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <div class="k-separator k-separator-horizontal"></div>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-left"></span>
                    <span class="k-menu-link-text">Left</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-center"></span>
                    <span class="k-menu-link-text">Center</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-right"></span>
                    <span class="k-menu-link-text">Right</span>
                </span>
            </li>
        </ul>
    </div>
</div>
```
</details>

<details>
  <summary>Default Rendering Toolbar (jquery / react / vue / blazor)</summary>
  
```html
<div class="k-toolbar k-toolbar-md k-toolbar-resizable">
    <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
        <span class="k-button-text">Button</span>
    </button>
    <div class="k-separator"></div>
    <div class="k-toolbar-button-group k-button-group">
        <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
            <span class="k-button-icon k-icon k-i-align-left"></span>
            <span class="k-button-text">Left</span>
        </button>
        <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
            <span class="k-button-icon k-icon k-i-align-center"></span>
            <span class="k-button-text">Center</span>
        </button>
        <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
            <span class="k-button-icon k-icon k-i-align-right"></span>
            <span class="k-button-text">Right</span>
        </button>
    </div>
    <div class="k-separator"></div>
    <div class="k-toolbar-item">
        <label>Label:</label>
        <input>
    </div>
    <button class="k-toolbar-overflow-button k-button k-button-md k-button-flat k-button-flat-base k-icon-button">
        <span class="k-button-icon k-icon k-i-more-vertical"></span>
    </button>
</div>
```
</details>

<details>
  <summary>Default Rendering Toolbar (angular)</summary>
  
```html
<div class="k-toolbar k-toolbar-md k-toolbar-resizable">
    <div class="k-toolbar-renderer">
        <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
            <span class="k-button-text">Button</span>
        </button>
    </div>
    <div class="k-toolbar-renderer">
        <div class="k-separator"></div>
    </div>
    <div class="k-toolbar-renderer">
        <div class="k-toolbar-button-group k-button-group">
            <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
                <span class="k-button-icon k-icon k-i-align-left"></span>
                <span class="k-button-text">Left</span>
            </button>
            <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
                <span class="k-button-icon k-icon k-i-align-center"></span>
                <span class="k-button-text">Center</span>
            </button>
            <button class="k-toolbar-button k-button k-button-md k-button-solid k-button-solid-base k-rounded-md">
                <span class="k-button-icon k-icon k-i-align-right"></span>
                <span class="k-button-text">Right</span>
            </button>
        </div>
    </div>
    <div class="k-toolbar-renderer">
        <div class="k-separator"></div>
    </div>
    <div class="k-toolbar-renderer">
        <label>Label:</label>
        <input>
    </div>
    <button class="k-toolbar-overflow-button k-button k-button-md k-button-flat k-button-flat-base k-icon-button">
        <span class="k-button-icon k-icon k-i-more-vertical"></span>
    </button>
</div>
```
</details>

<details>
  <summary>Default Rendering Overflow Popup/Menu</summary>
  
```html
<div class="k-animation-container">
    <div class="k-toolbar-popup k-popup k-menu-popup">
        <ul class="k-menu-group k-menu-group-md">
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-menu-link-text">Button</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <div class="k-separator k-separator-horizontal"></div>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-left"></span>
                    <span class="k-menu-link-text">Left</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-center"></span>
                    <span class="k-menu-link-text">Center</span>
                </span>
            </li>
            <li class="k-item k-menu-item">
                <span class="k-link k-menu-link">
                    <span class="k-icon k-i-align-right"></span>
                    <span class="k-menu-link-text">Right</span>
                </span>
            </li>
        </ul>
    </div>
</div>
```
</details>

**Important Notes**

1. Remove the `k-widget` class.
2. The `k-toolbar-resizable` class should be added if it is a Responsive Toolbar
3. The Toolbar Tools/Items should NOT be wrapped in a container (apart from the Templates and the Combobox/DropDownlist/ ColorPicker that should be wrapped in a `k-toolbar-item` element). React and Vue to remove the `span` wrapper.
4. In Angular the Toolbar Tools/Items (including the Templates) should be wrapped in a `k-toolbar-renderer` element. Add the `k-toolbar-renderer` class to the `kendo-toolbar-renderer` element.
5. The Overflow Popup/Menu should be Menu component (rendering above). Blazor already have the correct rendering.
6. The `k-overflow-anchor` class should be replace with `k-toolbar-overflow-button`.
7. Every Toolbar Tool/Item (except the Templates and the Combobox/DropDownlist/ ColorPicker) should have a unique class so UniteUX can target it without styles leaking to other elements (`k-toolbar-button`, `k-toolbar-toggle-button`, `k-toolbar-button-group`, `k-toolbar-menu-button`, `k-toolbar-split-button`, ~~`k-toolbar-combobox`~~, ~~`k-toolbar-dropdownlist`~~, ~~`k-toolbar-colorpicker`~~, `k-toolbar-overflow-button`)

NOTE: Components already wrapped in a `k-toolbar-item` element should not have a dedicated/unique class. Such components are Combobox, DropDownlist and ColorPicker.

**Deliverables**

* [x] Implement component options.
* [x] Create JSON structure
* [x] Variables (add prefix `$kendo-` if missing)
* [x] Docs article containing each mode.

**Visual test/s link**

**Comment by Juveniel** [comment]
Based on https://github.com/telerik/blazor/issues/2365, a concern arises with how the overflow popup button is currently implemented in the themes (absolute position). This approach results in custom styling for the button, that is not consistent with regular buttons, and furthermore has the caveat of going over the content when there are items that do not overflow(overflow: never), and the toolbar is resized below the minimum space available for those items:

![image](https://user-images.githubusercontent.com/16972160/161780083-e86af12c-b071-45d8-b9f2-288cd9cf2b66.png)

Consider changing the overflow button to be relatively positioned in the end of the Toolbar and remove style customization. In the `overflow: never` scenario, this will cause the button to not be visible once you resize the Toolbar past the minimum width needed to display the elements that do not overflow (expected behavior). If we decide to go with this approach, this should be implemented in all suites that support this feature.

//cc @KristianMariyanov

**Comment by Raisolution** [comment]
We had the same issue in Angular recently - https://github.com/telerik/kendo-angular/issues/3230 but the general statement was that a fix from the themes is not viable due to specific Toolbar usage scenarios. Thus it was handled internally in the component code.

cc @PaskalevStoyan @joneff

**Comment by KristianMariyanov** [comment]
We may also think about adding wrapper elements for our toolbar items.

Currently in Blazor managing the keyboard navigation and deciding which items are overflowing relies on the order of the items inside the k-toolbar element. We are forced to keep in sync our C# items with the Dom elements, which in some cases could be difficult.
In addition, when we have templates, the number of the dom elements may not match the number of ToolBar items (a template could introduce two root items)

After a quick check, it seems that [Angular ](https://www.telerik.com/kendo-angular-ui/components/toolbar/) and [jQuery](https://demos.telerik.com/kendo-ui/toolbar/index) also use wrappers, which currently is not according to the official rendering.

**Comment by JoomFX** [comment]
Since the goal is to use the Toolbar component in the Filter component I'm writing this here.

In an ad hoc meeting with @veselints we noticed that the Filter rendering is not quite ok.
Currently, the [referent rendering of the Filter](https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/filter/tests/filter.tsx#L23) suggests that all Filter items should be wrapped in a `k-filter-toolbar-item` element. This is the implementation that we currently have in [Angular](https://www.telerik.com/kendo-angular-ui/components/filter/) and [jQuery](https://demos.telerik.com/kendo-ui/filter/index), while in [React](https://www.telerik.com/kendo-react-ui-develop/components/datatools/filter/) and [Vue](https://www.telerik.com/kendo-vue-ui/components/datatools/filter/) they already use the Toolbar component, therefore they do not have the `k-filter-toolbar-item` wrapper.

We will update the referent rendering of the Filter but until then here are some key points:
- Since the Toolbar component will be used in the Filter component, the Toolbar recommendations and suggestions should be used.
- The "simple" items (Button, ButtonGroup, etc) should not be wrapped in a container and should not have the `k-toolbar-item` class.
- The "complex" items (DropDownList, Combobox, Input) should be wrapped in a `k-toolbar-item` element.

Once Angular and jQuery implement the Toolbar component (not only its rendering) in the Filter component the referent rendering will be updated in Kendo Themes.

@Juveniel @svetq @radkostanev
