### ISSUE TITLE
Component options for Dialog

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#3296]
**Dependencies**

**Component options for Dialog**

```ts
```

**Rendering**
* [ ] Rendering

**Dialog**
```html
<!-- default rendering -->


<!-- canonical rendering -->

```

**Deliverables**

* [ ] Implement component options.
* [ ] Create JSON structure
* [ ] Variables (add prefix `$kendo-` if missing)
* [ ] Docs article containing each mode.

**Visual test/s link**

**Comment by Juveniel** [comment]
Implementing component options for the Dialog are not a requirement for the High-density/compact Grid and we currently do not have design for the same. Thus, implementation of this item is currently postponed. Refer to https://github.com/telerik/web-components-ux/issues/432#issuecomment-1168431590 for additional info.

**Comment by Juveniel** [comment]
resolved with https://github.com/telerik/kendo-themes/pull/4093
