### ISSUE TITLE
Wrong Dialog header hight, if there is no title set and closable is set to false

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#33]
Dialog's header becomes shorter, if there is nothing in it - no title and no close button:
![image](https://user-images.githubusercontent.com/6614183/36589765-259ff152-1895-11e8-90b9-3b70f626b78e.png)

```
    $("#dialog").kendoDialog({
        visible: true,
        width: 300,
        height: 200,
        closable: false,
        actions: [{
            text: "OK",
            action: function (e) {
                return false;
            },
            primary: true
        }, {
            text: "Cancel"
        }]
    });
```

**Comment by Dimitar-Goshev** [comment]
Another header height issue: https://github.com/telerik/kendo-themes/issues/19

**Comment by gyoshev** [comment]
I don't believe that this is a styling issue. Rather, if there is no title and no buttons, why render a title at all? Setting `title: false` will remove the title, and it will [look good](https://dojo.telerik.com/esuFUMan). As a developer using the framework, I am puzzled at what the difference between `title: false` and providing no explicit `title` is.

**Comment by joneff** [comment]
I've added styles for `k-window-title::before` element so it keeps the height consistent even with empty title.

I agree that for the case that needs no title, then it should be specified as such
