### ISSUE TITLE
Dropdowns in the Toolbar are not wide enough

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#3311]
**Describe the regression**
Since v5 of the themes there is [a rule](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/toolbar/_layout.scss#L68) that sets the width of the Dropdowns in the Toolbar to `10em`.
However, the width of the Dropdowns in v4 was `12.4em`.
With the new/smaller width there are some visual issues that can be seen in the screenshot and the Stackblitz examples below.

**To reproduce**
[Example with Kendo Themes v4](https://stackblitz.com/edit/angular-asaxgh?file=index.html)
[Example with Kendo Themes v5](https://stackblitz.com/edit/angular-gmsjr9?file=app/app.component.ts)

**Expected behavior**
The Dropdowns in the Toolbar should be wider (probably the same as in v4 - `12.4em`).

**Screenshots**
![dd-width](https://user-images.githubusercontent.com/7753940/151368355-ae05f3e8-f999-4722-8917-50069f5b35c7.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
I've explained in detail why we'll not handle this issue -- https://github.com/telerik/kendo-themes/pull/3313#issuecomment-1025627606 -- but here is the gist of it:

* default input width is 20 characters, which is close to 10 em;
* even if we increase width, we are not guaranteed to fit, especially in languages like french
* we have the ability for non-wrapped items, which is the way we can and should handle format dropdown
* we can always use shorter labels for the inputs "Font size" and "Font family" vs "Select ..."
* finally, developers could customize the width of the components with inline styles when our guidelines are not wide enough.

Closing.
