### ISSUE TITLE
Undo and redo buttons are not working in kendo.bootstrap v4 theme

### ISSUE THREAD

**Issue by antonmironovv** [telerik/kendo-themes#3356]
**Describe the bug**
Undo and redo buttons for Kendo UI Spreadsheet are not working in kendo.bootstrap v4 theme

**To reproduce**

1. Go to [this dojo example](https://dojo.telerik.com/@anton.mironov/oreYElAt).
1. Make a change to a random cell of the Kendo UI Spreadsheet.
1. Click the Undo button in the top left of the Spreadsheet.

**Expected behavior**
The change of the content in the cell should be discarded.

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for MVC
* Kendo UI for Core

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by Juveniel** [comment]
The referred Dojo example references both the common.css from the Less themes and the Bootstrap Sass theme, thus leading to the observed behavior. Removing the common less stylesheet reference resolved the issue: https://dojo.telerik.com/@Juveniel/iDekuwAQ

Closing as invalid.
