### ISSUE TITLE
Kendo icons alignment in TextArea/TextBox suffix and prefix

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-themes#3364]
**Describe the regression**
The regression was initially described as part of https://github.com/telerik/kendo-themes/issues/3050#issuecomment-1007233840. It is related to a wrong sizing of kendo icons, which are part of suffix/prefix content of the TextArea and TextBox components.

Prior to v5, the themes provided the required CSS styles to size and align the icons accordingly.
<img width="202" alt="Screenshot 2022-01-07 at 10 38 41" src="https://user-images.githubusercontent.com/730205/148516753-85ce332f-2f1e-4806-98a7-e64559c22ffc.png">
<img width="220" alt="Screenshot 2022-01-07 at 10 38 52" src="https://user-images.githubusercontent.com/730205/148516766-e10d8457-5e73-49b6-b17b-b335ecdd4d5d.png">

After v5 those styles are missing, thus icons don't have the required sizing and spacing. The examples are using `kendo-icon` components.
<img width="231" alt="Screenshot 2022-01-07 at 10 39 25" src="https://user-images.githubusercontent.com/730205/148516815-bd299ac9-7d8b-476c-b318-dd5cf7a29522.png">

The same issue is observed when the icons are divided via separator
<img width="74" alt="Screenshot 2022-01-07 at 10 55 39" src="https://user-images.githubusercontent.com/730205/148518646-46fcf68c-b93a-4792-8d4d-b64e3b87a797.png">

**To reproduce**

TextArea - https://stackblitz.com/edit/angular-goisxa?file=app/app.component.ts
TextBox - https://stackblitz.com/edit/angular-zaetgu?file=app/app.component.ts

**Expected behavior**
The alignment and sizing of the icons should behave as prior to v5 i.e. styled by the themes. A suggested workaround is for the component to iterate the prefix/suffix content, look for icons and attach the `k-input-icon` CSS class. However this is problematic, as it would lead to:
- Performance issues
- Problems with the dynamically displayed/hidden prefix/suffix content
- Customer content modified by the component, which should be avoided

The sizing should be addressed from the themes as prior to v5 through the available `k-input-prefix` and `k-input-suffix` CSS classes. 

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular (Prefixes and Suffixes are currently available in Angular only)

**Affected browsers (please remove the unneeded items)**
* All

**Comment by tsvetomir** [comment]
Related https://github.com/telerik/kendo-themes/pull/3366

**Comment by joneff** [comment]
fixed by https://github.com/telerik/kendo-themes/pull/3366
