### ISSUE TITLE
Scheduler's popup action buttons border top missing

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#3367]
With the new styling changes, the Scheduler's popup edit buttons are missing border-top (reported in: https://github.com/telerik/kendo/issues/14462 ). Currently, they are inheriting styles from k-action-buttons which have assigned value 0 for border-width.

**Reproduction**
Open the examples from below and double click on an event to open the popup:

[Old](https://dojo.telerik.com/abuciFej)

![scheduler-popup](https://user-images.githubusercontent.com/45764088/152814457-28554a2e-5925-428f-9865-81b6950c9f89.png)

[New](https://dojo.telerik.com/EmOvOVej)

![scheduler-popup-new](https://user-images.githubusercontent.com/45764088/152814484-3090ae72-9ced-46fd-a462-9c5d0beef08e.png)

**Question**
Shall we add the border-top or it should be kept 0? @ivelina-penkova @telerik/kendo-ux 

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Comment by Juveniel** [comment]
Closed with https://github.com/telerik/kendo-themes/pull/4368, where theme tests are updated with the expected rendering.

We should make sure to use the Dialog/Window action buttons in the Scheduler Add/Edit forms and the top border should be there as well. See: https://github.com/telerik/kendo-themes/blob/develop/tests/_output/default/scheduler/scheduler-edit-dialog.png
