### ISSUE TITLE
Conversational UI "input" area customization

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-themes#3373]
Related AHA item - https://progresssoftware.aha.io/features/KUING2-314
Related UX item - https://github.com/telerik/web-components-ux/issues/449

**Additional context**
Possible FE work might be needed to accommodate the updated design in the Conversational UI component.

**Comment by PaskalevStoyan** [comment]
Closing this item as it is finished with https://github.com/telerik/kendo-angular-conversational-ui/pull/102
