### ISSUE TITLE
Does the kendo-theme-bootstrap build contain the bootstrap css ? 

### ISSUE THREAD

**Issue by smchargue** [telerik/kendo-themes#3396]
I'm probably wrong, but I can't see any indication that https://unpkg.com/@progress/kendo-theme-bootstrap/dist/all.css contains any of the boostrap css code?  Also don't see it in the default build of node_modules\@progress\kendo-theme-bootstrap\scss\index.scss

Is it supposed to?  Or are you just supposed to link and/or build in the bootstrap code yourself?

**Comment by joneff** [comment]
kendo-theme-bootstrap **does not** contain a copy of bootstrap, because bootstrap styles are not a requirement.

Indeed, you (or any developer for that matter) must link and / or build bootstrap yourself.
