### ISSUE TITLE
No vertical scrollbar in TextArea

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#3403]
**Describe the regression**
No vertical scrollbar in TextArea with 5.2.0

**To reproduce**

1. Run the following [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/OqAYupOv)

**Expected behavior**
Vertical scrollbar in TextArea as with 5.1.1 - [Dojo snippet](https://dojo.telerik.com/@Dimitar-Goshev/eMileyak)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-classic

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by epetrow** [comment]
With 5.2.0 classes with !mportant rule have been added e.g !k-overflow-auto, !k-overflow-x-auto, !k-overflow-y-auto.

Refer to this PR -  https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_overflow.scss#L55

@telerik/kendo-react-team Could you please add the new class if you haven't done so already?

**Comment by Dimitar-Goshev** [comment]
@epetrow The issue is resolved from Kendo UI for jQuery site.
