### ISSUE TITLE
Disabled kendoTextBox directive is not styled correctly

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-themes#3410]
**Describe the bug**
kendoTextBox directive does not add k-disabled class when used with formControl.

**To Reproduce**
https://github.com/jvalkeejarvi/kendo-textbox-disabled-bug

**Expected behavior**
Disabled styling is applied to input element

**Screenshots**
![image](https://user-images.githubusercontent.com/3441271/155137621-653d8d7c-c162-446b-babd-623d06110244.png)

**Comment by PaskalevStoyan** [comment]
Transfered to themes repo because its related to the themes.
