### ISSUE TITLE
Unified rendering for the DateRangePicker

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3427]
**Is your feature request related to a problem? Please describe.**

The DateRangePicker in React, Vue, jQuery and Blazor uses floating label containers to position the label on top of the date inputs. However, this looks like a hack as the picker do not provide the animation of the floating label. On the other side, in Angular the component is demonstrated with `label` element (it is not a DateRangePicker component, but a demo). 

https://www.telerik.com/kendo-react-ui/components/dateinputs/daterangepicker/
https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/

``` html
<span class="k-daterangepicker-wrap" style="display: inline-block;">
  <span class="k-floating-label-container">
     <!--> Date Input Rendering<-->   
     <label for="[DATEINPUTID]" class="k-label">Start</label>
  </span>
  <span class="k-floating-label-container">
     <!--> Date Input Rendering<-->   
     <label for="[DATEINPUTID]" class="k-label">Start</label>
  </span>
</span> 
```

**Describe the solution you would like to see implemented**

The purpose of this item is to verify whether the floating label containers are best choice for the rendering of the component. In both scenarios, it will be beneficial to have the approved html in the html package.

**Comment by TeyaVes** [comment]
As discussed with @telerik/kendo-front-end , the correct rendering for the DateRangePicker is:

```
<div class="k-daterangepicker">
    <span class="k-floating-label-container">
        <span class="k-dateinput k-input k-input-solid k-input-md k-rounded-md">
            <input class="k-input-inner" type="text" />
        </span>
        <label for="[DATEINPUTID]" class="k-label">Start</label>
    </span>
    <span class="k-floating-label-container">
        <span class="k-dateinput k-input k-input-solid k-input-md k-rounded-md">
            <input class="k-input-inner" type="text" /> 
        </span>
        <label for="[DATEINPUTID]" class="k-label">End</label>
    </span>
</div>
```

A reference rendering and html helper for this will be created in the kendo-themes repo

**Comment by jivanova** [comment]
//cc @telerik/kendo-theme-reviewers

**Comment by zdravkov** [comment]
Hi 👋 
We currently have the ability to provide a [swapButton](https://www.telerik.com/kendo-vue-ui/components/dateinputs/daterangepicker/reverse/#toc-swapping-start-and-end-dates-in-ranges) or a separation message that is ' ' by default between the DataRangePicker's inputs. Would you please provide the correct rendering for them, too.
Greetings,
Plamen
