### ISSUE TITLE
Review dialog action buttons layout across different components and suites

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#3442]
Currently the dialog action buttons have a different layout across the different components and suites. We should unify these and create a similar layout for the different scenarios and usage.

Below you can find some examples

### Kendo jQuery
![actionbuttons_jquery](https://user-images.githubusercontent.com/45764088/156995046-c719c0e2-b501-4030-ad7b-ce6bcb563d67.png)

- left aligned buttons
- no border top

### Kendo Angular
![actionbuttons_ng](https://user-images.githubusercontent.com/45764088/156995425-82c36765-5fc8-49f0-9a2e-1cf58dcbf174.png)

- stretched buttons
- no delete button
- save button on the right side

### Kendo React

![actionbuttons_react](https://user-images.githubusercontent.com/45764088/156997045-b0c0bc23-9b5d-49fc-844d-59c07d9cfbc7.png)

- stretched buttons
- save button on the left side

### Kendo Blazor

![actionbuttons_blazor](https://user-images.githubusercontent.com/45764088/156996254-492e1c33-0ac7-4c84-b0ca-6b4d30391703.png)

- left aligned buttons
- no border-top
- no delete button
- buttons with icons

**Comment by TeyaVes** [comment]
related to:
https://github.com/telerik/kendo-themes/issues/3367
https://github.com/telerik/kendo/issues/13922

**Comment by Juveniel** [comment]
Closed with https://github.com/telerik/kendo-themes/pull/4368
