### ISSUE TITLE
Add box-shadow to focused inputs

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#345]
Our current implementation for bootstrap theme inputs relies on [v4 alpha](https://v4-alpha.getbootstrap.com/components/forms/#form-controls), where as the current [v4.1](https://getbootstrap.com/docs/4.1/components/forms/#overview) has box-shadow for inputs

**Comment by TeyaVes** [comment]
related to: https://github.com/telerik/kendo-themes/issues/441
