### ISSUE TITLE
Implement corrensponding Sass Swatches for available Less Themes

### ISSUE THREAD

**Issue by nenchef** [telerik/kendo-themes#3506]
As the Kendo UI for jQuery, MVC, and Core are dropping the support for Less Themes, we need to provide the clients with all options for migration. That said, we need to have full parity of existing less themes and their sass swatch correspondence:

The table can be revised here: https://docs.telerik.com/kendo-ui/styles-and-layout/less-themes-migration#how-do-i-know-which-sass-theme-corresponds-to-my-current-less-theme 

//cc @bergenhem @mariaveledinova

**Comment by Juveniel** [comment]
There is already an issue for this in the themes: 

* https://github.com/telerik/kendo-themes/issues/994

The linked documentation is also somewhat not correct and misleading . I would suggest revising the status of the items, as well as adding additional information regarding using different base for the swatches (e.g swatch X will be based on theme Y).

**Comment by Xizario** [comment]
Duplicate item, closed
