### ISSUE TITLE
Create reference rendering for the date selector in the Scheduler component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#3530]
**Is your feature request related to a problem? Please describe.**
The rendering of the Scheduler's date selector is different in the different Kendo suites. This leads to inconsistent visualization of the date selector:
* Kendo UI for Angular:  
![image](https://user-images.githubusercontent.com/41293735/162413146-803435b5-a4e1-4f9c-8a2a-8af57cfe3062.png)
* Kendo UI for Vue:
![image](https://user-images.githubusercontent.com/41293735/162413225-61fa413e-0aac-4105-9de9-4c869a0b3206.png)
* Kendo React: 
![image](https://user-images.githubusercontent.com/41293735/162413322-ebd11144-b9e6-4d02-be2f-2fdbc1719a08.png)

**Describe the solution you would like to see implemented**
A reference rendering for the date selector should be created and implemented in the different suites. 

**Additional context**
The rendering can be checked in the following demos:
- Kendo UI for Agular - https://stackblitz.com/edit/angular-z5swxn?file=app/app.component.ts
- Kendo UI for Vue - https://stackblitz.com/edit/jq1w1f?file=src/main.vue
- Kendo React - https://stackblitz.com/edit/react-qproze?file=app/main.tsx

**Comment by Juveniel** [comment]
resolved with: https://github.com/telerik/kendo-themes/pull/3765
