### ISSUE TITLE
Text of items not visible in MultiSelect - Bootstrap Urban theme

### ISSUE THREAD

**Issue by StoyanGoranov** [telerik/kendo-themes#3534]
**Describe the bug**
The selected items of the MultiSelect in the Bootstrap Urban theme have invisible text

**To reproduce**
1. Open [this Demo](https://demos.telerik.com/kendo-ui/multiselect/index?autoRun=true&theme=bootstrap-urban)
1. Select any item

**Expected behavior**
The selected item should have its text visible

**Screenshots**
![image](https://user-images.githubusercontent.com/35375994/162736559-1c7bfb0d-a2f9-440d-be06-8f8428027bb8.png)

**Affected package **
* theme-bootstrap

**Affected suites **
* Kendo UI for jQuery
* Telerik UI for Blazor

**Affected browsers**
* All

**Comment by StoyanGoranov** [comment]
Also reproducible in the [Default Main Dark](https://demos.telerik.com/kendo-ui/multiselect/index?autoRun=true&theme=default-main-dark) and [Classic Main Dark swatches](https://demos.telerik.com/kendo-ui/multiselect/index?autoRun=true&theme=classic-main-dark)

**Comment by TeyaVes** [comment]
fixed by https://github.com/telerik/kendo-themes/issues/3445 in dark themes, however in the Urban Swatch the issue remains
