### ISSUE TITLE
Revise Multiselect unified rendering

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#3539]
**Is your feature request related to a problem? Please describe.**

During the revision of the accessibility specification for the multiselect component, we found that there are certain limitations to achieve a11y compliance related to the rendering. The issue stems from the chiplist that contains the input and leads to:

- [ ] No proper aria support can be applied to the chiplist. Specifying a role to it would dismiss the input role
- [ ] ChipList navigation is not descriptive enough due to lack of aria support
- [ ] Inability to reuse the ChipList component in the MultiSelect

https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/multiselect/README.md

``` html
<div class="k-input-values k-chip-list k-chip-list-md k-selection-multiple">
        {value}
        <input type={type} class="k-input-inner" value={value} placeholder={placeholder} disabled={disabled} />
</div>
```

**Describe the solution you would like to see implemented**

The best scenario is to have the input positioned outside of the chiplist. So, revision whether this is possible will be beneficial.

``` html
<div class="k-input-values k-chip-list k-chip-list-md k-selection-multiple">
        {value}
</div>
<div class="k-input-container">
        <input type={type} class="k-input-inner" value={value} placeholder={placeholder} disabled={disabled} />
</div>
```

**Additional context**

Existing spec for multiselect: https://github.com/telerik/web-components-ux/blob/master/docs/components/multiselect/aria.md

//cc: @veselints @dtopalov

**Comment by joneff** [comment]
If we commit to dropping IE support, we can handle layout with `display: contents` and the following, or similar markup:

```html
<div class="k-input-values">
    <ChipList></ChipList>
    <input class="k-input-inner" />
</div>

**Comment by jivanova** [comment]
@nenchef what are the plans for IE support drop in jQuery?

**Comment by nenchef** [comment]
@bergenhem plan was to drop the support for R1 2023 if I'm not mistaken.

**Comment by bergenhem** [comment]
R1 2023 was the original target but it may slip to R2 2023 based on the continuous IE support research that myself and @mariaveledinova are doing within our customer base. We have the product survey happening currently, and we'll get another data point in October.

That being said, we have to make sure we give our customers a long enough heads-up and we may be a little late for R1 2023 from that perspective.

Of course, we don't want to hold back a11y compliance or have to create multiple renderings per release just to keep IE support for a few more months. Is the preference to go with rendering that would not be supported in IE?

**Comment by pepinho24** [comment]
Hello all, do have any updates or plans when this issue would be resolved? 
We have the [ChipList for jQuery widget](https://github.com/telerik/kendo/issues/15671) planned for R1 2023 and it would be great to be able to use it in the MultiSelect, given the rendering is improved and compliant.

**Comment by Juveniel** [comment]
@pepinho24 the item is planned for the current iteration in the themes( 2023.1 PI2 ) and this can be seen in [the Front-end Board.](https://github.com/orgs/telerik/projects/72/views/14)

As this will be a breaking change, we will keep the themes implementation in a branch until the last PI and merge it in PI3, thus releasing the change for 2023 R1. Also, this will be done after all teams comply with the new rendering.
