### ISSUE TITLE
Add styles for Drag Handle

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-themes#3551]
Part of https://progresssoftware.aha.io/features/KUING2-154

The idea is to allow customers to drag elements only via dedicated drag handle (instead of dragging the whole element). Rendering, styles (and optionally design) will be needed for this _component_. Currently we have something similar in [the Grid via its drag cell](https://demos.telerik.com/kendo-ui/grid/drag-drop). The current item will allow us to utilize such handle on it's own in multiple scenarios.

Requirements:
- [x] List themes classes that could be reused during implementation i.e. positioning, cursor etc.
- [x] Add new `drag handle` icon
- [x] Improve drag and drop demos design

After syncing this item with @TeyaVes it turns out we have some styles available in the themes, that could potentially be reused here
https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/common/_dragdrop.scss

cc @dtopalov @slavenai

**Comment by TeyaVes** [comment]
The utility classes that can be used for the drag handle would be the following:

### Cursor:
`.k-cursor-move`

### Position:
`.k-pos-absolute` - for absolute positioning in a combination with any of the following:

`.k-top-start`, `..k-top-center`, `.k-top-end`, `.k-middle-start`, `.k-middle-center`, `.k-middle-end`, `.k-bottom-start`, `..k-bottom-center`, `.k-bottom-end` - [Position Utility Classes](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_position.scss)
