### ISSUE TITLE
Implement utility classes for sizing and Elevation(shadows)

### ISSUE THREAD

**Issue by epetrow** [telerik/kendo-themes#3559]
**Is your feature request related to a problem? Please describe.**

Request to implement utility classes for sizing and Elevation(shadow) similar to:

- sizing([PrimeFlex (primefaces.org)](https://www.primefaces.org/primeflex/width) like w-4 with sm to xl variations, with min and max variation
- Elevation(shadows): [PrimeFlex (primefaces.org)](https://www.primefaces.org/primeflex/elevation)

**Additional context**

Originated from  [1562337](https://supportheroes.telerik.com/ticket/1562337)

**Comment by joneff** [comment]
sizing is implemented #3609. shadow should stay put for a while.
