### ISSUE TITLE
Missing gap for grids numeric filter

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-themes#3563]
**Describe the bug**

There is no gap between And/Or operator and number input fields in grid for number fields. Styles are correct for string and date filters.

https://www.telerik.com/kendo-angular-ui/components/grid/

**Screenshots**
![image](https://user-images.githubusercontent.com/3441271/165235875-a3d978cb-b638-4569-a58e-1d6343b220a2.png)

**Browser**
 - OS: Linux Mint 20.3
 - Browser Chrome
 - Version 100

**Comment by PaskalevStoyan** [comment]
Transfering this issue from Kendo Angular public Repo to the Kendo Themes public Monorepo as this is an issue in the Themes.
