### ISSUE TITLE
Spin buttons of NumericTextBox in outline mode have black border in Bootstrap-V4 swatch

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3596]
<img width="111" alt="bootstrap-v2" src="https://user-images.githubusercontent.com/3844466/166952180-02b8f514-ee3f-48d7-a227-b9c6848bb714.PNG">

NumericTextBox class: `k-numerictextbox k-input k-input-outline k-input-md k-rounded-md`

The problem can be replicated with Bootstrap-V4 only

**Comment by NikoPenev21** [comment]
Not replicable anymore.
