### ISSUE TITLE
How to Compile Theme

### ISSUE THREAD

**Issue by smchargue** [telerik/kendo-themes#3597]
I'm trying to setup a basic build process using the page https://github.com/telerik/kendo-themes/wiki/Compiling-themes  
get this right away:
```
C:\kendo.theme>gulp sass
[12:34:00] Using gulpfile C:\kendo.theme\gulpfile.js
[12:34:00] Starting 'sass'...
[12:34:00] 'sass' errored after 13 ms
[12:34:00] TypeError: sass.sync is not a function
```

This a new environment and I've downloaded the LTS of node.js and all the dependencies listed, as far as I can tell. 

I know enough SASS to get done what I need to get done, but gulp issues are completely out of my wheelhouse.  Does anyone have a clearer step by step advise on how to setup an environment to make some modifications to the kendo/bootstrap theme?

**Comment by joneff** [comment]
`sass.sync` should exist. while any issues with gulp and gulp-sass are not strictly part of our forte, I guess we can make an exception. Can you you provide your package.json so I can setup your project locally and see what exactly is the issue.

Also, can you mention the version of node and npm?

**Comment by molequetu** [comment]
Any update on this; getting the same error when following the wiki doc to compile themes, about sass.sync not a function.

package.json
```
"dependencies": {
    "@progress/kendo-theme-bootstrap": "5.5.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.7",
    "gulp": "^4.0.2",
    "gulp-postcss": "^9.0.1",
    "gulp-sass": "^5.1.0",
    "node-sass": "^7.0.1",
    "postcss": "^8.4.14",
    "postcss-calc": "^8.2.4",
    "sass": "^1.53.0"
  }
}
```

node --version
v16.15.1

**Comment by smchargue** [comment]
i got it to compile.   Neither of these lines of code ever worked for me:
```javascript
// Use node sass
sass.compiler = require('node-sass');
// Use dart-sass
// sass.compiler = require('dart-sass');
``` 
This line ended up allowing the compile (transpile) to complete without error 
```javascript
const sass = require('gulp-sass')(require('dart-sass'));
``` 
I honestly have no idea why.  If I understood it, would probably have never posted a question. 

here is my package.json 
```json
{
  "dependencies": {
    "@fortawesome/fontawesome-free": "6.1.1",
    "@progress/kendo-theme-bootstrap": "5.4.1",
    "bootstrap": "5.1.3"
  },
  "devDependencies": {
    "autoprefixer": "10.4.5",
    "dart-sass": "1.25.0",
    "gulp": "4.0.2",
    "gulp-clean-css": "4.3.0",
    "gulp-minify-css": "1.2.4",
    "gulp-postcss": "9.0.1",
    "gulp-rename": "2.0.0",
    "gulp-sass": "5.1.0",
    "postcss-calc": "8.2.4",
    "sass": "1.51.0"
  }
}
```
and my npm version info , if that helps 
```
{
    npm: '8.9.0',
  node: '16.15.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by molequetu** [comment]
@smchargue thank you for your response. Seems you are using dart-sass(https://www.npmjs.com/package/dart-sass) which is deprecated and instead sass library is used. I followed your setup using dart-sass, but cannot still compile, getting an error
`Error: Can't find stylesheet to import.`
Seems it has the problem with the tilde import
Here is my .scss generated from the themebuilder with some customization

// kendo theme builder generated file
$border-radius: 0.25rem;
$dark-theme: false;
$primary: #1ab394;
$secondary: #6c757d;
$info: #17a2b8;
$success: #28a745;
$warning: #ffc107;
$error: #dc3545;
$body-text: #212529;
$body-bg: #ffffff;
$headings-text: #212529;
$subtle-text: #6c757d;
$disabled-text: #8f8f8f;
$component-text: #212529;
$component-bg: #ffffff;
$base-text: #212529;
$base-bg: #f8f9fa;
$hovered-text: #16181b;
$hovered-bg: #e9ecef;
$selected-text: #ffffff;
$selected-bg: #1ab394;
$kendo-button-text: #212529;
$kendo-button-bg: #f3f3f4;
$link-text: #1ab394;
$link-hover-text: #1ab394;

// custom
$font-size: 14px;

```
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/grid/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/treelist/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/combobox/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/numerictextbox/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/multiselect/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/dropdownlist/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/datetimepicker/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/datepicker/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/timepicker/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/maskedtextbox/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/listbox/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/editor/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/dialog/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/window/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/tooltip/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/tabstrip/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/typography/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/utils/_index.scss";
@import "~@progress/kendo-theme-bootstrap/scss/treeview/_index.scss";
```
It cannot import the first import statement(seems cannot find the corresponding path)

Would not know it would be such a hustle to get kendo themes compiled

**Comment by chrisjmccrum** [comment]
Confirming here that I'm experiencing the same issue with vanilla gulp files and only following the wiki guide. Everytime I try to compile with gulp + node-sass I get:

`TypeError: sass.sync is not a function`

**Comment by joneff** [comment]
After numerous on and off this issue, I've found the cause of the issue and it was before me the whole time -- the version of `gulp-sass`. With `gulp-sass` v5 there are some breaking changes -- https://github.com/dlmanning/gulp-sass#migrating-to-version-5.

Our original project, on which the wiki is based was using v4. And while we regularly update the rest of the modules, that module was stuck on v4 for the longest time.

We'll update the wiki to show examples both with `gulp-sass@4` and `gulp-sass@5`.

**Comment by joneff** [comment]
Wiki updated.
