### ISSUE TITLE
Inline Editor transfers words on separate lines after bold

### ISSUE THREAD

**Issue by martintabakov** [telerik/kendo-themes#3657]
**Describe the regression**
If you bold some text in the Inline Editor, the content will be displayed on separate lines

**To reproduce**

1. Open this example - https://dojo.telerik.com/aZAFUzuq/12
2. Type some text, e.g "Some editor text"
3. Bold the "editor" part
**Expected behavior**
The text should remain on a single line.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites
* Kendo UI for jQuery

**Affected browsers**
* All

**Additional context**
**Introduced with 2020.2.617**

**Comment by inikolova** [comment]
I am closing this issue in favor of https://github.com/telerik/kendo-themes/issues/5187
