### ISSUE TITLE
Theme builder bootstrap misses classes for Telerik ui-blazor 3.4.0

### ISSUE THREAD

**Issue by wimbaens** [telerik/kendo-themes#3677]
The Theme Builder for bootstrap is missing classes that are available in the bootstrap built-in theme version 3.4.0.

For example the selection of the grid:

```
.k-grid th.k-state-selected, .k-grid th.k-selected, .k-grid td.k-state-selected, .k-grid td.k-selected, .k-grid tr.k-state-selected > td, .k-grid tr.k-selected > td {
    color: #212529;
    background-color: rgba(13, 110, 253, 0.25);
}
```

Or selection of the pager:

```
.k-pager-numbers .k-link.k-state-selected, .k-pager-numbers .k-link.k-selected {
    border-color: #0d6efd;
    color: white;
    background-color: #0d6efd;
}
```

Those are visible in the Demos and when you use the built-in theme but not with the bootstrap Theme Builder for ui-blazor.

**Comment by TeyaVes** [comment]
The ThemeBuilder is now updated with the latest Kendo Sass themes version and there shouldn't be any discrepancies between the styles of the ThemeBuilder and the demos
