### ISSUE TITLE
Left arrow Icons are not centered in RTL mode in Edge and IE11

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-themes#368]
Appearance in IE:
![image](https://user-images.githubusercontent.com/11771009/46959339-76bb4b00-d0a4-11e8-9898-4bd68450c287.png)

Appearance in Edge:

![image](https://user-images.githubusercontent.com/11771009/46959381-90f52900-d0a4-11e8-9894-00c64a59ed15.png)

**Comment by PreslavKozovski** [comment]
This is caused by the demo styles:
![image](https://user-images.githubusercontent.com/17339722/47004991-79b54a80-d13b-11e8-9659-3f640408a5e0.png)

I opened a new issue for the less themes:
/telerik/kendo#9049
