### ISSUE TITLE
Improve Grid header cell rendering

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#3680]
**Describe the bug**

After the implementation of https://github.com/telerik/k2/issues/280 it turns out that we have different rendering of the th element depending on weather the Grid is sortable or not. This causes issues:

* https://github.com/telerik/kendo-angular/issues/3604
* makes customization difficult (e.g apply custom styling on the th)

**To reproduce**

Inspect the "Unit Price" and "Product Name" rendering in [the following StackBlitz example](https://angular-ni6idy-ohnifh.stackblitz.io).

**Expected behavior**

We should have single rendering regardless of the Grid sorting indicator is rendered or not. Making sure that the cell elements are wrapped in a container (.k-cell-inner) in order for the th elements (text, indicators, menu buttons) to align correctly in all scenarios.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by Juveniel** [comment]
@telerik/kendo-a11y please share your thoughts on this. Ultimately, we would like to use single rendering for the header cells. Are there any accessibility concerns regarding this ? 

The rendering that we are looking into using is the following
```html
<th class="k-header" rowspan="1" colspan="1">
    <span class="k-cell-inner">
        <span class="k-link">
            <span class="k-column-title"> ProductName </span>
            <span class="k-icon k-i-sort-asc-small"></span>
            <span class="k-sort-order">3</span>
        </span>
        <span class="k-sort-status" style="position: absolute; left: -10000px;">Sorted Ascending</span>
    </span>
</th>

Note: class names are taken from latest rendering with sorting and are up for further discussion.
```

**Comment by veselints** [comment]
A few comments on the above:
- we absolutely don't need the `k-sort-status` element which obviously is injected only to be announced by screen readers. When necessary, `th` elements must have an `aria-sort` attribute instead: https://github.com/telerik/web-components-ux/blob/41fa8960f278388e168a112f824a865ff2d510e0/docs/components/grid/aria.json#L182
- what is the purpose of the `k-sort-order` element?

p.s.: if possible, please include examples in CodeSandbox instead of StackBlitz. StackBlitz simply does not work way too often.

**Comment by Juveniel** [comment]
@veselints the sort-order element is used in multi-sort scenarios to denote the order - check [this Grid Demo](https://www.telerik.com/kendo-angular-ui/components/grid/sorting/multi-sort/) and apply sorting on two or more columns.

The questions is - are we OK to use single rendering for the header, even in scenarios when sorting is disabled e.g:
```html
<th class="k-header" rowspan="1" colspan="1">
    <span class="k-cell-inner">
        <span class="k-link">
            <span class="k-column-title"> ProductName </span>
        </span>
    </span>
</th>
```

**Comment by yanmariomenev** [comment]
Some of our clients raised a concern that the Grid shouldn't have `cursor: pointer` set to the headers if there aren't any data manipulation functionalities added to the Grid like sorting.

Here is an example of a basic Grid:
https://www.telerik.com/kendo-angular-ui/components/grid/get-started/

This might confuse the user as there are no actions that can be taken when clicking the column in a basic Grid configuration.
![chrome_4EgJbOSrfW](https://user-images.githubusercontent.com/49076727/206674665-6c9c1017-3a29-496d-8f60-607ab2b7c08d.png)

**Comment by Juveniel** [comment]
Resolved with: https://github.com/telerik/kendo-themes/pull/4031

@yanmariomenev the described issue with the cursor can be solved through triggering a specific class `!k-cursor-default` on the elements based on the Grid component configuration.
