### ISSUE TITLE
Grid Filter menu button pushed up in SASS themes on iOS

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-themes#37]
### Description:
The right margin of the header link is insufficient for the filter menu button's width, which is pushed up a line as a result.
![3d553dad-64c5-4576-b6e2-892fd8b4f0f9_kendofilteralignissue](https://user-images.githubusercontent.com/5155721/36657038-99c9dc2e-1ad3-11e8-97ca-cab668d8a6ed.PNG)

### How to reproduce:
Open [this dojo](https://dojo.telerik.com/iXUzu) on a iOS device.

_Reported in  ticket 1154907_

**Comment by chanaka1** [comment]
happen in kendo.bootstrap-v4 css

**Comment by matanasov** [comment]
Reported again in ticket 1162749

**Comment by gyoshev** [comment]
Fixed with https://github.com/telerik/kendo-themes/commit/bb6fef9bae6771be2bedda65594b7a5a1c4811eb and released in the last few versions of the themes.
