### ISSUE TITLE
DateTimePicker Calendar headers are not aligned correctly

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-themes#3775]
**Describe the bug**

DateTimePicker Calendar headers are not aligned correctly

**To reproduce**

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datetimepicker/

**Expected behavior**

Calendar headers should be stretched so that they align correctly with the columns below.

**Screenshots**

![image](https://user-images.githubusercontent.com/16972160/183026633-13a5c555-1f4d-4753-9f58-82da385d3068.png)

**Affected package (please remove the unneeded items)**

* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**

* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**

* All

**Build system information (please remove the unneeded items)**

* Not Applicable

**Comment by Juveniel** [comment]
related to: https://github.com/telerik/kendo-themes/pull/3734

**Comment by JoomFX** [comment]
It will be fixed in the Kendo Angular Calendar component (instead of in Kendo Themes).
