### ISSUE TITLE
Building version 2.57.1 of the Default theme leads to a SASS compiler error

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#378]
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

![image](https://user-images.githubusercontent.com/7533599/47149220-925c6680-d2db-11e8-857d-08c7ddd94f26.png)

Seems related to:

[https://github.com/sass/sass/issues/1873](https://github.com/sass/sass/issues/1873)

**Comment by joneff** [comment]
The issue is regarding https://github.com/telerik/kendo-themes/blob/1e693f729c261ca986baa2f44397f0708687d34a/packages/default/scss/notification/_layout.scss#L75 and it's a valid issue. The `&` shouldn't be there indeed

**Comment by joneff** [comment]
The issue is regarding https://github.com/telerik/kendo-themes/blob/1e693f729c261ca986baa2f44397f0708687d34a/packages/default/scss/notification/_layout.scss#L75 and it's a valid issue. The `&` shouldn't be there indeed

**Comment by elena-gancheva** [comment]
The issue has been fixed and is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе.

**Comment by elena-gancheva** [comment]
Shipped with `2.58.0` version of the theme.
