### ISSUE TITLE
Missing styles for focused cells in PivotGrid

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-themes#3804]
Example to check: https://stackblitz.com/edit/react-yvlxco?file=app%2Fmain.tsx

React issue: https://progresssoftware.aha.io/requirements/KUIR-295-5
Angular issue: https://progresssoftware.aha.io/requirements/KUING2-267-5

**Comment by dtopalov** [comment]
outline: none is missing, and the Chrome focused styling interfere with ours:

![image](https://user-images.githubusercontent.com/7533599/188200659-bec32a7b-9d91-4924-b098-60af3a9ef7bf.png)

![image](https://user-images.githubusercontent.com/7533599/188200709-06721ca7-9289-4907-b3b6-329c26cb44ce.png)
