### ISSUE TITLE
Kendo combobox and Dropdown conflict with kendo panel bar

### ISSUE THREAD

**Issue by olehvayda** [telerik/kendo-themes#3819]
**Describe the bug**
Kendo ComboBox and DropDownList controls are conflicting with kendo PanelBar. 
If ComboBox or DropDownList control is included inside a kendo PanelBar, the the dropdown elements of both controls are detached from the combobox or dropdownlist inputs respectively.

**To reproduce**
In order to reproduce the behaviour:
1. Create a kendo PanelBar with one item
2. In the previously created panel's bar item create a list
3. Add input value in one of the list items
4. Add ComboBox or DropDownList kendo control to the input
5. Both controls will have detached the dropdown elements
6. You can run the piece of code (additional context section) in dojo to reproduce the issue

**Expected behavior**
ComboBox or DropDownList controls should work correctly and the dropdown elements of controls should not be detached.

**Screenshots**
![image](https://user-images.githubusercontent.com/111047340/184099740-28886976-f014-4c91-a476-72f80ff965ee.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**

```html
<!DOCTYPE html>
<html>
<head>
    <base href="https://demos.telerik.com/kendo-ui/panelbar/index">
    <style>html { font-size: 14px; font-family: Arial, Helvetica, sans-serif; }</style>
    <title></title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.2.802/styles/kendo.default-ocean-blue.min.css" />

    <script src="https://kendo.cdn.telerik.com/2022.2.802/js/jquery.min.js"></script>
    
    
    <script src="https://kendo.cdn.telerik.com/2022.2.802/js/kendo.all.min.js"></script>
    
    

</head>
<body>
    
<div id="example">
    <ul id="panelbar">
        <li>
            Days
            <ul>
                <li><input id="daysInput" placeholder="Select day..." /></li>
            </ul>
        </li>
    </ul>
    <style>
        #panelbar {
            max-width: 400px;
            margin: 0 auto;
        }
        .teamMate h2 {
            font-size: 1.4em;
            font-weight: normal;
            margin-bottom: 0px;
        }
        .teamMate p {
            margin: 0;
        }
        .teamMate img {
            display: inline-block;
            margin: 5px 15px 5px 5px;
            border: 1px solid #ccc;
            border-radius: 50%;
        }
        .details {
            display: inline-block;
            vertical-align: top;
        }
    </style>
    <script>
        $(document).ready(function() {
            $("#panelbar").kendoPanelBar({
                expandMode: "single"
            });
          
          	$("#daysInput").kendoComboBox({
                        dataTextField: "text",
                        dataValueField: "value",
                        dataSource: [
                            { text: "Monday", value: "1" },
                            { text: "Tuesday", value: "2" },
                            { text: "Wednesday", value: "3" },
                            { text: "Thursday", value: "4" },
                          	{ text: "Friday", value: "4" },
                          	{ text: "Saturday", value: "4" },
                          	{ text: "Sunday", value: "4" }
                        ],
                        filter: "contains",
                        suggest: true,
                        index: 3
                    });
        });
    </script>
</div>



</body>
</html>
```

**Comment by joneff** [comment]
That's not an issue of the themes, but rather an option of the kendo-jquery components: by default the popup is appended inside the container of the combobox, but it can be placed elsewhere, by `using options.popup.appendTo`. Here is a and example: https://dojo.telerik.com/@joneff/aCInUHeT.

Since the issue has nothing to do with the themes, I am closing it.
