### ISSUE TITLE
Add styles for grid adaptive rendering

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#384]
The mobile styles we have for the LESS themes are necessary so the Kendo UI Grid can be responsive.

https://docs.telerik.com/kendo-ui/controls/data-management/grid/adaptive

Requested in tickets: 1146171, 1343811, 1146171

Related item: https://github.com/telerik/kendo/issues/9064

**Comment by politigf** [comment]
Until this is resolved, you may want to update [this post](https://www.telerik.com/blogs/getting-started-telerik-ui-for-asp-net-core-and-bootstrap-4) to indicate that users won't have a functional grid on mobile devices!

**Comment by PreslavKozovski** [comment]
Styles are added in https://github.com/telerik/kendo-themes/pull/695
