### ISSUE TITLE
Checkbox stays disabled in Edge

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#385]
When the disabled property of an input, type="checkbox" is bound to a dynamically changing value, and it is supposed to go from "disabled" to not disabled state, this does not happen in Edge (works as expected in Chrome and IE):

[https://stackblitz.com/edit/angular-vtr3ca?file=app/app.component.ts](https://stackblitz.com/edit/angular-vtr3ca?file=app/app.component.ts)

When the checkbox is clicked in its erroneously disabled state, it is working as expected, but initially is rendered as disabled.

Steps to reproduce:

1. Open stackblitz example

2. Select the "Single" radio button

3. The checkboxs stays disabled in Edge (but when clicked is working as expected)

Reported in Ticket ID: 1347583

**Comment by inikolova** [comment]
It appears everything is working as expected now.
