### ISSUE TITLE
Text overlaps icon in IE when dragging a groupable column to the grouping area

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#386]
When the Grid column is not wide enough, the icon overlaps with the column title when dragging the column to the grouping area. The undesired behavior is observed in IE only:

![image](https://user-images.githubusercontent.com/7533599/47481858-9b9a8580-d83d-11e8-9c06-8fbf224daa11.png)

Observable in the[ basic Grid grouping demo](https://www.telerik.com/kendo-angular-ui/components/grid/grouping/#toc-getting-started) from the documentation (try dragging the ID column).

**Comment by PreslavKozovski** [comment]
@tsvetomir 
We can add minimal width to the copied element as suggested here - https://github.com/telerik/kendo-angular-grid/issues/776
However, I believe that a better solution is to dynamically calculate the width of the tooltip based on the content. We have already implemented this enhancement in the jQuery Grid - https://demos.telerik.com/kendo-ui/grid/index

**Comment by inikolova** [comment]
The issue cannot be reproduced any more. Tested with kendo-theme-default": "^4.32.0"

![05 02 2021_14 11 12_REC](https://user-images.githubusercontent.com/1826086/107039698-e6e6c100-67c6-11eb-8c06-ff7b60f39a51.png)
