### ISSUE TITLE
Popover Callout display issue

### ISSUE THREAD

**Issue by michaelmarcuccio** [telerik/kendo-themes#3964]
The callout shows full diamond instead of proper display like it used to.
Most likely caused by recent theme updates.

![image](https://user-images.githubusercontent.com/20432260/190411500-be68dcdd-1367-4543-9d94-a444a7f94f8a.png)

**Comment by PaskalevStoyan** [comment]
I'm transfering this issue as it is related to the Kendo Themes. When the `k-popover-inner` element is not expanded below the `callout` - the callout is not covered and its top / left borders are visible. This can be fixed by adding `height: 100%` to the `k-popover-inner` class.
