### ISSUE TITLE
Menu items don't have padding in Fluent theme

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#3965]
**Describe the bug**
The ContextMenu and Menu list options don't have the required paddings in between using the Fluent theme:

Menu in Fluent theme:
![image](https://user-images.githubusercontent.com/33104481/190620240-14ea0994-7818-4303-abc5-8f45fedeb42b.png)

**To reproduce**
Kendo Angular Menu
https://stackblitz.com/edit/angular-s4zwzi?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Menu with Default ocean:
![image](https://user-images.githubusercontent.com/33104481/190620697-28147c6a-65fc-4d19-b9be-7c72c82b9cb6.png)

**Affected package (please remove the unneeded items)**
* theme-fluent

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue

**Comment by epetrow** [comment]
This is due to a missing sizing class `k-menu-group-md` in the rendering.

Currently it is only present in [jQuery ](https://demos.telerik.com/kendo-ui/menu/index) and the other suites will need to add it at some point.
