### ISSUE TITLE
Allow widget selectors to be styled independently of buttons.

### ISSUE THREAD

**Issue by leniency** [telerik/kendo-themes#398]
Currently the input widget selectors (combobox, date/time pickers, the entire dropdownlist) take the same coloring as secondary buttons.

Can the widget selectors be setup to be styled independently. They can still default to the button colors, but allow a way to change them without changing the buttons.

For example, if the secondary bootstrap color is a dark grey, the entire dropdownlist box is also a dark grey and stands out greatly from the default bootstrap select lists. Or the date picker - the selector stands out a lot - would be nice to tone that down without impacting other styles.

**Comment by joneff** [comment]
Dropdowns are fixed. The rest will follow

**Comment by joneff** [comment]
As of 2020 mid january, the issue is resolved. The following and newer versions include said improvements:

* @progress/kendo-theme-default@4.11.1
* @progress/kendo-theme-bootstrap@4.9.1
* @progress/kendo-theme-material@3.9.1
