### ISSUE TITLE
FloatingActionButton has unnecessary border on Safari and iOS

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#3983]
**Describe the bug**
When the FloatingActionButton is rendered on Safari and iOS an additional outline border is displayed. 

**To reproduce**

1. Go to ['https://demos.telerik.com/kendo-ui/floatingactionbutton/index'](https://demos.telerik.com/kendo-ui/floatingactionbutton/index)

**Expected behavior**
There should bo no additional square border around the FAB

**Screenshots**
![image](https://user-images.githubusercontent.com/14364791/191434128-7161d9ac-5f9b-4a96-9843-946106a98a51.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* Safari

**Build system information (please remove the unneeded items)**
* OS: [Mac]

**Workaroundt**
` .k-fab{
      outline: none;  
  }`

**Comment by kikostadinov** [comment]
This is a browser implementation where Safari's outline styles do not follow the rounded edges of an element.
