### ISSUE TITLE
Enhance Bootstrap forms integration

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#399]
Currently "**input-group-sm**" is not working in conjunction with **kendo-theme-bootstrap**. It would be nice to enhance our Bootstrap forms integration to include it.

Reported in a support thread - Ticket ID: 1131020

Inputs have different heights when in a bootstrap form. Reported in 1491744, **public** in the Blazor Feedback Portal in **1491801**
Sample project : [TelerikBlazorApp1.zip](https://github.com/telerik/kendo-themes/files/5416075/TelerikBlazorApp1.zip)
**Issues**: The textbox (the second input) is 2px taller than the numeric textbox (the first input). Both of them are several pixels taller than the combo box and date picker. The heights vary between the three themes too.
**Goal**: unified heights of the inputs in a bootstrap layout.

**Comment by marin-bratanov** [comment]
Reported for the masked textbox vs textbox too, in 1499726

**Comment by joneff** [comment]
Until our components have consistent rendering, there is not much we can do. There is also the fact that bootstrap form styles are not intended for anything else than an input.

You can see #68 the amount of work required.

**Comment by ntacheva** [comment]
Reported also for DatePicker vs TextBox, in 1503986

**Comment by joneff** [comment]
Sort of an update: with telerik/kendo-themes#2609 we removed all styling enhancements from applying `form-component` to an arbitrary kendo / blazor component for two reasons:

* we are upgrading to bootstrap 5
* we are preparing our own sizing options for components
  * that part requires changes in the rendering the and the classes would no longer make sense

Supporting any arbitrary third-party set of styles / class names within our components is hardly possible, next to impossible.

That is to say: we are not going to support bootstrap's input group class names. Instead, we are going to roll our own sizing system.

I am leaving the issue open, until we roll out at least the styles.
