### ISSUE TITLE
[Filter] row focus class

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#4009]
**Is your feature request related to a problem? Please describe.**
The Filter is a single tab stop component. The currently focused element within the Filter can be any filter row (FilterGroup or FilterExpression) or any of the filter row's focusable elements. Please see the description of the [Filter keyboard navigation spec](https://github.com/telerik/web-components-ux/blob/master/docs/components/filter/keyboard-navigation.md).

For example when a filter row (FilterGroup or FilterExpression) is focused it should look something like:

![1](https://user-images.githubusercontent.com/20015190/193209955-aa6683f8-98af-404f-9ed9-383d2bb1a40b.png)
![2](https://user-images.githubusercontent.com/20015190/193209985-7219fe52-2ecf-4c9f-a749-714f876c8055.png)

The wrapper elements:

- `<div class="k-filter-toolbar-item k-filter-field k-toolbar-item"/>`
- `<div class="k-filter-toolbar-item k-filter-operator k-toolbar-item"/>`
- `<div class="k-filter-toolbar-item k-filter-value k-toolbar-item"/>`

within a filter row (Filter Expression) should be focusable as well:
![4](https://user-images.githubusercontent.com/20015190/193210505-5dfcc6f0-1c5b-4f92-a7cd-8a246924b2b5.png)
![3](https://user-images.githubusercontent.com/20015190/193210160-59982249-8ea0-4af4-a266-05f9caa30888.png)
![5](https://user-images.githubusercontent.com/20015190/193210534-c6418a31-4ec4-41b4-b15f-8b64c0effeb1.png)

To achieve that, I am currently using the `k-toolbar-item` class in the wrapper elements. Please let me know if that is ok or I should use a different class.

**Describe the solution you would like to see implemented**
There should be a class that sets the focus state of the filter rows.

**Comment by JoomFX** [comment]
We discussed the focus state design with @imasyuko and she will add them to the Figma files.

**Comment by imasyuko** [comment]
Hey everyone,
The design files are updated as follows:
- [Default](https://www.figma.com/file/3fta3SPx6nJMPTUcHTKmNI/Telerik-%26-KENDO-UI-Kit-Default-2.2-(UNPUBLISHED)?node-id=8320%3A315274)
- [Bootstrap](https://www.figma.com/file/YjhpzSsYaZI5VOaamsvIku/Telerik-%26-KENDO-UI-Kit-for-Bootstrap-2.2--(UNPUBLISHED)?node-id=4577%3A263204)
- [Material](https://www.figma.com/file/Bun5XXsG0UuzCMz5GyDoHK/Telerik-%26-KENDO-UI-Kit-for-Material-2.2--(UNPUBLISHED)?node-id=4123%3A166617)
- [Fluent](https://www.figma.com/file/ezWHkvf2S0yalmqLQzu6Ed/MS-Fluent?node-id=7%3A145619)
