### ISSUE TITLE
No visual indication applied to selected Scheduler event

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#404]
It is not possible to tell which event is selected, as there is no indication to make it stand out.
Go to [Scheduler / Keyboard support](https://demos.telerik.com/kendo-ui/scheduler/selection) with Default v2/ Bootstrap v4
Click on an event - current appearance:
![image](https://user-images.githubusercontent.com/6614183/33605088-e9eecca4-d9c0-11e7-968e-daad13c5ac77.png)

Expected appearance - highlight similar to LESS themes:
![image](https://user-images.githubusercontent.com/6614183/33605114-05eca778-d9c1-11e7-9694-4ae782187e21.png)

**Comment by TeyaVes** [comment]
Updated designs for focused items in the SASS themes: https://github.com/telerik/kendo-ux-private/issues/9
