### ISSUE TITLE
Appearance issues of Adaptive Scheduler header components

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#405]
[Dojo](http://runner.telerik.io/fullscreen/eSuzIs)
- Today button has NO rounded corners to the right.
- Navigation buttons have inconsistent rounded corners.
- Navigation is not centered.
- Visible content below selected view in views' dropdown.

![image](https://user-images.githubusercontent.com/6614183/33601747-d422b224-d9b5-11e7-8fe0-eb510091b526.png)

**Comment by PreslavKozovski** [comment]
Should be fixed in https://github.com/telerik/kendo-themes/pull/695
