### ISSUE TITLE
Broken Create/Edit event view of Adaptive Scheduler

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#406]
The view for creating or editing an event does not appear correct and it does not respond to any actions.
The issue is reproducible for mobile: "tablet" and mobile: "phone" modes. [Dojo](http://runner.telerik.io/fullscreen/eSuzIs) :

![image](https://user-images.githubusercontent.com/6614183/33601454-f1c2b9b0-d9b4-11e7-85f3-8bc582659251.png)

**Comment by PreslavKozovski** [comment]
Should be fixed in https://github.com/telerik/kendo-themes/pull/695
