### ISSUE TITLE
No scrollbar appears in non resizable textarea with applied kendoTextArea directive

### ISSUE THREAD

**Issue by nchueva** [telerik/kendo-themes#4060]
**Describe the bug**
No scrollbar appears on non resizable textarea with applied kendoTextArea directive

**To reproduce**

- Create a textarea using kendoTextArea directive like:

         <textarea kendoTextArea [value]="textAreaValue"></textarea>

- Prevent textarea's resizing by applying 'resize: none;' in  css
- Set a height to the textarea

==> If content of the textarea is bigger than the height, there is no scrollbar appears anymore.

**Reason of the issue**: 
**.k-input** styles that provide ellipsis for all inputs including textarea where it is not needed:
 

    // Generic input
    .k-input,
    .k-picker {
        ...
        overflow: hidden;
        text-overflow: ellipsis;
        ...
}

*Link to an example*: https://stackblitz.com/edit/angular-dt3bzy?file=src/app/app.component.ts

**Expected behavior**
Scrollbar should appear in non resizable textarea with kendoTextArea directive applied if content is bigger than textarea's height

**Affected package**
* theme-bootstrap

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* All

**Build system information**
* Not Applicable

**Comment by joneff** [comment]
The fix will be available in the next dev version.

**Comment by nchueva** [comment]
thanks a lot 👍
