### ISSUE TITLE
$enable-shadows default value conflicts with the one in Bootstrap

### ISSUE THREAD

**Issue by kikostadinov** [telerik/kendo-themes#4068]
**Describe the bug**
Importing Bootstrap after Kendo-Bootstrap, as advised in Kendo documentation, will set $enable-shadows to true and apply predefined decorative box-shadow styles on Bootstrap components, while $enable-shadows is set to false in Bootstrap by default.

**To reproduce**

1. Create a React project with a Bootstrap input
`<input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">`
3. Import Kendo-Bootstrap and then Bootstrap
4. Inspect the input. There will be the following declaration:
`box-shadow: inset 0 1px 2px rgba(0,0,0,.075);`

**Expected behavior**
The box-shadow should not be present by default.

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
[DEMO](https://stackblitz.com/edit/react-tuq49c-ptaeeu?file=index.scss,app%2Fmain.tsx). Uncomment the the following code to see the expected behaviour:

`// $enable-shadows: false;`

**Comment by joneff** [comment]
Fixed with #4201 -- we now use a [prefixed variable](https://github.com/telerik/kendo-themes/blob/develop/packages/bootstrap/scss/_variables.scss#L9) that can be linked to bootstrap's should customers want to
