### ISSUE TITLE
Wrong appearance and position of Adaptive Scheduler events in Month View

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#407]
Events of Scheduler with **mobile: "phone"** setting are positioned below all time slots in Month View, instead of appearing as dots on the respective time slots - [Dojo](http://runner.telerik.io/fullscreen/eSuzIs) :

![image](https://user-images.githubusercontent.com/6614183/33601034-b9349b6e-d9b3-11e7-868c-3c63b75a8852.png)

**Comment by PreslavKozovski** [comment]
Should be fixed in https://github.com/telerik/kendo-themes/pull/695
