### ISSUE TITLE
Incorrect bottom border when the tabs are Scrollable

### ISSUE THREAD

**Issue by svdimitr** [telerik/kendo-themes#4100]
**Describe the bug**

When a TabStrip component has Scrollable tabs, the focused tab has a bottom border. According to the [design](https://www.figma.com/file/k8eCVo9JZeHZlV9o8SXZtd/Bootstrap-Theme---Internal-Usage?node-id=177%3A44508), there must be no bottom border. 

**To reproduce**

1. Go to any Scrollable Tabs demo, for example, the Blazor: [Scrollable Tabs](https://demos.telerik.com/blazor-ui/tabstrip/scrollable-tabs) ''
1. See that the focused tab has a bottom border.

**Expected behavior**
The focused tab must not have a bottom border when the Scrollable tabs feature is enabled

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
This is a limitation for the longest time. Closing as won't fix
