### ISSUE TITLE
Migrate to the new SASS modules API (@use and @forward instead of @import)

### ISSUE THREAD

**Issue by Harpush** [telerik/kendo-themes#4104]
**Is your feature request related to a problem? Please describe.**
The main motivating "issue" is that `@import` is now deprecated in favor of the new SASS modules API.

**Describe the solution you would like to see implemented**
An API similar to the new material theming API:
```scss
@use '@progress/kendo-theme-*' as kendo-theme;

@include kendo-theme.all-components-themes($options);
@include kendo-theme.dateinput-theme($options);
```

**Describe the alternatives you have considered**
Continue using the deprecated `@import`.

**Additional context**
None

```[tasklist]
### Tasks
- [ ] https://github.com/telerik/kendo-themes/pull/5061
- [ ] https://github.com/telerik/kendo-themes/pull/5053
```

**Comment by joneff** [comment]
Our Fluent theme is based on `@use` instead of `@import`. There were, and still are, many outstanding question, challenges with this syntax. We are threading carefully, because the "old" syntax is still supported.

**Comment by Harpush** [comment]
@joneff  Supported yet deprecated... All that's left is to wait I guess. Is it on the roadmap though?

**Comment by joneff** [comment]
> @joneff Supported yet deprecated... All that's left is to wait I guess. Is it on the roadmap though?

That's not a question I can answer in a politically correct way...

**Comment by goat67** [comment]
Angular 15 will not compile if this is not resolved so it is no longer supported.

**Comment by Roesh** [comment]
> Angular 15 will not compile if this is not resolved so it is no longer supported.

Is it because of this issue: https://stackoverflow.com/questions/70074186/worker-terminated-due-to-reaching-memory-limit-js-heap-out-of-memory

I am running into this as well, I assume the solution would be to revert to Angular V14?

**Comment by joneff** [comment]
`$kendo-color-white` and `$kendo-color-dark` and many many more, are part of v6, not v5. Speaking of v6, I urge you to look at the change log -- https://github.com/telerik/kendo-themes/releases/tag/v6.0.0. This time we made sure it's as humongous as it gets, although we still find it lacking in some areas.

**Comment by joneff** [comment]
> Angular 15 will not compile if this is not resolved so it is no longer supported.

@goat67 by "this", what exactly do you mean? Would it be the '~' imports, because those are fixed with v6?

**Comment by BaHXeLiSiHg** [comment]
I've tried version 6.0.1 and yes, seems like it is compiling. But scss bundle become too large if you want to import style just for few components, like +30 MB oO

With 5.0.x version we have imported styles like this:

```
@import "@progress/kendo-theme-material/dist/variables";
@import "@progress/kendo-theme-material/dist/maskedtextbox";
@import "@progress/kendo-theme-material/dist/editor";
@import "@progress/kendo-theme-material/dist/grid";
```

With 6.0.1 version it became like this (if i'm not wrong):

```
@import "@progress/kendo-theme-material/scss/variables";
@import "@progress/kendo-theme-material/scss/maskedtextbox/index";
@import "@progress/kendo-theme-material/scss/editor/index";
@import "@progress/kendo-theme-material/scss/grid/index";
```

+ styles for grid were not applied...

Somebody else facing same problem with partial styles importing, or am i doing something wrong?

**Comment by joneff** [comment]
@BaHXeLiSiHg #4227 targets the first part (which is utils). We'll followup with icons.

**Comment by Harpush** [comment]
@Juveniel @joneff how does it resolve the issue? Please reopen

**Comment by Juveniel** [comment]
@Harpush the issue was unintentionally closed by automation. 

@BaHXeLiSiHg the bundle size issue is be fixed in [6.0.3](https://github.com/telerik/kendo-themes/releases/tag/v6.0.3)

**Comment by BaHXeLiSiHg** [comment]
@Juveniel 6.0.3 fails to compile with Angular 15, imports starts with "~" throws error "Can't find stylesheet to import." :/

**Comment by joneff** [comment]
Can you specify which file? I am looking at our code and I can't find a single `~` import.

**Comment by BaHXeLiSiHg** [comment]
@joneff I'm so sorry, i just noticed that i was referencing old package from another project (working inside nx workspace), for some reason, package 6.0.3 was not installed...

Yep, with 6.0.3 version everything is compiling and seems like css bundle size is small like it was!

I'm feeling that some styles for grid were not applied and saw that all Kendo packages was updated to version 11.0 (npm repository). Should we update all of the, to match 6.0.3 theming version or it is not necessary?

Grid with material theme:

![image](https://user-images.githubusercontent.com/15612158/213188873-edd5a20c-45db-4ee4-b0ad-dfbe2ba8a704.png)

**Comment by BaHXeLiSiHg** [comment]
Tried to import all styles, hoping that it will fix broken grid styles issue:

```@import "@progress/kendo-theme-material/scss/all";```

But got an error:

![image](https://user-images.githubusercontent.com/15612158/213217386-b6478689-cc9a-42c9-a237-0f1a046d81be.png)

**Comment by Juveniel** [comment]
@BaHXeLiSiHg you should import the theme from the `/dist` folder and also update component packages to latest version.

**Comment by BaHXeLiSiHg** [comment]
@Juveniel importing from dist folder leads to same error...

By the way, after updating packages to the latest version, partial import seem like working, at least components looks normal (few styling fixes was made).

Probably editors component theming issue, applied styles like this:

```
$kendo-base-bg: white;

@import "@progress/kendo-theme-material/scss/variables";
@import "@progress/kendo-theme-material/scss/editor/index";
```

1) Background of editors toolbar controls wasn't changed (inputs + buttons) + background has different shades (inputs vs buttons).

![image](https://user-images.githubusercontent.com/15612158/213657578-c5161b87-1279-40ed-9117-d9c8eafdf7bb.png)

But if i change color, for example to red:

```
$kendo-base-bg: red;

@import "@progress/kendo-theme-material/scss/variables";
@import "@progress/kendo-theme-material/scss/editor/index";
```

2) Background of editors toolbar buttons was changed, but inputs - not.

![image](https://user-images.githubusercontent.com/15612158/213658070-e6aa3b00-9ea3-4fae-ba11-8327baf3edd8.png)

Can not find reason :\

**Comment by BaHXeLiSiHg** [comment]
Another issue about grid:

```
$kendo-color-primary: blue;
$kendo-base-bg: white;

@import "@progress/kendo-theme-material/scss/variables";
@import "@progress/kendo-theme-material/scss/grid/index";
```

1) Group footer borders are doubled (i think it's related to grids css).
2) Disabled color of navigation buttons was overridden by "@progress/kendo-theme-default/scss/pager/_layout.scss" (line 70).

![image](https://user-images.githubusercontent.com/15612158/213660350-56dd4c8a-2727-4e0c-983b-1c95ff543077.png)

3) Text and background colors of paging buttons  was overridden by "@progress/kendo-theme-default/scss/pager/_layout.scss" (line 59).

![image](https://user-images.githubusercontent.com/15612158/213660803-5b10e9d3-ef2c-4a28-b94b-7ffe2c810a6c.png)

Comparison screenshot of version 6.0.3

![image](https://user-images.githubusercontent.com/15612158/213661155-a8cdaf25-b5ed-4353-8757-a2497b99f700.png)

Comparison screenshot of version 5.12.0

![image](https://user-images.githubusercontent.com/15612158/213661321-26db2a0d-a288-4d8c-9019-73ba2d7a2eba.png)

**Comment by Harpush** [comment]
@Juveniel This issue was created for sass modules migration. It has gone off topic. I believe @BaHXeLiSiHg should a different issue.

**Comment by Juveniel** [comment]
@BaHXeLiSiHg, the current issue is related to dart sass 23.0 migration. Thus, please open a separate issue for the Grid Material issues, or alternatively open a product support ticket from [your telerik account](https://www.telerik.com/).

**Comment by Harpush** [comment]
Any news concerning this?

**Comment by Juveniel** [comment]
Hey @Harpush, 

We are working on the internals - integrating and expanding the [core module system](https://github.com/telerik/kendo-themes/pull/4285) that is the base for each theme. This will allow us to gradually migrate all themes and align them with the latest sass spec.

Also, there has been news from the sass team, that the `@import` syntax will still be supported throughout `v2.0.0`. You can read more here:

* https://github.com/sass/sass/issues/3513

Taking the above into consideration, we will try to push for the kendo themes to support both the `@import` and `@use` syntax (this year/early next year) and align with the sass releases for the deprecation.

**Comment by Harpush** [comment]
Hey @Juveniel where is it standing now? It seems to be going in right direction :)

**Comment by Juveniel** [comment]
Hey @Harpush,

We are moving in that direction, yes. We are working on abstracting common chunks in the core package that will enable faster transition to the new syntax. However, we still need to wait for the official announcement from the sass team and evaluate the usage of node-sass. A specific discussion with more concrete information and steps regarding the migration will be created here in the themes repo.

**Comment by Harpush** [comment]
Any news?

**Comment by joneff** [comment]
> Any news?

Yep!

We are beginning with simple code refactoring. More broadly speaking, #5036 is the PR that, when merged, will resolve the issue, but there are myriad of other small tweaks that must be done. We'll update the issue as we go.

**Comment by Harpush** [comment]
Do what's the status?

**Comment by epetrow** [comment]
> Do what's the status?

Hey @Harpush,

We have begun the process of migration to the modern syntax starting with common modules and will gradually continue with each theme.

**Comment by epetrow** [comment]
[v10.0.0](https://github.com/telerik/kendo-themes/releases/tag/v10.0.0) of the Kendo Themes marks the official adoption of the dart-sass implementation. All Kendo UI theme products (including CSS Utilities and Font icons) have been updated to the `@use/@forward` syntax. Below is a short summary of the enchancements that this breaking change brings: 

- Significantly decreased Telerik and Kendo UI themes bundle size.
- Faster compilation for the Telerik and Kendo UI themes.
- Improved capability for future development and maintenance due to the adoption of the Dart Sass module system.
- Resolution of all deprecation warnings during the Telerik and Kendo UI themes compilation.
- Bug fixes and compatibility with the latest Sass language features.
- Enhanced compatibility with modern JavaScript frameworks and build tools (e.g., Webpack, Vite, Next.js), ensuring smooth integration into - modern development workflows.
- Better alignment with CSS specifications, facilitating the creation of future-proof styles.

For more detailed information about the change and how to customize and import the themes, please refer to [our official documentation](https://www.telerik.com/design-system/docs/themes/release-notes/breaking-changes/v10-0-0/).
