### ISSUE TITLE
Provide option for default action alignment

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-themes#411]
Providing a variable that controls whether the primary action is on the left or the right by default allows developers to match the components to the UX guidelines of their application. Adding a variable like `$align-primary-action: left | right;` and taking it into account in dialogs / pickers will make this easier.

**Comment by joneff** [comment]
We can't really do that, or at least not in the themes... This should be decided on per framework basis with sort of a service / provider that reorders buttons depending on platform.

We could, however, have utility classes that deal with alignment. Those will be able to visually reorder things. That will not help with border radius in button groups, but is a step in the right direction. Eventually, when custom props (css vars) are supported enough, we could have it with those as well.

**Comment by joneff** [comment]
Here is an example of OS dependant button ordering https://dojo.telerik.com/@joneff/AMAriXOh
