### ISSUE TITLE
Dropdownlist items not displayed properly in IE when selected/hovered

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#413]
Reproducible in the following example:

[http://plnkr.co/edit/dv5VRXmG77tQprsyXdmh?p=preview](http://plnkr.co/edit/dv5VRXmG77tQprsyXdmh?p=preview)

Set the popup width to 'auto' (optional, if no width is set, other issues are observed).
- An unexpected horizontal scrollbar is rendered.
Scroll horizontal to the right. 
Select or hover the top (longest) item.

Issues: 
When selecting, the long word is cut.
When selecting row, not the whole row gets selected. There is unnecessary space on the right.

Reported in ticket ID: 1122413

**Comment by inikolova** [comment]
After some research, testing and discussion with @joneff , it appears there is no a feasible fix for this case. The possible workarounds which I could suggest are as follows:
	

-  Set **width "_auto_'** to the popup via the **popupSettings** property.

https://www.telerik.com/kendo-angular-ui/components/dropdowns/styling/

Example:
	 https://stackblitz.com/edit/angular-a67qu9-4r7pb1?file=app/app.component.ts

-  Display ellipsis for the long items. Example:
https://stackblitz.com/edit/angular-gyz19v?file=app/app.component.ts
