### ISSUE TITLE
Show multiple visible overlays in nested Layouts scenarios

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#414]
Currently when a Layout is opened from within another Layout, the overlay between the two Layouts is not visible:
[http://plnkr.co/edit/rF2hn1jDxRrYIClsouLM?p=preview](http://plnkr.co/edit/rF2hn1jDxRrYIClsouLM?p=preview)

We should provide a built-in solution, resulting in a better UX similar to the following:
[http://plnkr.co/edit/OBJoucyDjq9cDWffDR6K?p=preview](http://plnkr.co/edit/OBJoucyDjq9cDWffDR6K?p=preview)

**Comment by joneff** [comment]
Fixed by #782
