### ISSUE TITLE
Issues related to 6.0.0

### ISSUE THREAD

**Issue by radkostanev** [telerik/kendo-themes#4218]
### Umbrella for issues related to the latest version of the themes - 6.0.0

- [x] Material theme only - Multi column headers do not have the appropriate border styles
![image](https://user-images.githubusercontent.com/49035696/212287657-8ad552aa-2753-472b-acd7-44418bbc1f57.png)

- [x] Bootstrap theme only - The border-radius of the checkbox is too aggressive in all of its sizes. For example, a checkbox with `k-rounded-md` and `k-input-sm` is practically shaped as a circle. Can be seen in the tests: https://github.com/telerik/kendo-themes/blob/develop/tests/_output/bootstrap/checkbox/checkbox-rounded.png

**Comment by Juveniel** [comment]
- [ ] Grid header new rendering sets `cursor: pointer` by default. However, when the Grid is not sortable, the cursor should be set to `default`.
