### ISSUE TITLE
specifying rem units for $font-size throws error in v2.59.0

### ISSUE THREAD

**Issue by sgordon3** [telerik/kendo-themes#422]
## I'm submitting a...

* Regression report 

## Current behavior

In v 2.59.0 kendo-theme-default, specifying rem units for the $font-size variable generates the following error
      272em*px/rem isn't a valid CSS value.
      in C:\dev\cw.webapp\node_modules\@progress\kendo-theme-default\scss\mixins\core\_math.scss (line 6, column 12)

This does not occur in 2.58.0

## Expected behavior

As in 2.58.0 there should not be error

## Minimal reproduction of the problem with instructions
STEPS TO REPRODUCE
1. Follow the instructions for Using the Build Process of the Application
https://www.telerik.com/kendo-react-ui/components/styling/#toc-using-the-build-process-of-the-application

import the grid.scss
@import '~@progress/kendo-theme-default/scss/grid';

2.  before the import statement set $font-size: 1rem;
3. build the application

## What is the motivation or use case for changing the behavior?
being able to use rem allows the site to set fonts based the root font-size.

## Environment
Product:
* Kendo Ui for React

```

```

Browser:
- Chrome (desktop) Version 70.0.3538.77

System:
- Node version: 10.13.0 npm 6.4.1
- Platform:  Windows

**Comment by maximedupre** [comment]
It seems like I have the same issue:

    ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    $_one: $multiplier * $one;
          ^
      272em*px/rem isn't a valid CSS value.
      in /Users/maximedupre/Desktop/Dropbox/Programming/frontend/node_modules/@progress/kendo-theme-default/scss/mixins/core/_math.scss (line 4, column 12)

**Comment by maximedupre** [comment]
Still not fixed in `v3.1.0`

**Comment by dtopalov** [comment]
Also reported in private support thread:

Ticket ID: 1383654

**Comment by phil-lgr** [comment]
This is the first time in ages that I try to use a so called commercial package for UI.. I follow the docs to customize the theme, gets the same error..

why is this not fixed yet?, it's been opened for a year now

**Comment by phil-lgr** [comment]
I see this error in "@progress/kendo-theme-default": "^4.6.0"

**Comment by joneff** [comment]
#2565 fixes the issue completely (there was an issue with the calendar). Going forward, we'll try not to have reverse engineered font-size based units.
