### ISSUE TITLE
SassError: Index out of range while using kendo-theme-bootstrap v6

### ISSUE THREAD

**Issue by davidyee** [telerik/kendo-themes#4231]
**Describe the bug**
When using @progress/kendo-theme-bootstrap v6 with latest Angular v14.2.12 I get the following error when running ng serve:

```
./src/app/@theme/styles/styles.scss - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Index out of range
    ╷
820 │     @return function-exists( $name );
    │             ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 820:13   k-meta-function-exists()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 7614:19  generate-utils()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 7702:1   @import
  src\app\@theme\styles\styles.scss 6:9                               root stylesheet

./src/app/@theme/styles/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Index out of range
    ╷
820 │     @return function-exists( $name );
    │             ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 820:13   k-meta-function-exists()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 7672:19  generate-utils()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 7771:5   kendo-utils--layout--aspect-ratio()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 8185:5   kendo-utils--layout()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 9689:5   kendo-utils()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 9705:5   @content
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 2174:9   exports()
  node_modules\@progress\kendo-theme-bootstrap\dist\all.scss 9704:1   @import
  src\app\@theme\styles\styles.scss 6:9                               root stylesheet

```

My styles.scss contains the line `@import '@progress/kendo-theme-bootstrap/dist/all';` at line 6 per the error message.

**To reproduce**
Add `@import '@progress/kendo-theme-bootstrap/dist/all';` to your project's styles.scss and reference this styles.scss in the `styles` block of the angular.json (e.g. in the architect:build:styles section).

**Expected behavior**
No scss build error

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: Windows 10 x64
* Node version: 16.18.1
* NPM version: 8.19.2

**Additional context**
Workaround for now is to downgrade to v5 of kendo-theme-bootstrap e.g. v5.10.0

**Comment by Juveniel** [comment]
@davidyee could you take a look at [the following Stacklbitz](https://stackblitz.com/edit/angular-kdsrdk-fgpf8j), where the Bootstrap theme is imported in the styles.scss with no additional modification and update it so that the issue can be reproduced ?

**Comment by davidyee** [comment]
Thanks @Juveniel. I couldn't reproduce it after making similar changes to your StackBlitz which lead me to try adjusting other styling imports in my styles.scss. The error I was receiving turned out to be a false positive caused possibly by conflicts with other style imports.

**Comment by joneff** [comment]
Just a quick update on this issue, an infact any compile issue: you can check with the native compiler to see if it works. We do apply some sort of ... optimization to our process. However, it something does work with the native compiler **as expected**, it's highly unlikely it will not when integrated in our build process or webpack.

```bash
# with @progress/kendo-theme-bootstrap v6.0.3
npx sass ./node_moules/@progress/kendo-theme-bootstrap/dist/all.scss ./dist/all.css
```

yields a single warning about slash division and compiles correctly, so you shouldn't get more than that when compiling with any other tool.
