### ISSUE TITLE
mixin spacing utiliti missing !important

### ISSUE THREAD

**Issue by Ketec** [telerik/kendo-themes#4234]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25903372/213703694-94ccc4a3-5bae-4dcb-a9fb-b0094e89e95b.png)

Switching to v6 of the theme, the !important has gone missing from the utility spacing classes.
Compared to v5
![image](https://user-images.githubusercontent.com/25903372/213703947-e0daaaa1-134b-4a45-bc80-f9d912afb759.png)

$kendo-important has the default value of true.

My theme import format etc has not changed:
"custom variables, colors"
"dist/all.scss"
"custom additional overrides for edge cases"

**Comment by joneff** [comment]
There is a really quick answer to your question, but I will go to lengths never the less:

Initially, we didn't have a strategy on what was `!important` and what was not: some utils had it, some didn't. To make matters worse, sometimes we needed a certain utility to be not `!important` so it could be overridden. We tried different versions, like suffixing with `-f` for force, but that didn't feel right.

Also, it really depends where the styles are declared...

Finally, we came up with our current solution, which will answer your question -- to prefix utility class names with `!` when the `!important` flag is needed. In other words use `!k-mr-4`.

Here is a really quick example that shows everything in action -- https://dojo.telerik.com/@joneff/oJaxIbuh.

There is a bullet in our change log -- "use utility class names from utils package". I suppose we could have been more clear what that meant -- streamline utility class names by prefixing them with `!` to denote `!important` flag.
