### ISSUE TITLE
Grid: Extensive UI change in kendo-theme-bootstrap in version @6.x

### ISSUE THREAD

**Issue by dettner** [telerik/kendo-themes#4244]
**Describe the bug**
I am using Sass and @progress/kendo-theme-bootstrap. 

Also using bootstrap@5.2.3.

My adaptations (Sass variables) are in 98% of the cases in Bootstrap. My only kendo variable adaptions are series colors: `$series-a` etc. 

I upgraded kendo-theme-bootstrap from
 from 5.12.0
 to 6.0.3

I noticed that `$series-a` had changed names to `$kendo-series-a`. (I didn't find clear documentation about this. Perhaps I wasn't looking good enough.) But the generated Kendo Grids look very different. A customer described them like this: "my eyes bleed". I don't know about that - but they have really changed, and I have yet to find a person that prefers the new look. Maybe I did something wrong?

Please see screenshot below.

**To reproduce**

1. Use @progress/kendo-theme-bootstrap **@5.12.0**
2. Observe the generated grids in any browser
3. Upgrade to @progress/kendo-theme-bootstrap **@6.0.3**
4. Observe the UI differences to the kendo Grids

**Expected behavior**
I expected any UI changes to be minor, and to be somewhat inline with how the tables look in "default" Bootstrap.

**Screenshots**
![themechange](https://user-images.githubusercontent.com/9929907/214524558-51da5d45-64a2-41bc-855b-5759e2c90083.png)

**Affected package**
* theme-bootstrap

**Affected suites**
* Kendo UI for jQuery
* Kendo UI for ASP.NET Core
* Haven't tested other suites

**Affected browsers**
* All

**Build system information**
* Not Applicable

**Additional context**
Thanks,

**Comment by joneff** [comment]
Just a quick note on the documentation -- here is mostly (99%) complete changelog of all the changes in v6 https://github.com/telerik/kendo-themes/releases/tag/v6.0.0

As for the grid, v6 it's not yet usable with kendo-jquery components: we made significant improvements in the grid, including, but not limited to sizes. That part has not yet been implemented in kendo-jquery. That's a bit hidden in the documentation -- https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes/compatibility -- KendoUI for jQuery 2023 R1 works with v5.10.0 of the themes.

**Comment by dettner** [comment]
Oh, I see.

Thank you for this!

I will check the links you provided, before trying to upgrade next time. 

Best regards,
