### ISSUE TITLE
TextBoxDirective is missing the ripple effect and has a smaller bottom border size

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-themes#4279]
**Describe the bug**
The applied TextBoxDirective styling is missing the ripple effect and has a smaller bottom border compared to the TextBox component.

**To reproduce**

1. Go to https://stackblitz.com/edit/angular-vowvzv?file=src%2Fapp%2Fapp.component.ts
1. Focus on each input field to see the differences.

**Screenshots**
![chrome_U3h5zGiVG1](https://user-images.githubusercontent.com/49076727/218043850-6cf7f9b7-92ac-4202-8fa9-f3cc2d187b53.gif)

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Comment by joneff** [comment]
We use `::after` to create the ripple. The ripple is missing in the directive, because it's a simple input element and per spec, input elements, other than checkbox and radio, do not have `::before` or `::after`.
