### ISSUE TITLE
Add a possibility to have color variant per widget

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#4283]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to set primary/secondary/tertiary colors per widget. Currently, the swatch or the color could not be set per component. 

**Describe the alternatives you have considered**
We created a Mixin which will import the required property names and then accept the primary/secondary/tertiary palette names, and apply contrast and light/dark theme arguments. It will then go and configure the colors used for the widget in exactly the same way it is currently set up inside the dist/all.scss file. It emulates the proper/default way of applying styles but can be done to override the SASS properties.

@mixin set-panelbar-swatch( $primary-palette-name: indigo, $secondary-palette-name: pink, $tertiary-palette-name: teal, $adjust-contrast: true, $theme-type: light ) {
  
  $primary-palette: material-palette( $primary-palette-name, 500, 300, 700, $adjust-contrast );
  $secondary-palette: material-palette( $secondary-palette-name, 500, 300, 700, $adjust-contrast );
  $tertiary-palette: material-palette( $tertiary-palette-name, 500, 300, 700, $adjust-contrast );
  
  $theme: material-theme(
      $primary-palette,
      $secondary-palette,
      $theme-type
  );
  //@debug "primary-palette-name: #{$primary-palette-name}";
  //@debug "secondary-palette-name: #{$secondary-palette-name}";

  //@debug "$kendo-color-secondary: #{material-color( $secondary-palette, main )}";

// Theme colors
  /// The color that focuses the user attention.
  /// Used for primary buttons and for elements of primary importance across the theme.
  /// @group color-system
  /// @type Color
  $kendo-color-primary: material-color( $primary-palette, main );
  $kendo-color-primary-lighter: material-color( $primary-palette, lighter );
  $kendo-color-primary-darker: material-color( $primary-palette, darker );

More detail can be found in ticket ID: **1596823**

**Comment by joneff** [comment]
This will be solved when we introduce the color system for all themes and components

**Comment by epetrow** [comment]
I am closing this, since the Color system has been introduced and is available for a while now.
