### ISSUE TITLE
Implement Material for AutocompleteBox - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#43]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
![image](https://user-images.githubusercontent.com/6614183/37089691-203e5a54-220a-11e8-8101-23eb111be0d4.png)
- [ ] Unexpected rounded corners at the end of the bottom border.
- [ ] Bottom border width should become 2px on hover
- [ ] Bottom border of disabled AutoComplete is not dotted
- [ ] No focus indicator for focused dropdown item

**Comment by mvgmvg** [comment]
Waiting for design for grouping implementation to finish the issue.

**Comment by Dimitar-Goshev** [comment]
- [ ] Grouping header is not all caps and it should be higher than other items - design:
![image](https://user-images.githubusercontent.com/6614183/38561289-55e040dc-3ce0-11e8-9055-2e7c3655e19a.png)
- [ ] RTL - Loading icon is not on the left:
![image](https://user-images.githubusercontent.com/6614183/38564851-a386b80e-3ce8-11e8-80bc-99a11a3cd24f.png)

**Comment by Dimitar-Goshev** [comment]
- [ ] Group tags are not swapped in RTL (All SASS themes):
![image](https://user-images.githubusercontent.com/6614183/38567380-bb422c5c-3cee-11e8-8dc9-34d21d9e5e4b.png)

**Comment by Dimitar-Goshev** [comment]
- Wrong padding of Group header in RTL:
![image](https://user-images.githubusercontent.com/6614183/39121366-1bbaaa04-46fa-11e8-96f2-1e76d6102dc9.png)
NOTE: Not reproducible in all cases, e.g. on the demo it is reproducible, if you type a, but not reproducible, if you type z.

**Comment by mvgmvg** [comment]
This is JavaScript issue not related to implementing the Material theme. I have logged the issue here https://github.com/telerik/kendo/issues/8415
