### ISSUE TITLE
MVVM Upload input is wrapped by '.k-upload-button' but sass defines '.k-upload-button-wrap'.

### ISSUE THREAD

**Issue by chriseaton** [telerik/kendo-themes#4302]
**Describe the bug**
Using `@progress/kendo-theme-default` v6.1.0. and `@progress/kendo-ui` v2023.1.117 - both the most recent versions.

in `upload/_layout.scss` the class '.k-upload-button-wrap` helps stretch/hide the actual upload input, but it's class is not correct for the generated widget. It uses '.k-upload-button' there is no '-wrap'. 

**To reproduce**
Use the packages above and simply use
```
<input name="files" id="file"
       type="file"
       data-role="upload"
       autocomplete="off" />
````
```
 kendo.init($('#file'));
```
notice the browser default input is not styled
![image](https://user-images.githubusercontent.com/5247568/219824534-437c5353-31fd-489c-9bff-b8508654ff58.png)
and the wrapper class in the scss is not used:
![image](https://user-images.githubusercontent.com/5247568/219824561-819bbd8a-7d1f-465b-a9f0-f0f31275d016.png)

**Expected behavior**
Either the widget needs to be setting the class "k-upload-button-wrap" or the scss needs to be updated to just use "k-upload-button" to adjust the input style.

**Screenshots**
Attached above.

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: Linux
* Node version: 18.14
* NPM version: 9.5

**Additional context**
none

**Comment by Juveniel** [comment]
This is fixed in Kendo jQuery `2023.1.314`. Here is a link to the updated demos: https://demos.telerik.com/kendo-ui/upload/mvvm
