### ISSUE TITLE
In a Grid with at least one locked column, selecting a row makes the text of the cell that is under the locked column overlap with the text above

### ISSUE THREAD

**Issue by xristianstefanov** [telerik/kendo-themes#4309]
**Describe the regression**
As of version **6.0.3**, there is a translucent background color ("**rgba(255, 99, 88, 0.25);**") on the Grid selected cell in a locked column, which makes the text on the cell that is under the locked column to overlap the original text. This appears only for the non-alt rows.

Reported in: 1598527.

**To reproduce**

1. Go to '[this REPL link](https://blazorrepl.telerik.com/wRYwmwFP541oBDRp23)'
1. Lock the "Name" column
1. Resize the "Title" column so a horizontal scrollbar appears
1. Scroll to the left

**Expected behavior**
The expected result is that the text of a cell that is under a locked column is hidden.

**Screenshots**
Here is a video of the reproduction:
![themes-repro](https://user-images.githubusercontent.com/72554148/220614089-531a2377-f247-4cac-b349-538bce39b91d.gif)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the regression problem.

**Comment by xristianstefanov** [comment]
Two more tickets about the same issue:

- 1603613
- 1603063

**Comment by cnp5** [comment]
I think that the issue is still present in other than the default theme. I think it should also be resolved in all affected themes before marking it as "closed".

**Comment by epetrow** [comment]
@cnp5 Indeed you are correct and the following [PR](https://github.com/telerik/kendo-themes/pull/4428) should resolve the issue across all themes, not just Default and Fluent. Please accept my apologies in case this has caused any inconvenience.
