### ISSUE TITLE
TreeList / Unable to set alternate row background w/ variable

### ISSUE THREAD

**Issue by shieldsjared** [telerik/kendo-themes#4345]
Unable to set background color of alternating rows of TreeList component.

Attempted to use both `$kendo-table-alt-row-bg` and `$kendo-grid-alt-bg`, but neither have any impact on a treelist's alternate rows. Not sure if this is deliberate or not, but my guess is that it's not deliberate since there are no `*-treelist-*` variables _documented_.

Bug exists in v6.2.0 of the default theme.

Appreciate the help!

**Comment by inikolova** [comment]
Kendo UI TreeList uses the Grid component styling, therefore there are not *-treelist-* specific variable. I tested Kendo UI Default theme v6.2.0 and was able to customize the TreeList alternate row background through both $kendo-table-alt-row-bg and $kendo-grid-alt-bg. Please make sure that you are importing the theme when you are finished with the variables customization:
https://www.telerik.com/design-system/docs/themes/customization/
