### ISSUE TITLE
k-resize both, horizontal, vertical and none are no longer available

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-themes#4361]
**Describe the bug**
k-resize both, horizontal, vertical and none are no longer available

**To reproduce**
https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/

1. Go to [Setting the Resize Directions](https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/#toc-setting-the-resize-directions)
Classes that are used for resizing are no longer working

**Expected behavior**
Classes k-resize both, horizontal, vertical and none are applying the needed styles

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for Vue

**Comment by zdravkov** [comment]
Reported once again in ticket: 1643617. Can we increase the priority of this one?

**Comment by inikolova** [comment]
The classes for resizing are as follows **k-resize**, **k-resize-none**, **k-resize-x** and **k-resize-y.** All of them are working as expected - https://www.telerik.com/kendo-angular-ui/components/inputs/textarea/sizing/
