### ISSUE TITLE
Add outer group header to selects

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#438]
Since the limitation caused by the virtualization does not apply for angular and react, we could have outer group header:

Default theme: https://github.com/telerik/kendo-ux/blob/master/themes/default/dropdowns.psd
Material theme: https://github.com/telerik/kendo-ux/blob/master/themes/material/dropdowns.psd

Top group header should be bold to separate it from the list items.

**Comment by tapopov** [comment]
This is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе.

**Comment by tapopov** [comment]
Available in @progress/kendo-theme-default@3.3.0
