### ISSUE TITLE
Grid header text overlaps with the column menu icon

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#4388]
**Describe the bug**
Overlap of the header text and the menu button icon.

**To reproduce**

1. Go to https://netcorerepl.telerik.com/cxOIEKvo35Ol98ts16
1. Run the example and reduce the size of the right pane. 
1. At a smaller column width, the header text overlaps with the menu button icon.

**Expected behavior**
No overlapping should occur. Check the difference in behavior, when the **.Sortable()** option in the Grid is uncommented.

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Telerik UI for MVC
* Telerik UI for Core

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by epetrow** [comment]
@IvanDanchev The rendering of the Grid Header needs to be updated as specified [here](https://github.com/telerik/kendo-themes/issues/4004).

The default rendering of the header cell should be the following: 

```html
<th class="k-header">
    <span class="k-cell-inner">
        <span class="k-link">
            <span class="k-column-title"> ProductName </span>
        </span>
    </span>
</th>
```
