### ISSUE TITLE
Loading icon changes height of DropDownList in Bootstrap theme

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#4396]
**Describe the bug**
The loading icon increases the height of the Kendo UI for Angular DropDownList using Material or Bootstap theme:

![image](https://user-images.githubusercontent.com/33104481/231436293-682bc0d2-205f-4aa0-a19a-03083836956d.png)

https://stackblitz.com/edit/angular-tgyjby-gqvn8n

When using the Default theme, the height is the same:

![image](https://user-images.githubusercontent.com/33104481/231436511-89e3f688-16b7-4634-a29d-4bf8ccafdd19.png)

https://stackblitz.com/edit/angular-tgyjby-tch6y5

Could be related to https://github.com/telerik/kendo-themes/issues/3655

**Comment by inikolova** [comment]
The issue can be observed in all themes, when using "_medium_" and "_large_" [DropDownList sizes](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/appearance/#toc-size)

**Comment by inikolova** [comment]
After further investigation it appears the DDL rendering does not follow the specification [here](https://github.com/telerik/kendo-themes/issues/2802). I logged [an item](https://github.com/telerik/kendo-angular-private/issues/840) for updating the DDL rendering - its implementation will resolve this issue.
