### ISSUE TITLE
In Grid with German localization, the buttons of the Columns option in the ColumnMenu overflow the menu

### ISSUE THREAD

**Issue by xristianstefanov** [telerik/kendo-themes#4402]
**Describe the bug**
When using Grid with German localization or a language with longer words, the buttons of the Columns option in its ColumnMenu overflow the menu due to fixed width.

Reported in: 1605902.

**To reproduce**

1. Open this project: [repro-LocalizationOverflowColumnMenuTest.zip](https://github.com/telerik/kendo-themes/files/11283569/repro-LocalizationOverflowColumnMenuTest.zip).
2. Switch the language to German from the dropdown in the right corner.
1. Click the column menu of one of the columns (using the three dots at the right corner of the column).
1. Choose "Columns" from the menu.
1. See the right button.

**Expected behavior**
The buttons of that option should not overflow the menu.

**Screenshots**
![ColumnMenuThemesBug](https://user-images.githubusercontent.com/72554148/233293347-dae752f8-a178-4a9e-93e3-822315de5f4c.PNG)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
* Not Applicable
* Firefox version: [for example, 72, lts]
* Chrome version: [for example, 80]
* Edge version: [for example, 80]
* Safari version: [for example, 13]
* IE version: [for example, 11]

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Comment by Juveniel** [comment]
@xristianstefanov in addition to the improvement that we will introduce in the themes (setting `min-width` and `max-width` based on guidelines from the design team), it is also a good idea to introduce a `width` option for the ColumnMenu component that allows to modify the default. Note: this option should set both `width` and `max-width` to successfully apply the change.

//cc @Raisolution, @radkostanev, @ag-petrov, @jivanova
