### ISSUE TITLE
An error occurs when attempting to import the Kendo Theme using a CSS class.

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-themes#4407]
**Describe the bug**
The error is thrown when building the application. It can be avoided when going to the `node_modules\@progress\kendo-theme-material\dist\all.scss` and resaving (ctrl + s) the file on line 32191.
![Code_HsZARW2fbR](https://user-images.githubusercontent.com/49076727/233598982-b631e6e4-ee65-4e9f-a76d-6622dfe38fc7.png)

This behavior is indeed strange and is also discussed in the following forum thread:
https://www.telerik.com/forums/angular-compile-error-after-upgrading-kendo-theme-default-to-6-1-0

**To reproduce**
[scoped-project.zip](https://github.com/telerik/kendo-themes/files/11294267/scoped-project.zip)
Extract the project and use `npm install` in the root folder. Afterward `ng s` to run the project and see the error in the console.

**Screenshots**
![Code_bErQE6IkCl](https://user-images.githubusercontent.com/49076727/233598691-7a2996f8-65ac-4b1f-b2c0-08849e43bd8b.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Build system information (please remove the unneeded items)**
* OS: [Windows]
* Node version: [16.13.2]

**Comment by epetrow** [comment]
With the adoption of the dart-sass module system this issue is no longer relevant. Currently the described behaviour can be achieved in two ways:

- using `@import` syntax (comes with a deprecation warning as support for this feature will be dropped with 3.0.0)
```scss
.dark-theme {
  @import "@progress/kendo-theme-material/dist/all.scss";
}
```
- using `@use` syntax (this would be the preferred way)
```scss
@use "sass:meta";

.dark-theme {
  // This is required since @use rules are not allowed inside classes
  @include meta.load-css("@progress/kendo-theme-material/dist/all.scss");
}
```
