### ISSUE TITLE
Update kendo-theme-bootstrap to match bootstrap 4.4.1

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#441]
As visible from this dojo -- https://dojo.telerik.com/aVoXaniW -- there is a slight difference between kendo-theme-bootstrap and bootstrap framework. More specifically, the border of the input and the focused shadow.

We need to update those.

Possibly related to #399, #273, #68.

**Comment by joneff** [comment]
Note: `$input-border-color` is changed to `$gray-400` from transparent black. As such we need to change the background-color of the buttons to `$gray-400` as well. Current value for button background is `$gray-200`.

**Comment by alexandrejobin** [comment]
I thought that the kendo-boostrap4 styling was based on a sass file that had a one-to-one mapping with the bootstrap sass variables. So in theory, we just have to refresh the kendo theme?

**Comment by joneff** [comment]
@alexandrejobin that's not entirely the case. Certain variables are too dark to be used directly so we override them. The said button background is too dark to be used directly, since we depend on button background for many of our variables. Or sometimes there is no color / the color is used with transparency and we need a solid color.

In few cases, mostly regarding spacing, bootstrap uses a single value for x and y coordinate, where as we almost always use two variables: one for x and one for y coordinate.

The rest of the variables are almost a direct map.
