### ISSUE TITLE
Wrong Switch animation in Material

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#442]
## I'm submitting a...
* Bug report
Switch does not render animation properly in Material theme.

## Current behavior
Circle of ON switch is NOT to the right end of the widget
![image](https://user-images.githubusercontent.com/6614183/48465806-b5037180-e7ec-11e8-8e4a-71360512df13.png)

## Expected behavior
Circle of ON switch is to the right end of the widget as with all other themes, such as Default
![image](https://user-images.githubusercontent.com/6614183/48465851-d3696d00-e7ec-11e8-86bc-32873be022eb.png)

## Minimal reproduction of the problem with instructions
Run the Switch [Index demo](https://demos.telerik.com/kendo-ui/switch/index) with SASS Material theme. Try to switch on/off the widget. The circle will not move all the way to the right.

## Environment
Product:
* Kendo Ui for jQuery - 2018.3.1017

Browser:
- Chrome (desktop) version 70
- Firefox version 62
- Edge version 40

System:
- Platform: Windows

**Comment by Alex-Bubblemaster** [comment]
Reported in ticket with ID: 1381586

**Comment by PreslavKozovski** [comment]
fixed with https://github.com/telerik/kendo-themes/pull/458
