### ISSUE TITLE
There is an additional white space in the switch handler

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#444]
There is a white space between the switch handler border and the filling gradient

![screen shot 2018-11-14 at 5 18 28 pm](https://user-images.githubusercontent.com/16577622/48492572-c1122200-e832-11e8-902b-804fb3018666.png)

**Comment by elena-gancheva** [comment]
The fix is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе.
