### ISSUE TITLE
The data in a frozen Grid column is not aligned with the column header

### ISSUE THREAD

**Issue by mihaela-lukanova** [telerik/kendo-themes#4450]
**Describe the regression**

When the value of a cell in a frozen grid column is longer than the column width, the column and its header are not aligned.

**To reproduce**

1. Open [this Dojo sample](https://dojo.telerik.com/AfICAnOz)
1. Edit any value in column "ProductName".

**Expected behavior**
The column should be aligned with its header.

**Screenshots**
![image](https://user-images.githubusercontent.com/79098346/235470600-3c7eac4c-62ba-41fb-b346-e1c4d648e936.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Additional context**
The frozen column and its header are aligned correctly in version 2023.1.117: https://dojo.telerik.com/ekOmawiT
Possible workaround:
```
.k-grid-content table,.k-grid-content-locked table {
    table-layout: fixed
}
```

**Comment by inikolova** [comment]
I tested the provided example with the latest official version and it appears everything is rendered correctly - https://dojo.telerik.com/qrrusAoM. Therefore I am closing this issue
