### ISSUE TITLE
Map Sass variables to CSS custom properties

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/kendo-themes#4452]
**Is your feature request related to a problem? Please describe.**

I feel that it would be useful to have CSS custom properties of Kendo theme variables. It would help users who aren't using Sass integrate Kendo with non-UI elements. In addition, it would allow better scaffolding of templates. 

For example, we currently have 4 templates for Blazor users to get started, each have theme issues. The current experience only works with the default themes, and completely breaks with some theme options (i.e. dark themes). Below are screen captures of the File > New Project experience.

The CRUD template is selected.

<img width="677" alt="2023-05-01_11-30-29" src="https://user-images.githubusercontent.com/945168/235478937-75d60e35-d2bc-43a5-99de-60100014ecbd.png">

The Material Lime Dark theme swatch is selected.

<img width="677" alt="2023-05-01_11-31-08" src="https://user-images.githubusercontent.com/945168/235478967-f0e9e18c-5833-4786-8d13-1c34e42996b3.png">

Running the app shows a broken UI.  The menu is completely unreadable with white elements on white background. The anchors do not match the theme (blue vs. lime). 

<img width="1158" alt="2023-05-01_11-29-33" src="https://user-images.githubusercontent.com/945168/235478995-65403d5b-8a58-4f53-b23a-591d57f09264.png">

**Describe the solution you would like to see implemented**

If we could export the variables as CSS, interoperability with non-UI elements would be much easier. This would make our templates much simpler to automate. Below is a sample of the mapping.

```css
--kendo-border-radius: $kendo-border-radius;
--kendo-color-primary: $kendo-color-primary;
--kendo-color-secondary: $kendo-color-secondary;
--kendo-body-bg: $kendo-body-bg;
--kendo-link-text: $kendo-link-text;
--kendo-link-hover-text: $kendo-link-hover-text;

...more base theme vars
```

With the variables exported the templates can utilize some of the theme colors.

```
.top-bar { background-color: var(--kendo-body-bg) }
a { color: var(--kendo-link-text) }
a:hover {color: var(--kendo-link-hover-text) }
```

**Describe the alternatives you have considered**

Reuse of `.k-*` classes is a viable alternative but is frowned upon per [our own guidelines](https://www.telerik.com/design-system/docs/foundation/design-tokens/usage/).

**Summary**

Access to CSS custom properties would allow further customization for non-Sass users and fix template issues.

**Comment by epetrow** [comment]
With the addition of the Color system, Spacing, Radii, Elevation and Typography modules we have exposed the necessary CSS custom properties to enable runtime customization, so I am closing this thread.
