### ISSUE TITLE
Grid, Mobile Mode, Column Settings, Title Not Correct

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-themes#4467]
**Describe the regression**
Hi,
i use kendo grid mobile mode in android and click Column Settings Title Not Correct

```javascript
$("#grid").kendoGrid({
   mobile: true,
});
```

**To reproduce**
1. open chrome in android
2. go to [Dojo](https://dojo.telerik.com/@vzsoft/uboREToq)
3. Run Code
4. Click (...) "Column Settings"

**Screenshots**
![Column Settings Title Not Correct](https://user-images.githubusercontent.com/5305981/236042833-5de625fc-5164-45ec-9c61-48425b72a17a.jpg)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: [Android]

**Comment by TeyaVes** [comment]
Hello @vzsoft ,

The reported issue is fixed in the latest version of **Kendo jQuery - v. 2024.4.1112** and **Kendo themes v.10.0.1**
 
Here is a Dojo showcasing it: [https://dojo.telerik.com/aWNlTcrI](https://dojo.telerik.com/aWNlTcrI)

Thus, I am closing this regression for now.
