### ISSUE TITLE
Themebuilder BorderRadius

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-themes#447]
Hi,

could you add the option to set the BorderRadius in the Themebuilder, that would be cool.
like:

    $border-radius:  0px;   
    $border-radius-lg: 0px;
    $border-radius-sm: 0px;

**Comment by boyandim** [comment]
The border-radius editor will use a Kendo UI NumericTextBox to display the current border-radius value and will allow the end user to modify that value.  The end user will be able to change the numeric value, but the unit of measurement will remain same. The entire value (numeric and unit of measurement) will be displayed as formatted value for the editor when it is not focused.
