### ISSUE TITLE
Typography: `k-{element}` styles overwrite the styles of additional utility classes

### ISSUE THREAD

**Issue by kikostadinov** [telerik/kendo-themes#4502]
The styles of utility classes `k-m-*`, `k-font-weight-*` and `k-fs-*` are overwritten by the element classes.

The problem can be reproduced in the demo available here:
https://www.telerik.com/kendo-react-ui/components/utils/typography/appearance/

**Comment by silviyaboteva** [comment]
The issue starts from `v6.2.0` where the utility classes are imported prior to the components' styles. Detaching all of the utilities from the themes will be the solution.

**Comment by PekoPPT** [comment]
The issue is no longer replicable and all appearance demos will be returned to the React documentation.
