### ISSUE TITLE
Calendar Modern RTL Arrow Icon Not Correct

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-themes#4536]
**Describe the regression**
Calendar Modern RTL Arrow Icon Not Correct

**To reproduce**
1. Goto [dojo](https://dojo.telerik.com/@vzsoft/iTuyAZug)

**Screenshots**
![calendar](https://github.com/telerik/kendo-themes/assets/5305981/b58dde3e-6bbb-4cb2-be79-1e00dafa3e9d)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Windows 10

**Comment by inikolova** [comment]
Thank you for reporting this issue with the Calendar Modern type. The correct approach for fixing it is by replacing the icons in the rendering with their left/right equivalent. I forwarded this problem to the corresponding team and the rendering changes will be available in the next official version of Kendo UI for jQuery.
