### ISSUE TITLE
twbs-compat.css missing from dist folder

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-themes#459]
## I'm submitting a...

* Regression report 

## Current behavior
Starting from v2.60.0, the [dist folder](https://unpkg.com/@progress/kendo-theme-default@2.60.0/dist/) does not contain a `twbs-compat.css` file.

## Expected behavior
Up to and including v2.59.0, the [dist folder](https://unpkg.com/@progress/kendo-theme-default@2.59.0/dist/) contains the file.

## Environment
Product:
* Kendo Ui for Angular

Package versions:

```
@progress/kendo-theme-default@2.60.0
```

**Comment by joneff** [comment]
The file `twbs-compat.scss` is used only to confirm that kendo-themes can be built against bootstrap framework and that our variables are compatible. It was never meant for production.
