### ISSUE TITLE
MultiSelectTree does not show the placeholder text

### ISSUE THREAD

**Issue by pepinho24** [telerik/kendo-themes#4618]
**Describe the bug**
The updated MultiSelectTree rendering and output do not show the placeholder text: 
- https://github.com/telerik/kendo-themes/blob/develop/tests/multiselecttree/multiselecttree.html#L26
- https://github.com/telerik/kendo-themes/blob/develop/tests/_output/default/multiselecttree/multiselecttree.png

**To reproduce**
Run the Empty MultiSelectTree test

**Expected behavior**
The `MultiSelectTree...` text should be visible in the input-like element.

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Additional context**
The issue comes from the `width: 100%` style for the `k-input-values` selector. Potential fix that needs further testing could be:

```
.k-input-values {
  width: auto;
  max-width: 100%;
}
```

**Comment by vladislavstratan** [comment]
+1

**Comment by erothfield** [comment]
> The issue comes from the width: 100% style for the k-input-values selector. Potential fix that needs further testing could be:
> 
> .k-input-values {
>   width: auto;
>   max-width: 100%;
> }

Using this workaround, the clear button is no longer pushed to the far right.

**Comment by inikolova** [comment]
Fixed with https://github.com/telerik/kendo-themes/commit/a04fad2f7fef8e3868aacf5ad2d8c9bed54ee925
