### ISSUE TITLE
Search icon not aligned in the filter menu since svg icons introduced.

### ISSUE THREAD

**Issue by NikoPenev21** [telerik/kendo-themes#4628]
Describe the bug
Search icon not aligned in the filter menu since svg icons introduced.

To reproduce
Dojo: https://dojo.telerik.com/ojowuMEy

![image](https://github.com/telerik/kendo-themes/assets/46747298/f6f8db38-c7ef-41ab-b334-3850aa36260f)

Expected behavior
Search icon shall be aligned.

Kendo UI for jQuery
Kendo UI for MVC
Kendo UI for Core

**Comment by Juveniel** [comment]
@NikoPenev21 this is bug in the Component rendering - the `k-input-icon` class is missing from the icon. See [the HTML spec](https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/searchbox/searchbox.spec.tsx#L92) for reference.
