### ISSUE TITLE
Scrollview completely broken

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-themes#465]
## I'm submitting a...

* Regression report 

## Current behavior
![screenshot](https://user-images.githubusercontent.com/4143177/49015077-b2a8fc00-f18a-11e8-86c2-805228d746a2.png)

## Minimal reproduction of the problem with instructions
1. Visible [here](https://k2build.openstack.progress.com/kendo-angular-ui-develop/components/scrollview/)

## Environment
Product:

* Kendo Ui for jQuery
* Kendo Ui for Angular
* Kendo Ui for React
* Kendo Ui for Vue

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by elena-gancheva** [comment]
The fix is available in the latest version of the themes.
