### ISSUE TITLE
Importing Fluent theme fails with undefined variables

### ISSUE THREAD

**Issue by glapointe** [telerik/kendo-themes#4669]
**Describe the bug**
Per the documentation I'm trying to import the Fluent them in an Angular 16.x project but I'm receiving the following error:
```
SassError: Undefined variable.
   ╷
85 │ $kendo-code-padding-x: map.get( $kendo-spacing, 1 ) !default;
   │                                 ^^^^^^^^^^^^^^
   ╵
  node_modules\@progress\kendo-theme-fluent\scss\typography\_variables.scss 85:33  @forward
  node_modules\@progress\kendo-theme-fluent\scss\typography\index.scss 9:1       
  @forward
  node_modules\@progress\kendo-theme-fluent\scss\index.scss 6:1
  @use
  @progress\kendo-theme-fluent\scss\all.scss 1:1
  @use
  src\app\main\app.component.scss 5:1
  root stylesheet
```
The above error is when I tried to import all.scss using the following:
```
@use "@progress/kendo-theme-fluent/scss/all.scss";
```
I've also tried importing specific components using the following and receive the same error (this is what I'd like to do but I can't get either working):
```
@use "@progress/kendo-theme-fluent/scss/index.scss" as kendo-theme;
@include kendo-theme.config(
    $config: (
        "components": (
            "button", 
            "input"
        )
    )
);
```
I'm not sure if this is just a documentation issue or an actual bug - either way, I'm following the docs and it's not working.

**To reproduce**

1. Create an angular 16 project and add the latest fluent theme ("@progress/kendo-theme-fluent": "^6.7.0")
2. Add either of the previously noted @use/@include statements to the .scss file
3. Perform a build

**Expected behavior**
Successful compilation without any errors.

**Affected package (please remove the unneeded items)**
* theme-fluent

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* OS: Windows 10
* Node version: 16.17.0
* NPM version: 8.15.0

**Comment by glapointe** [comment]
Note that reverting back to v6.4.0 does work.

**Comment by epetrow** [comment]
Hi, @glapointe we were unable to reproduce the issue on our end using angular 16.1.8 and the latest version of `kendo-theme-fluent`. Could you maybe provide a sample project so we can investigate further?

**Comment by glapointe** [comment]
[angular.zip](https://github.com/telerik/kendo-themes/files/12587810/angular.zip)
I've attached a stripped down version of my project. Do an install and then a build and you'll see the error. Sorry for not including this initially.

**Comment by epetrow** [comment]
Hi, @glapointe it seems like the deduped version of `kendo-theme-utils` in the example is 6.3.0 instead of 6.7.0.

Deleting `node_modules and package-lock.json`, and doing an install resolved the issue on my end.

Could you please check if this would work for you as well?
