### ISSUE TITLE
Upload component's input height is inconsistent in Safari

### ISSUE THREAD

**Issue by gdenchevprog** [telerik/kendo-themes#4682]
**Describe the bug**

The problem occurs only in Safari on a Mac machine.

The issue is that the height of the input goes beyond that of the container. It can cover elements underneath the Upload component itself and whenever a user attempts to click on them, the Upload dialog will open instead.

**To reproduce**

1. Open Safari on Mac
1. Go to the Upload overview demo - https://demos.telerik.com/kendo-ui/upload/index
1. Click anywhere underneath the first component.

![image](https://github.com/telerik/kendo-themes/assets/70957719/e1db04fb-5ee7-4c6d-ba32-3722edb5f5e6)

4. The dialog of the Upload will open even though the user hasn't clicked anywhere near the actual element.

**Expected behavior**
The input should not be clickable outside of its container.

**Affected package (please remove the unneeded items)**
* theme-default (I haven't checked the other themes, reproduced with the ocean-blue swatch)

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery (reproduced in jQuery but it most likely affects all suites).

**Affected browsers (please remove the unneeded items)**
* Safari version: 16.5

**Build system information (please remove the unneeded items)**
* OS: Mac

**Additional context**

The problem seems to be related to the following font style:

![image](https://github.com/telerik/kendo-themes/assets/70957719/4ffd61ef-e83b-4e00-95f0-17109a4950ec)

If the font is reduced to around 30px, the issue no longer appears. Aside from that, the client also mentioned that this problem also caused a scrollbar to appear on the page and they couldn't figure out where it was coming from. It seems to be from this "hidden" height as well.

**Comment by martintabakov** [comment]
Also reported in 1627909

**Comment by inikolova** [comment]
@gdenchevprog I tested this case and it appears the issue does not persist any more -> could you please confirm?
