### ISSUE TITLE
ListBox is not sized correctly when its height is defined as a percentage

### ISSUE THREAD

**Issue by mihaela-lukanova** [telerik/kendo-themes#4832]
**Describe the bug**
When setting the ListBox height as a percentage, the ".k-list-scroller" and "k-list" elements have different heights.

**To reproduce**
Dojo sample for reproduction: https://dojo.telerik.com/UbIbIpiY

**Expected behavior**
The ".k-list-scroller" and "k-list" elements must inherit the height of their parent element ("k-listbox").

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by inikolova** [comment]
I investigated the case and believe the described behavior is expected, as the height of a block element depends on its content, unless you specify a specific height. Take a look at the following section from the spec:
https://www.w3.org/TR/CSS21/visudet.html#propdef-height
_"The percentage is calculated with respect to the height of the generated box's containing block. If the height of the containing block is not specified explicitly (i.e., it depends on content height), and this element is not absolutely positioned, the value computes to 'auto'."_

Percentage heights work when the element has a parent with set height. If the parent has a percentage height as well, then this rule applies recursively until an element with a fixed height is reached, or until the `<html>` element is reached.
In the provided dojo, height (100% - 50px) of height: auto is _auto_, which is 0 in the case of #selected and 106px for #optional .k-list-scroller. To achieve the expected outcome , you should set percentage heights to all elements above the listbox:

body,
html,
.container,
.pnlbtm,
.row,
.col-4,
.pnlLance,
.col {
    height: 100%;
}

Take a look at the updated example -> https://dojo.telerik.com/@inikolova/EcOberoL
