### ISSUE TITLE
Need styles for Sankey component

### ISSUE THREAD

**Issue by nstoychev** [telerik/kendo-themes#4864]
We agree to use the charts series colors for the Sankey nodes.

Please, make sure the charts series colors matches the design.

Sankey Design - https://www.figma.com/file/BymtJkZqx5xoLw8ihF01F2/Sankey-Diagram-Chart?type=design&node-id=305-230&mode=design&t=qpvQ9z8JUs97Ow1v-0.

~~Also, we need the #757575 color for the Sankey links - https://www.telerik.com/kendo-react-ui-develop/components/charts/sankey/events/.~~

Links opacity:
normal: 0.4
highlight: 0.8
inactive: 0.2

Rendering for the tooltips:
![image](https://github.com/telerik/kendo-themes/assets/13251479/9147057e-302b-4b44-8bc8-28258f955fb7)

// cc @dmanova

**Comment by Juveniel** [comment]
No additional updates needed as the themes pass all the required variables to the Charts. Closing.
