### ISSUE TITLE
Need documentation of new swatches functionality

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-themes#487]
## I'm submitting a...

* Documentation issue or request

## Current behavior
Missing documentation about how to create & build own swatch 

## Expected behavior
Since it is really good new feature it is a must to have.

## Environment
Product:

* Kendo Ui for jQuery
* Kendo Ui for Angular
* Kendo Ui for React
* Kendo Ui for Vue

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by joneff** [comment]
Added https://github.com/telerik/kendo-themes/wiki/Swatches
