### ISSUE TITLE
SplitButton not render correctly in grid toolbar - default theme

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-themes#492]
## I'm submitting a...
* Bug report

## Current behavior
Rendered split button looks like 2 buttons and not one.

## Expected behavior
Split button in grid toolbar has the same look as standalone split button.

## Minimal reproduction of the problem with instructions
[Plunkr](https://stackblitz.com/edit/angular-qemwh9?file=app/app.module.ts).

## What is the motivation or use case for changing the behavior?
It looks ugly.

## Notes
I think problem is here:
```
.k-grid-toolbar .k-button + .k-button {
    margin-left: 4px;
}
```
Without this, split button is rendered correctly.
![chrome_2018-12-13_15-14-11](https://user-images.githubusercontent.com/1589573/49944060-c8882200-fee9-11e8-8df9-52e7281cb334.png)

**Comment by joneff** [comment]
Fixed by #766
