### ISSUE TITLE
The Toolbar tools and background have inconsistent colors.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#496]
## I'm submitting a...

* Bug report 

## Current behavior
The Toolbar tools and background have inconsistent colors. All tools are white, but the space where there are no tool is grey.

![image](https://user-images.githubusercontent.com/11087921/50009750-63533000-ffc0-11e8-89c2-c8243cd078c3.png)

## Expected behavior

Consistent colors between the tools and the backgroud:

https://github.com/telerik/kendo-ux/blob/master/themes/material/toolbar.psd

## Minimal reproduction of the problem with instructions

Demo: https://stackblitz.com/edit/angular-wtnv9r?file=index.html

## Environment
Product:
* Kendo Ui for Angular
* Kendo Ui for React

**Comment by dimitar-pechev** [comment]
The fix is included in the latest dev version of the themes.

**Comment by dimitar-pechev** [comment]
Shipped in `@progress/kendo-theme-material@2.3.0`.
