### ISSUE TITLE
Calendar weekdays not rendered in Edge

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#5]
The Calendar weekdays row is invisible in Edge as it is covered by the scrollable container:

![image](https://user-images.githubusercontent.com/7533599/35980924-a47908f8-0cf4-11e8-9af0-64eb9bacb994.png)

Observable in the online demos:

[https://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/](https://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/)

Suggested workaround:

    styles: [ `
      .k-calendar { margin: 0 auto; }
      >>> .k-calendar-weekdays {
        flex: 0 0 auto;
      }
    ` ],

**Comment by gyoshev** [comment]
The issue is fixed in the latest development build. [Updated plunker](https://plnkr.co/edit/uA8UfkHLYsPEwr3MYG3Q?p=preview).
