### ISSUE TITLE
The placeholder of all DropDowns is black instead of gray

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#500]
## I'm submitting a...
* Bug report 

## Current behavior
The placeholder of all DropDowns is black instead of gray, when using Kendo Bootstrap or Kendo Material theme in IE 11.

## Minimal reproduction of the problem with instructions
Check the following example in IE 11 and Chrome:
[https://stackblitz.com/edit/angular-kryafu?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-kryafu?file=app%2Fapp.component.ts)

## Environment
Product:

* Kendo Ui for Angular

Browser:
- IE version 11

**Comment by joneff** [comment]
This is browser limitation: the text of the placeholder can not be styled in IE 11. Reference: https://caniuse.com/#feat=css-placeholder
