### ISSUE TITLE
Upload text overlap

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#5027]
**Describe the bug**
When selecting multiple files in a synchronous Upload, the summary text and the text of the last selected file overlap.

**To reproduce**

1. Go to the following demo: https://demos.telerik.com/kendo-ui/upload/basicusage
1. Select 2 or more files in the Upload
1. The summary text **Total: 2 files** and the text of the last selected file overlap.

**Expected behavior**
The summary text should have a proper margin, so that it does not overlap with the file text.
 
The overlap is caused by the following CSS rule in the themes:

```
.k-upload .k-multiple-files-wrapper .k-file-summary {
    margin-top: -4px;
}
```
As a workaround the margin can be set to 4px:

```
.k-upload .k-multiple-files-wrapper .k-file-summary {
    margin-top: 4px;
}
```

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by inikolova** [comment]
@IvanDanchev I tested the described scenario, however it appears everything is rendered fine now. Could you please confirm the problem has been resolved? Thank you in advance
