### ISSUE TITLE
Passing percentage units to the global abs() function is deprecated

### ISSUE THREAD

**Issue by WissamProgress** [telerik/kendo-themes#5073]
**Describe the bug**
When building a project that has kendo-themes, the following warning appears:
```
DEPRECATION WARNING: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(-80%)
To emit a CSS abs() now: abs(#{-80%})
More info: https://sass-lang.com/d/abs-percent

  ╷
8 │     @return abs( $number );
  │             ^^^^^^^^^^^^^^
  ╵
    ..\node_modules\@progress\kendo-theme-core\scss\functions\_math.import.scss 8:13                 k-math-abs()
    ..\node_modules\@progress\kendo-theme-core\scss\functions\_color-manipulation.import.scss 18:13  k-color-level()
    ..\node_modules\@progress\kendo-theme-core\scss\functions\_color-manipulation.import.scss 38:13  k-color-tint()
    ..\node_modules\@progress\kendo-theme-core\scss\functions\_color-manipulation.import.scss 83:13  k-try-tint()
    ..\node_modules\@progress\kendo-theme-core\scss\functions\_color-variations.import.scss 33:82    k-generate-color-variations()
    src\app.scss 6:43          
```

based on their docs, one possible solution would be to replace it with `math.abs`
https://sass-lang.com/documentation/breaking-changes/abs-percent/

The other option would be to not use percentage values.

Percentage values in `abs` is used in the below two files:

https://github.com/telerik/kendo-themes/blob/develop/packages/core/scss/functions/_color-manipulation.import.scss

https://github.com/telerik/kendo-themes/blob/develop/packages/core/scss/functions/_math.import.scss

**To reproduce**

Build a React project for production that includes kendo-themes.

**Expected behavior**
Deprecated methods are not used. 

**Affected package**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for React (possibly all of them, but it was reproduced in KendoReact)

Reported in Ticket ID: 1654744

**Comment by epetrow** [comment]
This has been addressed in the effort of migrating the Kendo Themes to the dart-sass module system.
