### ISSUE TITLE
Grid footer is misaligned with the table cells

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#511]
### Bug report

Grid footer is misaligned with the table cells.

Reported in 1380496;

### Reproduction of the problem

https://dojo.telerik.com/OwEfukUw

### Workaround
```
    .k-grid-footer-wrap {
      margin-right: -1px; 
    }
```

**Comment by matanasov** [comment]
The workaround (fix) seems to be working for Chrome only.
Here is a screenshot taken in FF - zoom it and 
notice how the footer gets misaligned somewhere in the middle of the grid

![ff](https://user-images.githubusercontent.com/5861835/51754269-8b0bdc80-20c4-11e9-81cc-064bbfc7f738.png)
