### ISSUE TITLE
[Bug] Disabled styles cannot be overwritten

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-themes#5120]
**Describe the bug**
It is not possible to override the kendo-disabled styles neither through the map nor through the variables. 

**Workaround**
Override directly the .k-disabled class:

 - https://stackblitz.com/edit/react-kkbka1-enzjhp?file=app%2Fapp.tsx,app%2Fstyles.scss

```scss
@import '@progress/kendo-theme-default/dist/all.scss';

.k-disabled {
  @include disabled($bg: blue, $color: green);
}
```

**To reproduce**

1. Try to override the `$kendo-disabled-styling` map like in https://stackblitz.com/edit/react-kkbka1-nmycaw?file=app%2Fapp.tsx,app%2Fstyles.scss

**Expected behavior**
The disabled text and background color is changed.

**Screenshots**
The overriden variables are never used:
![image](https://github.com/user-attachments/assets/c92444f7-a9c0-44e5-8fb7-dfb79a0c88ab)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Additional context**
Reported in Ticket ID: 1658720, 1660779

**Comment by inikolova** [comment]
I am glad to inform you that we have addressed this issue with the migration to the SASS module system - a fix is available in the Pre-release dev version https://github.com/telerik/kendo-themes/releases/tag/v10.0.0-dev.0 and will be available in the upcoming stable version too
