### ISSUE TITLE
Incomplete util css class generation in 9.0.0 (ex k-flex-grow)

### ISSUE THREAD

**Issue by Ketec** [telerik/kendo-themes#5126]
After update to 9.0.0 i noticed my layouts were broken, i quickly traced it down to missing classes 
k-flex-grow, k-flex-shrink etc - it seems almost everything under the flex are missing.

Not present in the precompiled all.css either.

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Comment by JoomFX** [comment]
This is a breaking change that we introduced in v9.0 of Kendo Theme. You can read more about it in the [Changelog](https://github.com/telerik/kendo-themes/releases/tag/v9.0.0).

_For developers using utility classes for custom layouts, you will now
need to manually import the utilities as a separate stylesheet on your
pages. For step-by-step instructions on how to do this, please visit:
https://www.telerik.com/design-system/docs/utils/get-started/installation/_

**Comment by Ketec** [comment]
https://www.telerik.com/design-system/docs/utils/get-started/installation/
Might need an update, as it explicitly mentions these are included by default.
