### ISSUE TITLE
[Scheduler] Current Time Marker

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-themes#5148]
**Describe the bug**

Scheduler scss module does not pull in time-markers

**To reproduce**

1. Click '...'
1. Scroll down to '...'
1. See error '...'

**Expected behavior**
Scheduler scss module to pull in time-markers

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

Add any other context about the bug.

https://github.com/telerik/kendo-themes/blob/b5d71f7e16dfa643f0e2671a1c897185bf2758e1/packages/default/scss/scheduler/_index.scss
https://github.com/telerik/kendo-themes/commit/b5d71f7e16dfa643f0e2671a1c897185bf2758e1#diff-f6c7f8776dc002156ebd549d8c0ce4adb2f3cdf1ac9db758d920034ce06723c8L21

**Comment by cheng93** [comment]
It's possible I'm building the styles wrong, as I'm currently going from v7 -> v9. But I noticed the k-current-time classes are missing

I'm not sure what `$_kendo-module-meta` does, but the PR linked above includes time-markers in it, but does not pull in the scss files

**Comment by cheng93** [comment]
Oh I have to explicitly import `time-marker` module?

**Comment by epetrow** [comment]
Hey @cheng93, if you are only importing the styles related to the Scheduler,  you should not have to explicitly import the `time-marker` module. The Scheduler should import all necessary modules and this is a genuine bug on our part.

Basically what needs to be done is to add the time-marker module in the imported dependencies:

```scss
// Dependencies
@import "../icons/_index.scss";
@import "../adaptive/_index.scss";
@import "../button/_index.scss";
@import "../datetimepicker/_index.scss";
@import "../dropdownlist/_index.scss";
@import "../dialog/_index.scss";
@import "../tooltip/_index.scss";
@import "../time-marker/_index.scss";
```
