### ISSUE TITLE
Chart: Set background-color in sass

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-themes#518]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior

I like to set the background-color of the charts at a global place.
I can not use the global variables $bg-color or $base-bg. In my case the base colors are different.
I know that I can use <kendo-chart-area background="..."></kendo-chart-area> to set the background-color of the chart. But I must do this then every time.

Is there a global styling option available?

## Expected behavior

Possibility to set the background-color of a chart via css-class or sass-variable.

**Comment by elena-gancheva** [comment]
This functionality has been implemented and is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themеs.

**Comment by joneff** [comment]
The improvement is available both with

* @progress/kendo-theme-default@2.63.0
* @progress/kendo-theme-bootstrap@2.18.0
* @progress/kendo-theme-material@1.6.0

and 

* @progress/kendo-theme-default@3.0.0+
* @progress/kendo-theme-bootstrap@3.0.0+
* @progress/kendo-theme-material@2.0.0+
