### ISSUE TITLE
Focused state not indicated on Grid header

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-themes#519]
## I'm submitting a...

* Bug report 

## Current behavior
The focused state is not visible on the Grid header cells.

## Minimal reproduction of the problem with instructions
1. Open [Keyboard Navigation demo](https://www.telerik.com/kendo-angular-ui-develop/components/grid/keyboard-navigation/) for Kendo UI / Angular.
1. Click the cell containing "Gorgonzola Telino"
1. Press the Up Arrow on your keyboard
1. The filter cell is now focused, but it is not indicated visually
1. Press the Up Arrow on your keyboard
1. The header cell is now focused, but it is not indicated visually

## Environment
Product:
* Kendo UI for Angular

Browser:

- Chrome (desktop) version 71
- Firefox version 65

**Comment by TeyaVes** [comment]
reproducible in Kendo Grid for jQuery as well
