### ISSUE TITLE
Update from kendo-theme-* from 9.0.0 to 10.0.1: error "Can't find stylesheet to import" setting $kendo-colors variable

### ISSUE THREAD

**Issue by Gambero81** [telerik/kendo-themes#5246]
**Describe the bug**
I am updating kendo themes from v9.0.0 to v10.0.1

i reference these libraries in ASP.NET Core application using package.json configures as: 

```
{
   "dependencies" {
      "@progress/kendo-font-icons": "4.0.0",
      "@progress/kendo-theme-core": "10.0.1",
      "@progress/kendo-theme-bootstrap": "10.0.1",
      "@progress/kendo-theme-default": "10.0.1",
      "@progress/kendo-theme-material": "10.0.1",
   }
}
```

**in my scss file i have some code to redefine $kendo-colors variable**

using v9.0.0 my code was:

```
@import "../node_modules/@progress/kendo-theme-core/scss/functions/index.import.scss";

$kendo-colors: ();
$kendo-colors: k-map-merge($kendo-colors, ( 
        app-surface: $app-surface-color, 
        on-app-surface: $on-app-surface-color, 
        subtle: $subtle-color, 
        surface: $surface-color, 
        surface-alt: $surface-alt-color, 
        border: $border-color, 
        border-alt: $border-alt-color 
    ), 
    k-generate-color-variations( 'primary', $primary-color, 'material' ), 
    k-generate-color-variations( 'secondary', $secondary-color, 'material' ), 
    k-generate-color-variations( 'info', $info-color, 'material' ), 
    k-generate-color-variations( 'success', $success-color, 'material' ), 
    k-generate-color-variations( 'warning', $warning-color, 'material' ), 
    k-generate-color-variations( 'error', $error-color, 'material' ), 
    k-generate-color-variations( 'base', $base-color, 'material' ) 
);
```

reading the migration steps in https://www.telerik.com/design-system/docs/themes/release-notes/breaking-changes/v10-0-0/#migration-to-dart-sass
i changed my code to:

```
@use "sass:map";
@use "../node_modules/@progress/kendo-theme-material/scss/index.scss" as *;

$kendo-colors: ();
$kendo-colors: map.merge( $kendo-colors, ( 
        app-surface: $app-surface-color, 
        on-app-surface: $on-app-surface-color, 
        subtle: $subtle-color, 
        surface: $surface-color, 
        surface-alt: $surface-alt-color, 
        border: $border-color, 
        border-alt: $border-alt-color ));

$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('primary', $primary-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('secondary', $secondary-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('info', $info-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('success', $success-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('warning', $warning-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('error', $error-color, 'material'));
$kendo-colors: map.merge($kendo-colors, k-generate-color-variations('base', $base-color, 'default'));
```

bug with this code i have the error: 

```
Error: Can't find stylesheet to import.
   ╷
19 │ ┌ @forward "@progress/kendo-theme-core/scss/index.import.scss" with (
20 │ │     $kendo-enable-color-system: $kendo-enable-color-system !default,
21 │ │     // Color System
22 │ │     $_default-colors: $kendo-colors,
23 │ │     $kendo-colors: $kendo-colors !default,
24 │ │     // Elevation
25 │ │     $_default-elevation: $kendo-elevation,
26 │ │     $kendo-elevation: $kendo-elevation !default,
27 │ │     // Typography
28 │ │     $_default-font-sizes: $kendo-font-sizes,
29 │ │     $kendo-font-sizes: $kendo-font-sizes !default,
30 │ │     $kendo-font-size: $kendo-font-size !default,
31 │ │ 
32 │ │     $_default-line-heights: $kendo-line-heights,
33 │ │     $kendo-line-heights: $kendo-line-heights !default,
34 │ │     $kendo-line-height: $kendo-line-height !default,
35 │ │ 
36 │ │     $_default-letter-spacings: $kendo-letter-spacings,
37 │ │     $kendo-letter-spacings: $kendo-letter-spacings !default,
38 │ │     $kendo-letter-spacing: $kendo-letter-spacing !default,
39 │ │ 
40 │ │     $_default-font-families: $kendo-font-families,
41 │ │     $kendo-font-families: $kendo-font-families !default,
42 │ │     $kendo-font-family: $kendo-font-family !default,
43 │ │     // Radii
44 │ │     $_default-border-radii: $kendo-border-radii,
45 │ │     $kendo-border-radii: $kendo-border-radii !default,
46 │ │     // Spacing
47 │ │     $_default-spacing: $kendo-spacing,
48 │ │     $kendo-spacing: $kendo-spacing !default,
49 │ │ );
```

effectively if i go inside the file `../node_modules/@progress/kendo-theme-material/scss/core/_index.scss` i can find the @forward specified in error description.  

the issue is **THE PATH SPECIFIER IN THE FORWARD WHO IS INVALID**: `@progress/kendo-theme-core/scss/index.import.scss`

i don't have this path! the correct one would be: `../node_modules/@progress/kendo-theme-core/scss/index.import.scss`

How to solve?

Thanks

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Build system information (please remove the unneeded items)**
* NPM version: 10.2.5

**Comment by epetrow** [comment]
Hey @Gambero81, can you let me know how you are compiling the themes? Are you using `sass` or `WebCompiler`?

In both cases you will need to specify the path to the `node_modules` folder. Judging by the use of `package.json` and `npm` I would guess that you use `sass`, so you will need to use `--load-path`.

For example if you have a `sass` script in you `package.json` it may look something like this `sass --load-path=node_modules input.scss output.css` However please note that the path to `node_modules` might differ depending on your project structure.

**Comment by Gambero81** [comment]
i have found a similar issue but can't solve my problem: https://github.com/telerik/kendo-themes/issues/5090

**Comment by epetrow** [comment]
@Gambero81, if neither of the suggested approaches solve your problem , I will need a sample reproduction.

**Comment by Gambero81** [comment]
@epetrow i solved with --load-path parameter, but after this error i had to update all my scss with the new keyword @use who is not so compatible with the old @import keyword.

It was a very breaking change this telerik update..

**Comment by epetrow** [comment]
@Gambero81, you are correct the relase is breaking, however we did mention this in our [changelog](https://github.com/telerik/kendo-themes/releases/tag/v10.0.0) as well as in our [official documentation](https://www.telerik.com/design-system/docs/themes/release-notes/breaking-changes/v10-0-0/).
