### ISSUE TITLE
Switch Improvements proposal

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#529]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
1. In the switch styles, the $switch-on-shadow is defined, but never used in the theme.scss- it should either be used or removed.

2. The following layout of the switch in the Material theme is impossible:
![material-notpos](https://user-images.githubusercontent.com/45764088/50688831-dedc5600-102f-11e9-9af9-65fdeba962d9.png)

These shall be:
- $switch-on-hovered-shadow
- $switch-off-hovered-shadow

## Expected behavior
1. The $switch-on-shadow variable should either be used or removed.
2. Two new variables should be added in order to achieve the desired layout:
- $switch-on-hovered-shadow
- $switch-off-hovered-shadow

**Comment by joneff** [comment]
fixed by 10a7a02274d986ebe22d15b19d9665a6c14136e9
