### ISSUE TITLE
In IE11 NumericTextBox has white shadow near the right border

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-themes#545]
## I'm submitting a...
* Bug report

## Current behavior

![image](https://user-images.githubusercontent.com/11771009/51040690-d2707400-15c0-11e9-8223-50f6950c08be.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/11771009/51041117-db157a00-15c1-11e9-8844-e46fc6e260f1.png)

## Minimal reproduction of the problem with instructions
Open [this demo](https://demos.telerik.com/kendo-ui/numerictextbox/index) in IE 11
Select Default-v2 SASS theme

## Environment
Product:

* Kendo Ui for jQuery

Browser:
- IE version 11

**Comment by PreslavKozovski** [comment]
This bug is related to the IE width calculations. At this stage, there is no way to control this behavior from the styles.
