### ISSUE TITLE
Upgrading to Angular 7 causes SCSS loading errors

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#551]
Upgrading to Angular 7 caused the following error when the Default theme is imported in **_styles.scss_**:

```
**styles.scss** 
 
@import "~@progress/kendo-theme-default/scss/all";
```

> ERROR in ./src/scss/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/scss/styles.scss)
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
> undefined
>                ^
>       Compound selectors may longer be extended.
> Consider `@extend .k-i-loading, ::before` instead.
> See http://bit.ly/ExtendCompound for details.
> 
>         @extend .k-i-loading::before;
>                 ^^^^^^^^^^^^^^^^^^^^
>   node_modules\@progress\kendo-theme-default\scss\common\_loading.scss 94:17  root stylesheet

**Comment by tsvetomir** [comment]
The recommended workaround is [Using the Build Process of the Themes](https://www.telerik.com/kendo-angular-ui/components/styling/custom-themes/#toc-using-the-build-process-of-the-themes) and swatches.

**Comment by joneff** [comment]
If that's something that is failing with webpack, it's eventually going to fail without webpack. Be it because the node-sass implementation is changed, or something else. Ideally, the themes should be able to build against all valid compilers, be it node-sass, webpack, ruby sass, dart sass etc.

**Comment by mattfelten** [comment]
My project is swapping out `node-sass` for `dart-sass` and this error is now showing up that we can't solve without creating a whole new theme. `dart-sass` is the most up-to-date version of the Sass spec so any problems there will eventually trickle down into all the other compilers as well.
