### ISSUE TITLE
Material Theme - ComboBox and TextBox text selection has different color

### ISSUE THREAD

**Issue by blemaire** [telerik/kendo-themes#557]
## I'm submitting a...
* Bug report

## Current behavior
A Combox box with a floating label is not aligned with a TextBox with a floating label:

![image](https://user-images.githubusercontent.com/7140322/51260628-ff50cc80-19ae-11e9-925b-a371439242ec.png)

## Minimal reproduction of the problem with instructions
* navigate to this link and select all text on the rendered page
https://stackblitz.com/edit/angular-p9jmsj

## Environment
Product:
* Kendo Ui for Angular

Package versions:
kendo-theme-material@2.2.0/

Browser:
- Chrome (desktop) version 71.0.3578.98

System:
- Platform:  Mac

**Comment by TeyaVes** [comment]
Also reproducible in jQuery for a normal input: https://dojo.telerik.com/iTamiSeN
