### ISSUE TITLE
Add predefined resource colors for Scheduler events

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-themes#560]
We can use chart series colors as a background color for predefined resources in Scheduler events:

- Default theme: https://github.com/telerik/kendo-ux/blob/master/themes/default/color-palette.psd
- Material theme: https://github.com/telerik/kendo-ux/blob/master/themes/material/charts.psd
- Bootstrap theme: https://github.com/telerik/kendo-ux/blob/master/themes/bootstrap/Theme-Guides.psd

**Comment by TeyaVes** [comment]
LESS selected styles issue: https://github.com/telerik/kendo/issues/8937
