### ISSUE TITLE
Switch layout is broken when used within a k-form element

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#566]
Within **.k-form**:

![image](https://user-images.githubusercontent.com/7533599/51542831-d32cc400-1e64-11e9-8917-40f233275fca.png)
![image](https://user-images.githubusercontent.com/7533599/51542853-dfb11c80-1e64-11e9-8bb9-b66b593869e6.png)

Within a regular FORM element (with no k-form class):

![image](https://user-images.githubusercontent.com/7533599/51542883-f5bedd00-1e64-11e9-9238-f22c24a4df0f.png)
![image](https://user-images.githubusercontent.com/7533599/51542893-fbb4be00-1e64-11e9-828b-5eb321ee6d73.png)

Runnable demo:

[https://stackblitz.com/edit/angular-wbz1be-kxvxb3?file=app/app.component.ts](https://stackblitz.com/edit/angular-wbz1be-kxvxb3?file=app/app.component.ts)

**Comment by kspeyanski** [comment]
We've also received a bug report for the React Switch. A quick fix is to apply the 'k-display-inline-flex' class to the root element of the switch.
