### ISSUE TITLE
Switch labels are not visible when Bootstrap theme is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#567]
The Switch On/Off labels are not visible when the Bootstrap theme is used:

[https://stackblitz.com/edit/angular-wbz1be-ggqpgc?file=app/app.component.ts](https://stackblitz.com/edit/angular-wbz1be-ggqpgc?file=app/app.component.ts)

Works as expected with the Default theme:

[https://stackblitz.com/edit/angular-wbz1be-e61nmk?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-wbz1be-e61nmk?file=app%2Fapp.component.ts)

**Comment by PreslavKozovski** [comment]
This behavior is by design:
https://github.com/telerik/kendo-ux/blob/master/themes/bootstrap/switch.psd
If you need to change the default layout, follow the steps from this wiki:
https://github.com/telerik/kendo-themes/wiki/Kendo-UI-Switch-Layout

**Comment by aiscrim** [comment]
Sorry to reopen this old discussion, but I updated my project with "@progress/kendo-angular-buttons@7.0.2" and I think there's a regression: the proposed solution doesn't work anymore and the labels are not shown.

**Comment by michaelmarcuccio** [comment]
Same issue here when upgrading to the material v5 theme. The wiki does not have updated steps to resolve the issue.

**Comment by scoussens** [comment]
You have to look in the _variables file of the boostrap them for the switch and change those variables:

$kendo-switch-label-display: inline;
$kendo-switch-label-text-transform: capitalize;

Basically in V5 they added 'kendo' to the front of the variable.
