### ISSUE TITLE
Where is _bootstrap-map.scss? Or what is the alternative?

### ISSUE THREAD

**Issue by sdurnov** [telerik/kendo-themes#60]
I want to use Bootstrap 4 and I want Kendo to get all possible values from my customized Bootstrap's _variables.scss. As I understand, there was a solution for that with using _bootstrap-map.scss, but it's now absent in repository.

What is the right solution for this task right now?

**Comment by sdurnov** [comment]
Hi @gyoshev, just wanted to add few extra things to what I've described in support ticket.
Even if my solution works, it's not very good to use, as Kendo Bootstrap theme's scss makes recompilation impossibly long.
So I guess we need some solution which will 1) compile fast 2) will still give variables, functions and bootstrap classes available to use for @import in scss.

**Comment by joneff** [comment]
The file is still available, albeit with a small change in the name: https://github.com/telerik/kendo-themes/blob/develop/packages/bootstrap/scss/_bootstrap-overrides.scss. The idea to customize both Bootstrap 4 and Kendo Bootstrap 4 theme with a single file.

We tend to have different names than Bootstrap. For once, we call our button variables `$button-*`, where as Bootstrap uses `$btn-*`. Another difference is that we want to "inherit" variables form abstract to concrete... Say you have a base `$component-*` set of variables that propagates further down to `$card-*` or `$modal` etc...

Finally, we use a tad lighter shade of gray for our default (or secondary in Bootstrap terms) buttons.

All these changes require us to have the aforementioned file.

**Comment by sdurnov** [comment]
@joneff you know what, I think I had a misconception about how to use Kendo, because I didn't like how it looks and for that reason I wanted to do some heavy customization.
But that is, obviously, not something that Kendo is about, and this is hard to setup and too hard to maintain.
As I understand, Kendo is more like "take and use as-is with some very light visual customization".
So the problem for me (as customer) is just in a lack of consitent (or good enough) design system in Kendo and not very enterprise-looking enough components visual style.
Obviously, when you do have consitent design system, you don't really need all the Bootstrap 4 scss variables to control spacing and layout and keep your UI rhytm consistent.
So I think I can close it, and ask Kendo team to provide or re-export some basic Bootstrap layout and content classes, and it should be enough for most cases.
