### ISSUE TITLE
Window content does not stretch when iframe configuration is used

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#608]
## I'm submitting a...

* Bug report 

When an `iframe` is used, the window content does not stretch.

## Current behavior

https://dojo.telerik.com/arUZarik

## Expected behavior

https://dojo.telerik.com/UCuJaTIP

## Environment
Product:

* Kendo Ui for jQuery

## Workaround

```
    <style>
      .k-window-content {
        height: 100%;
      }
    </style>
```

**Comment by joneff** [comment]
The issue appears to be due to mismatch of styles and scripts -- version 2019.1.115 works correctly. The issue was present more than two years ago, and probably fixed by 36bbcfac6a95d36025ea5d3d2611b62da81c3125.
