### ISSUE TITLE
No visible weekend styles

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-themes#626]
Seems to be broken after 2.49.1
Last working: https://stackblitz.com/edit/angular-tdhnak?file=index.html
Latest: https://stackblitz.com/edit/angular-tdhnak-idhbuq?file=index.html

Probably caused by: https://github.com/telerik/kendo-themes/commit/e28232da29375ae02d33c9fc3d6dd15cecaafc1a

**Comment by joneff** [comment]
This behaviour is as per design. See https://github.com/telerik/kendo-ux/blob/master/themes/default/calendar.psd

![image](https://user-images.githubusercontent.com/8048/61851290-33a5c800-aebf-11e9-8f72-f5f67ca4f9a3.png)
