### ISSUE TITLE
Grid column menu button is not highlighted when a column is filtered

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-themes#629]
## I'm submitting a...

* Bug report 

## Current behavior

When you filter a column through the Grid column menu, there is no indication for that in the column header ([screenshot](https://www.screencast.com/t/1jx4giZ4on3)). 

## Environment
Product:
* Kendo Ui for jQuery

**Comment by MilenaCh** [comment]
The indicator is not high enough in IE:
https://www.screencast.com/t/GlZWelHV3
