### ISSUE TITLE
Error: ExtendCompound when building with Dart Sass- Invalid scss files 

### ISSUE THREAD

**Issue by Bjego** [telerik/kendo-themes#641]
When I try to compile the scss files from all.scss it fails with 
"Error: compound selectors may no longer be extended."

OS: Windows 7.
Package.json: 
[package.json.txt](https://github.com/telerik/kendo-themes/files/2930260/package.json.txt)

Here are the commands I use to build the scss file:
```

c:\Git\kendoIssue>npm i
c:\Git\kendoIssue>.\node_modules\.bin\sass .\node_modules\@progress\kendo-theme-default\scss\all.scss .\kendo.css
Error: compound selectors may no longer be extended.
Consider `@extend .k-button, ::before` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
99 │                 @extend .k-button::before;
   │                         ^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@progress\kendo-theme-default\scss\toolbar\_layout.scss 99:25  root stylesheet
```

After fixing this one file. It fails on other places as well

**Comment by blemaire** [comment]
Just had the same issue, it appears it has been deprecated for a while and now removed:
https://sass-lang.com/documentation/at-rules/extend#disallowed-selectors

What the changes of getting this fixed in the next kendo theme release?

**Comment by cluetjen** [comment]
Same here. As soon as you install sass node package, angular cli will fail with this error. Our problem is, that we're using ng-packagr and ng-packagr >= 5.x will install sass and so, it will break angular cli. Our workaround for now: Use ng-packagr 4.x

s.a. 
https://github.com/telerik/kendo-themes/issues/551
https://github.com/ng-packagr/ng-packagr/issues/1253

**Comment by blemaire** [comment]
@cluetjen have you had any issues with downgrading to ng-packager v4?

**Comment by cluetjen** [comment]
@blemaire - no, but I fear it will break for angular 8, see https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md . What's the reason for your thumbs down on my comment?

**Comment by blemaire** [comment]
> What's the reason for your thumbs down on my comment?

@cluetjen apologies for the thumb down it wasn't meant for your comment but rather to express how I felt about having to downgrade to ng-packagr v4. I removed it to prevent this confusion.

Thanks for your reply about the effect of downgrading

**Comment by joneff** [comment]
As of dart-sass v 1.14.3, the `::before` pseudo element is treated as such and that particular problem does not appear.

The rest of the compound selectors like `.k-button.k-flat` or `.k-button.k-primary.k-flat` are however problematic. @blemaire has offered a solution in #705, which solves the compilation issues.

To sum up the conversation there: we do have a bigger issue at hand and that is how to deal inconsistencies between the compilers. This is one such example. In addition, perhaps we should revisit our modifier classes, say `.k-button-flat` instead of `.k-button.k-flat`.

**Comment by esr360** [comment]
You guys should express your concerns here because I do not believe this deprecation from Sass has been added with due diligence https://github.com/sass/sass/issues/1599

**Comment by joneff** [comment]
#775 targets dart compilation.

**Comment by cluetjen** [comment]
Update for those using ng-packagr: After an update to angular cli 8 the cli will behave the same as ng-packagr, that means: just install "node-sass" and it should work. (s.a. https://github.com/telerik/kendo-themes/issues/641#issuecomment-487385593)

**Comment by joneff** [comment]
The themes are now in the dev channel:

* @progress/kendo-theme-default v3.8.0-dev.ee54ef17
* @progress/kendo-theme-bootstrap v3.5.0-dev.ee54ef17
* @progress/kendo-theme-material v2.6.0-dev.ee54ef17

Note that the next non dev release will bump the major version.
