### ISSUE TITLE
Floating X on k-multiselect-wrap k-buttons

### ISSUE THREAD

**Issue by AlexMcConnell** [telerik/kendo-themes#644]
Kendo Ui for React - kendo-theme-default-3.3.1
- Chrome (desktop) version 72.0.3626.119
- Platform: Mac

In the edit popup for a Scheduler.

Current behavior:

![screen shot 2019-03-05 at 10 14 47 am](https://user-images.githubusercontent.com/8899861/53815433-ab368300-3f2f-11e9-9e2d-00357dfedaac.png)

<img width="182" alt="screen shot 2019-03-05 at 10 18 00 am" src="https://user-images.githubusercontent.com/8899861/53815627-fea8d100-3f2f-11e9-9e2f-9fc22cd376d7.png">

This fixes the problem, but I don't know what else it does.

![screen shot 2019-03-05 at 10 19 12 am](https://user-images.githubusercontent.com/8899861/53815728-2c8e1580-3f30-11e9-99e6-bdab1fdcab31.png)

<img width="141" alt="screen shot 2019-03-05 at 10 19 39 am" src="https://user-images.githubusercontent.com/8899861/53818020-6b729a00-3f35-11e9-9be3-14bd334827db.png">

I'm sorry if this isn't enough information. I have to go hack a solution now. 😁

**Comment by TeyaVes** [comment]
no longer reproducible as of Kendo UI v 2019.3.917
