### ISSUE TITLE
Custom cell editors do not work properly in Firefox and Chrome when filter is enabled for their range and SCSS based themes are used

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#65]
### Bug report
Custom cell editors do not work properly in Firefox and Chrome when filter is enabled for their range and SCSS based themes are used.

### Reproduction of the problem
* Go to the following [Dojo](https://dojo.telerik.com/uyANuXIb/2);
* Try to select an option in column A or B;
* The cell editor will open and close immediately after;

### Environment
* **Browser:** [ Chrome | Firefox ]

**Comment by TeyaVes** [comment]
no longer reproducible as of Kendo UI v. 2019.3.917
