### ISSUE TITLE
Allow vertical orientation in multiview calendar

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#662]
Currently the MultiViewCalendar, and all related DateInputs that can render more than one Calendar, are horizontally oriented only. It would be a nice enhancement to allow configuring the orientation, or use a vertical one by default depending on the viewport size (for example on mobile devices).

**Comment by rsseurope** [comment]
Is there a workaround that we can use right now? I need this for my app.

**Comment by dtopalov** [comment]
The only currently available workaround is overwriting the built-in styling as necessary, e.g.:

[https://stackblitz.com/edit/angular-txbzv9?file=app/app.component.ts](https://stackblitz.com/edit/angular-txbzv9?file=app/app.component.ts)

**Comment by rsseurope** [comment]
for now this works..

**Comment by joneff** [comment]
The issue is resolved with just a bit of markup sprinkled (k-vstack instead of k-hstack). We may need additional styling once we go near the comletion of the task, such as handling size etc.
