### ISSUE TITLE
k-state-disabled hide the element when container is animated

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-themes#665]
* Bug report

## Current behavior
When for example Grid column menu filtering is expanded the buttons with k-state-disabled are invisible. When you hover the container (browser repaint happens) the element becomes visible, but it's annoying.

## Expected behavior
The disabled buttons to be always visible as expected.

## Minimal reproduction of the problem with instructions
[Grid column menu demo](https://www.telerik.com/kendo-react-ui/components/grid/columns/column-menu/)

![image](https://user-images.githubusercontent.com/2195951/54611672-17e96b80-4a60-11e9-8413-6e6b462e6fc3.png)

After some testing it becomes clear that the issue is caused by the following style applied by *k-state-disabled* CSS class:

**filter: 'grayscale(.5)'**

## Environment
* Kendo Ui for Angular
* Kendo Ui for React
* Kendo Ui for Vue

Browser:
- Chrome (desktop) version v.73, not reproducible in v.75
- Edge version v.41.16299.967.0 (Html v.16.16299)

**Comment by joneff** [comment]
We'll wait for v75 to become official (currently, it's canary) and if the problem persists, we'll fix the issue by removing the said styles

**Comment by inikolova** [comment]
It appears everything is working as expected in the latest browsers versions
