### ISSUE TITLE
Angular Scheduler edit-dialog Material theme improvements

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#679]
Several improvements for Kendo UI for Angular Scheduler edit-dialog in Material theme:

Checkout the the design [specifications](https://github.com/telerik/kendo-ux/blob/master/themes/material/dialogs-scheduler.psd).

- [ ] The width of the dialog content is larger
Current state: 
![image](https://user-images.githubusercontent.com/8842674/55476684-e657cf00-561f-11e9-934f-9b456fb0a4dd.png)

- [x] There are inconsistent spacings between the elements in the edit-form
Current state: 
![image](https://user-images.githubusercontent.com/8842674/55476879-5fefbd00-5620-11e9-8ece-aa2205ca19c4.png)

- [x] Dialog buttons are not aligned as the design specification
Current state: 
![image](https://user-images.githubusercontent.com/8842674/55476926-7dbd2200-5620-11e9-8199-b7751f56c427.png)

- [ ] We should consider small screens, for example adding scrollbars when the dialog's content is overflowing.

- [x] Some labels are not aligned
Current state: 
![image](https://user-images.githubusercontent.com/8842674/55477085-f2905c00-5620-11e9-93bf-f3ec38c45b90.png)

- [ ] Different classes for the different sizes of the dialog `k-dialog-sm, k-dialog-xs, etc` for the Material theme

@joneff @Raisolution @TeyaVes @PreslavKozovski

**Comment by joneff** [comment]
* The components breaking on two lines can be targeted with specific styles. 
* The vertical misalignment of inputs and text can easily be targeted
* The sizing may prove a bit challenging (note: we must extend the sizing map slightly)

The rest is fine.

**Comment by svetq** [comment]
The DropDowns located in the repeat "monthly" and "yearly" tabs are too narrow:
![image](https://user-images.githubusercontent.com/20015190/60576744-a91ded00-9d86-11e9-8133-d457155f8670.png)
and:
![image](https://user-images.githubusercontent.com/20015190/60576891-f5692d00-9d86-11e9-800d-ad6ab47925b9.png)

**Comment by joneff** [comment]
Fixed by applying form guidelines in https://github.com/telerik/kendo-angular-scheduler/pull/321
