### ISSUE TITLE
Multiview Calendar Arrow is doesn't work in Material theme (z-index related)

### ISSUE THREAD

**Issue by eeasss** [telerik/kendo-themes#688]
* Bug report

## Current behavior
When you click on the side arrows in the MultiViewCalendar, if you click directly on the icon it does not transition to the next month

## Expected behavior
Transition should happen no matter where inside the circle you click

## Minimal reproduction of the problem with instructions
See the custom rendering demo:
https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/custom-rendering/#toc-customizing-the-calendar

See video:https://www.loom.com/share/c9c465f2d5e94d389ae2e5bb593bdcb7

## What is the motivation or use case for changing the behavior?
Less frustrating experience for the user

## Environment

Browser:

- Chrome (desktop) version 73

System:

- Platform:  Windows

**Comment by joneff** [comment]
fixed by 73841725d6109ab1dcddad856f9e04d9575d946b in #711
