### ISSUE TITLE
Validation tooltip in the Grid is not consistently styled in the different edit modes

### ISSUE THREAD

**Issue by TsvetinaIvanova** [telerik/kendo-themes#690]
The validation tooltip in the popup edit mode is not absolutely positioned, so it messes with the edit form layout.
Also, the tooltip is missing other styles (background, callout styling), as compared to the validation tooltip in inline an incell edit mode:
[https://dojo.telerik.com/IBEsuKoT](https://dojo.telerik.com/IBEsuKoT)

Have this issue in mind when addressing the problem, as it seems the validation tooltip base styling is still incomplete: #480.

**Comment by joneff** [comment]
Fixed by #1374
