### ISSUE TITLE
Shadow for frozen columns is too wide

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-themes#692]
## I'm submitting a...
* Bug report 

## Current behavior
The [design spec](https://github.com/telerik/kendo-ux/blob/master/themes/material/grid.psd) for the Material theme specifies a shadow over the non-locked columns:

![image](https://user-images.githubusercontent.com/247917/56047288-c5912700-5d4d-11e9-975b-09a597fbb8a9.png)

In reality the shadow it's around 10px wider:

![image](https://user-images.githubusercontent.com/247917/56049143-7f3dc700-5d51-11e9-902e-542d8947f0dc.png)

## Expected behavior
The shadow should be of the specified size.

## Minimal reproduction of the problem with instructions
1. Open [the Kendo UI for Angular](https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/) or [Kendo UI for jQuery](https://demos.telerik.com/kendo-ui/grid/frozen-columns) locked (frozen) column examples.
2. Set the theme to Material

**Comment by KeiBlag** [comment]
Fixed with https://github.com/telerik/kendo-themes/pull/791
