### ISSUE TITLE
Incorrect flex value for .k-dialog-button-layout-stretched .k-button

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#706]
Incorrect flex value for .k-dialog-button-layout-stretched .k-button

![image](https://user-images.githubusercontent.com/11087921/56640109-d9585980-667a-11e9-83f4-25721b50a2f2.png)

**Comment by elena-gancheva** [comment]
related to https://github.com/telerik/kendo-themes/issues/679
