### ISSUE TITLE
Grid pager visibility is not displayed correctly.

### ISSUE THREAD

**Issue by jthope** [telerik/kendo-themes#716]
## I'm submitting a...

* Bug report 

## Current behavior
Incorrect grid pager styles when building the default theme in the develop branch. The pager visibility is lost with grid widths below ~1035px.

## Expected behavior
For the pager to be visible..

## Minimal reproduction of the problem with instructions

https://dojo.telerik.com/IPoFAHEZ
The styles generated @ https://cdn2.phyletec.com/content/bundled/site.dark.kendo.css is a result from running npm run build (default theme) with the latest changes in the develop branch. Colors, and padding variables were customized in the _variables.scss file.

The original css file from the demo pages @ https://kendo.cdn.telerik.com/2019.1.220/styles/kendo.default-v2.min.css does not have this issue.

Screenshot with grid width > ~1035px
![image](https://user-images.githubusercontent.com/114626/56980470-766b3480-6b4a-11e9-98e8-5fecadbdc901.png)

Screenshot with grid width < ~1035px
![image](https://user-images.githubusercontent.com/114626/56980546-a31f4c00-6b4a-11e9-80f1-8446c468542e.png)

## What is the motivation or use case for changing the behavior?
Not a behavior change, I believe this to be a bug with the grid pager style in the recent kendo-themes default theme.

## Environment
Product:

* Kendo Ui for jQuery

Package versions:

```
+-- UNMET PEER DEPENDENCY @semantic-release/npm@2.7.0
+-- cz-conventional-changelog@1.2.0
+-- editorconfig-tools@0.1.1
+-- ghooks@1.3.2
+-- http-server@0.11.1
+-- jquery@3.4.0
+-- karma@1.7.1
+-- karma-chrome-launcher@2.2.0
+-- karma-qunit@1.2.1
+-- lerna@2.11.0
+-- pastshots@1.5.0
+-- qunitjs@2.4.1
+-- semantic-release@12.4.1
+-- semantic-release-monorepo@4.2.1
`-- validate-commit-msg@1.3.0

npm ERR! peer dep missing: @semantic-release/npm@2 - 2.6.0, required by semantic-release-monorepo@4.2.1
npm ERR! peer dep missing: @semantic-release/npm@2 - 2.6.0, required by semantic-release-monorepo@4.2.1
```

Browser:

- Chrome (desktop) version 74.0.3729.108

System:
- TypeScript version: 2.5 
- Node version: 8.9.2 npm: 6.9.0
- Platform: Windows

[_variables.txt](https://github.com/telerik/kendo-themes/files/3132393/_variables.txt)

**Comment by jthope** [comment]
The issue appears to be related to the .k-pager-wrap.k-pager-lg .k-pager-numbers, .k-pager-wrap.k-pager-md .k-pager-numbers, .k-pager-wrap.k-pager-sm .k-pager-numbers  style:
![image](https://user-images.githubusercontent.com/114626/56984472-19747c00-6b54-11e9-8d56-e661a85f3a3e.png)

Left side is what is generated from this repository, right side comes from the https://kendo.cdn.telerik.com/2019.1.220/styles/kendo.default-v2.min.css file.

**Comment by joneff** [comment]
@PreslavKozovski any thoughts?

**Comment by PreslavKozovski** [comment]
@jthope 

You are using the latest styles for the theme, however, you are using the rendering(the scripts) from 2019.1.220 version.

To resolve the issue, use the latest scripts available in the Latest Internal Build. You can either get Kendo's latest internal build from here:
https://www.telerik.com/account/product-download?product=KENDOUICOMPLETE

or use the following workaround until the new Kendo version is officially released:
https://dojo.telerik.com/OdEsuvey

If everything goes as expected, the release will be out next week.

The workaround suggests adding the following line within the script tags:

```
$("#grid").find(".k-pager-numbers").wrap("<div class='k-pager-numbers-wrap'></div>");
```

**Comment by jthope** [comment]
Will do, thanks for your response!

**Comment by CultivateCreate** [comment]
This is still an issue. I removed and installed:


npm install @progress/kendo-theme-material


and the grid's breadcrumb element does not have the:

div.k-pager-numbers-wrap

its just:

 ul.k-pager-numbers

**Comment by PreslavKozovski** [comment]
@CultivateCreate 
Generally speaking, the HTML rendering comes from the JavaScript.
Having said that, could you please elaborate on what version of the Kendo UI scripts are you using?
