### ISSUE TITLE
Broken highlight alignment when the bootstrap styles are included 

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-themes#718]
Example: https://stackblitz.com/edit/angular-oocy2y-7nzgch?file=index.html

Occurs because of the following bootstrap style:

    *, ::after, ::before {
        box-sizing: border-box;
    }

possible fix: 

    .k-time-list .k-item {
        box-sizing: content-box;
    }

https://stackblitz.com/edit/angular-oocy2y-mzfcqf?file=index.html

**Comment by JoomFX** [comment]
The issue is no longer reproducible.
Please reopen the issue if I have missed something.
