### ISSUE TITLE
Upload Loading indicator broken

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-themes#737]
## I'm submitting a...
* Bug report

## Current behavior
 Upload component loading indicator is too big in React component:
![UploadBug](https://user-images.githubusercontent.com/2195951/57835583-81b79480-77c7-11e9-98fd-0f5776b24e8c.png)

## Expected behavior
Loading indicator to be regular size.

## Minimal reproduction of the problem with instructions
Open any Upload component demo and start file upload. 

## Environment
* Kendo Ui for React

Package versions:
Latest.

Browser:
- Chrome (desktop) version Latest

**Comment by joneff** [comment]
The issue is related to styles on the page.
