### ISSUE TITLE
The font-size of the Notification is not overwritten when adding a custom class

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#738]
## I'm submitting a...

* Bug report 

## Current behavior
When using a custom class for the Notification, it is not possible to change the font-size.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-18n7h1?file=app/app.component.ts

## Workaround
Add the following custom style to the demonstrated example in order to control the font-size:

`        .button-notification .k-notification-wrap {
          font-size: 20px;
        }`

## Environment
Product:
* Kendo Ui for Angular

**Comment by KeiBlag** [comment]
Fixed with #763
