### ISSUE TITLE
Missing focus selector in Material Theme

### ISSUE THREAD

**Issue by shekerev-progress** [telerik/kendo-themes#745]
Material Theme is missing on focus selector that other themes have. Issue occurs for both Kendo UI for Angular and KendoReact

How to reproduce:
- Try to navigate KendoReact Menu component with keyboard only using Default Theme vs using Material theme:
https://www.telerik.com/kendo-react-ui/components/layout/menu/keyboard-navigation/
- With default you clearly see which item is on focus. With material you do not see which item is on focus.

Discussed with Ivan Zhekov

**Comment by elena-gancheva** [comment]
Reproducible for Kendo UI for Angular too: https://www.telerik.com/kendo-angular-ui/components/menus/menu/keyboard-navigation/
