### ISSUE TITLE
[ButtonGroup] Incorrect margins when is used in Grid's toolbar

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#751]
If a button is before (or after) the ButtonGroup in Grid's toolbar, there is no margin between them.
Also, gaps are showing between buttons that are in ButtonGroup (same appear when  ButtonGroup is used in Toolbar Component).

## Expected behavior
Margin (4px) should be added between the ButtonGroup and any other buttons. 

There should be no gaps between buttons in ButtonGroup

## Minimal reproduction of the problem with instructions
Check the following stackblitz example:
[https://stackblitz.com/edit/angular-nud4dl-tchh9x?file=app/app.component.ts](https://stackblitz.com/edit/angular-nud4dl-tchh9x?file=app/app.component.ts)

Screenshot:
![buttons-group](https://user-images.githubusercontent.com/33104481/58252151-16913380-7d6e-11e9-91b6-d47a88c992d1.png)

## Environment
Product:
* Kendo UI for Angular

Browser:
- Chrome (desktop) [ 74.0.3]
- Firefox [66.0.5]
- IE [11]
- Edge [latest]
- Opera [latest]

**Comment by joneff** [comment]
fixed by #766
