### ISSUE TITLE
Double border in editor toolbar

### ISSUE THREAD

**Issue by ivelina-penkova** [telerik/kendo-themes#771]
In Angular and React there is a border of the editor component and another border of the toolbar component which results in double border in all themes:
<img width="857" alt="Screen Shot 2019-06-10 at 10 58 51 AM" src="https://user-images.githubusercontent.com/12846286/59180928-ccca8a80-8b6e-11e9-8961-39d7ac5e31d3.png">

There should be border of the whole component and only bottom border of the toolbar component.

cc: @joneff @elena-gancheva @kspeyanski

**Comment by joneff** [comment]
Fixed by #773
