### ISSUE TITLE
Implement Material for Menu- Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#78]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- [ ] No padding around separators - <li class="k-separator> (image below)
- [ ] No padding before first and after last item of Sub Sub items
Used Keyboard Navigation demo for easier setup - [snippet](http://dojo.telerik.com/OxIcazuG).
![image](https://user-images.githubusercontent.com/6614183/38422775-9f9056f6-39b4-11e8-9904-45e3d8dd886e.png)
- [ ] Wrong height of scrollable menu submenu items - also reproducible for Default and Bootstrap:
![image](https://user-images.githubusercontent.com/6614183/38423007-542bf78c-39b5-11e8-8037-52d708d31f81.png)

**Comment by gyoshev** [comment]
The last two items should be resolved with an added rendering change from https://github.com/telerik/kendo-themes/commit/833debeb592a761e47a3e15a17d45ccd803ebde4. I've [added a PR](https://github.com/telerik/kendo/pull/8380) that should resolve this in KUI for jQuery.
