### ISSUE TITLE
SUGGESTION: Add .browserlistrc for our apps to comply with

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-themes#780]
Bootstrap provides a .browserlistrc at https://github.com/twbs/bootstrap/blob/v4.3.1/.browserslistrc

```
# https://github.com/browserslist/browserslist#readme

>= 1%
last 1 major version
not dead
Chrome >= 45
Firefox >= 38
Edge >= 12
Explorer >= 10
iOS >= 9
Safari >= 9
Android >= 4.4
Opera >= 30
```

This makes it very clear what browser versions Bootstrap supports at any time.

It would be nice to have a .browserlistrc to copy into our apps in order to make sure our apps do not pretend to support browsers that kendo-themes do not support.

**Comment by joneff** [comment]
We do use the browserlist format, albeit in an older form: https://github.com/telerik/kendo-themes/blob/develop/packages/theme-tasks/lib/globals.js#L20.

We are currently working on a release target at adding support for dart sass and we will add said changes so we comply with the newer requirements. The same will apply for sasslintrc file

**Comment by joneff** [comment]
Having changed our theme compilation process completely it's now possible to extract a `.browsersrc` file, which I did.
