### ISSUE TITLE
"No records available." is incorrectly positioned

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#783]
## I'm submitting a...
* Bug report 

## Current behavior
The "No records available." is positioned only in the first column of the Grid.

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts](https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts)

## Environment
Product:

* Kendo Ui for Angular

**Comment by danielkaradachki** [comment]
duplicate of https://github.com/telerik/kendo-themes/issues/781
