### ISSUE TITLE
Textboxes are moved to a new line in IE 11

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#785]
## I'm submitting a...
* Bug report 

## Current behavior
In IE11 each Kendo Textbox is moved to a new line by default.

## Minimal reproduction of the problem with instructions
Check the following example in IE 11:
https://stackblitz.com/edit/angular-m5egnj-9ezh6b?file=app/app.component.ts

## Workaround

Add the following style:
`    .k-textbox{
      display:inline-block;
    }`

https://stackblitz.com/edit/angular-m5egnj-c16ofe?file=app/app.component.ts

## Environment
Product:
* Kendo Ui for Angular

**Comment by joneff** [comment]
Apparently, IE 11 has issues with input elements that are inline-flex. So this must be targeted specifically:

```scss
input.k-textbox {
    display: inline-block;
}
```
