### ISSUE TITLE
Kendo UI for jQuery Scheduler dialogs issues in Material theme

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#792]
## I'm submitting a...
* Bug report
Scheduler dialogs do not match [Material theme design](https://github.com/telerik/kendo-ux/blob/master/themes/material/dialogs-scheduler.psd)

## Current behavior
- [ ] Consider changing the rendering of checkboxes inside the dialogs with Kendo checkboxes as per design
- [ ] Event dialog - All day event label should be at one line together with the checkbox: 
![image](https://user-images.githubusercontent.com/7202037/45304846-a7e2b180-b521-11e8-8ce8-21b5a461a84b.png)
- [ ] Dialogs - Cancel button should be on the left and the primary Save button should be on the right: 
![image](https://user-images.githubusercontent.com/7202037/45305526-2f7cf000-b523-11e8-9353-408599152fb6.png)

## Expected behavior
[Material theme design](https://github.com/telerik/kendo-ux/blob/master/themes/material/dialogs-scheduler.psd)

## Minimal reproduction of the problem with instructions
1. Go to https://demos.telerik.com/kendo-ui/scheduler/index and choose SASS Material theme
1. Double click on an event to open its Edit dialog

## Environment
* Kendo Ui for jQuery - R2 2019 SP1

Package versions:
[kendo theme material 2.5.2](https://www.npmjs.com/package/@progress/kendo-theme-material/v/2.5.2)

Browser:
- Chrome (desktop) version 75
- Firefox version 65

**Comment by Juveniel** [comment]
The edit dialog is already refactored based on the latest design. Here is a [link to the visual tests for the edit popup](https://github.com/telerik/kendo-themes/blob/develop/tests/_output/material/scheduler/scheduler-edit-dialog.png).
