### ISSUE TITLE
Not editable field in popup not vertically aligned with label

### ISSUE THREAD

**Issue by TeyaVes** [telerik/kendo-themes#805]
In grid edit popup, when a field is not editable, it is not vertically aligned with the label:

![alignment](https://user-images.githubusercontent.com/45764088/60248078-901ac500-98ca-11e9-9c70-536c42f1592c.png)

Can be seen here:
https://dojo.telerik.com/opadEHiL

**Comment by dmanova** [comment]
Verified in Kendo UI for jQuery.
