### ISSUE TITLE
Provide different looks for the selected and focused colors of the Kendo React ColorPalette

### ISSUE THREAD

**Issue by asen-arizanov** [telerik/kendo-themes#807]
## I'm submitting a...
  * Feature request

## Current behavior
The Kendo React ColorPalette is WIP. However the undesired behavior can be seen in the [Angular version](https://www.telerik.com/kendo-angular-ui/components/inputs/colorpalette/#toc-basic-usage).
The `k-state-selected` is used for the focused color and not for the selected one. Even when I try to introduce `k-state-focused` and use both classes, the colors under question look the same.

## Expected behavior
`k-state-selected` and `k-state-focused` should look different.

## Minimal reproduction of the problem with instructions

  1. Open [https://www.telerik.com/kendo-angular-ui/components/inputs/colorpalette/#toc-basic-usage](https://www.telerik.com/kendo-angular-ui/components/inputs/colorpalette/#toc-basic-usage)
   2. Click on a color and then navigate via keyboard to another color. The first/selected color is lost visually.

## What is the motivation or use case for changing the behavior?
 Improve the behavior of the ColorPalette.

**Comment by silviyaboteva** [comment]
This is resolved in the `4.42.0` version of the Kendo Themes.
