### ISSUE TITLE
Tooltip content is not wrapped in IE

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#816]
## I'm submitting a...
* Bug report 

## Current behavior
If tooltip's content is larger, the tooltip content container is not wrapped in IE. 

## Expected behavior
Max-width of the content should be provided in the styles.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-atdm1d?file=app/app.component.ts

## Environment
Product:
* Kendo Ui for Angular

Browser:
- IE

**Comment by joneff** [comment]
@JoomFX can you confirm that this is still an issue?

**Comment by JoomFX** [comment]
@joneff yes, this is still an issue.
