### ISSUE TITLE
Buttons overlap in Grid when in editing mode

### ISSUE THREAD

**Issue by keiblag** [telerik/kendo-themes#817]
## I'm submitting a...

* Bug report 

## Current behavior
When the Grid component is in editing mode and the width of the column that holds the command buttons is not big enough, they overlap.

![grid](https://user-images.githubusercontent.com/10484594/61212509-2cd2c480-a70b-11e9-8f50-31255a0c7722.PNG)

## Expected behavior
The buttons shouldn't overlap.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-reactive-forms/

  1. Click button Add new
  2. In column command see the buttons overlap

## Environment
Product:

* Kendo Ui for Angular

**Comment by TeyaVes** [comment]
duplicate of https://github.com/telerik/kendo-themes/issues/239

**Comment by joneff** [comment]
Fixed by #1226
