### ISSUE TITLE
Implement Material for ContextMenu - Kendo U

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#83]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- What design is followed for context menu?
- [ ] Unexpected space above and below horizontal root items (image below)
- [ ] No margin around separators:
![image](https://user-images.githubusercontent.com/6614183/38428033-76ffcea6-39c3-11e8-9442-b601948d825c.png)
- [ ] No RTL styles... seems common issue for all themes SASS and LESS.

**Comment by Dimitar-Goshev** [comment]
- [ ] All SASS themes - only the first item of Horizontal Context menu has background in IE:
![image](https://user-images.githubusercontent.com/6614183/38926754-71e9ff48-430c-11e8-84a6-95ca1e33b9d8.png)
