### ISSUE TITLE
Grid is not scrollable inside element with k-form class

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-themes#835]
Example: https://stackblitz.com/edit/angular-wat969-imsah1?file=app/app.component.ts

The problem seems to be cause by the style that overrides the widgets display:

https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/input/_layout.scss#L430

Can be workaround by setting display: flex to the grid:

https://stackblitz.com/edit/angular-wat969-xbufkm?file=app/app.component.ts

**Comment by inikolova** [comment]
Fixed with https://github.com/telerik/kendo-themes/pull/1204
