### ISSUE TITLE
[ProgressBar] Update styling to accommodate user-defined label positioning

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-themes#852]
The Kendo UI for Angular ProgressBar component envisages a configuration option that will allow developers to set the label position (e.g. start, center, end) which necessitates changes to how the label container is currently handled when the orientation is set to vertical.

Adding styling based on the [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) property (e.g. writing-mode: tb-lr) will allow for a clean approach to position the label based on the user setting and the flex justify-content and/or align-self settings.

**Comment by joneff** [comment]
Targeted by by #871
