### ISSUE TITLE
Validation tooltip inside grid is sized incorrectly

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#862]
Based on customer report: In grid inline editing, the tooltip is sized incorectly -- 100% of width, instead of auto width.

* ok: https://dojo.telerik.com/aBuKaDun/9
* not ok: https://dojo.telerik.com/aBuKaDun/8

reported in ticket: 1425303

possibly related #690, #480

**Comment by dmanova** [comment]
The tooltip size is fixed.
