### ISSUE TITLE
use $primary instead of $accent

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#867]
Trough out the themes we use `$accent` as a variable name for ... well accent color. Which is fine in terms of name, but limits us to using another color variable name. 

A much better name would be to use `$primary`, as it will play along with other frameworks and will allow us to use `$secondary` and `$tertiary`, should we need it.

This will be a major change, so it should be done in steps:

1) Replace usages `$accent` with `$primary` but leave `$accent` as fallback
2) Remove `$accent` variable entirely. That it self will trigger v5 for themes

@tsvetomir @elena-gancheva thoughts?

**Comment by tsvetomir** [comment]
Any reason not to keep the `$accent` alias indefinitely?

**Comment by joneff** [comment]
Most usages are replaced. `accent` and `accent-contrast` variable remain for the time being.

Note: neither is used in Material theme, as it on palettes rather than actual colors
