### ISSUE TITLE
Describe add / commit / rebase / push workflow somewhere in the Wiki

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-themes#869]
Please, describe add / commit / rebase / push workflow somewhere in the Wiki. Currently, the workflow differs from the one establishet in the Kendo repo. More specifically, the automated procedure that runs the visual test causes confusions.

**Comment by elena-gancheva** [comment]
@veselints https://github.com/telerik/kendo-themes/wiki/Front-End-Workflow#themes-development-with-visual-tests here is the wiki for developing with visual tests
![image](https://user-images.githubusercontent.com/8842674/64936094-e6a9f680-d85c-11e9-8cff-d42699fd489d.png)

**Comment by veselints** [comment]
resolved
