### ISSUE TITLE
Kendo theme import inside class throws error

### ISSUE THREAD

**Issue by MinSma** [telerik/kendo-themes#883]
![image](https://user-images.githubusercontent.com/10289561/64780302-af8bca80-d568-11e9-9ef1-36e4bbbd7181.png)
I am trying to make dark/light theme modes for the website, but while I nest Kendo theme inside class and try to compile it, it throws error:
![image](https://user-images.githubusercontent.com/10289561/64778950-933a5e80-d565-11e9-855c-8a95361fbc71.png)
Firstly, I have tried to write variables and mixins imports before Kendo theme usage in class as it is specified in the same problem two years ago: https://github.com/telerik/kendo-angular/issues/352, but after that button styles aren't working.
![image](https://user-images.githubusercontent.com/10289561/64780360-ce8a5c80-d568-11e9-8a59-0d429e6c4698.png)

Also, I have tried to add "!optional" at the end of the error code line, but the result is the same as in the previous try.
![image](https://user-images.githubusercontent.com/10289561/64779222-2f646580-d566-11e9-85b6-5f95dac98dde.png)

Maybe anything changed in the past 2 years based on this problem (last and only one issue associated with this error was created 2 years ago) or there is any workaround?

**Comment by IT-CASADO** [comment]
Today i noticed the same error on same situation.

Nesting Kendo SCSS files inside a class name ( e.g.: .them-light) breaks my build!!

Any solution to this behaviour?
