### ISSUE TITLE
Add additional how-to topic for DartSass compilation

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#908]
**Describe the issue or request**
The current compilation of the project should include postcss-calc in the start up pipeline so that the values computed with calc() are proper.

**Comment by joneff** [comment]
Related to #846, #834

**Comment by joneff** [comment]
We've provided documentation for:

* [Compiling themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes)
* [Customizing themes](https://github.com/telerik/kendo-themes/wiki/Customizing-themes)
* [Including themes in React projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-React-projects)
* [Including themes in Angular projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-Angular-projects)
