### ISSUE TITLE
Style native checkboxes and radio

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#926]
The way `k-checkbox` and `k-radio` work now is a bit misleading -- it is applied to checkboxes and radios, respectively, but works only in one certain scenario.

By styling the native elements, instead pseudo elements of the succeeding span, developers will be able to achieve all scenarios they would normally do with checkboxes / radio.

**Describe the solution you would like to see implemented**
1) Keep the current styles with a suffix. Say, `.k-checkbox-legacy`
2) Apply the styles from `.k-checkbox-label` to the native elemen

**Describe the alternatives you have considered**
There is no alternative

**Additional context**
Styling native checkboxes (and radio) works in all modern browsers. That is to say, not IE 11. That's why we are keeping our current styles as `-legacy`

**Comment by silviyaboteva** [comment]
The point 2 is on PR: https://github.com/telerik/kendo-themes/pull/992
