### ISSUE TITLE
Incorrect items' text vertical alignment in the popup of a Combobox with virtualization

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#927]
**Describe the bug**
The text of the items inside the popup of a Combobox with virtualization are not correctly aligned in the li tag in which they are positioned. The text is positioned below the horizontal center.  

**To reproduce**
1. Go to [this Dojo](http://kendobuild.telerik.com/dojo-staging/AWIMOKuH)
2. Enter "**Toms Spezialitäten**" in the **ComboBox** input and select the item. At this point, the reported issue can be seen if we hover an item from the popup. However, continue with the next step. 
3. Click on the arrow of the **ComboBox** to trigger the popup opening
4. The selected item is marked in red and the text is aligned lower than the horizontal center of the space reserved for the item.

**Expected behavior**
The text of the items inside the popup should be aligned to the horizontal center of the space reserved for it. 

**Screenshots**
Current behavior:
![1](https://user-images.githubusercontent.com/41293735/66144785-2c630f00-e612-11e9-94f2-6799541092c4.png)

Expected behavior:
![2](https://user-images.githubusercontent.com/41293735/66144985-8237b700-e612-11e9-88a1-866b382d2821.png)

**Affected package (please provide)**
* theme-material SASS
* theme-Fiori
* theme-Material black
* theme-Nova
* theme-Office 365
* theme-material LESS

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Vue

**Affected browsers (please provide)**
- Firefox: 60.9.0esr 
- Chrome: 77
- Edge version: 42

**Build system information (please provide)**
- OS: Windows

**Comment by joneff** [comment]
That's not an issue of the themes, it's an issue of the demo: adjust virtual.itemHeight property
