### ISSUE TITLE
Implement Material for ListBox

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-themes#93]

**Comment by matanasov** [comment]
Some issues found:
1. The items paddings (left and right) should be 24px, but currently are 16.
2. When an item is dragged-dropped, it doesn't have correct background color set (see dragged item in the design)

**Comment by theOrlin** [comment]
Design has been updated, and the dragged item now is a selected item with opacity, with no background.

**Comment by theOrlin** [comment]
Regarding **3**:

The colors are inherited from the Popup styling. After consulting with @mvgmvg, I was informed that the hovered item text color fix is currently in a separate branch, to be merged into develop at a future time.

**Comment by joneff** [comment]
@matanasov I am closing this item, as we have already released ListBox as part of material theme.

Please double check if there are any outstanding issues, including the ones you've already mentioned and if  needed, open a new issue.
