### ISSUE TITLE
Tooltip in SASS themes is over Calendar, Dropdown

### ISSUE THREAD

**Issue by dmanova** [telerik/kendo-themes#936]
**Describe the bug**
Tooltip in SASS themes is over other containers like Calendar, Dropdown. The z-index of the tooltip is bigger than the one of other elements.

For the LESS themes it is fine. 

**To reproduce**
Click on any of the calendars in:
https://dojo.telerik.com/aBuKaDun/9

**Expected behavior**
Tooltip is over grid cells but behind selectable/editable components.

**Screenshots**
![TooltipsZ-Index](https://user-images.githubusercontent.com/52446546/66404168-9c95da00-e9f0-11e9-88dc-4ab86949de36.png)

**Affected package (please provide)**
*  All SASS themes

**Affected browsers (please provide)**
- All

**Comment by joneff** [comment]
It's actually expected to have the tooltip **above** the rest of the elements. Perhaps the example in question is wrong usage:
* either the tooltip or the calendar should be visible at the same time
* upon next focus, the tooltip should be hidden and shown on the next blur, when the calendar is hidden
