### ISSUE TITLE
[TimePicker] the selected time is not aligned correctly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#938]
**Describe the bug**
The time list (hours and minutes) alignment gets worse with every selected item which is at the bottom of the list.

**To reproduce**
Observed in our documentation demo:
https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/#toc-basic-usage

**Screenshots**
![bug_1](https://user-images.githubusercontent.com/33104481/66462286-6d7c7880-ea83-11e9-8304-b28d78d05bae.png)

![bug](https://user-images.githubusercontent.com/33104481/66462281-6a818800-ea83-11e9-9c20-42c29ce613bc.png)

**Affected suites**
* Kendo UI for Angular
* Kendo UI for React

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Comment by JoomFX** [comment]
TimePicker uses the native browser scroll.
The above issue is reproducible in Chrome only (when zoomed in) and is not something Kendo-Themes should handle or address.
