### ISSUE TITLE
W3C CSS Validator errors

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#959]
**Describe the bug**
Fix the following errors from the W3C CSS Validator - https://jigsaw.w3.org/css-validator/

# Default:

<div id="errors">
            <h3>Sorry! We found the following errors (17)</h3>
                    <div class="error-section-all">
                                                                                                    <div class="error-section">
		                    <h4>URI : TextArea</h4>
		                    <table>
                                                    <tbody><tr class="error">
                            <td class="linenumber" title="Line 4942">4942</td>
                            <td class="codeContext"> .k-resize-w </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 4952">4952</td>
                            <td class="codeContext"> .k-resize-e </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 7215">7215</td>
                            <td class="codeContext"> .k-scheduler-mobile .k-scheduler-times .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-times .k-scheduler-groupcolumn .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-groupcolumn .k-scheduler-group-text </td>
                            <td class="parse-error">
                                            <code>tb</code> is not a <code>writing-mode</code> value : 
                                            <span class="exp">
                                    tb
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 7916">7916</td>
                            <td class="codeContext"> .k-grid .k-grouping-row .k-group-cell, .k-grid .k-grouping-row + tr .k-group-cell </td>
                            <td class="parse-error">
                                            <code>none</code> is not a <code>text-overflow</code> value : 
                                            <span class="exp">
                                    none
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 18193">18193</td>
                            <td class="codeContext"> .k-buttons-vertical </td>
                            <td class="parse-error">
                                            <code>vertical</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    vertical
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21261">21261</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21393">21393</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(156 156 156 / 0.7) #dedede
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21510">21510</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-start</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21512">21512</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-end</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21514">21514</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-start</code> doesn't exist : 
                                            <span class="exp">
                                    0.5em
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21516">21516</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-end</code> doesn't exist : 
                                            <span class="exp">
                                    0.5em
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21548">21548</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21549">21549</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21591">21591</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21592">21592</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 22372">22372</td>
                            <td class="codeContext"> .k-timeline-card .k-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 22764">22764</td>
                            <td class="codeContext"> .k-timeline .k-timeline-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(0 0 0 / 0.08) #ffffff
                                </span>
                                        </td>
                        </tr>
                                    </tbody></table>
                </div>
                    </div>
        </div>

# Bootstrap:

<div id="errors">
            <h3>Sorry! We found the following errors (19)</h3>
                    <div class="error-section-all">
                                                                                                    <div class="error-section">
		                    <h4>URI : TextArea</h4>
		                    <table>
                                                    <tbody><tr class="error">
                            <td class="linenumber" title="Line 4913">4913</td>
                            <td class="codeContext"> .k-resize-w </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 4923">4923</td>
                            <td class="codeContext"> .k-resize-e </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 6671">6671</td>
                            <td class="codeContext"> .k-scheduler-mobile .k-scheduler-times .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-times .k-scheduler-groupcolumn .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-groupcolumn .k-scheduler-group-text </td>
                            <td class="parse-error">
                                            <code>tb</code> is not a <code>writing-mode</code> value : 
                                            <span class="exp">
                                    tb
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 7377">7377</td>
                            <td class="codeContext"> .k-grid .k-grouping-row .k-group-cell, .k-grid .k-grouping-row + tr .k-group-cell </td>
                            <td class="parse-error">
                                            <code>none</code> is not a <code>text-overflow</code> value : 
                                            <span class="exp">
                                    none
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 9525">9525</td>
                            <td class="codeContext"> .k-window-actions </td>
                            <td class="parse-error">
                                Value Error :  margin-top                                             Too many values or values are not recognized : 
                                            <span class="exp">
                                    -1rem 1rem
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 9526">9526</td>
                            <td class="codeContext"> .k-window-actions </td>
                            <td class="parse-error">
                                Value Error :  margin-bottom                                             Too many values or values are not recognized : 
                                            <span class="exp">
                                    -1rem 1rem
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 17824">17824</td>
                            <td class="codeContext"> .k-buttons-vertical </td>
                            <td class="parse-error">
                                            <code>vertical</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    vertical
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 20807">20807</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 20957">20957</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(156 156 156 / 0.7) #dedede
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21074">21074</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-start</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21076">21076</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-end</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21078">21078</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-start</code> doesn't exist : 
                                            <span class="exp">
                                    0.5rem
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21080">21080</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-end</code> doesn't exist : 
                                            <span class="exp">
                                    0.5rem
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21112">21112</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21113">21113</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21155">21155</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21156">21156</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 21915">21915</td>
                            <td class="codeContext"> .k-timeline-card .k-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 22311">22311</td>
                            <td class="codeContext"> .k-timeline .k-timeline-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(33 37 41 / 0.125) #ffffff
                                </span>
                                        </td>
                        </tr>
                                    </tbody></table>
                </div>
                    </div>
        </div>

# Material:

<div id="errors">
            <h3>Sorry! We found the following errors (20)</h3>
                    <div class="error-section-all">
                                                                                                    <div class="error-section">
		                    <h4>URI : TextArea</h4>
		                    <table>
                                                    <tbody><tr class="error">
                            <td class="linenumber" title="Line 5032">5032</td>
                            <td class="codeContext"> .k-resize-w </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 5042">5042</td>
                            <td class="codeContext"> .k-resize-e </td>
                            <td class="parse-error">
                                            <code>col</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    col
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 7335">7335</td>
                            <td class="codeContext"> .k-scheduler-mobile .k-scheduler-times .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-times .k-scheduler-groupcolumn .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-group-cell .k-scheduler-group-text, .k-scheduler-mobile .k-scheduler-agenda .k-scheduler-groupcolumn .k-scheduler-group-text </td>
                            <td class="parse-error">
                                            <code>tb</code> is not a <code>writing-mode</code> value : 
                                            <span class="exp">
                                    tb
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 8033">8033</td>
                            <td class="codeContext"> .k-grid .k-grouping-row .k-group-cell, .k-grid .k-grouping-row + tr .k-group-cell </td>
                            <td class="parse-error">
                                            <code>none</code> is not a <code>text-overflow</code> value : 
                                            <span class="exp">
                                    none
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 13716">13716</td>
                            <td class="codeContext"> .k-slider .k-draghandle:active, .k-slider .k-draghandle.k-pressed </td>
                            <td class="parse-error">
                                            <code>inset</code> is not a <code>box-shadow</code> value : 
                                            <span class="exp">
                                    inset
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 13767">13767</td>
                            <td class="codeContext"> .k-slider.k-state-disabled .k-draghandle </td>
                            <td class="parse-error">
                                Value Error :  border                                             Too many values or values are not recognized : 
                                            <span class="exp">
                                    2px solid inherit
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 17971">17971</td>
                            <td class="codeContext"> .k-numerictextbox .k-select &gt; .k-state-selected, .k-numerictextbox .k-select &gt; .k-state-active </td>
                            <td class="parse-error">
                                            <code>inset</code> is not a <code>box-shadow</code> value : 
                                            <span class="exp">
                                    inset
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 19879">19879</td>
                            <td class="codeContext"> .k-buttons-vertical </td>
                            <td class="parse-error">
                                            <code>vertical</code> is not a <code>flex-direction</code> value : 
                                            <span class="exp">
                                    vertical
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23119">23119</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23269">23269</td>
                            <td class="codeContext"> .k-drawer-wrapper </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(156 156 156 / 0.7) #dedede
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23386">23386</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-start</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23388">23388</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-block-end</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23390">23390</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-start</code> doesn't exist : 
                                            <span class="exp">
                                    0.5em
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23392">23392</td>
                            <td class="codeContext"> .k-progress-status </td>
                            <td class="parse-error">
                                            Property <code>padding-inline-end</code> doesn't exist : 
                                            <span class="exp">
                                    0.5em
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23424">23424</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23425">23425</td>
                            <td class="codeContext"> .k-progressbar-horizontal .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-inline-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23467">23467</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-start-width</code> doesn't exist : 
                                            <span class="exp">
                                    1px
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 23468">23468</td>
                            <td class="codeContext"> .k-progressbar-vertical .k-item + .k-item </td>
                            <td class="parse-error">
                                            Property <code>border-block-end-width</code> doesn't exist : 
                                            <span class="exp">
                                    0
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 24490">24490</td>
                            <td class="codeContext"> .k-timeline-card .k-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-width</code> doesn't exist : 
                                            <span class="exp">
                                    thin
                                </span>
                                        </td>
                        </tr>
                                                                                            <tr class="error">
                            <td class="linenumber" title="Line 24890">24890</td>
                            <td class="codeContext"> .k-timeline .k-timeline-card .k-card-body </td>
                            <td class="parse-error">
                                            Property <code>scrollbar-color</code> doesn't exist : 
                                            <span class="exp">
                                    rgb(0 0 0 / 0.12) white
                                </span>
                                        </td>
                        </tr>
                                    </tbody></table>
                </div>
                    </div>
        </div>

**Comment by joneff** [comment]
@PreslavKozovski some of the properties are false positive:
* `*-block-start` is direction independent `border-top`, `padding-top`, `margin-top`
* the same applies for other direction independent properties, like `*-inline-end` etc.

**Comment by PreslavKozovski** [comment]
Having the following properties that do not exist is by design:

1. `scrollbar-*`
1. `*-block-start-*`
1. `*-block-end-*`
1. `*-inline-start-*`
1. `*-inline-end-*`
