### ISSUE TITLE
Extract all ColorPicker styles from common logic

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#973]
**Is your feature request related to a problem? Please describe.**
Currently, the styles responsible for `layout`/`theme` sizings, colors, border-widths, etc. for the ColorPicker component are separated in global `common` files.

Next step, extract all variables for the Colorpicker component, that are including appearances and depending on other styles.

**Describe the solution you would like to see implemented**
Extract those styles from the common files and apply them in the corresponding for the component style folders. This refactoring must **not** regress the current design and behavior.

**Additional context**
We can achieve decoupled styles and more flexibility when customizing the styles for a given component. This enhancement will be needed for creating a consistent and flexible styleguide for creating forms with Kendo components.

Related to: https://github.com/telerik/k2/issues/150

**Comment by joneff** [comment]
closed by #977
