### ISSUE TITLE
Kendo jQuery Dropdownlist group image is misaligned in FF

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#975]
**Describe the bug**

The issue is reproduced with recommended settins on Lenovo ThinkVision P24q-10 monitor: 
Resolution:2560x1440
Default Scale: 125%

https://dojo.telerik.com/aVoliten - Latest dev theme
SASS Firefox - The 2 parts of the group image are 1px misaligned  

**To reproduce**
1. Go to 'https://dojo.telerik.com/aVoliten' or https://demos.telerik.com/kendo-ui/dropdownlist/grouping in FireFox
2. Open the dropdownlist popup

**Expected behavior**
Dropdownlist group image is rendered consistently

**Screenshots**
![image](https://user-images.githubusercontent.com/7202037/65332697-d8930780-dbc7-11e9-9864-5cb5902eacd1.png)

**Affected package (please provide)**
* theme-default
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery

**Affected browsers (please provide)**
- Firefox: [69]

**Comment by PreslavKozovski** [comment]
@joneff Do we support scale/zoom when it is the recommended setting for a monitor?
