### ISSUE TITLE
DateTimePickers have hover styles when disabled

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-themes#985]
**Describe the bug**
**DatePicker, TimePicker & DateTimePicker** have hover-specific styles when in disabled state in the **Default** theme (border and icon colors change).

**To reproduce**
See [example](https://stackblitz.com/edit/react-j3g4kb?file=app%2Fmain.jsx). Hover on any of the three components - hover styles are incorrectly applied although the components are disabled.

**Expected behavior**
Hover-specific styles shouldn't be applied when the components are in disabled state.

**Affected package**
* theme-default

**Affected suites**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React

**Additional context**
The problem is not evident in Angular's **DatePicker** and **TimePicker** as both use a local work-around of setting the `k-state-disabled` class on the `k-datepicker` and `k-timepicker` elements. According to the proposed rendering in the visual tests, however, the `k-state-disabled` class should be applied one level down - on the `k-picker-wrap` element.

**Comment by JoomFX** [comment]
fixed in https://github.com/telerik/kendo-themes/pull/990
