### ISSUE TITLE
Kendo jQuery Autocomplete clear button doesn't appear on mouse hover 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-themes#988]
Clear button doesn't appear when hovering the Autocomplete input.

1. Go to http://kendobuild-windows.openstack.progress.com/kendo-ui-dev/autocomplete/index
2. Select an item
3. Click outside the Autocomplete widget
4. Hover the Autocomplete widget's input

**Expected behavior**
The clear button appears on the right
The issue is regression compared to R3 2019
The proper behavior could be observed on the live demos: https://demos.telerik.com/kendo-ui/autocomplete/index

**Screenshots**
The clear button doen't appear unless click in the input

* Kendo UI for jQuery

**Comment by joneff** [comment]
The issue is related to extracting the styles in a separate files. there is a comma missing in the selectors.

https://github.com/telerik/kendo-themes/blob/f0aa05501a5f430b43a93f61b89f2a94631a6952/packages/default/scss/autocomplete/_layout.scss#L85

@JoomFX please fix.
