### ISSUE TITLE
Card component styles additions

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#989]
Currently, there are missing styles for full customization of card component and some of the existing styles should be refactored so that they have complete consistency with the component's api.

**Styles for refactoring**
- `k-card-state-{error/info/warning/success}` - those are not states of the card. This class should be renamed to something like `k-card-{success/error/warning/info/default}`
- card action buttons layout - if set to `stretched`, the styles are depending on having a class `k-card-action` on each element within the `k-card-actions` class. This is not flexible, if the user has configured the card's actions with a template and custom classes.
- `k-hr` should be renamed to `k-card-separator` - separate card content with a `hr` or styles, and should be `vertical` or `horizontal`, depending on the layout of the card

**Styles for adding**
- `k-card-thumbnail` (avatar, thumbnail, circled image for the card header, should be aligned with the card title and subtitle within a `k-hbo` container with `flex-shrink: 0`; Should set `background-image` property with the proper sizings for it.
- `k-card-actions-{start/center/end/stretched}` - the position of the card action buttons, aligned horizontally (same for `k-card-vertical-actions`)
- `k-card-footer` - this class is missing. Should be same as header, body with paddings and border.

@joneff @Juveniel

**Comment by Juveniel** [comment]
I agree with all of the above.

Suggestion: a divider is currently available in the themes as `.k-hr`, so we could move this bullet to the refactoring column and just create a `.k-card-separator` class for the cards that extends it?

**Comment by elena-gancheva** [comment]
Updated, thanks :)

**Comment by elena-gancheva** [comment]
Related to https://github.com/telerik/kendo-themes/issues/176 - discussion about card-deck, card-list and widths of the card in a container
