### ISSUE TITLE
Theming: Bootstrap rules not applied

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-themes#999]
* Bug report 

## Current behavior
DropDowns / DateInputs aren't taking the whole width, in my case col-md-6 (50%)

## Expected behavior
Controls should fit the defined bootstrap width

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/GeNsU2wJLV8RYqrUFrNa?p=preview

## Environment

Package versions:
    "progress/kendo-angular-buttons": "1.1.0",
    "progress/kendo-angular-dateinputs": "1.2.0",
    "progress/kendo-angular-dialog": "1.1.0",
    "progress/kendo-angular-dropdowns": "1.2.1",
    "progress/kendo-angular-excel-export": "1.0.4",
    "progress/kendo-angular-grid": "1.4.2",
    "progress/kendo-angular-inputs": "1.3.0",
    "progress/kendo-angular-intl": "1.2.2",
    "progress/kendo-angular-l10n": "1.0.3",
    "progress/kendo-angular-popup": "1.2.1",
    "progress/kendo-angular-sortable": "1.0.3",
    "progress/kendo-angular-upload": "1.2.1",
    "progress/kendo-data-query": "1.0.7",
    "progress/kendo-date-math": "1.0.3",
    "progress/kendo-drawing": "1.4.0",
    "progress/kendo-file-saver": "1.0.4",
    "progress/kendo-theme-bootstrap": "2.8.1",
    "telerik/kendo-intl": "1.2.1"

Browser:
- Chrome (desktop) version 61

**Comment by silviyaboteva** [comment]
In `v5` release of all Kendo Themes (including the Bootstrap), we've removed the default width of the inputs and pickers and   they now [have 100% width](https://github.com/telerik/kendo-themes/blob/develop/packages/bootstrap/scss/input/_variables.scss#L2).

Here is the updated demo: https://stackblitz.com/edit/angular-nymkuj?file=index.html
